### ISSUE TITLE
Create a tool which allows for bootstrapping / conversion of Cordova plugins -> Capacitor plugins

### ISSUE THREAD

**Issue by patrickjquinn** [ionic-team/capacitor-plugins#1001]
### Plugin

Cordova Plugins

### Description

A CLI tool which converts or at least attempts to map and scaffold Cordova plugins 

### Platform(s)

Android, iOS

### Preferred Solution

A CLI tool one could point at a Cordova plugin directory and it would create a new Capacitor plugin with the as much of the core implementation mapped to Capacitor 3's plugin structure

### Alternatives

Use an old Cordova plugin via the bridge or write your own from scratch.

### Additional Context

One of the major reasons, to my mind, why people don't adopt Capacitor in more enterprise use cases is the relative immaturity of the plugin ecosystem when compared to react native or Cordova itself. 

Investing in tooling which vastly simplifies the plugin creation process, doing as much of the work in a descriptive way for the developer as well as allowing for the porting of the older much more fully realised Cordova ecosystem to the newer Capacitor format is critical for bolstering it's ecosystem  IMO.

**Comment by jcesarmobile** [comment]
thanks for the issue, but this issue tracker is for reporting issues related to the core plugins.
If you want to provide ideas you can use [the forum ](https://forum.ionicframework.com/), the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository or[ ionic discord](https://ionic.link/discord)

Anyway, having Cordova plugin compatibility built-in into capacitor, I don't see the need of converting those plugins that already work into Capacitor plugins.
