### ISSUE TITLE
Toast gravity setting doesn't work on Android version's > 11

### ISSUE THREAD

**Issue by patrickjquinn** [ionic-team/capacitor-plugins#1002]
### Plugin(s)

capacitor-toast 

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1
  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

When I set position to centre, the toast appears down the bottom of the screen. Logcat also reports that setting gravity is no longer supported.

### Expected Behavior

The plugin should honour the position passed to it.

### Code Reproduction

```
  await Toast.show({
	  text,
	  position: 'center'
  })
```

### Other Technical Details

Android target version 31 & 32

### Additional Context

None.

**Comment by jcesarmobile** [comment]
yeah, position is no longer supported, I reported it some time ago https://github.com/ionic-team/capacitor-plugins/issues/688
