### ISSUE TITLE
Splash screen plugin still references jcenter

### ISSUE THREAD

**Issue by macdja38** [ionic-team/capacitor-plugins#1020]
### Plugin(s)

[splash-screen/android/build.gradle](https://github.com/ionic-team/capacitor-plugins/blob/main/splash-screen/android/build.gradle#L47)

### Platform(s)

Android

**Comment by jcesarmobile** [comment]
We are working on version 4 of the plugins (to match future Capacitor 4 version), the work is done in capacitor-4 branch
https://github.com/ionic-team/capacitor-plugins/blob/capacitor-4/splash-screen/android/build.gradle
