### ISSUE TITLE
Error: "App" plugin is not implemented in android

### ISSUE THREAD

**Issue by sattasundar** [ionic-team/capacitor-plugins#1024]
## Bug Report
While I set **minifyEnabled & shrinkResources** to **true** in release config in app's build.gradle file;
`
buildTypes {

       release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
`
### Plugin(s)

 "@capacitor/app": "1.0.7"

### Capacitor Version

"@capacitor/core": "^3.4.3"
"@capacitor/android": "^3.4.3"

```
In catch exception; Error: "App" plugin is not implemented in android
```

### Platform(s)

Android

### Current Behavior

Error: "App" plugin is not implemented in android

### Expected Behavior

It should work while we set **minifyEnabled & shrinkResources** to **true** for app optimization.

**Comment by jcesarmobile** [comment]
this is a known issue on capacitor-android, as workaround you can add this proguard rules to your app
https://github.com/ionic-team/capacitor/issues/5606#issuecomment-1122461215

**Comment by jcesarmobile** [comment]
can you please provide a sample app where the issue can be reproduced?
