### ISSUE TITLE
PushNotifications.requestPermissions() creates splash screen layout behind a popup when IdentityVault plugin is used

### ISSUE THREAD

**Issue by faroukh-dev** [ionic-team/capacitor-plugins#1027]
### Plugin(s)

capacitor-push-notificarion

### Capacitor Version

```
@capacitor/cli: 3.5.1
@capacitor/core: 3.5.1
@capacitor/android: 3.5.1
@capacitor/ios: 3.5.1
```

### Platform(s)
iOS

### Current Behavior

Capacitor PushNotifications plugin creates a splash screen UI layout, which overlaps an app during requesting Notifications permissions. 

### Expected Behavior

Capacitor PushNotifications plugin creates a blank/transparent background, which makes an app visible in the background during requesting Notifications permissions.

<img width="607" alt="Screenshot 2022-06-07 at 14 42 20" src="https://user-images.githubusercontent.com/28514019/172371110-aa0ce3b0-f062-4655-bc7a-10a53366e51e.png">

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
That's @ionic-enterprise/identity-vault's Privacy screen, you can configure it to not use a privacy screen or call `Device.setHideScreenOnBackground(false);` and then `Device.setHideScreenOnBackground(true);` after the permission is requested if you want to keep it but not appear in the prompt.
