### ISSUE TITLE
Capacitor Clipboard - Not writing to clipboard (Android)

### ISSUE THREAD

**Issue by sjwarner** [ionic-team/capacitor-plugins#1029]
### Plugin(s)
```
"@capacitor/clipboard": "^1.0.8",
```

### Capacitor Version
```
 % npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/cli: 3.5.1

[success] Android looking great! 👌

```

### Platform(s)
Android

### Current Behavior

Invoking `Clipboard.write({string: 'Hello World'})`, or similar (see code snippet below)

```
const writeToClipboard = async (input) => {
    await Clipboard.write({
        string: input
    });
};
```

Results in the following error:

```
/Capacitor/Console: File: http://localhost/static/js/main.c9bccf7c.js - Line 2 - Msg: Uncaught (in promise) NotAllowedError: Write permission denied.
```

I cannot find any documentation describing how to set up permissions for the clipboard plugin, unlike other plugins (e.g. filesystem: https://github.com/ionic-team/capacitor-plugins/tree/main/filesystem).

### Expected Behavior
Either some documentation regarding how to set up permissions for clipboard plugin, or that the string is successfully copied to clipboard.

### Other Technical Details
Capacitor in a React app (`"react-scripts": "^5.0.1"`). Built and imported to Android Studio, solution run in a virtual device (Pixel 3a 32 Google APIs | arm64)

### Additional Context
I've not used Capacitor or it's plugins for too long - if I am doing something wrong when setting permissions in my project up, please forgive me, and let me know! I can't find any mention of similar in the repository's issues or elsewhere online.

Once I understand what I'm doing wrong, I'll happily add info regarding permissions errors to documentation in the plugin if deemed appropriate - hopefully I'm not the only person to have had this problem!

**Comment by sjwarner** [comment]
Hi @jcesarmobile - thank you for coming back to me!

I've made a little bit of progress this evening thanks to your feedback. I am no longer getting the "Permission Denied" error, but the current behaviour I am experiencing is still odd. Now, the logs indicate that `Clipboard.write` is correctly called with the expected string - but when I go to paste afterwards, my clipboard is empty. I would expect the `string` provided to `write` to be there.

Logs:
```
2022-06-09 21:27:44.542 V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 118914189, pluginId: Clipboard, methodName: write
2022-06-09 21:27:44.542 V/Capacitor: callback: 118914189, pluginId: Clipboard, methodName: write, methodData: {"string":"http:\/\/localhost\/?first=DARE&second=MIGHTY&third=THINGS&coords=34%2011%2058%20N%20118%2010%2031%20W"}
2022-06-09 21:27:44.542 I/Capacitor/Console: File: http://localhost/static/js/main.68ce20ce.js - Line 2 - Msg: android
2022-06-09 21:27:44.550 I/Capacitor/Console: File: http://localhost/ - Line 201 - Msg: undefined
2022-06-09 21:27:44.583 13240-13278/me.sjwarner.msg2mars D/EGL_emulation: app_time_stats: avg=1572.98ms min=13.87ms max=15515.96ms count=10
```

My code sample can be found here - it's a bit messy as it's a WIP:
https://github.com/sjwarner/perseverance-parachute-generator/commit/1acddc8841b6ed7402c1f2b868aab0eaa2b24c66

Specifically the `InputPane` component, which on Android will use this method to copy/paste:

```
const writeToClipboard = async (input) => {
    await Clipboard.write({
        string: input
    });
};
```

Thank you for your help so far!

**Comment by jcesarmobile** [comment]
Your app is working fine for me, if I go in example to Chrome and tap the url bar I see on the keyboard the pasteboard icon with the url and also see "link you copied" as autocomplete in the url bar that pastes the url if tapped.

It might be possible that some apps might not detect the url correctly, since you are copying an url try using "url" instead of "string" on Clipboard.write method call.
