### ISSUE TITLE
feat: [Camera] add support for returning a blob

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor-plugins#103]
[`CameraResultType`](https://capacitorjs.com/docs/apis/camera#cameraresulttype) should also support a return type of `Blob`. This will make it possible to more efficiently upload photos to a server or compress photos on the client for example.

**Comment by jcesarmobile** [comment]
The bridge doesn’t allow to pass Blob objects.
You can easily use the webPath to get a Blob.

**Comment by tafelnl** [comment]
I agree that you could easily use the result to generate a Blob. I also am aware of the fact that - as of this moment - it is not possible for the native bridge to return a Blob. But I saw https://github.com/ionic-team/capacitor/issues/984 to make this possible. So I thought this would be a legit use case. I expect it to be at least somewhat faster and it would also support large files.

So yes, it is probably just a luxury option. But hey, if [that issue ](https://github.com/ionic-team/capacitor/issues/984) is closed, we could maybe give it a try and implement it.
