### ISSUE TITLE
Type '"prompt-with-rationale"' is not assignable to type 'PermissionState'.

### ISSUE THREAD

**Issue by mattsputnikdigital** [ionic-team/capacitor-plugins#1030]
It seems either PermissionState is missing 'prompt-with-rationale' or the docs are incorrect.

type PermissionState = "prompt" | "granted" | "denied"

generated the error -> Type '"prompt-with-rationale"' is not assignable to type 'PermissionState'.

**Comment by jcesarmobile** [comment]
Make sure you are importing PermissionState from @capacitor/core and that you are in @capacitor/core 3.x.x version

"prompt-with-rationale" is declared here https://github.com/ionic-team/capacitor/blob/main/core/src/definitions.ts#L124-L128
