### ISSUE TITLE
Polylines

### ISSUE THREAD

**Issue by rameshbansal** [ionic-team/capacitor-plugins#1036]
How we can draw polylines using this plugin?

**Comment by hardmaster92** [comment]
I think there is no support for that yet but it would be a great feature request. Not having polylines is the only reason I'm not using the capacitor maps yet (since I need that feature)

**Comment by nemoneph** [comment]
Same here ! 
I'm currently using Leaftlet, just waiting the polyline feature to switch to this plugin :)

**Comment by NePheus** [comment]
Also waiting for this to switch. Is this feature in the roadmap?

**Comment by ShaunBrassell** [comment]
Same here, need to show the route taken. That, and also be able to adjust zoom to fit bounds of all markers. Hopefully both on the roadmap, will have to stick with Mapbox GL for now

**Comment by cwcarlson10** [comment]
This is also a blocker for us to switch over.  Any updates on where this falls on the priority list would be greatly appreciated.  Thanks for you hard work on this!

**Comment by ThinkinDragon** [comment]
any one find any proper solution for draw Polylines in map plugin i am using Gmap Javascript api but it very slow and not smooth for native experience and causing high usage bill, thinking to switch the route encoding function to server side rather that using google api

**Comment by tomek-em** [comment]
Same here.
We also need this to switch.

**Comment by Dev-it-a-dev** [comment]
+1

**Comment by JoCodeX** [comment]
+1 .. It will be so useful!!

**Comment by AE1NS** [comment]
@jcesarmobile are there any internal information about this feature request? Is it even on a roadmap or doesnt it have any priority? Just wanted to know this, because I think many are waiting for this to switch to this really useful plugin.

**Comment by Aksoom-Hussain** [comment]
any news about polylines or route line figure in the plugin or at lest they provide way to pass gmap js library to send data to map

**Comment by fgrmt** [comment]
+1.
The polylines feature would allow us to switch over to this Capacitor plugin from the legacy cordova-plugin-googlemaps.

**Comment by aljabr** [comment]
waiting for circles to use this plugin :)

**Comment by EdByrnee** [comment]
> waiting for circles to use this plugin :)

Same here !!

**Comment by jonasriecken** [comment]
+1 
polylines would be great as that would allow to draw routes

**Comment by AE1NS** [comment]
Thanks for the implementation! Is it possible to access a polygon/polyline after it was added to the map, i.e. to change the colors. My current workaround would be to remove and add it again.
