### ISSUE TITLE
Capacitor Google Map @capacitor/google-maps get coordinate after marker dragend

### ISSUE THREAD

**Issue by payen83** [ionic-team/capacitor-plugins#1046]
Hi, 

How to get latest coordinate (lat & lng) after the marker dragend (via listener)?
I search on documentation there's no feature for that except for .setOnMarkerClickListener(...)

Appreciate your help!

**Comment by jcesarmobile** [comment]
You can use `setOnMarkerDragEndListener` https://capacitorjs.com/docs/apis/google-maps#setonmarkerdragendlistener
It includes latitude and longitude of where the marker was placed.

If it's not working as expected, please, create a new issue and provide more information and a sample app where the issue can be reproduced.
