### ISSUE TITLE
@capacitor/google-maps - map doesn't show

### ISSUE THREAD

**Issue by LukasBrass** [ionic-team/capacitor-plugins#1047]
### Plugin(s)
@Capacitor/google-maps

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/core: 3.5.1
  @capacitor/cli: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

### Platform(s)
iOS and Android, both on emulators and devices

### Current Behavior
I want to display the map but all I have is a blank div. The map is displayed when I do ionic serve, and when I try to scroll in the div that is supposed to have the map, the scroll event is fired, but nothing is shown.
I added the CUSTOM_ELEMENTS_SCHEMA like I saw in some other questions, and I updated the Map.swift in iOS but it didn't change anything. I know that my google API keys are working because I just created them for this project and the goog cloud platform shows that my API keys are called.

### Expected Behavior
I expect to see the map, like I see it in the web version

### Code Reproduction
[Here is public repo](https://github.com/LukasBrass/ionic-capacitor-google-maps-test). In this project I also have a test for notifications I implemented before the google maps so I know that it works, but I can remove it for the reproduction if it is necessary.

Thanks a lot !

**Comment by mannok** [comment]
Same issue

**Comment by mannok** [comment]
Same issue

**Comment by ProXyTG** [comment]
any updates on this one???

`java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.app,`

**Comment by mahen23** [comment]
This bug is present since June 17th and its almost 2023 and still NO FIX. I have been forced to revert back to AGM Core maps just to get our apps running. Imagine how many thousands of developers around the world and installing the latest "@capacitor/google-maps": "^4.3.0"  and spend hours debugging it just to find out there is an unfixed bug since JUNE 17th!

**Comment by guillermodelagala** [comment]
Same problem here using capacitor 4. Is there any update on this?

**Comment by mannok** [comment]
> Same problem here using capacitor 4. Is there any update on this?

I suggest developer not to use capacitor/ionic anymore. Bad support, bad performance and not even a stable approach to develop a stable app

**Comment by jcesarmobile** [comment]
I've updated the provided test app to Capacitor 4 and then to Capacitor 5 and to the latest version of @capacitor/google-maps and the map is showing on iOS.
On Android it's working after adding this to the variables.css
```
ion-content {
  --background: transparent;
}
body {
  background: transparent;
}
```
it's documented that making things transparent is a requirement for android
https://capacitorjs.com/docs/apis/google-maps#usage

**Comment by jcesarmobile** [comment]
As I said, I tested on the provided test app. In other apps there might be other issues.
If somebody faces the same issue on Capacitor 5 and version 5 of google maps plugin, please, report a new issue and provide a sample app.
