### ISSUE TITLE
iOS Camera timer not available

### ISSUE THREAD

**Issue by kinggolf** [ionic-team/capacitor-plugins#1070]
### Plugin(s)
Camera Version 1.3.1

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/ios: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
```

### Platform(s)
iOS

### Current Behavior
Opening camera using this plugin on iOS does not show timer option that appears when opening the camera directly on iPhone.

![IMG_1470](https://user-images.githubusercontent.com/9776423/176234235-ec0cd5ba-1504-4fca-bf80-0feb3a7f65fd.PNG)

### Expected Behavior
Opening camera directly on iPhone presents timer option.

![IMG_1469](https://user-images.githubusercontent.com/9776423/176234279-ff4298d7-4a6a-421d-b3db-305b1cb305df.PNG)

### Code Reproduction
```
    const ImageOptions: ImageOptions = {
      quality: 90,
      source: CameraSource.Camera,
      allowEditing: false,
      direction: CameraDirection.Front,
      resultType: CameraResultType.Uri,
    };
    if (this.platform.is('ios')) {
      ImageOptions.width = 800;
    }
    const myPhoto: Photo = await Camera.getPhoto(ImageOptions);
```

### Other Technical Details
Timer is still available on Android when using this plugin.

### Additional Context
Not sure if this is a bug or feature request or even if it possible. Thanks.

**Comment by jcesarmobile** [comment]
It's not possible, we use what the system APIs provide, it doesn't have the same features as camera app.

**Comment by kinggolf** [comment]
Thanks again.
