### ISSUE TITLE
Storage | Multiple groups

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor-plugins#1071]
### Plugin

- Storage

### Description

I would like to define different Storage groups for different purposes so that `clear()` is easier to use. For example when the user applies for tracking, I dont want this approval to be cleared on logout when storing user related stuff.

### Platform(s)

- ios
- android
- pwa
- web
- ...

### Preferred Solution

- Storage.get({ key: "", group: "" })
- Storage.set({ key: "", value: "", group: "" })

### Alternatives

Storage.configure could return a cloned Storage instance with the group name applied.

**Comment by jcesarmobile** [comment]
Whenever you call configure, following calls to set/get/remove/clear/keys will query the last configured group and won't affect other groups, then if you want to go back to the previous group just use configure again with an existing group and set/get/remove/clear/keys will use the new group.
