### ISSUE TITLE
@capacitor/camera: exif gps on Android is alway "0/1,0/1,0/1"

### ISSUE THREAD

**Issue by kyoz** [ionic-team/capacitor-plugins#1074]
### Plugin(s)

- @capacitor/camera: 1.3.1

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.6.0
  @capacitor/ios: 3.6.0
  @capacitor/android: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android

Tested on Android 12 Phone

### Current Behavior

On iOS, the exif return with has gps info like latitude, longitude is correct.

On Android the exif return also has those info, but they's alway "0/1,0/1,0/1"

I'v tried request for geolocation permission on Android but it's still the same.

![Screen Shot 2022-07-01 at 00 14 34](https://user-images.githubusercontent.com/29815830/176739850-ca61f488-7b9e-43a6-a04b-3bb61eb4913a.png)

### Expected Behavior

Should return correctly GPS info on Android

### Code Reproduction

```js
const res = await Camera.pickImages({
    quality: 70,
    height: 1920,
    correctOrientation: true,
});

console.log(res);
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by kyoz** [comment]
I've found that, there is not the problem of the plugin, I've tested on all iOS and Android Simulator version, they all work fine.

The problem I've showed that only occurred on my Samsung Note 10+ phone, so I think there maybe something to do with it.

Since it's not the bug of @capacitor/camera. I'll close this issue for now, till on finding something new.

For anyone facing this problem, here is a similar issue: https://github.com/ivpusic/react-native-image-crop-picker/issues/1810

**Comment by kyoz** [comment]
For anyone who face this issue, i'v found the reason.

In Android with SDK >=29, you need `ACCESS_MEDIA_LOCATION` permission.

```
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" android:minSdkVersion="29" />
```

Request for permission before pick image and then GPS will return correctly 😄
