### ISSUE TITLE
Google Maps onmarkerclick-listener not working on Android

### ISSUE THREAD

**Issue by trabdin** [ionic-team/capacitor-plugins#1076]
### Plugin(s)

@capacitor/google-maps

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

When pressing a marker in the map, nothing happens, despite it working perfectly fine on iOS. (The only thing that happens is that two icons appear on the lower right, a directions icon and a google maps icon).

Have I missed something special you need to do for this to work on Android or should it work the same as on iOS?

### Expected Behavior

The function in my listener should be run:

```
await this.newMap.setOnMarkerClickListener((event: any) => {
        console.log('HERE');
});
```

### Code Reproduction

```
await this.newMap.setOnMarkerClickListener((event: any) => {
        console.log('HERE');
});
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
