### ISSUE TITLE
Storage is not storing boolean value

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor-plugins#1077]
### Plugin(s)

"@capacitor/storage": "^1.2.5",

### Capacitor Version

```
npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.1

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

boolean value is not getting stored.  Is there any way to debug it. 
Also I am not storing much data in it. On web it is working properly.

### Expected Behavior

It should store the boolean value as per doc **This method can also be used to store non-string values, such as numbers and booleans.**

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by indraraj26** [comment]
Hi @jcesarmobile ,

I have refactor it little bit and came to know that boolean value is not getting stored. If I am trying to store string it will work.

Repo: https://github.com/indraraj26/storage-boolean-issue
![image](https://user-images.githubusercontent.com/23274631/177477283-341b3cae-98f3-486c-8c12-d60f2a028ea5.png)

**Comment by jcesarmobile** [comment]
Storage plugin only stores strings, not numbers nor Boolean.

https://capacitorjs.com/docs/apis/storage#setoptions

There is a feature request for adding other types
https://github.com/ionic-team/capacitor-plugins/issues/1009

What the doc says is

> Working with JSON
> 
> The Storage API only supports string values. You can, however, use JSON if you JSON.stringify the object before calling set(), then JSON.parse the value returned from get().
> 
> This method can also be used to store non-string values, such as numbers and booleans.

Meaning you can use JSON.stringify to store objects, booleans or numbers, but in your code you only stringify objects, not the booleans or numbers.

https://capacitorjs.com/docs/apis/storage#working-with-json
