### ISSUE TITLE
Browser cannot open some links

### ISSUE THREAD

**Issue by Orilow** [ionic-team/capacitor-plugins#1081]
### Plugin(s)

`"@capacitor/browser": "1.0.7"`

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/ios: 3.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

`ios`

### Current Behavior

on ios im trying to direct user to download new version of an app. 
`await Browser.open({ url: itms-services://?action=download-manifest&url=some_kind_of_url_to_download });`
but nothing happens on user screen and in console I get this error

<img width="643" alt="image" src="https://user-images.githubusercontent.com/32433465/178668137-5cbe6221-81b7-4132-a81b-d4a6e78b986c.png">

i fixed it with `window.open` but it doesn't seem the right way with capacitor...

### Expected Behavior

on ios browser can open all types of links.

### Code Reproduction

`await Browser.open({ url: itms-services://?action=download-manifest&url=some_kind_of_url_to_download });`
you need to replace `some_kind_of_url_to_download` on url to **plist** file of ios app

**Comment by jcesarmobile** [comment]
Browser plugin can only open http/https urls, it's a limitation on the native component used by the plugin.

For opening app links you can use @capacitor/app-launcher plugin instead, or probably using window.open could work too.
