### ISSUE TITLE
Impossible to paste image if it has text alternative

### ISSUE THREAD

**Issue by iBobik** [ionic-team/capacitor-plugins#1083]
### Plugin(s)

Clipboard

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/core: 3.6.0
```

### Platform(s)

Tested on iOS, but by [source](https://github.com/ionic-team/capacitor-plugins/blob/main/clipboard/android/src/main/java/com/capacitorjs/plugins/clipboard/Clipboard.java) it seems like Android has similar problem.

### Current Behavior

When copied image from e-g- Safari system will record not only the image, but also URL of the image or href of the link. But capacitor plugin tries to read text version first, so it will never try to fetch image.

Only way how to read image is to save it to the gallery and copy it from there, so origin URL will not be in the clipboard. And even then it gives me just PNG version, original file is JPG.

### Expected Behavior

Ideally I can decide what variant and format is preferred or get all available variants.

Or at least move image read to the first.

### Other Technical Details

https://github.com/ionic-team/capacitor-plugins/blob/main/clipboard/ios/Plugin/Clipboard.swift
https://github.com/ionic-team/capacitor-plugins/blob/main/clipboard/android/src/main/java/com/capacitorjs/plugins/clipboard/Clipboard.java

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by iBobik** [comment]
@jcesarmobile Really? It is obvious, see linked sources.

**Comment by jcesarmobile** [comment]
Sorry, I don’t make the rules, a sample app is required for us to investigate.

**Comment by iBobik** [comment]
It is a good rule, but following rules blindly could waste human resources. I am not going to waste my.
