### ISSUE TITLE
Marker(s) can be draggable so a setOnMarkerDragEndListener method would be nice

### ISSUE THREAD

**Issue by chrisweb** [ionic-team/capacitor-plugins#1089]
### Plugin
@capacitor/google-maps

### Description
We can set a Marker to be "draggable", but there is no function like setOnMarkerDragEndListener(…) to listen to the drop happening, this means we don't know when or where the marker got dropped (the drag ended) on the map

### Platform(s)
All please :) 

### Preferred Solution
The one that works best... no but seriously now, I always feel bad for filling out feature requests and not doing it myself, but I'm behind in my shedule already, so I can't offer my help at this time to work on a PR. but I thought it would be nice to have a ticket, even if it is only to have a place where people can subscribe to get updates

### Alternatives
My alternative right now is that instead of dragging the marker, the user clicks to set the marker and if he wants to have it somewhere else he clicks on a new location, I remove the previous marker and create a new one at the location the user just clicked, luckily for me I have only one marker to manage at a time so this works

### Additional Context
not really

**Comment by elabayoub** [comment]
Due to the lack of this feat, i have to use another library.

**Comment by dallastjames** [comment]
As a heads up @elabayoub, if this specifically was the deal breaker for you, it will be coming in the next release of this plugin. The PR for it just went up today https://github.com/ionic-team/capacitor-plugins/pull/1155. 👍

**Comment by chrisweb** [comment]
Amazing, I just saw the PR landed in release 4.2.0, thank you @ItsChaceD :)

**Comment by jcesarmobile** [comment]
Closing since this was included in 4.2.0 version of google-maps plugin.
The other mentioned issue is also fixed, but not released yet.
