### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: "Geolocation" plugin is not implemented on ios

### ISSUE THREAD

**Issue by yannickcare** [ionic-team/capacitor-plugins#1094]
## Bug Report
When running my Angular 14 app using Capacitor, I am getting the error: 
   ERROR Error: Uncaught (in promise): Error: "Geolocation" plugin is not implemented on ios

### Plugin(s)
"@capacitor/geolocation": "^1.3.1",

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/cli: 3.6.0
  @capacitor/ios: 3.6.0

```

### Platform(s)
IOS

### Current Behavior
When running the app, and trying to get the current position

### Expected Behavior
Getting the current position

### Code Reproduction
```
private async setCurrentLocation() {
    console.log('Set Current Position');
    let perm = await Geolocation.checkPermissions();
    console.log('Perm', perm);
    if (perm !== PermissionStatus['granted']) {
      await Geolocation.requestPermissions();
    }

    Geolocation.getCurrentPosition({
      timeout: 6000,
      enableHighAccuracy: true,
      maximumAge: 1,
    })
      .then((coordinates) => {
        this.latitude = coordinates.coords.latitude;
        this.longitude = coordinates.coords.longitude;
        this.zoom = 16;
        this.getAddress(this.latitude, this.longitude);
        this.geoEnable = true;
      })
      .catch((error) => {
        notify('Location is not available', 'error');
        this.geoEnable = false;
      });
  }
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by yannickcare** [comment]
I see the same result on Android (Pixel 5)
```
Msg: ERROR Error: Uncaught (in promise): Error: "Geolocation" plugin is not implemented on android
    Error: "Geolocation" plugin is not implemented on android
```

**Comment by jcesarmobile** [comment]
Please, provide a sample app so we can investigate

**Comment by yannickcare** [comment]
Since I am using NX.js, had to add 

```
  includePlugins: ["@capacitor/geolocation", "@capacitor/status-bar"]
```

in the capacitor.config.ts

this solved it.
