### ISSUE TITLE
Android 13 (API level 33) introduces a new runtime permission for notifications

### ISSUE THREAD

**Issue by bhandaribhumin** [ionic-team/capacitor-plugins#1116]
## Feature Request

Android 13 (API level 33) introduces a new [runtime permission](https://developer.android.com/guide/topics/permissions/overview#runtime) for sending [non-exempt](https://developer.android.com/about/versions/13/changes/notification-permission#exemptions) notifications from an app: [POST_NOTIFICATIONS](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS).

### Plugin

Currently this plugin doesn't work when we set notifications because user don't see runtime permission popup on Android 13.

### Preferred Solution

- I have implemented this fix for Cordova in this repo [cordova-plugin-local-notification-12](https://github.com/bhandaribhumin/cordova-plugin-local-notification-12)

- I have added few changes to get permission popup [FIX](https://github.com/bhandaribhumin/cordova-plugin-local-notification-12/blob/master/src/android/LocalNotification.java#L214)

- The permission that you need to declare in your app's manifest file appears in the following code snippet:

`<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>`

### Additional Context

![Screenshot 2022-08-08 at 7 09 50 PM](https://user-images.githubusercontent.com/3336047/183431559-d64edbb1-bd77-455a-9653-91161a50d949.png)

**Comment by bhandaribhumin** [comment]
any update?

**Comment by jcesarmobile** [comment]
Please, don’t ping me.
