### ISSUE TITLE
@capacitor/app-launcher ionic capacitor run android error 

### ISSUE THREAD

**Issue by BenzHuang** [ionic-team/capacitor-plugins#1121]
### Plugin(s)

@capacitor/app-launcher

### Capacitor Version

v4.0.0

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1

[success] Android looking great! 
```

### Platform(s)

Android 11

### Current Behavior

run `ionic capacitor run android`

error: 
 /Users/xxx/Projects/xxx/xxxx/node_modules/@capacitor/app-launcher/android/src/main/java/com/capacitorjs/plugins/applauncher/AppLauncherPlugin.java:3: error: package android.content does not exist

### Expected Behavior

run `ionic capacitor run android` is success

### Code Reproduction

/android/variables.gradle
```
ext {
    minSdkVersion = 30
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '10.1.1'
}
```

Command
```
npm install @capacitor/app-launcher
npx cap sync
ionic capacitor run android
```

### Other Technical Details

/android/build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        classpath 'com.google.gms:google-services:4.3.5'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

### Additional Context

java sdk vesrion: 11

**Comment by IT-MikeS** [comment]
It looks like your migration is incomplete to v4 of capacitor. Take a look at this similar issue: https://github.com/ionic-team/capacitor/issues/5824

**Comment by jcesarmobile** [comment]
Version 4 or capacitor plugins are meant to be used with Capacitor 4, but you are still using Capacitor 3.
Downgrade the plugin to 1.x or upgrade Capacitor to 4 following this guide: https://capacitorjs.com/docs/updating/4-0

**Comment by BenzHuang** [comment]
Resolved. The Gradle Plugin Version should be 7.2.1 or later and the Gradle Version should be 7.4.2 or later
