### ISSUE TITLE
Migrated to Capacitor 4, now dependency problem with Capacitor/Storage

### ISSUE THREAD

**Issue by Th-Barth** [ionic-team/capacitor-plugins#1123]
Hello there,

I ve updated my project to Capacitor 4 . Now I ve a dependency problem with Capacitor/Storage. It depends on Capacitor/core 3?

I tried to reinstall @capacitor/storage, but always the same problem. I read that some people delete their node_modules folder. I only deleted the entry @capacitor/storage. After the reinstallation I get the same values. Is this broken now?

package.json of @capacitor/storage
[...]
 "devDependencies": {
    "@capacitor/android": "^3.0.0",
    "@capacitor/core": "^3.0.0",
    "@capacitor/docgen": "0.0.18",
    "@capacitor/ios": "^3.0.0",
[...]

npm uninstall @capacitor/storage

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @capacitor/storage@1.2.5
npm WARN Found: @capacitor/core@4.0.1
npm WARN   peer @capacitor/core@"^4.0.0" from @capacitor/android@4.0.1
npm WARN   node_modules/@capacitor/android
npm WARN     @capacitor/android@"4.0.1" from the root project
npm WARN   8 more (@capacitor/app, @capacitor/camera, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @capacitor/core@"^3.0.0" from @capacitor/storage@1.2.5
npm WARN node_modules/@capacitor/storage
npm WARN
npm WARN Conflicting peer dependency: @capacitor/core@3.7.0
npm WARN node_modules/@capacitor/core
npm WARN   peer @capacitor/core@"^3.0.0" from @capacitor/storage@1.2.5
npm WARN   node_modules/@capacitor/storage

removed 2 packages, and audited 1314 packages in 2s

176 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm install @capacitor/storage@latest --force

npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @capacitor/storage@1.2.5
npm WARN Found: @capacitor/core@4.0.1
npm WARN node_modules/@capacitor/core
npm WARN   peer @capacitor/core@"^4.0.0" from @capacitor/android@4.0.1
npm WARN   node_modules/@capacitor/android
npm WARN     @capacitor/android@"4.0.1" from the root project
npm WARN   8 more (@capacitor/app, @capacitor/camera, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @capacitor/core@"^3.0.0" from @capacitor/storage@1.2.5
npm WARN node_modules/@capacitor/storage
npm WARN   @capacitor/storage@"1.2.5" from the root project
npm WARN
npm WARN Conflicting peer dependency: @capacitor/core@3.7.0
npm WARN node_modules/@capacitor/core
npm WARN   peer @capacitor/core@"^3.0.0" from @capacitor/storage@1.2.5
npm WARN   node_modules/@capacitor/storage
npm WARN     @capacitor/storage@"1.2.5" from the root project

added 1 package, and audited 1315 packages in 2s

176 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ecap-app@0.0.1
npm ERR! Found: @capacitor/core@4.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^4.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @capacitor/storage@1.2.5
npm ERR! node_modules/@capacitor/storage
npm ERR!   @capacitor/storage@"^1.2.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

Angular CLI: 14.1.2
Node: 16.15.1
Package Manager: npm 8.17.0 
OS: win32 x64

Angular: 14.1.2
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.2
@angular-devkit/build-angular   14.1.2
@angular-devkit/core            14.1.2
@angular-devkit/schematics      14.1.2
@schematics/angular             14.1.2
rxjs                            6.6.7
typescript                      4.7.4

**Comment by IT-MikeS** [comment]
Storage was renamed to `preferences` so you will need to use `@capacitor/preferences` and replace `storage` imports in your code.

**Comment by IT-MikeS** [comment]
It is in the migration guide to v4 (https://capacitorjs.com/docs/updating/4-0#storage) but I'll look into getting a deprecation warning up on the npm package

**Comment by jcesarmobile** [comment]
npm now shows a deprecated warning for @capacitor/storage, closing
