### ISSUE TITLE
Error: "Storage" plugin is not implemented on android

### ISSUE THREAD

**Issue by vikicoder007** [ionic-team/capacitor-plugins#1134]
### Plugin(s)
@capacitor/preferences

### Capacitor Version

```
4.0.1
```

### Platform(s)
Android

### Current Behavior

Error on get , set  methods 
``
ERROR Error: Uncaught (in promise): Error: "Storage" plugin is not implemented on android
``

### Expected Behavior
with capacitor/storage there was no errors it was working perfectly then i replaced with preferences now it's throwing error

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by vikicoder007** [comment]
i am using angular 14 with capacitor 4 before i was using angular 13 and capacitor 3 with lot of plugins ,  i found that capacitor migration is bit of complex process so i decided to create new project and copy the old project files and fix the errors except the storage plugin one. just now i have created a basic project with only preferences capacitor plugin installed and there is no error at all. i  think error came because of some sort of caching or maybe there is other plugin conflicting or interfering with this preferences plugin i am not sure .

**Comment by vikicoder007** [comment]
Issue has been fixed it was because of other plugin when app was starting it downloaded old version of code from server which was using capacitor/storage plugin.
