### ISSUE TITLE
@capacitor/preferences returned value is null on android

### ISSUE THREAD

**Issue by Th-Barth** [ionic-team/capacitor-plugins#1144]
Hello
I tested my app on smartphone today and saw a problem with preferences value. On web it works like expected, but on Android a certain value becomes null. It seems that default string value "1" becomes an integer in the set-method and cannot be saved? It drives me crazy, please help me :)

Here very simple to follow

export class Tab4Page implements OnInit {
 
  //default
  selected_product_id: string = "1";
[...]

 async ionViewDidEnter() {
    await Preferences.set({key: 'ordered_product_id', value: this.selected_product_id});

    const _product_id = await Preferences.get({ key: 'ordered_product_id' });
    console.log(`Tab4Page ionViewDidEnter() hello ordered_product_id ${_product_id.value}!`);

    this.loadProducts();
}

Output in Android
V/Capacitor: callback: 59580685, pluginId: Preferences, methodName: set, methodData: {"key":"ordered_product_id","value":1}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 59580686, pluginId: Preferences, methodName: get
V/Capacitor: callback: 59580686, pluginId: Preferences, methodName: get, methodData: {"key":"ordered_product_id"}

I/Capacitor/Console: File: http://localhost/src_app_tab4_tab4_module_ts.js - Line 515 - Msg: Tab4Page ionViewDidEnter() hello ordered_product_id null!

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Th-Barth** [comment]
Hello,
the error happened in a method. Because of the parameter product_id of type string I thought I get a string. But it was a number

before
async setSelectedProductID(product_id: string) {
    console.log("Tab4Page setSelectedProduct() Product-ID", product_id);
    this.selected_product_id = product_id;
    await Preferences.set({key: 'ordered_product_id', value: product_id});
  }

I changed the type of parameter product_id to number to not get confused in the future any more and extended it in the method block to ""+product_id to make sure it is a string!

after
async setSelectedProductID(product_id: number) {
    console.log("Tab4Page setSelectedProduct() Product-ID", product_id);
    this.selected_product_id = ""+product_id;
    await Preferences.set({key: 'ordered_product_id', value: this.selected_product_id});
  }

The method setSelectedProductID is called in the template and item.product_id is a number

<ion-item button *ngFor="let item of products" (click)="setSelectedProductID(item.product_id)">

**Comment by jcesarmobile** [comment]
Yeah, the plugin only supports saving strings, you can also use JSON.stringify(value); in case you want to save other types such as arrays or simple objects, that would turn them into strings and would be saved,
