### ISSUE TITLE
@capacitor/camera - getPhoto doesn't respect the user permissions on iOS

### ISSUE THREAD

**Issue by pedromiba** [ionic-team/capacitor-plugins#1147]
## Bug Report

On iOS `getPhoto` doesn't respect the user permissions. 
If we only allow access to 2 photos we shouldn't be presented with the entire gallery.

### Plugin(s)

@capacitor/camera 4.1.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behaviour
When I am trying to add a new photo from the library in iOS, it first gives me the option to select from all my photos in my library, and then it presents me with the full gallery with unauthorised photos.

### Expected Behaviour
When trying to add a new photo from the library in iOS, at first it should ask you to "Select More Photos..." or "Keep Current Selection" then you should choose from one of the selected photos.

### Code Reproduction
[Repository with an example of the issue](https://github.com/pedromiba/photo-library-issue-example)

**Comment by jcesarmobile** [comment]
Sadly that's how the native picker works, there is nothing we can do about it, the only difference with the pictures you granted access and the other you didn't grant access is the ones you didn't grant access don't include sensitive information (exif).
On version 4.1.0 of the plugin released yesterday it includes two new methods, one that allows you to present a picker to change the selection and another method that returns all the images that have been granted full access, but still is not what you want.
