### ISSUE TITLE
(android) change output of screen-reader to accessibility audio stream

### ISSUE THREAD

**Issue by Dervol03** [ionic-team/capacitor-plugins#1154]
### Plugin
`@capacitor/screen-reader`

### Description
Currently, the `ScreenReader.speak()` method uses the default audio stream of the Android's TextToSpeech, which is the music-stream.
The issue is that Android now has a separate accessibility stream, which users depending on assisitive technologies can configure to their liking. Thus, the output of the plugin is most likely either louder or quieter then the volume preferred by the user for their assistive technologies (the latter being worse, of course, as they might overhear the output).

Therefore, it would be good to either switch the output channel to the accessibility stream (aka `AudioManager.STREAM_ACCESSIBILITY` or to allow the plugin user to decide which channel they'd like to use.

### Platform(s)
Android

### Preferred Solution
Default the plugin's `speak()` output to the accessibility audio stream.

### Alternatives
Make the output configurable to the user.

### Additional Context

If I understand it correctly, the relevant changes would be to add the parameters to the `speak()` method:

```java
public void speak(final String text, final String languageTag) {
        if (isEnabled()) {
            final Locale locale = Locale.forLanguageTag(languageTag);
            final Bundle speakParams = new Bundle();
            speakParams.putInt(TextToSpeech.Engine.KEY_PARAM_STREAM, AudioManager.STREAM_ACCESSIBILITY);

            textToSpeech =
                new TextToSpeech(
                    context,
                    status -> {
                        textToSpeech.setLanguage(locale);
                        textToSpeech.speak(text, TextToSpeech.QUEUE_FLUSH, speakParams, "capacitor-screen-reader" + System.currentTimeMillis());
                    }
                );
        }
    }
```

**Comment by jcesarmobile** [comment]
I've tried that code you provided and it's not working (the speak function no longer speaks and if I call it twice the app crash without showing any error).

I've tried setting the `TextToSpeech` audio attributes, but not sure how can I know if it's working, I notice no difference.

```
AudioAttributes attributes = new AudioAttributes.Builder().setUsage(USAGE_ASSISTANCE_ACCESSIBILITY).build();
textToSpeech.setAudioAttributes(attributes);
```

**Comment by Dervol03** [comment]
The way you can test it is as follows:
On the android phone, play some media (e.g. music) and turn down/off the volume (this should turn down the regular media-output). Then activate TalkBack (settings -> accessibility). When TalkBack says something, turn up the volume, which should turn up the accessibility-channel respectively.
Once done, trigger the manual `speak()` call. If it is as loud as TalkBack before, the change worked. If its very low or even mute, then it's still running on the media output channel.

**Comment by jcesarmobile** [comment]
Thanks, I've been able to test. In fact some of my devices show the accessibility icon for the TalkBack volume.

With my proposed change, speak is respecting the configured TalkBack volume, but not any of the other TalkBack configurations (pitch, speech rate, etc.), is that good enough?

Those values can also be configured, but I can't get the actual values to make them match.

**Comment by Dervol03** [comment]
Well, if it works volume-wise, it's already a great improvement, I think. :)
Before, there was the risk that people who require it, may overhear what was sent via `speak()`. Pitch and speech rate are surely nice-to-haves, but I guess, that can be looked upon separately. :)

**Comment by Dervol03** [comment]
awesome, many thanks 👍
