### ISSUE TITLE
Can't scroll/move map on android

### ISSUE THREAD

**Issue by elabayoub** [ionic-team/capacitor-plugins#1157]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: not installed
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
```
Android
```

### Current Behavior

Map doesn't scroll or move on Android after migrating from cordova to capacitor (sometimes map doesn't even load), it's just stuck, i can't even move marker or do anything.
-> Tested on emulator (Android 9) & on device (Android 11)

### Expected Behavior

User should be able to move map and marker efficiently.

### Code Reproduction

google-maps.page.html
```
<ion-content style="height: 100%;width:100%;">
    <ion-button (click)="getPosition()" slot="fixed" class="get-position" color="tertiary">
      <ion-icon name="locate" class="navigation" size="25"></ion-icon>
    </ion-button>

    <div class="map-tip-holder">
      <ion-text class="map-tooltip">{{ position ? 'Validate' : 'Locate' }}</ion-text>
    </div>
  <capacitor-google-map #Cmap id="Cmap"></capacitor-google-map>
</ion-content>
```
google-maps.page.scss
```
#Cmap {
  display: inline-block;
  height: 100%;
  width: 100%;
  z-index: 999;
}
```
google-maps.page.ts
```
import {Geolocation} from "@capacitor/geolocation";
import {GoogleMap, Marker} from '@capacitor/google-maps';

@ViewChild('Cmap') mapElement: ElementRef;
    Cmap: GoogleMap;
```
Method called from `async ionViewDidEnter() {}` to load existing location or new one.
```
async initMap(lat, lng, withMarker?) {
        this.Cmap = await GoogleMap.create({
            id: 'google-map',
            apiKey: environment.mapsKey,
            element: this.mapElement.nativeElement,
            forceCreate: true, // disable later
            config: {
                center: {
                    lat: lat, //33.533908
                    lng: lng,//-7.123854
                },
                zoom: 16,
                androidLiteMode: true,
            },
        });
    }
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by elabayoub** [comment]
Code reproduction part has been provided.

**Comment by elabayoub** [comment]
Issue caused by the fact that the component is rendered before finishing loading, which created an overlapping (ion-content is on top of map).

**Comment by prupp** [comment]
I have exactly the same Problem. @elabayoub How did you fix it?
