### ISSUE TITLE
@capacitor/camera - pickLimitedLibraryPhotos doesn't return GalleryPhotos like API says

### ISSUE THREAD

**Issue by pedromiba** [ionic-team/capacitor-plugins#1158]
### Plugin(s)
@capacitor/camera 4.1.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.1.0
  @capacitor/ios: 4.1.0
  @capacitor/core: 4.1.0

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
When the user is prompted for permissions and decides to choose only 2 photos from its library we end up with a limited permission for photos. Then we have the method `pickLimitedLibraryPhotos` to allow the user to change these photos and perhaps add new ones, but there is no way of knowing when the user actually changes them, according to the API it should return `GalleryPhotos`.

### Expected Behavior
When using `pickLimitedLibraryPhotos` it should return the GalleryPhotos just like the method `getLimitedLibraryPhotos`.

### Code Reproduction
[Repository with example of the issue](https://github.com/pedromiba/camera-example)

Look at -> PhotoGallery.tsx -> handleManage

**Comment by SaroGFX** [comment]
I got the same issue, really need a fix for this
