### ISSUE TITLE
Front camera support for Android

### ISSUE THREAD

**Issue by garri1105** [ionic-team/capacitor-plugins#1166]
## Feature Request
Front camera support for Android

### Plugin
Camera

### Description
As of now, CameraDirection.Front only works for iOS and Web according to the docs. I confirmed that CameraDirection.Front doesn't work on my personal Android device. I also haven't seen any open issues or feature requests about this which is surprising. What are the reasons this basic functionality hasn't been implemented? 

### Platform(s)
Android

### Preferred Solution
Add support for front camera in Android

### Alternatives
No clue. Any ideas?

**Comment by jcesarmobile** [comment]
There is no official way of setting the front Camera on the Android Intent the Camera plugin uses.

There is an unofficial way, but it's not supported by all devices. I've tried in and worked on 2 of 5 of my devices, so it's not worth implementing as will just create confusion and complaints.
