### ISSUE TITLE
Ionic Capacitor Push Notification Invalid Platform token on SNS

### ISSUE THREAD

**Issue by joshuavillano** [ionic-team/capacitor-plugins#1167]
### Plugin(s)
@capacitor/push-notifications

### Capacitor Version
@capacitor/ios: 3.4.1
@capacitor/cli: 3.5.1
@capacitor/android: 3.5.1
@capacitor/core: 3.5.1

### Platform(s)
IOS

### Current Behavior
I've successfully setup Push Notifications for both iOS and Android via SNS.

However, when I deployed it to a Production app, SNS returns "Platform token associated with the endpoint is not valid" when sending to APNS tokens/endpoints.

I'm creating the platform application endpoint via the Key method (.p8), and I use the Capacitor Push plugin `.register()` to register device tokens.

Did I miss anything?

### Expected Behavior
Production Token

### Code Reproduction
Use of .register for Production APNS

**Comment by jcesarmobile** [comment]
Sorry, I have no experience with SNS, but capacitor push tokens are valid with regular APNS, so the problem is not on the plugin, it’s probably in some misconfiguration on your part in the communication between APNS and SNS.

**Comment by joshuavillano** [comment]
Yes this is confirmed, problem was on my configuration of bundleID. Sorry and thanks!
