### ISSUE TITLE
Update the docs of Push Notifications for iOS

### ISSUE THREAD

**Issue by colenso** [ionic-team/capacitor-plugins#1170]
### Plugin
Capacitor Push Notifications Plugin @capacitor/push-notifications

### Description
The current documentation in https://capacitorjs.com/docs/apis/push-notifications doesn't mention :
1. We need to add Firebase SDK to the iOS project via cocoapods. I had to dig and find that in a separate document here https://capacitorjs.com/docs/guides/push-notifications-firebase#add-the-firebase-sdk-via-cocoapods
2. We need to create and add the APNS Key to the Google Firebase project and then add the `GoogleService-Info.plist` file to the iOS project. I found out about that here https://capacitorjs.com/docs/guides/push-notifications-firebase#integrating-firebase-with-our-native-ios-app

### Platform(s)
iOS

### Preferred Solution
The 2 separate docs https://capacitorjs.com/docs/apis/push-notifications and https://capacitorjs.com/docs/guides/push-notifications-firebase should be combined.

**Comment by jcesarmobile** [comment]
The plugin docs are for using push notifications with APNS, which is the iOS way of sending push notifications.

Then, if you want to use FCM for iOS we have the separate guide for that, but it's not mandatory to use FCM on iOS, so docs should not be combined as you don't need FCM for sending push notifications for iOS, it's just an option.
