### ISSUE TITLE
splashScreen config showSpinner is true but not working Android

### ISSUE THREAD

**Issue by diendv** [ionic-team/capacitor-plugins#1174]
Hi guys
I just recreated the application using capacitor 4.0.1 but when I start the app up on splashcreen screen I have showSpinner config is true but it doesn't work, no effect.
Hope someone can explain to me what's wrong
Thank you !

This is my configuration:

const config: CapacitorConfig = {
  appId: 'com.xxx.xxx',
  appName: 'AppName',
  webDir: 'www',
  bundledWebRuntime: false,
  plugins: {
    SplashScreen: {
      launchAutoHide: false,
      backgroundColor: "#FFFFFF",
      androidSplashResourceName: "splash",
      androidScaleType: "CENTER_CROP",
      androidSpinnerStyle: "horizontal",
      iosSpinnerStyle: "small",
      spinnerColor: "#ffc409",
      showSpinner: true
    },
    PushNotifications: {
      presentationOptions: ["badge", "sound", "alert"]
    },
    LocalNotifications: {
      smallIcon: "logo.png",
      iconColor: "#170085",
      sound: "notify_sound.mp3"
    }
  }
};

export default config;

/**********/
Ionic:

   Ionic CLI                     : 6.20.1
   Ionic Framework               : @ionic/angular 6.2.1
   @angular-devkit/build-angular : 14.1.1
   @angular-devkit/schematics    : 14.1.1
   @angular/cli                  : 14.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0
   npm    : 8.5.5

**Comment by jcesarmobile** [comment]
Most configuration options are useless now when using the new Android 12 Splash Screen API, the docs have been updated and specify it, every option that is no longer supported says something like "Doesn't work on launch when using the Android 12 API.". That is specified on all the spinner options.

If you want to go back to the old behavior, you can disable the Android 12 Splash Screen API for Android < 12 (SDK < 31) by changing `Theme.SplashScreen` to `AppTheme.NoActionBar` on the `AppTheme.NoActionBarLaunch` style.
The Android 12 Splash Screen API can't be disabled for SDK 31+ devices.
