### ISSUE TITLE
(google-maps) setOnMarkerClickListener and setOnCameraIdleListener not working

### ISSUE THREAD

**Issue by hanslbua** [ionic-team/capacitor-plugins#1176]
[capApp.zip](https://github.com/ionic-team/capacitor-plugins/files/9623298/capApp.zip)
### Plugin(s)
@capacitor/google-maps@4.2.0

### Capacitor Version
Capacitor Doctor

Latest Dependencies:       

  @capacitor/cli: 4.2.0    
  @capacitor/core: 4.2.0   
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0    

Installed Dependencies:    

  @capacitor/cli: 4.1.0    
  @capacitor/android: 4.1.0
  @capacitor/core: 4.1.0   
  @capacitor/ios: 4.1.0 

### Platform(s)
Android and iOS

### Current Behavior
setOnMarkerClickListener and setOnCameraIdleListener not working

### Expected Behavior
setOnMarkerClickListener and setOnCameraIdleListener should work :D

#### map.component.html

`<capacitor-google-map #map></capacitor-google-map>`

#### map.component.ts

```
@ViewChild('map', {static: true}) mapContainer: ElementRef;

ngOnInit() {
     this.mapService.initMap(this.mapContainer.nativeElement);
}
```

#### map.service.ts

```
async initMap(nativeElement: any) {
    
    let start_lat = 48.208553;
    let start_lng = 16.373027;

      await GoogleMap.create({
        id: 'cool_map',
        element: nativeElement,
        apiKey: "here_key",
        config: {
          center: {
            lat: start_lat,
            lng: start_lng,
          },
          zoom: 14
        },
      }).then((map: GoogleMap) => {
        this.map = map;

        this.map.setMapType(MapType.Normal);

        this.map.enableCurrentLocation(true);

        this.map.enableClustering();

        this.map.setOnCameraIdleListener((data: CameraIdleCallbackData) => {
          console.log("CameraIdleCallback");
        });

        this.map.setOnMarkerClickListener(async (data: MarkerClickCallbackData) => {
          console.log("Marker clicked");
        });
      });


}
```

**Comment by hanslbua** [comment]
i created a testapp with the code in it.

you can download the project [here](https://we.tl/t-ZeFw6NXPwY)

**Comment by hanslbua** [comment]
i also made a comment in the initMap call. i have to put a setTimeout around, to get the map loaded. is this also an issue?

**Comment by jcesarmobile** [comment]
The link says the download expired, can you attach the project to the original message or a comment or commit it to github?

**Comment by hanslbua** [comment]
hey. i added the zip file direct to the posts.

**Comment by jcesarmobile** [comment]
I can reproduce the setOnMarkerClickListener not working on Android, it's working fine on iOS.

For setOnCameraIdleListener, you have not set the camera. If I add this to your app I see the event on iOS. I don't see it on Android.

```
this.map.setCamera({
          coordinate: {
              lat: start_lat,
              lng: start_lng
          },
          angle: 45,
          bearing: 200,
          zoom: 12,
          animate: true,
          animationDuration: 50,
      });
```

**Comment by Binyam-Yohannes** [comment]
I encountered also the same problem. setOnMarkerClickListener  and setOnBoundsChangedListener are not working on Android platform. Any update on this issue?

**Comment by jcesarmobile** [comment]
resolved on https://github.com/ionic-team/capacitor-plugins/pull/1227

**Comment by hanslbua** [comment]
when will it be published?
