### ISSUE TITLE
update content in existing local notification?

### ISSUE THREAD

**Issue by basbroens** [ionic-team/capacitor-plugins#1178]
I'm building a live tracker app and i would like to get the current speed of the user in the localNotification.

Is this possible?

i tried:

`  vm.ids = Math.floor(Math.random() * 10000) + 1;
                 
                    LocalNotifications.schedule({
                        notifications: [
                            {
                                title       : 'Title' + vm.currentSpeed+ ' m',
                                body        : '<btn>TEST</btn>',
                                ongoing     : true,
                                id          : vm.ids,
                                sound       : null,
                                vibrate     : false,
                                attachments : null,
                                actionTypeId: '',
                                extra       : null,
                            },
                        ],
                    });`

But this opens a new notifcation each time.

**Comment by jcesarmobile** [comment]
No, you can't.
But if you always use the same id then the notification will be replaced instead of showing a new one.
