### ISSUE TITLE
Share plugin: sharing on facebook does not work as expected

### ISSUE THREAD

**Issue by moblizeit** [ionic-team/capacitor-plugins#1182]
My payload goes like below:

```
 await Share.share({
      title: 'Got new badge: ' + this.core.badges[0].title,
      text: this.core.badges[0].description,
      url: this.core.badges[0].url,
      dialogTitle: 'Share with buddies',
    });
```

when i am sharing on the facebook what happens is that no text gets added to the post and just the url which in the meta text shows the name of the url. Is that the expected behavior?  with the passed text or title the sharing looks useless. 

here is how it looks: https://www.dropbox.com/s/j32awt5vvph29rn/Screenshot_20220915-224946_Facebook.jpeg?dl=0

**Comment by jcesarmobile** [comment]
Yeah, it's up to the receiving app to handle what they allow and what not, and facebook doesn't accept predefined texts like title or descriptions (so users have to type them manually).
https://developers.facebook.com/support/bugs/332619626816423/
