### ISSUE TITLE
Splash screen not working

### ISSUE THREAD

**Issue by sys-walker** [ionic-team/capacitor-plugins#1183]
### Plugin(s)
@capacitor/splash.screen

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android: Fails
iOS: Not tried

### Current Behavior
Android API <31
[Stretched -Real device (Xiaomi Redmi7 : Android10 )](https://postimg.cc/1fcM8TCX)

Android API >= 31
[Black screen -Real device (Xiaomi Redmi Note 10 Pro  : Android12 )](https://postimg.cc/gwqzw3X3)

### Expected Behavior
Android API <31
splash without stretching

Android API >= 31
[Expected -Emulator Pixel2](https://postlmg.cc/0K5gSxC5)

### Code Reproduction
Just create a sample project and install @capacitor/splash-screen
```
"plugins": {
		"SplashScreen": {
			"launchShowDuration": 3000,
			"launchAutoHide": true,
			"backgroundColor": "#ffffffff",
			"androidScaleType": "CENTER_CROP",
			"showSpinner": false,
			"androidSpinnerStyle": "large",
			"iosSpinnerStyle": "small",
			"spinnerColor": "#999999",
			"splashFullScreen": true,
			"splashImmersive": true
		}
	}
```
Add custom icon and splash using ```cordova-res``` or using Android Studio or just default assets of ionic

**Comment by jcesarmobile** [comment]
> NOTE: Some issues may exist on SDK >= 31 when using the new API for the splash screen, which pertain to the splash screen only showing when launched from the launcher icon. [Google Issue Tracker](https://issuetracker.google.com/issues/205021357)

https://capacitorjs.com/docs/apis/splash-screen#android-12-splash-screen-api
