### ISSUE TITLE
Splash Screen Plugin - Android 12 with fallback?

### ISSUE THREAD

**Issue by jlachniet** [ionic-team/capacitor-plugins#1186]
### Plugin

Splash Screen Plugin

### Description

Right now, using the Android 12 API for Capacitor prevents the user from defining a fallback splash screen. If your app is taking a while to load (with autoHide disabled), this means that during the loading period non-Android 12 users get an empty screen.

### Platform(s)

Android

### Preferred Solution

Allow the user to use the Android 12 API for splash screens while still allowing a fallback splash screen for lower APIs.

**Comment by jcesarmobile** [comment]
The Splash Screen plugin uses the [AndroidX SplashScreen](https://mvnrepository.com/artifact/androidx.core/core-splashscreen) compat library, so it supports any Android version.

Also, you can opt out of the Android 12 Splash Screen on older devices by changing the Splash Screen theme back to `AppTheme.NoActionBar`.
