### ISSUE TITLE
CocoaPods could not find compatible versions for pod "CapacitorSplashScreen"

### ISSUE THREAD

**Issue by rosman21** [ionic-team/capacitor-plugins#1193]
### Plugin(s)
@capacitor/splash-screen

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
Returns Error
```
[!] CocoaPods could not find compatible versions for pod "CapacitorSplashScreen":
  In Podfile:
    CapacitorSplashScreen (from `../../node_modules/@capacitor/splash-screen`)

Specs satisfying the `CapacitorSplashScreen (from `../../node_modules/@capacitor/splash-screen`)` dependency were found, but they required a higher minimum deployment target.
```

### Expected Behavior
No error

### Code Reproduction
just run `npm install @capacitor/splash-screen` on a M1 mac

### Other Technical Details
M1 Mac

**Comment by jcesarmobile** [comment]
Version 4.x of the plugins are meant to be used with capacitor 4.x, but you are still using capacitor 3.

Upgrade to Capacitor 4 following [this guide ](https://capacitorjs.com/docs/updating/4-0)or downgrade the plugin to 1.x version
