### ISSUE TITLE
How to automate modifications  'ENABLE_BITCODE' = 'NO'

### ISSUE THREAD

**Issue by Ryanccl** [ionic-team/capacitor-plugins#1200]
### Description

Referencing the sdk requires setting 'ENABLE_BITCODE' = 'NO'
How to automate modifications

### Platform(s)

IOS

### Additional Context

![image](https://user-images.githubusercontent.com/51909525/192413539-dccc0b69-49dd-4ec1-9ddc-0394ad07adb9.png)

**Comment by jcesarmobile** [comment]
Please, for questions use [GitHub discussions](https://github.com/ionic-team/capacitor/discussions) in Capacitor repository or [Capacitor section](https://forum.ionicframework.com/c/capacitor/26) of Ionic forum.

You can add `config.build_settings['ENABLE_BITCODE'] = 'NO'` in the `post_install` section of your Podfile.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```

**Comment by Ryanccl** [comment]
> Please, for questions use [GitHub discussions](https://github.com/ionic-team/capacitor/discussions) in Capacitor repository or [Capacitor section](https://forum.ionicframework.com/c/capacitor/26) of Ionic forum.
> 
> You can add `config.build_settings['ENABLE_BITCODE'] = 'NO'` in the `post_install` section of your Podfile.
> 
> ```
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings['ENABLE_BITCODE'] = 'NO'
>         end
>     end
> end
> ```

  config.build_settings['ENABLE_BITCODE'] = 'NO' is invalid. I solved it in the .podspec file **s.pod_target_xcconfig = { 'ENABLE_BITCODE' => 'NO' }**

**Comment by jcesarmobile** [comment]
My answer is for doing it on an app, if you meant for doing it in a plugin, then the file to edit is the podspec, not the Podfile, and it should be as you described.
