### ISSUE TITLE
Geolocation plugin not implemented on web

### ISSUE THREAD

**Issue by ThomasTraineau** [ionic-team/capacitor-plugins#1203]
I am using the geolocation plugin on a vuejs project. It has been working fine for months and I am now somehow getting this message : 

```
Uncaught (in promise) Error: Not implemented on web.
    at GeolocationWeb.unimplemented
    at GeolocationWeb.requestPermissions
```

This maybe comes from an update of something, but probably not a package directly related to the project. I recently switched computers and the plugin works on my old machine. I installed the same version of node (16.13.2) and even tried to move the whole project directory (together with node_modules etc) to my new computer, but without success.

Extra information : on the old machine, the plugin works in brave but not in firefox.

Any idea about what could be going wrong ?

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ThomasTraineau** [comment]
[Here](https://github.com/ThomasTraineau/capacitor-geolocation) is a reproduction link.

Install the deps with `yarn install` and start the local web server with `quasar dev`. Open the console and see the error mentionned above.

**Comment by jcesarmobile** [comment]
`requestPermissions()` is not implemented on web, there is no API for requesting permissions on web, so the plugin rejects with "Not implemented on web" message. All other plugin methods are working.
You should check the platform with [getPlatform](https://capacitorjs.com/docs/core-apis/web#getplatform) and if it's web you shouldn't call `Geolocation.requestPermissions()`

**Comment by ThomasTraineau** [comment]
I see, but was is weird is that there is no issue on one machine of mine (with the exact same code). Thanks anyway
