### ISSUE TITLE
Unable to load or View map in Android

### ISSUE THREAD

**Issue by jagatb880** [ionic-team/capacitor-plugins#1206]
Unable to update local snapshot for com.google.android.libraries.consentverifier#io.ionic.starter, may result in stale flags.
    java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=io.ionic.starter,

**Comment by jcesarmobile** [comment]
please, when creating issues don't delete the template and provide all the requested information.
