### ISSUE TITLE
[Filesystem] Function to get access to bundle files

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor-plugins#1212]
### Plugin

- Filesystem

### Description

We are using fetch to get our language files the user currently needs, unfortunately with caps new HTTP wrapper and also with the old Community HTTP Plugin this does not work. The reason for this is that the native code cannot access the web view to get access to the public files.

### Platform(s)

all

### Preferred Solution

Add a new location "Bundle" to access bundle files. But not only in public.

### Alternatives

Some hack in HTTP wrapper to come around this

### Additional Context

We are running an Angular application

**Comment by jcesarmobile** [comment]
Bundle files are read only, so not a candidate for filesystem plugin.

the problem with local assets and the new http wrapper has been reported on capacitor repository m this PR should fix it
https://github.com/ionic-team/capacitor/pull/5953
