### ISSUE TITLE
NSPhotoLibraryUsageDescription translation not working the second time

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/capacitor-plugins#1213]
### Plugin(s)
capacitor-camera

### Capacitor Version
 @capacitor/camera": "^4.1.2
  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

### Platform(s)
iOS

### Current Behavior
The first time the dialog box shows, the correct translation is prompted. After the first prompt the translation breaks and shows 'NSPhotoLibraryUsageDescription'

### Expected Behavior
Use translated string from info.plist

### Code Reproduction

In `Info.plist`
```
    <key>NSPhotoLibraryUsageDescription</key>
    <string>NSPhotoLibraryUsageDescription</string>
```

in `App/en.lproj/InfoPlist.strings` for English
```
NSPhotoLibraryUsageDescription = "To pick photos from library";
```

in `App/nl.lproj/InfoPlist.strings` for Dutch 
```
NSPhotoLibraryUsageDescription = "Om foto's uit uw galerij te gebruiken";
```

### Other technical Details

![Screenshot 2022-10-04 at 10 02 10](https://user-images.githubusercontent.com/3781800/193773353-a09fb4de-9d76-48c6-81a4-08a529b84202.png)

**Comment by jcesarmobile** [comment]
Capacitor doesn't handle the translations nor the prompts, you should report the issue to Apple.
