### ISSUE TITLE
Google-maps plugin not displaying the top side on Android

### ISSUE THREAD

**Issue by Dev-it-a-dev** [ionic-team/capacitor-plugins#1215]
### Plugin(s)

- capacitor/google-maps

### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
```

### Platform(s)

- Android

### Current Behavior

Inside the google-map box, the map view is cut on the top.

![Screenshot_20221005-174115_app](https://user-images.githubusercontent.com/55631574/194241028-5c709221-acd5-4812-97b5-36ace6d0150a.png)
_(Red rectangle represents the bounds of 'capacitor-google-maps' tag)_

### Expected Behavior

- The map should be displayed fully in the view

### map.component.html
```html

<capacitor-google-maps #mappa></capacitor-google-maps>

```

### map.component.scss
```scss

capacitor-google-maps {
  display: inline-block;
  width: 100%;
  height: 100vh;
}
```

### map.component.ts

```typescript
import { GoogleMap } from '@capacitor/google-maps';
//...

@Component({
  selector: 'app-componente-pagina-mappa-sito',
  templateUrl: './componente-pagina-mappa-sito.component.html',
  styleUrls: ['./componente-pagina-mappa-sito.component.scss'],
})
export class MapComponent implements OnInit, AfterViewInit {
  @ViewChild('mappa') mappaRef: ElementRef<HTMLElement>;
  nuovaMappa: GoogleMap;
  //...


  ngAfterViewInit() {
   this.MyService.flagMapToLoad.pipe( filter( t => t !== false), take(1)).subscribe( async ok => {   // <--- Don't mind this, I just wait to load some data from another service before creating the map

     //initialize map
     this.nuovaMappa = await GoogleMap.create({
          id: 'my-map',
          element: this.mappaRef.nativeElement,
          apiKey: "MY_API_KEY",
          config: this.myConfig,  // <-- Here I just set center and zoom of the map
          forceCreate: true
        }).then( m => 
          {
             // Here I set some flag from another service and then return the map
             //....

             return m;  // Return the map to this.nuovaMappa
          });
    });

    }
  }
}
```

### Other Technical Details

- I'm using Angular with Ionic added via `ng add @ionic/angular`  
- The MapComponent is loaded to a page via routing:
### sitepage.module.ts
``` typescript
//...
const routes: Routes = [
  {
    path: '',
    component: SitepagePage,
    children: 
    [
      { path: '', redirectTo: 'Map', pathMatch: 'full'},
      { 
        path: 'Map',
        component: MapComponent
      }
    ]
  }
];
//...
```

### Additional Context

- I didn't test it on IOS device
- In WEB it works as it should be, displaying all the map as intended

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
