### ISSUE TITLE
Preferences Plugin not working with integers/booleans in Android

### ISSUE THREAD

**Issue by ccruz182** [ionic-team/capacitor-plugins#1217]
### Plugin(s)

preferences

### Capacitor Version

```
PASTE OUTPUT HERE
```

### Platform(s)

Android

### Current Behavior

When I'm trying to save a boolean or int in the Preferences object; no error is showed but whenever I try to fetch those values, a null object is returned.

### Expected Behavior

Store an integer or boolean successfully and get it back as well.

### Code Reproduction

```typescript
saveValue = async (key, value) => {
    await Preferences.set({
      key,
      value,
    });
  };

  getValue = (key) => {
    return Preferences.get({ key });
  }

await saveValue('a', true);
const a = await getValue('a');
a.value; // NULL
```

**Comment by jcesarmobile** [comment]
The plugin only accepts strings
https://capacitorjs.com/docs/apis/preferences#setoptions

You can stringify other values
https://capacitorjs.com/docs/apis/preferences#working-with-json

There is a feature request for supporting more types
