### ISSUE TITLE
error building after instaling @capacitor/splash-screen

### ISSUE THREAD

**Issue by vadimchilinciuc** [ionic-team/capacitor-plugins#1229]
Hi , can someone help me ?
My app worked well but affter install this plugin i have this error and not found nowere so hope some of you can help me , ty .

So:
Node version: 14.2

After install :
npm install @capacitor/splash-screen
npx cap sync
npx cap copy
npx cap run android 

This is the Error :
> Task :capacitor-splash-screen:compileDebugJavaWithJavac FAILED
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java:3:
        error: package android.widget does not exist
        import android.widget.ImageView;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:3:
        error: package android.animation does not exist
        import android.animation.Animator;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:4:
        error: package android.animation does not exist
        import android.animation.AnimatorListenerAdapter;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:5:
        error: package android.animation does not exist
        import android.animation.ObjectAnimator;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:6:
        error: package android.app does not exist
        import android.app.Activity;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:7:
        error: package android.app does not exist
        import android.app.Dialog;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:8:
        error: package android.content does not exist
        import android.content.Context;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:9:
        error: package android.content.res does not exist
        import android.content.res.ColorStateList;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:10:
        error: package android.content.res does not exist
        import android.content.res.Resources;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:11:
        error: package android.graphics does not exist
        import android.graphics.PixelFormat;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:12:
        error: package android.graphics.drawable does not exist
        import android.graphics.drawable.Animatable;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:13:
        error: package android.graphics.drawable does not exist
        import android.graphics.drawable.Drawable;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:14:
        error: package android.graphics.drawable does not exist
        import android.graphics.drawable.LayerDrawable;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:15:
        error: package android.os does not exist
        import android.os.Handler;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:16:
        error: package android.view does not exist
        import android.view.Gravity;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:17:
        error: package android.view does not exist
        import android.view.LayoutInflater;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:18:
        error: package android.view does not exist
        import android.view.View;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:19:
        error: package android.view does not exist
        import android.view.ViewGroup;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:20:
        error: package android.view does not exist
        import android.view.ViewTreeObserver;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:21:
        error: package android.view.ViewTreeObserver does not exist
        import android.view.ViewTreeObserver.OnPreDrawListener;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:22:
        error: package android.view does not exist
        import android.view.WindowManager;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:23:
        error: package android.view.animation does not exist
        import android.view.animation.LinearInterpolator;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:24:
        error: package android.widget does not exist
        import android.widget.FrameLayout;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:25:
        error: package android.widget does not exist
        import android.widget.ImageView;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:26:
        error: package android.widget does not exist
        import android.widget.LinearLayout;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:27:
        error: package android.widget does not exist
        import android.widget.ProgressBar;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenConfig.java:3:
        error: package android.widget.ImageView does not exist
        import android.widget.ImageView.ScaleType;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenConfig.java:17:
        error: cannot find symbol
        private ScaleType scaleType = ScaleType.FIT_XY;
        ^
        symbol:   class ScaleType
        location: class SplashScreenConfig
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenConfig.java:97:
        error: cannot find symbol
        public ScaleType getScaleType() {
        ^
        symbol:   class ScaleType
        location: class SplashScreenConfig
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenConfig.java:101:
        error: cannot find symbol
        public void setScaleType(ScaleType scaleType) {
        ^
        symbol:   class ScaleType
        location: class SplashScreenConfig
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:36:
        error: cannot find symbol
        private Dialog dialog;
        ^
        symbol:   class Dialog
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:37:
        error: cannot find symbol
        private View splashImage;
        ^
        symbol:   class View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:38:
        error: cannot find symbol
        private ProgressBar spinnerBar;
        ^
        symbol:   class ProgressBar
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:39:
        error: cannot find symbol
        private WindowManager windowManager;
        ^
        symbol:   class WindowManager
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:42:
        error: cannot find symbol
        private Context context;
        ^
        symbol:   class Context
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:43:
        error: cannot find symbol
        private View content;
        ^
        symbol:   class View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:45:
        error: cannot find symbol
        private OnPreDrawListener onPreDrawListener;
        ^
        symbol:   class OnPreDrawListener
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:47:
        error: cannot find symbol
        SplashScreen(Context context, SplashScreenConfig config) {
        ^
        symbol:   class Context
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:365:
        error: cannot find symbol
        private Drawable getSplashDrawable() {
        ^
        symbol:   class Drawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java:105:
        error: package android.R does not exist
        int spinnerBarStyle = android.R.attr.progressBarStyleLarge;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java:139:
        error: package ImageView does not exist
        ImageView.ScaleType scaleType = null;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java:141:
        error: package ImageView does not exist
        scaleType = ImageView.ScaleType.valueOf(scaleTypeName);
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java:143:
        error: package ImageView does not exist
        scaleType = ImageView.ScaleType.FIT_XY;
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:91:
        error: cannot access Activity
        if (activity == null || activity.isFinishing()) return;
        ^
        class file for android.app.Activity not found
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:103:
        error: cannot access View
        final ObjectAnimator fadeAnimator = ObjectAnimator.ofFloat(windowSplashScreenView.getView(), View.ALPHA, 1f,
        0f);
        ^
        class file for android.view.View not found
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:93:
        error: cannot find symbol
        activity.runOnUiThread(
        ^
        symbol:   method runOnUiThread(()->{ andr[...]r); })
        location: variable activity of type AppCompatActivity
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:103:
        error: cannot find symbol
        final ObjectAnimator fadeAnimator = ObjectAnimator.ofFloat(windowSplashScreenView.getView(), View.ALPHA, 1f,
        0f);
        ^
        symbol:   class ObjectAnimator
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:103:
        error: cannot find symbol
        final ObjectAnimator fadeAnimator = ObjectAnimator.ofFloat(windowSplashScreenView.getView(), View.ALPHA, 1f,
        0f);
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:103:
        error: cannot find symbol
        final ObjectAnimator fadeAnimator = ObjectAnimator.ofFloat(windowSplashScreenView.getView(), View.ALPHA, 1f,
        0f);
        ^
        symbol:   variable ObjectAnimator
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:104:
        error: cannot find symbol
        fadeAnimator.setInterpolator(new LinearInterpolator());
        ^
        symbol:   class LinearInterpolator
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:108:
        error: cannot find symbol
        new AnimatorListenerAdapter() {
        ^
        symbol:   class AnimatorListenerAdapter
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:110:
        error: cannot find symbol
        public void onAnimationEnd(Animator animation) {
        ^
        symbol: class Animator
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:109:
        error: method does not override or implement a method from a supertype
        @Override
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:128:
        error: package ViewTreeObserver does not exist
        new ViewTreeObserver.OnPreDrawListener() {
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:129:
        error: method does not override or implement a method from a supertype
        @Override
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:135:
        error: cannot find symbol
        new Handler(context.getMainLooper())
        ^
        symbol: class Handler
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:180:
        error: cannot find symbol
        if (activity == null || activity.isFinishing()) return;
        ^
        symbol:   method isFinishing()
        location: variable activity of type AppCompatActivity
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:187:
        error: cannot find symbol
        activity.runOnUiThread(
        ^
        symbol:   method runOnUiThread(()->{ if ([...]} } })
        location: variable activity of type AppCompatActivity
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:190:
        error: cannot find symbol
        dialog = new Dialog(activity, R.style.capacitor_immersive_style);
        ^
        symbol:   class Dialog
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:192:
        error: cannot find symbol
        dialog = new Dialog(activity, R.style.capacitor_full_screen_style);
        ^
        symbol:   class Dialog
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:194:
        error: cannot find symbol
        dialog = new Dialog(activity, R.style.capacitor_default_style);
        ^
        symbol:   class Dialog
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:206:
        error: cannot find symbol
        Drawable splash = getSplashDrawable();
        ^
        symbol:   class Drawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:207:
        error: cannot find symbol
        LinearLayout parent = new LinearLayout(context);
        ^
        symbol:   class LinearLayout
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:207:
        error: cannot find symbol
        LinearLayout parent = new LinearLayout(context);
        ^
        symbol:   class LinearLayout
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:209:
        error: package LinearLayout does not exist
        new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT)
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:209:
        error: package LinearLayout does not exist
        new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT)
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:209:
        error: package LinearLayout does not exist
        new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT)
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:211:
        error: cannot find symbol
        parent.setOrientation(LinearLayout.VERTICAL);
        ^
        symbol:   variable LinearLayout
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:225:
        error: cannot find symbol
        new Handler()
        ^
        symbol:   class Handler
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:275:
        error: cannot find symbol
        Drawable splash;
        ^
        symbol:   class Drawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:285:
        error: cannot find symbol
        Activity activity = (Activity) context;
        ^
        symbol:   class Activity
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:285:
        error: cannot find symbol
        Activity activity = (Activity) context;
        ^
        symbol:   class Activity
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:286:
        error: cannot find symbol
        LayoutInflater inflator = activity.getLayoutInflater();
        ^
        symbol:   class LayoutInflater
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:287:
        error: cannot find symbol
        ViewGroup root = new FrameLayout(context);
        ^
        symbol:   class ViewGroup
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:287:
        error: cannot find symbol
        ViewGroup root = new FrameLayout(context);
        ^
        symbol:   class FrameLayout
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:289:
        error: package FrameLayout does not exist
        new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:289:
        error: package ViewGroup does not exist
        new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:289:
        error: package ViewGroup does not exist
        new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
        ^
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:295:
        error: cannot find symbol
        if (splash instanceof Animatable) {
        ^
        symbol:   class Animatable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:296:
        error: cannot find symbol
        ((Animatable) splash).start();
        ^
        symbol:   class Animatable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:299:
        error: cannot find symbol
        if (splash instanceof LayerDrawable) {
        ^
        symbol:   class LayerDrawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:300:
        error: cannot find symbol
        LayerDrawable layeredSplash = (LayerDrawable) splash;
        ^
        symbol:   class LayerDrawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:300:
        error: cannot find symbol
        LayerDrawable layeredSplash = (LayerDrawable) splash;
        ^
        symbol:   class LayerDrawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:303:
        error: cannot find symbol
        Drawable layerDrawable = layeredSplash.getDrawable(i);
        ^
        symbol:   class Drawable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:305:
        error: cannot find symbol
        if (layerDrawable instanceof Animatable) {
        ^
        symbol:   class Animatable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:306:
        error: cannot find symbol
        ((Animatable) layerDrawable).start();
        ^
        symbol:   class Animatable
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:311:
        error: cannot find symbol
        splashImage = new ImageView(context);
        ^
        symbol:   class ImageView
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:314:
        error: cannot find symbol
        ImageView imageView = (ImageView) splashImage;
        ^
        symbol:   class ImageView
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:314:
        error: cannot find symbol
        ImageView imageView = (ImageView) splashImage;
        ^
        symbol:   class ImageView
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:325:
        error: cannot find symbol
        View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:326:
        error: cannot find symbol
        View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:327:
        error: cannot find symbol
        View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:328:
        error: cannot find symbol
        View.SYSTEM_UI_FLAG_HIDE_NAVIGATION |
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:329:
        error: cannot find symbol
        View.SYSTEM_UI_FLAG_FULLSCREEN |
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:330:
        error: cannot find symbol
        View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:333:
        error: cannot find symbol
        splashImage.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN);
        ^
        symbol:   variable View
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:344:
        error: cannot find symbol
        spinnerBar = new ProgressBar(context, null, spinnerBarStyle);
        ^
        symbol:   class ProgressBar
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:346:
        error: cannot find symbol
        spinnerBar = new ProgressBar(context);
        ^
        symbol:   class ProgressBar
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:359:
        error: cannot find symbol
        ColorStateList colorStateList = new ColorStateList(states, colors);
        ^
        symbol:   class ColorStateList
        location: class SplashScreen
        /home/vadim/git/mirror-pass-alpha/node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java:359:
        error: cannot find symbol
        ColorStateList colorStateList = new ColorStateList(states, colors);
        ^
        symbol:   class ColorStateList
        location: class SplashScreen
        100 errors
        
        > Task :app:processDebugManifestForPackage
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':capacitor-splash-screen:compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 4s

**Comment by vadimchilinciuc** [comment]
i upgrade everything using this link and it works :)
https://capacitorjs.com/docs/updating/4-0

**Comment by Dev-it-a-dev** [comment]
Paste the output of your `npx cap doctor`

In the meanwhile, you could try to sync your project with Gradle Files:

- Open your project on Android Studio,
- Wait for your project to load correctly,
- Go to File -> Sync Project with Gradle files
