### ISSUE TITLE
iconUrl doesn't works with

### ISSUE THREAD

**Issue by intermedia54** [ionic-team/capacitor-plugins#1231]
### Plugin(s)
@capacitor/google-maps 4.2.1

### Capacitor Version

```
PASTE OUTPUT HERE
```

### Platform(s)
Android 12 API 31

### Current Behavior
IconUrl works fine with addMarker, but when i enable enableClustering and addMarkers, custom iconUrl doesn't works.
Only default marker appear on android

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
