### ISSUE TITLE
[Capacitor/App] provide removeListener to remove particular listener

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor-plugins#1232]
### Plugin

@capacitor/app

### Description

We have `removeAllListeners`  which will remove all the native listeners that we had registered. 

 Now I want to use `appStateChange` on a particular page and remove the listener on `destroy`

### Platform(s)

Android
iOS

**Comment by jcesarmobile** [comment]
`addListener` returns a `PluginListenerHandle` that contains a `remove()` method you can use to remove that specific listener.

Check the motion page on our capacitor-testapp  repository
https://github.com/ionic-team/capacitor-testapp/blob/353205ec75ef50016ebc4f77ceaab1eb33bb8912/src/pages/Motion.tsx#L39-L61
