### ISSUE TITLE
window is not defined for Preferences plugin

### ISSUE THREAD

**Issue by Olyno** [ionic-team/capacitor-plugins#1234]
### Plugin(s)

``@capacitor/preferences``

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/android: 4.3.0
  @capacitor/cli: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/core: 4.3.0

[error] Xcode is not installed
[success] Android looking great! 👌
```

### Platform(s)

Android (should produce the same issue on IOS)

### Current Behavior

There is a ``ReferenceError: window is not defined`` error when using the ``Preferences.get`` method on mobile.

### Expected Behavior

It should not have any error, and work on mobile.

### Code Reproduction

```ts
import { Preferences } from '@capacitor/preferences';

Preferences.get({ key: 'hello' });
```

### Other Technical Details

Related to [this line](https://github.com/ionic-team/capacitor-plugins/blob/main/preferences/src/web.ts#L80)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Olyno** [comment]
Looks like it was a problem from my side, nevermind.
