### ISSUE TITLE
Capacitor splash screen uses deprecated API.

### ISSUE THREAD

**Issue by broomfn** [ionic-team/capacitor-plugins#1235]
### Plugin
"@capacitor/splash-screen": "^4.1.0"

### Description

node_modules/@capacitor/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java uses or overrides a deprecated API.

### Platform(s)
Android SDK 32

### Preferred Solution
Replace deprecated API

**Comment by jcesarmobile** [comment]
This is a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/846
