### ISSUE TITLE
Status bar glitches and do not animate

### ISSUE THREAD

**Issue by Mortenjoe** [ionic-team/capacitor-plugins#1238]
### Plugin(s)
@capacitor/status-bar@4.0.1

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/core: 4.3.0
  @capacitor/cli: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
When hiding the status bar at launch and later showing it with a DARK style (white text) it shortly shows black text before changing to white. The slide show-animation is also left out:

![Statusbar-glitch](https://user-images.githubusercontent.com/51312165/197139651-c02587a1-11a9-4021-a3dc-bb42bc2b69e6.gif)

### Expected Behavior
The status bar should show white text and slide in from top

### Code Reproduction
The status bar is initially hidden by setting ```UIStatusBarHidden``` in info.plist where ```UIStatusBarStyle``` is set to ```UIStatusBarStyleLightContent``` (does not seem to make any difference). In App.vue I set

```
onMounted(async () => {
   try {
      await StatusBar.setStyle({ style: Style.Dark })
      await StatusBar.show({ animation: Animation.Slide })
   } catch (error) {
      console.log(error)
   }
})
```
Repro:
https://github.com/Mortenjoe/capacitor-statusbar-animation-bug

### Other Technical Details
Xcode 14.0.1
iOS 16

**Comment by jcesarmobile** [comment]
Looks like it's an iOS bug. It's not Capacitor related, I created a native app and the behavior is the same.

`.slide` animation no longer works on iOS 15, and on iOS 16 it not only doesn't work, it also causes this glitch.

We will document it.

To workaround the problem you can use `None` as the animation, as `Fade`, despite it still works on iOS 15+, it also presents this glitch on iOS 16 where the first time it's called it transitions from black to white.
