### ISSUE TITLE
Push notification error Targeting 31+ with capacitor v3

### ISSUE THREAD

**Issue by GabrieleGruppoInformatico** [ionic-team/capacitor-plugins#1240]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/ios: 3.6.0
  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
```

### Platform(s)

Android api level >= 31

### Current Behavior / Error

Error receiving a push notification on Android 12, with closed/background app:

"FATAL EXCEPTION: Firebase-Messaging-Intent-Handle"
"java.lang.IllegalArgumentException: [our packagename] : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles."

### Expected Behavior

No error on receiving push notification on Android 12 or greater, as it was with previously targeting level >= 30

### Other technical info
We find that there is a solution from the official repo, that talks about a fix in the new sdk.

https://github.com/firebase/firebase-android-sdk/blob/fe6475688d2a00c266f82a44005f1ac045eb729c/firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java#L539

### Additional Context

We read that the problem is fixed in version 4.x of the plugin, but it requires capacitor 4 installed and unfortunatly we can't proceed to update to it.
Updating it will stop us from using the app on IOS 12 and it will require a lot of time reviewing the compatibility of other components and plugins.

We identified the problem in how the intent is generated, and the new version solve it by adding that flag in an existing method. 
Is there a workaround to solve this problem with @capacitor/push-notifications@1.0.9 ? 
It'd be really helpful a way to override that call/parameters without upgrading everything else...

**Comment by jcesarmobile** [comment]
I'm sorry to hear that you don't want to update to Capacitor 4, but this won't be fixed for Capacitor 3

**Comment by GabrieleGruppoInformatico** [comment]
We're updating to Capacitor 4, but we scheduled it in a future sprint. In order to do it, we need to let every user to dismiss old iphone (Cause IOS 12 we'll be not supported anymore).
We were looking for a workaround, if availaible, for these months (2-3). 
If there is a way to edit the plugin or override a method or two, we would be very happy about it.

Thank you

**Comment by danbunkr** [comment]
@GabrieleGruppoInformatico - I had the same situation as you. We are slating a Capacitor 4 upgrade but needed to support SDK 31 on Capacitor 3 until we can get some time to properly upgrade and test our application. I forked the plugin and created a package https://www.npmjs.com/package/@bunkr.official/push-notifications that will fix this issue. Just npm install it instead of the @capacitor/push-notification package.

Note: You'll need to set `firebaseMessagingVersion= '23.0.0'` in `variables.gradle` file and make sure you use 1.0.13 as the version
