### ISSUE TITLE
@capacitor/app addEventListener('backButton') not working on android

### ISSUE THREAD

**Issue by VanIseghemThomas** [ionic-team/capacitor-plugins#1241]
### Plugin(s)

@capacitor/app:  "^4.0.1"

### Capacitor Version

```
@capacitor/cli: 4.3.0
@capacitor/core: 4.3.0
@capacitor/ios: 4.3.0
@capacitor/android: 4.3.0
```

### Platform(s)

Android

### Current Behavior

When pressing the back button inside the native Android version (in my case swipe gesture), nothing happens.
From the logs I can confirm the event listener is created:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/55881698/197188014-1ff536fa-f560-4ce0-a099-47fe18d3af2e.png">

### Expected Behavior

When using the back button, the event listener gets fired

### Code Reproduction

Created in Vue3:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/55881698/197188570-5d409791-997b-4e31-ad0d-f0880a696d20.png">

This might be me being dumb and missing something but I really think I got it right with this one.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by VanIseghemThomas** [comment]
Any update on this? Please reopen?
