### ISSUE TITLE
Push Notification - event capacitorDidRegisterForRemoteNotifications not called

### ISSUE THREAD

**Issue by thommydz** [ionic-team/capacitor-plugins#1242]
### Plugin(s)
@capacitor/push-notifications 4.1.0

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0
```

### Platform(s)
iOS

### Current Behavior
After adding my event listeners and registering PushNotification (`PushNotifications.register();`), when I run my app on iOs I get this error:
`ERROR MESSAGE:  {"errorMessage":"event capacitorDidRegisterForRemoteNotifications not called.  Visit https:\/\/capacitorjs.com\/docs\/apis\/push-notifications for more information","message":"event capacitorDidRegisterForRemoteNotifications not called.  Visit https:\/\/capacitorjs.com\/docs\/apis\/push-notifications for more information"}
`

In my AppDelegate.swift I have these lines:
```
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }
```

### Expected Behavior
capacitorDidRegisterForRemoteNotifications should be called because PushNotifications.register(); does get called

### Code Reproduction
- [ ] Set up capacitor in Nuxt app
```
npx create-nuxt-app
npm install @capacitor/core @capacitor/cli @capacitor/iOS
npm install @capacitor/push-notifications
npx cap init
npx cap add ios
npx cap sync
```

- [ ] In xCode,  enable the Push Notifications capability

- [ ] Add lines to AppDelegate.swift

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
  NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
}

func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
  NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
}
```

- [ ] Load and register push notification in startup (layouts > default.vue)
```
import { PushNotifications } from '@capacitor/push-notifications';
	async fetch() {
		await PushNotifications.addListener('registration', token => {
			console.info('Registration token: ', token.value);
		});

		await PushNotifications.addListener('registrationError', err => {
			console.error('Registration error: ', err.error);
		});

		await PushNotifications.addListener('pushNotificationReceived', notification => {
			console.log('Push notification received: ', notification);
		});

		await PushNotifications.addListener('pushNotificationActionPerformed', notification => {
			console.log('Push notification action performed', notification.actionId, notification.inputValue);
		});
		let permStatus = await PushNotifications.checkPermissions();

		if (permStatus.receive === 'prompt') {
			permStatus = await PushNotifications.requestPermissions();
		}

		if (permStatus.receive !== 'granted') {
			throw new Error('User denied permissions!');
		}

		await PushNotifications.register();
		
		const notificationList = await PushNotifications.getDeliveredNotifications();
		console.log('delivered notifications', notificationList);
	},
```

- [ ] Run app in Xcode > simulator. The app asks for push permission, it registers but it has no token and his the error as described above.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by AlessioChen** [comment]
Hello, i am having the same problem. 

i am working on React 17.0.2 project with following dependencies: 

     "@capacitor/app": "^4.0.1",
      "@capacitor/assets": "^1.0.10",
      "@capacitor/cli": "^4.3.0",
      "@capacitor/core": "^4.3.0",
      "@capacitor/device": "^4.0.1",
      "@capacitor/ios": "^4.3.0",
      "@capacitor/push-notifications": "^4.1.0",

For the notification i am using Firebase and it returns these errors:

ERROR MESSAGE:  {"errorMessage":"event capacitorDidRegisterForRemoteNotifications not called.  Visit https:\/\/capacitorjs.com\/docs\/apis\/push-notifications for more information","message":"event capacitorDidRegisterForRemoteNotifications not called.  Visit https:\/\/capacitorjs.com\/docs\/apis\/push-notifications for more information"}

[error] - {"message":"Not available on iOS","errorMessage":"Not available on iOS","code":"UNIMPLEMENTED","data":{}}

Waiting for you feedback. 
Thank you. 
Alessio.

**Comment by thommydz** [comment]
> Hello, i am having the same problem.
> 
> i am working on React 17.0.2 project with following dependencies:
> 
> ```
>  "@capacitor/app": "^4.0.1",
>   "@capacitor/assets": "^1.0.10",
>   "@capacitor/cli": "^4.3.0",
>   "@capacitor/core": "^4.3.0",
>   "@capacitor/device": "^4.0.1",
>   "@capacitor/ios": "^4.3.0",
>   "@capacitor/push-notifications": "^4.1.0",
> ```
> 
> For the notification i am using Firebase and it returns these errors:
> 
> ERROR MESSAGE: {"errorMessage":"event capacitorDidRegisterForRemoteNotifications not called. Visit https://capacitorjs.com/docs/apis/push-notifications for more information","message":"event capacitorDidRegisterForRemoteNotifications not called. Visit https://capacitorjs.com/docs/apis/push-notifications for more information"}
> 
> [error] - {"message":"Not available on iOS","errorMessage":"Not available on iOS","code":"UNIMPLEMENTED","data":{}}
> 
> Waiting for you feedback. Thank you. Alessio.

From what I can tell by documentation the base setup for React, Vue/Nuxt and also Angular are identical. Or at least it amounts to the same thing. So you are probably experiencing the same problem/bug. 

I've been dealing with this for quite some hours now but not really finding anything that helps me further. 

Both on simulator and real device push notifications are registrered, permStatus = granted, but device has no token and 'capacitorDidRegisterForRemoteNotifications' is not called. 

Weird thing is that the other function in AppDelegate.swift is "didFailToRegisterForRemoteNotificationsWithError" but that function is also not called. I would expect it should get in to either this function or the didRegisterForRemoteNotificationsWithDeviceToken function.

**Comment by jcesarmobile** [comment]
Code reproduction is not some snippets of code, is a full app that we can run to reproduce the issue, check the link the bot provided
https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction

**Comment by thommydz** [comment]
> Hello, i am having the same problem.
> 
> i am working on React 17.0.2 project with following dependencies:
> 
> ```
>  "@capacitor/app": "^4.0.1",
>   "@capacitor/assets": "^1.0.10",
>   "@capacitor/cli": "^4.3.0",
>   "@capacitor/core": "^4.3.0",
>   "@capacitor/device": "^4.0.1",
>   "@capacitor/ios": "^4.3.0",
>   "@capacitor/push-notifications": "^4.1.0",
> ```
> 
> For the notification i am using Firebase and it returns these errors:
> 
> ERROR MESSAGE: {"errorMessage":"event capacitorDidRegisterForRemoteNotifications not called. Visit https://capacitorjs.com/docs/apis/push-notifications for more information","message":"event capacitorDidRegisterForRemoteNotifications not called. Visit https://capacitorjs.com/docs/apis/push-notifications for more information"}
> 
> [error] - {"message":"Not available on iOS","errorMessage":"Not available on iOS","code":"UNIMPLEMENTED","data":{}}
> 
> Waiting for you feedback. Thank you. Alessio.

I managed to get the plugin to work by ignoring the [official capacitor docs](https://capacitorjs.com/docs/apis/push-notifications) for this plugin and following [this example](https://capacitorjs.com/docs/guides/push-notifications-firebase) from the capacitor website, which is different from the docs.

The difference is in the AppDelegate.swift, adding "pod 'Firebase/Messaging'" to your podfile and the way the plugin is loaded. In the example Angular is used but it's pretty easy to convert it to Vue/Nuxt/React.

Let me know if you need any help!

**Comment by jcesarmobile** [comment]
glad you figured out
