### ISSUE TITLE
Splash screen shows app name with distorted image.

### ISSUE THREAD

**Issue by opindia123** [ionic-team/capacitor-plugins#1251]
### Plugin(s)

@capacitor/splash-screen@4.1.0 and 4.1.1

### Capacitor Version

Latest Dependencies :
 @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0

Installed Dependencies : 
  @capacitor/ios: not installed
  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0

### Platform(s)

 @capacitor/android: 4.1.0
 minSdkversion = 22
 CompileSdkVersion = 32
 TargetSdkVersion 32
### Current Behavior

In devices with android 12 OS or some devices with android 11 OS , splash screen comes with App name on header section with
distorted app logo .

### Expected Behavior

It should display proper splash screen for all android devices.

### Other Technical Details

I have used @capacitor/assests package to generate images,
I tried with cordova-res package also but same result.

### Additional Context
 
Check below image , It is a splash screen with app name display in top with distorted image.

![WhatsApp Image 2022-10-27 at 15 06 47 (1)](https://user-images.githubusercontent.com/17309152/198283222-a88f8ba0-fe6f-4a49-acdd-42ba00dcd095.jpeg)

**Comment by jcesarmobile** [comment]
This is a bug in how some vendors have implemented the Android 12 Splash Screen API. 

Check https://github.com/ionic-team/capacitor/issues/5813#issuecomment-1271740492 for some tips that might solve your issue.

**Comment by opindia123** [comment]
Hi @jcesarmobile , thanks for reply , above said issue is solved, but on some devices blank screen display instead of splash screen, white blank image instead of splash screen. Can you help me out on this.

**Comment by jcesarmobile** [comment]
If it's an Android 12 device it's an Android 12 bug. Android 12 devices won't show the splash screen when you launch the app from Android Studio. It should work well when opening the app from the app icon, but some device vendors that use custom roms/launchers launch the apps in a different way that doesn't show the splash screen neither.
Most of those problems have been fixed on Android 13, but won't be fixed for Android 12, so there is nothing you can do.
There is a note about it on splash screen plugin docs
https://capacitorjs.com/docs/apis/splash-screen#android-12-splash-screen-api

**Comment by opindia123** [comment]
Hi @jcesarmobile  , thanks for reply , we will wait for android 13 .
