### ISSUE TITLE
Splash-Screen plugin - iOS - NSInvalidArgumentException when using ".storyboard" in Info.plist's dict entry for UILaunchStoryboardName

### ISSUE THREAD

**Issue by spenweb** [ionic-team/capacitor-plugins#1253]
### Plugin(s)
- @capacitor/splash-screen: ^4.1.1

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
- iOS

### Current Behavior
When using Xcode Version 14.0.1 (14A400), I set the "Launch Screen File" in Xcode's UI:
![image](https://user-images.githubusercontent.com/46385475/198406295-23efd375-5a13-4551-9f3a-b468398382cf.png)
Here is a snippet of the `dict` in the `Info.plist` file:
```xml
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen.storyboard</string>
```
I run my app  and then I receive this misleading error message and the app exits:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'LaunchScreen.storyboard' in bundle NSBundle 
```
It is misleading as I have a *file* named LaunchScreen.storyboard, but it seems that the error is there is no file called 'LaunchScreen.storyboard.storybaord.

It works after I remove the ".storyboard" file extension directly in my Info.plist. The following works:
```xml
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
```

### Expected Behavior
I expect that the app will not crash if I specify a "Launch Screen File" via Xcode's UI, or in other words, I do not need to modify my Info.plist file directly and that the storyboard extension remains.

Either this is a bug in Xcode (the file extension should not be part of the storyboard name) or this line of code needs to be updated to take into account the `UILaunchStoryboardName` value includes the file extension:
https://github.com/ionic-team/capacitor-plugins/blob/5bb30005df075ce1679695792e33f398eee298c4/splash-screen/ios/Plugin/SplashScreen.swift#L91

I am willing to create a PR if it is determined that the Ionic code should be changed.

**Comment by jcesarmobile** [comment]
Yeah, looks like Xcode 14 adds the .storyboard to the UILaunchStoryboardName, using Xcode 13 removes the .storyboard again.
Not sure if it's a bug on Xcode 14 or a behavior change, but the plugin should account for it.
