### ISSUE TITLE
Bug when you can build the version 4.3.0 of google-map. 

### ISSUE THREAD

**Issue by francolondra** [ionic-team/capacitor-plugins#1261]
### Plugin(s)
@capacitor/google-map

### Capacitor Version
4.3.0

```
PASTE OUTPUT HERE
```

### Platform(s)
Angular,Android

### Current Behavior
I update the version of googleMap from 4.2.1 to 4.3.0 and When I could build the app , I received the error of the image.

### Expected Behavior
the build should run well

### Code Reproduction

![but-update-version](https://user-images.githubusercontent.com/40376158/200202241-bb25e2a9-77e0-49eb-b088-14b9bdb50bf3.PNG)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Robertndrei** [comment]
Same issue, just installed the plugin.
