### ISSUE TITLE
Simulate native events in browser

### ISSUE THREAD

**Issue by thebalaa** [ionic-team/capacitor-plugins#1275]
Is there an easy way to simulate native plugin events in the browser?

For example how could I simulate firing the `App.addListener("appUrlOpen")` event?

I tried `document.dispatchEvent(new CustomEvent("appUrlOpen"), {})` but had no luck.

Any ideas would be appreciated!

**Comment by jcesarmobile** [comment]
Please, for asking questions use the [github discussions in Capacitor repository](https://github.com/ionic-team/capacitor/discussions) or the [capacitor section](https://forum.ionicframework.com/c/capacitor/26) of the ionic forum.

As far as I know, the only way of firing an event is from the plugin itself by calling `notifyListeners('appUrlOpen', data);`, but that would require to fork and edit the App plugin to do that.
