### ISSUE TITLE
[@capacitor/camera] web format wrong if not jpeg/png/gif

### ISSUE THREAD

**Issue by ChrisHSandN** [ionic-team/capacitor-plugins#1279]
### Plugin(s)
@capacitor/camera 4.1.3

### Capacitor Version

```
Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0

```

### Platform(s)

Web

### Current Behavior

The `Photo.format` on web [defaults to `jpeg`](https://github.com/ionic-team/capacitor-plugins/blob/b342061b41e26761f3d47b5dad06bd2e4f151216/camera/src/web.ts#L108) for all files which are not `png|gif`.

However the `accept=image/*` allows numerous other formats through e.g. `tiff|svg|bmp...` etc. which all get reported incorrectly as `format: jpeg`

### Expected Behavior

Either:
The accept: should be something like `image/jpeg,image/png,image/gif` so only expected formats can be selected.
or
The format needs to handle all the possible image formats.
or
The format needs to default to something like `unknown` so we can trust `format: jpeg` == `image/jpeg`

### Code Reproduction

```ts
const cameraGetPhoto = await Camera.getPhoto({
	resultType        : CameraResultType.DataUrl,
	webUseInput       : true,
});

// Select any file which isn't a jpeg/png/gif

console.log(cameraGetPhoto.format); // jpeg
```

-->

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
