### ISSUE TITLE
feat: `weekday` support in LocalNotifications

### ISSUE THREAD

**Issue by littke** [ionic-team/capacitor-plugins#129]
# Feature Request

## Describe the Feature Request
I'd like to schedule recurring local notifications on Tuesdays and Thursdays at a given hour.

## Platform Support Requested

- Android
- iOS

## Describe Preferred Solution
I'd like to schedule it using the `on` keyword together with a (new) `weekday` (0-6) keyword. 

## Describe Alternatives
I don't see a way around this, as `day` is only 0-30. I could use `every` — but that doesn't let me set the hour of delivery. https://github.com/ionic-team/capacitor/issues/2752 goes into further detail.

## Related Code
```...
schedule: {
  on: {
    hour: 20,
    weekday: 2
  }
},
...
schedule: {
  on: {
    hour: 20,
    weekday: 4
  }
},
```

## Additional Context
- iOS: [DateComponent](https://developer.apple.com/documentation/foundation/datecomponents) has [`weekday`](https://developer.apple.com/documentation/foundation/datecomponents/1780094-weekday), support so it could easily be added in [`LocalNotifications.swift`](https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift#L276) from what I gather. 
- Android: I don't know Java but it seems in [`LocalNotificationsSchedule.java`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java) we are using [`SimpleDateFormat`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java) which has a [`u` — day number of week](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) (1-7) support.

**Comment by MarekGogol** [comment]
Would be really great to have this feature!

**Comment by dahyui** [comment]
@littke Just wondering if you managed to work around this? If so, what did you do? 

I managed to fix it for iOS and get it working by adding `weekday` in the `DateComponent`. I'm having trouble getting Java working as I'm not familiar with Java either.

**Comment by littke** [comment]
@dahyui I never got it to work! I gave up. Sorry!

**Comment by kim-jos** [comment]
I was able to add weekday functionality for the `on` keyword for Android . I created a pull request, but if you need it before it merges you should check out the following link and copy and paste the pertinent files. #601
