### ISSUE TITLE
"Select Photos..." not working

### ISSUE THREAD

**Issue by michael-arboleda** [ionic-team/capacitor-plugins#1292]
### Plugin(s)

Cap v3: 
```
"node_modules/@capacitor/camera": {
            "version": "1.3.1",
            "resolved": "https://registry.npmjs.org/@capacitor/camera/-/camera-1.3.1.tgz",
            "peerDependencies": {
                "@capacitor/core": "^3.0.0"
            }
        }
```

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0
```

and with cap v3: 
```
Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 3.9.0
  @capacitor/core: 3.9.0
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4
```
### Platform(s)

 iOS 

### Current Behavior

Ask user for photos permission. User presses 'Select Photos...' from the prompt. Either: nothing happens and only the grey background is visible or photos select shows up for less than a second and then only the grey background is visible.

### Expected Behavior

User should see their gallery and select the photos to give access permission to. 

### Code Reproduction

```
           try {
                await Camera.requestPermissions({permissions: ['camera']});
                await Camera.requestPermissions({permissions: ['photos']});
            }
            catch {
                // do nothing
            }
```

### Other Technical Details

Tested on iPad Air (4th Gen) running iPadOS 16.1 (20879)

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
