### ISSUE TITLE
Add message event handler to Browser

### ISSUE THREAD

**Issue by VictorienTardif** [ionic-team/capacitor-plugins#1298]
### Plugin
Browser

### Description
Add a [MessageEvent](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent) listener to Browser so the app can handle it.

### Platform(s)
iOS, Android

### Additional Context
I'd like to use it the same we can use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) on `window.parent` from an `iframe`.

**Comment by jcesarmobile** [comment]
That's technically not possible as the native components used by the plugin (Safari View Controller on iOS and Chrome Custom Tabs on Android) don't allow that.

**Comment by VictorienTardif** [comment]
I don't know about Safari View Controller but Chrome Custom Tabs seems to have a `onPostMessage` method: https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsCallback#onPostMessage(java.lang.String,android.os.Bundle)

Would it be possible to use something else than the Safari View Controller? I don't know iOS at all sorry. 

If it's not possible with post message, how can I communicate from the browser to the app? Is there a way to do that?

Thanks.
