### ISSUE TITLE
Error when using Dialog

### ISSUE THREAD

**Issue by evoxeed** [ionic-team/capacitor-plugins#1300]
### Plugin(s)
` "@capacitor/dialog": "^4.1.0"`

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0
  @capacitor/android: 4.5.0
```

### Platform(s)
```IOS```

### Current Behavior
An error appears when calling any functionality Dialog, the error looks like this:
```2022-11-24 15:40:33.313520+0400 App[15612:409100] [Presentation] Attempt to present <UIAlertController: 0x10307b600> on <Capacitor.CAPBridgeViewController: 0x10400ad50> (from <Capacitor.CAPBridgeViewController: 0x10400ad50>) which is already presenting <_UIContextMenuActionsOnlyViewController: 0x104516270>.```

### Expected Behavior
bring up a dialog box and break nothing

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
