### ISSUE TITLE
Any way to "refresh" localStorage after changing it via the Filesystem plugin? [iOS]

### ISSUE THREAD

**Issue by nijakobius** [ionic-team/capacitor-plugins#1306]
### Description
I am migrating from Cordova and am using the [Filesystem Plugin](https://capacitorjs.com/docs/apis/filesystem) to copy the `.../LocalStorage/` and `.../IndexedDB/` directories in `.../Library/WebKit/WebsiteData/Default/...`.

**This works, but only after an app restart can the data be accessed via `localStorage.getItem('someOldData')`.**

I have already tried `location.reload()` and `document.location.href = 'index.html';` but this only reloads the html. The copied LocalStorage is still not available until I manually restart the app.

### Platform(s)
iOS

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
