### ISSUE TITLE
Google Maps white screen with no errors

### ISSUE THREAD

**Issue by chriswatt** [ionic-team/capacitor-plugins#1319]
### Plugin(s)

"@capacitor/google-maps": "^4.3.2",

### Capacitor Version
```

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.6.1
  @capacitor/cli: 4.6.1
  @capacitor/android: 4.6.1

[success] Android looking great! 👌
```

### Platform(s)
`android`

### Current Behavior

1. Started a new ionic application using ionic start --capacitor. Selected the list template to start with. 
2. Installed @capacitor/google-maps - 4.3.2
3. Added schemas: [CUSTOM_ELEMENTS_SCHEMA] to both app module and page module that the map is on
4. Added CSS to make all other content have a transparent background
5. Added API Key to AndroidManifest.xml
6. Used example code from the documentation (API Key removed)

![image](https://user-images.githubusercontent.com/488912/206438452-4956808b-d2b0-4c79-8a97-bf377c4b0a4e.png)

7.  App runs but shows only a white box where the map should be

![image](https://user-images.githubusercontent.com/488912/206438508-52cb9dea-b545-495b-ab38-b68b7c79020c.png)

8. No errors show on the console, if you click and drag anywhere in the white box, onScroll events show on the log

![image](https://user-images.githubusercontent.com/488912/206438828-2ba39cbe-ad3e-4253-9657-c2648e572a10.png)

### Code Reproduction
I've created a repo with my code here - https://github.com/chriswatt/ionic-capacitor-maps

### Other Technical Details

Currently testing with Android 11 API 30 using the emulator.

**Comment by jcesarmobile** [comment]
you have not committed the android folder, can you commit it?

**Comment by chriswatt** [comment]
> you have not committed the android folder, can you commit it?

@jcesarmobile I've committed the android folder

**Comment by jcesarmobile** [comment]
Please, don't ping me.
Since I've commented I'm already subscribed and will get notified when somebody comments, and even if I unsubscribe, since I added the "needs reply", I will notice it has been removed after somebody comments. Pinging people is unnecessary and annoying.

End of rant.

First of all, delete your sample app, you have committed your API key on the Android project.

Your sample app is working fine.
You said you are using an emulator to test. Google Maps SDK doesn't work on all emulators, when using emulators, make sure you are using one that have Google APIs or Google Play. Even better if you test on a real device.

**Comment by chriswatt** [comment]
Noticed the API key just before you commented and republished the repo. Tested on a real device, Pixel 6, same empty box

![image](https://user-images.githubusercontent.com/488912/206456166-7c6136e7-bcb0-477b-a42b-4b18a77b8f5d.png)

**Comment by chriswatt** [comment]
Noticed the background was black on the Pixel 6, found the background was also being set in variables.scss

![image](https://user-images.githubusercontent.com/488912/206458159-cbc2183b-ea4a-40b3-a16c-464c07ed0766.png)

Updating this to transparent made the map show 

![image](https://user-images.githubusercontent.com/488912/206458291-b8779186-2456-4e9b-8366-526eb201a9a9.png)
