### ISSUE TITLE
Google maps doesn't show HTML objects on ios  its rendered on top of webview

### ISSUE THREAD

**Issue by mragwa** [ionic-team/capacitor-plugins#1320]
### Plugin(s)
 
@Capacitor/googlemaps
 

### Capacitor Version

```
  @capacitor/cli: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
```

### Platform(s)
IOS 

### Problem
I recently upgraded to capacitor 4 & used @Capacitor/googlemaps instead of capacitor-community/google-maps
It works fine on android devices but i got an issue running it on IOS devices 
it takes all the screen and hide all HTML elements on the page seems like its come over the webview itself.
as shown on the image: 

![image](https://user-images.githubusercontent.com/5574454/206566453-87b90087-ecd8-4cdc-9f8c-68a5d94ab38c.png)

as you can see both header & footer are gone away i searched a lot about that issue but i didn't get any workaround or solution.

also if it will help i got on xcode debug that error direct after map creation :
 
```
2022-12-08 23:36:03.319063+0300 App[3647:1011396] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
```

after a while i confirmed that the map rendered on top of the webview.

If you can help with that thank you.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mragwa** [comment]
I created a repo for the issue can be found here : 
https://github.com/mragwa/capacitor-google-maps-ios-error.git

**Comment by mragwa** [comment]
@jcesarmobile  any help with that ?
