### ISSUE TITLE
local-notifications: Android 13 asks for permissions after first app start

### ISSUE THREAD

**Issue by nijakobius** [ionic-team/capacitor-plugins#1321]
### Plugin(s)
@capacitor/local-notifications@4.1.3

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
```

### Platform(s)
Android 13. Other Android versions and iOS work fine.

### Current Behavior
When launching the app for the first time, the following permission request pops up, even if I don't use any of the plugin's functions (like schedule a notification):
```
Allow XXX to send you notifications?
```

### Expected Behavior
The dialogue should only appear after e.g. scheduling a notification or requesting the permission (like it does in iOS).

**Comment by jcesarmobile** [comment]
If targeting SDK 32, the prompt appears when you (or a plugin) creates a notification channel.

If you target SDK 33, you can requests the permission whenever you want, but requesting the permission is not possible at the moment and won't be implemented until we start working on Capacitor 5.
You can subscribe to this issue https://github.com/ionic-team/capacitor-plugins/issues/1135
