### ISSUE TITLE
camera - opening the gallery fails in Android 13

### ISSUE THREAD

**Issue by modus-jose** [ionic-team/capacitor-plugins#1334]
### Plugin(s)
@capacitor/camera -  4.1.4

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/ios: 4.4.0
  @capacitor/android: 4.4.0

### Platform(s)
Android 13

### Current Behavior
When opening the gallery while using the camera plugin, the plugin always fails due to android 13 using new permissions.
This fails even if the app has the right permissions

### Expected Behavior
The plugin asks for the right permissions, and does not fail.

### Code Reproduction
https://github.com/modus-jose/capacitor-camera-android-13-gallery-issue-reproduction-repo

### Other Technical Details
https://developer.android.com/about/versions/13/behavior-changes-13

### Additional Context
I've added a PR for this
https://github.com/ionic-team/capacitor-plugins/pull/1331

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by modus-jose** [comment]
@Ionitron I just added the code reproduction for this issue. 
A PR is also included, this is for apps targeting SDK 33

**Comment by jcesarmobile** [comment]
Thanks for the sample app, I've been able to reproduce.

As you mentioned, this is only a problem if you target SDK 33, and Capacitor 4 targets SDK 32.

We won't be making any targetSDK changes until we start working on Capacitor 5. I've added the issue to a new Capacitor 5 milestone.

**Comment by modus-jose** [comment]
Hey @jcesarmobile does this means my PR fix will wait for Capacitor 5 then?
We are lowering our mobile department's min target SDK as part of this Capacitor 5 decision

**Comment by jcesarmobile** [comment]
We won't be making any targetSDK changes until we start working on Capacitor 5.
