### ISSUE TITLE
bug(Keyboard): keyboardDidShow and keyboardWillShow Event triggers twice

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/capacitor-plugins#1339]
### Plugin(s)

- Keyboard

### Capacitor Version

```
  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0
  @capacitor/keyboard": "4.1.0
```

### Platform(s)

- ios

### Current Behavior

If you have a view with > 1 input elements and one is already focused with keyboard visible, focus change to another input with visible keyboard will result in triggering `keyboardWillShow` and `keyboardDidShow` twice per focus until blur.

This seems to happen only on ios.

### Expected Behavior

if input is focused and keyboard is visible, focus change to another input element should not trigger `keyboardWillShow` and `keyboardDidShow`, since it's already visible.

### Code Reproduction

Just create a starter Ionic app with two `ion-input` elements and console.log `keyboardWillShow` and `keyboardDidShow`.

```typescript

    Keyboard.addListener('keyboardDidShow', () => {
      console.log('triggers twice if already focused');
    });

    Keyboard.addListener('keyboardWillShow', () => {
       console.log('triggers twice if already focused');
    })

```

```html

<ion-content>
 <ion-list>
      <ion-item>
        <ion-label>Input 1</ion-label>
        <ion-input slot="end"></ion-input>
      </ion-item>

      <ion-item>
        <ion-label>Input 2</ion-label>
        <ion-input slot="end"></ion-input>
      </ion-item>
 </ion-list>
</ion-content>


```

**Comment by jcesarmobile** [comment]
This is by design, the plugin fires the events whenever the native events are fired, and the native events are fired when changing from different fields as the keyboard technically closes and reopens itself.
Note that different inputs can have different types which will show different keyboard types with different sizes, so the event is required for calculating the correct size on input type changes.
