### ISSUE TITLE
Critical behavior to create a custom FormCrontrol with an ion-input element inside. (ControlValueAccessor writeValue)

### ISSUE THREAD

**Issue by francolondra** [ionic-team/capacitor-plugins#1342]
https://forum.ionicframework.com/t/critical-behavior-to-create-a-custom-formcrontrol-with-an-ion-input-element-inside-controlvalueaccessor-writevalue/166127 
In this post  is all description the problem in the format that you requested

**Comment by IT-MikeS** [comment]
This isn't an issue with a Capacitor Plugin, and would be better served as a forum/discord post for help, and if it turns out to be an issue it should be opened on the Ionic Framework repo.

**Comment by francolondra** [comment]
Thanks @IT-MikeS  , you are right  , I put it in the wrong place.
