### ISSUE TITLE
Local Notifications not showing any actions in iOS 14 Simulator

### ISSUE THREAD

**Issue by alpfactory-alex** [ionic-team/capacitor-plugins#1350]
### Plugin(s)
Local-Notifications

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS 14 Simulator running on Mac

### Current Behavior
Actions are not shown in scheduled notifications at all

### Expected Behavior
Actions should be correctly shown in notifications

### Code Reproduction

Here's the most simple, self-contained hacky code I used and I don't see anything wrong with this. It shows the notification correctly but no actions at all no matter what I am trying:

```
const handleClickNotification = useCallback(async () => {
        await LocalNotifications.registerActionTypes({
            types: [
                {
                    id: 'OPEN_PRODUCT',
                    actions: [
                        {
                            id: 'yes',
                            title: 'Yes',
                        },
                        {
                            id: 'later',
                            title: 'Later',
                            destructive: true,
                        },
                    ],
                },
            ],
        })

        LocalNotifications.schedule({
            notifications: [
                {
                    title: 'Notification Title',
                    body: 'Notification Body,\nNewline?',
                    // largeBody: 'This is a much much larger body containing more info',
                    id: 386,
                    actionTypeId: 'OPEN_PRODUCT',
                    schedule: {
                        at: new Date(new Date().getTime() + 5000),
                    },
                },
            ],
        })
    }, [])
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
Another user created a similar issue and provided a sample app
https://github.com/ionic-team/capacitor-plugins/issues/1376

I ran the app and the actions are working as expected, I provided a screenshot, but the buttons on iOS only appear if you long press the notification.
