### ISSUE TITLE
Splash screen Android 12 not working

### ISSUE THREAD

**Issue by marshall86** [ionic-team/capacitor-plugins#1356]
Hi, I'm using Ionic 6.4 and Capacitor 4.6.1 with Angular.

My capacitor config looks like this:

SplashScreen: {
      launchAutoHide: false,
      androidScaleType: "CENTER_CROP",
      splashFullScreen: true,
      splashImmersive: false,
      backgroundColor: "#003366",
      launchShowDuration: 2000
 }

Unfortunately, when i run the app on an android 12 device the splash screen doesn't show my image but a black screen. Any idea how to fix it?

I'm even using this android style

<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
    <item name="android:background">@drawable/splash</item>
 </style>

**Comment by silvar23** [comment]
See Android 12 splash screen api section: https://capacitorjs.com/docs/apis/splash-screen#android-12-splash-screen-api

**Comment by marshall86** [comment]
i already have been through that doc.. no luck

**Comment by silvar23** [comment]
Working for me since I used a SVG square image instead of generated png files. (Android Studio -> new vector asset -> loaded local SVG file)

**Comment by marshall86** [comment]
what's your android studio xml style config?

**Comment by silvar23** [comment]
Here: https://pastebin.com/0in7strs

**Comment by marshall86** [comment]
yeah i was doing something like you did and i managed to show the icon in the splash screen.. now my problem is the background color that isn't the one i'm setting. What i mean is i have a logo with a blue background as icon and i set the same blue as splash screen color but it's showing in a different way

**Comment by silvar23** [comment]
The value in **windowSplashScreenBackground** is working for me.

**Comment by marshall86** [comment]
do you have a v31 styles.xml?

**Comment by silvar23** [comment]
Tested with 31 and 32

**Comment by marshall86** [comment]
i didn't manage to make it works yet.. i changed the theme in the android manifest with AppTheme.NoActionBarLaunch and in the styles.xml file i'm using the same config you passed me. The only thing i changed is drawable/ls with drawable/splash but i can see a black background (don't know where it comes from) and the image (squared) in the middle of the screen.

**Comment by marshall86** [comment]
i found out that the issue is because of the dark mode... trying to figure it out that now

**Comment by marshall86** [comment]
I managed! My solution is like this:

`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">

    
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="android:windowBackground">@color/colorPrimary</item>
        <item name="windowSplashScreenBackground">@color/colorPrimary</item>
    </style>

    
    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.NoActionBar">
        
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:background">@drawable/splash</item>


        
        <item name="android:statusBarColor">@color/colorPrimary</item>
        <item name="android:navigationBarColor">@color/colorPrimary</item>

        <item name="android:windowBackground">@color/colorPrimary</item>
        <item name="windowSplashScreenBackground">@color/colorPrimary</item>
    </style>

    
    <style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="android:background">@drawable/splash</item>

        <item name="android:windowBackground">@drawable/splash</item>
        <item name="android:windowSplashScreenBackground" tools:targetApi="31">@color/colorPrimary</item>

        // Set this to the single background color of the splash screen.
        // If you want to change the background color in dark mode, create
        // a night version of the color.
        <item name="windowSplashScreenBackground">@color/colorPrimary</item>

        // Set this to a VectorDrawable. On API 31+ it may animated,
        // in which case it will be animated during launch.
        // See https://developer.android.com/guide/topics/ui/splash-screen
        // for info on size limits.
        <item name="windowSplashScreenAnimatedIcon">@drawable/splash</item>
    </style>
</resources>`

I had to create a night version of the colours and the styles to make it works properly, thanks for your help @silvar23

**Comment by jcesarmobile** [comment]
closing since you figured out

**Comment by marshall86** [comment]
I'm not sure if it's related but i found out that when i create the apk i get this error:

`android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class o.getPadding Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class o.getPadding Caused by: java.lang.reflect.InvocationTargetException`

This issue happens on old android version 7, 8 ecc  because I have a kyc(Jumio) plugin that requires the switch to a new activity

Any idea on how to fix it please?
