### ISSUE TITLE
pushNotificationReceived never gets called when app is in foreground and a push notification is received.

### ISSUE THREAD

**Issue by vanderbreye** [ionic-team/capacitor-plugins#1365]
### Plugin(s)

       @capacitor/push-notifications@4.1.2

### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/core: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)

Android 13, Device

### Current Behavior
When sending a push notification when the app is in foreground, the function pushNotificationReceived gets never called, although listeners are correctly registered AFTER deviceready().
I have no additional push-plugins installed (no local notifications, no other fcm...)

### Expected Behavior
When the App is open, the function pushNotificationReceived should be triggered (worked on cordova) when a push notification is received, although the notification is not displayed by Android.

### Code Reproduction

```

    $additionalData =  ['type'=> 'test'];

    $notification    = array(
        'body' => 'testbody',
        'title' => 'thanks',
        'channelId' => "highfive"
    );
    $fields = array(
        'notification' => $notification,
        'to' => MOBILEID,
        'priority' => 'high',
        'data' =>  $additionalData 
    );

    $headers = array(
        'Authorization: key=' . API_ACCESS_KEY,
        'Content-Type: application/json'
    );
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
    $result = curl_exec($ch);
    curl_close($ch);
```
    

window.addListeners = async function () {
    await Capacitor.Plugins.PushNotifications.addListener('registration', token => {
        console.info('Registration token: ', token.value);
        var registrationId = token.value;
        console.log("registration event: " + registrationId);
        }
    });

    await Capacitor.Plugins.PushNotifications.addListener('registrationError', err => {
        console.error('Registration error: ', err.error);
    });
    await Capacitor.Plugins.PushNotifications.addListener('pushNotificationReceived', notification => {
        console.log("Push received");
        alert("PUSH!");
    });

    await Capacitor.Plugins.PushNotifications.addListener('pushNotificationActionPerformed', notification => {
        console.log('Push notification action performed', notification.actionId, notification.inputValue);
        alert(JSON.stringify(notification));
    });
}

window.registerNotifications = async function () {
    let permStatus = await Capacitor.Plugins.PushNotifications.checkPermissions();
    if (permStatus.receive === 'prompt') {
        permStatus = await Capacitor.Plugins.PushNotifications.requestPermissions();
    }
    if (permStatus.receive !== 'granted') {
        console.log("denied");
    }
    await Capacitor.Plugins.PushNotifications.register();
    Capacitor.Plugins.PushNotifications.createChannel({
        id: 'Match',
        description: 'Match',
        importance: 5,
        visibility: 1,
        name: 'Match',
    }).then(sucesso => console.log('sucessPush')).catch(erro => console.log('errorPush'));
    Capacitor.Plugins.PushNotifications.createChannel({
        id: 'highfive',
        description: 'highfive',
        importance: 5,
        visibility: 1,
        name: 'highfive',
    }).then(sucesso1 => console.log('sucessPush')).catch(erro1 => console.log('errorPush'));
}

### Additional Context

- Worked well back on Cordova
- Could not be tested of Android<13 yet.
- Push is received well when app is in background OR killed

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by vanderbreye** [comment]
closing:
I had started a fresh project, copied over all files and reinstalled the plugins by hand - now "pushNotificationReceived" works as expected.
