### ISSUE TITLE
Time Sensitive Local Notifications on iOS

### ISSUE THREAD

**Issue by nkalupahana** [ionic-team/capacitor-plugins#1367]
### Plugin
Local Notifications

### Description
iOS Local Notifications can be marked as Time Sensitive, which is useful for many apps. It would be nice to be able to have this functionality in the Local Notifications plugin.

### Platform(s)
- iOS

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/659
