### ISSUE TITLE
Use default notification channel for foreground push notifications

### ISSUE THREAD

**Issue by nip3o** [ionic-team/capacitor-plugins#1368]
### Plugin
"@capacitor/push-notifications": "4.1.2",

### Description

If [presentationOptions](https://capacitorjs.com/docs/apis/push-notifications#push-notifications-appearance-in-foreground) are given in the capacitor config, the push notification plugin automatically [creates a notification channel](https://github.com/ionic-team/capacitor-plugins/blob/3c90fea63e2c24deacc38ba9fd8471c2cc0bde56/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/NotificationChannelManager.java#L155-L157) to use for those foreground notifications, with a hard-coded name and description ("Push Notifications Foreground" / "Push notifications in foreground"). This is quite unexpected, especially if the app is internationalized and/or specifies its own channels.

### Platform(s)

Android

### Preferred Solution

Push notifications in foreground should hade the same behavior as other push notifications, and use the "regular" [default notification channel](https://stackoverflow.com/questions/46047343/firebase-how-to-set-default-notification-channel-in-android-app) if no channel is specified on the notification.

An issue with this solution is however that a notification channel might be needed in order to use the "sound" option for `presentationOptions`.

### Alternatives

An alternative solution would be to make it possible to specify a `channelId` to use for this in settings and let the user be responsible for creating the channel themselves if set.

Another option would be to document this behavior so that developers at least knows that this is happening when using `presentationOptions` and instead handle foreground notifications themselves if they do not want the current behavior.

**Comment by RaddishIoW** [comment]
I have completed a PR (#1423) which allows you to:

1. Specify a manually created channel to post notifications to when they are received in the foreground, or
2. Specify options for the default foreground channel (e.g. sound), or
3. Specify that the notification should be posted to the channel for which it was originally intended (i.e. the channel in the notification payload).

This is done through the plugin config, with the default behaviour being the current (post to a special foreground channel created by the plugin).
