### ISSUE TITLE
Google Maps, Android: Y coordinate of click events incorrect when map is not in focus

### ISSUE THREAD

**Issue by jasonroyle** [ionic-team/capacitor-plugins#1369]
### Plugin(s)

@capacitor/google-maps@4.3.0

### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)

Android

### Current Behavior

On click event (or likely any touch event), when the map is determined [not to be in focus](https://github.com/ionic-team/capacitor-plugins/blob/14a045d3880124996b2770cec7b3e28a9f13d231/google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt#L72) the Y coordinate of the click event emitted to the WebView layer is incorrect.

### Expected Behavior

The coordinates of click events should be accurate.

### Code Reproduction

Component:

```typescript
import { Component, ElementRef, HostListener, ViewChild } from '@angular/core';
import { GoogleMap } from '@capacitor/google-maps';

@Component({
  selector: 'my-google-map',
  template: `
    <capacitor-google-map #map></capacitor-google-map>
    <canvas #canvas></canvas>
  `,
  styles: [`
    canvas {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
    capacitor-google-map {
      display: block;
      height: 300px;
    }
  `]
})
export class GoogleMapComponent {
  @ViewChild('canvas') canvasRef!: ElementRef<HTMLCanvasElement>;
  @ViewChild('map') set mapRef(mapRef: ElementRef<HTMLElement>) {
    GoogleMap.create({
      apiKey: '...',
      config: { ... },
      element: mapRef.nativeElement,
      forceCreate: true,
      id: '...'
    });
  }

  @HostListener('document:click', ['$event'])
  onClick(event: MouseEvent): void {
    const canvas = this.canvasRef.nativeElement;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw 'No canvas context';
    const textHeight = 26;
    const canvasRect = canvas.getBoundingClientRect();
    const x = devicePixelRatio * (event.clientX - canvasRect.left);
    const y = devicePixelRatio * (event.clientY - canvasRect.top);
    canvas.height = Math.round(devicePixelRatio * canvasRect.bottom) - Math.round(devicePixelRatio * canvasRect.top);
    canvas.width = Math.round(devicePixelRatio * canvasRect.right) - Math.round(devicePixelRatio * canvasRect.left);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = 'rgb(0, 0, 0)';
    ctx.fillRect(x - 3, y - 3, 7, 7);
    ctx.fillStyle = 'rgb(255, 255, 255)';
    ctx.fillRect(x - 2, y - 2, 5, 5);
    ctx.fillStyle = 'rgb(0, 0, 0)';
    ctx.fillRect(x - 1, y - 1, 3, 3);
    ctx.fillStyle = 'rgb(255, 255, 255)';
    ctx.fillRect(x, y, 1, 1);
    ctx.fillStyle = 'rgb(0, 0, 0)';
    ctx.font = `${textHeight}px monospace`;
    ctx.fillText(`x: ${Math.round(x * 10) / 10}`, x, y + textHeight);
    ctx.fillText(`y: ${Math.round(y * 10) / 10}`, x, y + textHeight * 2);
  }
}
```

### Other Technical Details

Discovered while rendering a side nav element overlaying the map element area. Clicks were registering on navigation items below the one which had actually been pressed. I calibrated the interpreted event by enabling the 'Pointer location' developer option on the device while using a canvas to represent the captured event coordinates. While testing on a real Pixel 6a and emulated Pixel 5, I determined the Y coordinate of the event is offset by 45 pixels, meanwhile, on an emulated Pixel 4 it is around 21 pixels.

### Additional Context

I'm a TypeScript developer and relatively new to hybrid platform development.

As the offset differs between devices, could this have anything to do with the 'status bar' area of the device? If this is included in the coordinate caught by the plugin and simply emitted to the WebView without consideration then this might explain why the offset is only ever vertical and positive and doesn't translate correctly to the WebView.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
closing as duplicate
