### ISSUE TITLE
Notifcations permissions are not requested until after the first one fails

### ISSUE THREAD

**Issue by indiebloom** [ionic-team/capacitor-plugins#1378]
Continuing a discussion from issue 1116, since it has the following inaccurate resolution. What I'm seeing is that using targetSdkVersion = 32, notification permissions are not requested by Android until the first one fails to be delivered while the app is backgrounded. This is not a good user experience.

Previous resolution, which is not correct:
Local notifications are working fine on Android 13 devices as long as the app uses target SDK 32, which is the officially supported SDK of Capacitor 4.
If you target SDK 32 and use notifications the app prompts for permission automatically on first app startup automatically.

If you target SDK 33 then you'll need to do the changes made on this PR
https://github.com/ionic-team/capacitor-plugins/pull/1189

_Originally posted by @jcesarmobile in https://github.com/ionic-team/capacitor-plugins/issues/1116#issuecomment-1217720273_

**Comment by jcesarmobile** [comment]
See https://github.com/ionic-team/capacitor-plugins/issues/1258  and specially this comment
https://github.com/ionic-team/capacitor-plugins/issues/1258#issuecomment-1303991541
