### ISSUE TITLE
User denying camera permission in the prompt on android still opens camera 

### ISSUE THREAD

**Issue by mdm-hub** [ionic-team/capacitor-plugins#1381]
### Plugin(s)

@capacitor/camera - 4.1.4

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.2
  @capacitor/android: 4.6.2
```

### Platform(s)

Android 12

### Current Behavior

When trying to access camera user is being prompted to allow or deny camera permission to the app. Once user clicks "Don't allow" or outisde of permission dialog (overlay) camera is still being opened.

![image](https://user-images.githubusercontent.com/92590772/213492281-81238a9b-72ae-4786-8cb0-135eec90c206.png)

### Expected Behavior

If user clicks "Don't allow" camera should not be opened.

### Code Reproduction

Link to code reproduction:
https://github.com/Exerlol/IonicCameraApp
Repro steps are part of README.md file on above github repo link

### Other Technical Details

Using code following code to open camera (if user is first time requesting camera this will result in camera permission prompt):
```
    const capturedPhoto = await Camera.getPhoto({
      resultType: CameraResultType.DataUrl,
      source: CameraSource.Camera,
      quality: 100,
      saveToGallery: true
    });
```

### Additional Context

Here's the link to gif that demos issue in question:
https://gifyu.com/image/SmLE0

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mdm-hub** [comment]
Code Reproduction that demonstrates the issue is added

**Comment by jcesarmobile** [comment]
The permission is not for taking the picture, no permission is needed for taking a picture using an Intent to the Camera app (which is what the Camera plugin does).
The permission is requested for being able to save the image to the gallery, if not approved it will still take the picture, but won't save it to the gallery.
If you change `saveToGallery: true` to `saveToGallery: false` then it won't request the permission.
