### ISSUE TITLE
Custom notification sound is not played while the app is in foreground

### ISSUE THREAD

**Issue by PuscasAdi** [ionic-team/capacitor-plugins#1388]
### Plugin(s)

@capacitor/push-notifications": "^4.0.0"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
```

### Platform(s)

Android

### Current Behavior

I created an android notification channel and a custom notification sound for it. The issue is that the custom sound only plays while the user has the app closed or in background.

### Expected Behavior

The custom notification sound should be played even if the app is in foreground.

### Code Reproduction

```            
await PushNotifications.createChannel(
            {id: 'orders', name: 'orders', importance: 3, sound: 'order_sound'}
      );
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by RaddishIoW** [comment]
Could be related to https://github.com/ionic-team/capacitor-plugins/issues/1368

**Comment by RaddishIoW** [comment]
I created a PR which should fix this issue - it will allow you to use a custom channel for foreground notifications.

**Comment by RaddishIoW** [comment]
This is caused by the fact that the plugin creates it's own special channel for displaying notifications when the app is in the foreground (and you have the `'alert'` presentation option set in the config for the plugin).
Subsequently, all notifications received when the app is in the foreground ignore the channel specified in the notification payload and instead post to this special foreground channel. Currently, there is no control over this behaviour or the sound played for this channel.

My PR (#1423) fixes this by allowing you to specify a sound, or in fact specify the channel yourself for foreground notifications.

**Comment by RaddishIoW** [comment]
@jcesarmobile Forgive me for the ping, but I don't believe this needs a code reproduction? The behaviour described is exactly the behaviour you would get by default with this plugin - as such, it's not really a 'bug' that would require special reproduction, but a problem with the way the plugin is designed.
Developers would expect that their channel specified in the notification payload would be respected, but it's not, and that is not reflected anywhere in the documentation for the plugin.
I'm not sure a 'code reproduction' would help in any way, even for a regression test?
Again, sorry for the 'ping', but hopefully you understand.

**Comment by RaddishIoW** [comment]
I've given up and created my own plugin to fix this, in case anyone comes across this...
[@haylltd/capacitor-push-notifications](https://www.npmjs.com/package/@haylltd/capacitor-push-notifications)
It's a drop-in replacement for the official plugin. PRs welcome.
