### ISSUE TITLE
feat(google-maps) Use Google Maps SDK 7.3 compatible with ARM

### ISSUE THREAD

**Issue by epitomz** [ionic-team/capacitor-plugins#1403]
### Plugin

`"@capacitor/google-maps": "^4.3.2"`

### Description

For now, it's only possible to build a project containing Google Maps native component on physical device. They just released a new version and the changelog says `Maps SDK [framework installation](https://developers.google.com/maps/documentation/ios-sdk/config#use-cocoapods) with CocoaPods now includes built-in support for XCFramework. This framework allows developers to build code for Xcode Simulator on M1 Macs.`

### Platform(s)

iOS

### Additional Context

[The new Google Maps SDK 7.3](https://developers.google.com/maps/documentation/ios-sdk/release-notes)
I don't know how hard it will be to update from the version 6 to 7 but that would be a real joy for me to be able to build on a simulator directly on my Mac.

Thanks for any news about that

**Comment by jcesarmobile** [comment]
While `GoogleMaps` already supports  ARM, the other dependency, `Google-Maps-iOS-Utils`, used for clustering, is not compatible with ARM.

People interested in this feature can go to the issue on the ios-utils repository and react with the 👍  reaction so they prioritize doing a release.

https://github.com/googlemaps/google-maps-ios-utils/issues/437
