### ISSUE TITLE
Google Map - Draw Polygon

### ISSUE THREAD

**Issue by rateltechcom** [ionic-team/capacitor-plugins#1404]
Feature Request

Plugin
google-map

Description
I cannot continue to my project without draw a polygon on map. Please help me :)

Platform(s)
IOS - Android - Web

**Comment by jcesarmobile** [comment]
You already created a feature request for this
https://github.com/ionic-team/capacitor-plugins/issues/1396
which was closed as duplicate of another existing issue.

please, stop creating issues for this, subscribe to the existing issue
