### ISSUE TITLE
Crash upon retrieving the limited library photos list (with 0 images selected)

### ISSUE THREAD

**Issue by pedromiba** [ionic-team/capacitor-plugins#1408]
### Plugin(s)
@capacitor/camera

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
When selecting limited library permissions and giving access to 0 photos. 
If you attempt to retrieve the limited library photos list it will crash.

### Expected Behavior
It should just return an empty array.

### Code Reproduction
``` 
const limitedLibraryPhotos: GalleryPhotos = await Camera.getLimitedLibraryPhotos();
```

### Other Technical Details
Nothing to add

### Additional Context
![Error](https://user-images.githubusercontent.com/47518029/217211844-d355591d-1868-4e9b-bdef-194e99c358b8.png)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by pedromiba** [comment]
As requested, here is the code to reproduce the reported issue:
[Github link](https://github.com/pedromiba/camera-plugin-issue)

Thanks in advance!
