### ISSUE TITLE
@capacitor/browser -- Enable setting control tint color on iOS and secondary toolbar color on Android

### ISSUE THREAD

**Issue by tallpants** [ionic-team/capacitor-plugins#1411]
### Plugin
`@capacitor/browser`: https://capacitorjs.com/docs/apis/browser

### Description
Currently `@capacitor/browser`'s `open` method allows setting the toolbar color, this would allow additionally setting the control tint color on iOS with [`preferredControlTintColor`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/2274393-preferredcontroltintcolor?language=objc) and the secondary toolbar color on Android (which sets the color of the controls) using [`setSecondaryToolbarColor`](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabColorSchemeParams.Builder#setSecondaryToolbarColor(int)).

Being able to set the toolbar color alone (which is all the package currently allows) is not particularly useful because the default control color of Safari is blue, which conflicts with most colors.

### Platform(s)

- iOS
- Android

### Preferred Solution

- Accept an additional `controlTintColor` parameter in [`OpenOptions`](https://github.com/ionic-team/capacitor-plugins/blob/main/browser/src/definitions.ts#L56) and use it to set the control tint color on iOS and secondary toolbar color on Android.

### Alternatives

None

### Additional Context

This is relatively straightforward -- if your team is open to it I can open a PR adding this functionality instead of having it be a feature request for you to work on.

**Comment by jcesarmobile** [comment]
merging with https://github.com/ionic-team/capacitor-plugins/issues/911 which already request it for iOS
