### ISSUE TITLE
@capacitor/keyboard 4.1.0 -> 4.1.1 update breaks resizing webview on iOS  

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/capacitor-plugins#1413]
### Plugin(s)
@capacitor/Keyboard 

### Capacitor Version
Updating from 4.1.0 to 4.1.1 caused this issue
https://github.com/ionic-team/capacitor-plugins/releases/tag/%40capacitor%2Fkeyboard%404.1.1

### Platform(s)
iOS 

### Current Behaviour
The webview goes fullscreen when keyboard is still showing and input still focussed, overlapping the input. 

https://user-images.githubusercontent.com/3781800/217522791-4b544b0d-a63d-4224-9098-d059410c91d5.mov

### Expected Behavior
The webview should not resize to full screen. 

### Code Reproduction

Reproduction: https://github.com/SaroGFX/capacitor-keyboard-bug

The keyboard plugin is not being called explicitly. It is possibly related to the CSS, as removing all the styling, appears to fix the issue. I tried to isolate what styling properties are triggering the bug, but no success.

Maybe it's a possibility to only apply the new height calculation when stage manager is open? As the fix seems to address an issue with stage manager only.

**Comment by staff0rd** [comment]
Can confirm the same - rolling back to 4.1.0 fixes.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by SaroGFX** [comment]
Please find the reproduction here: 

https://github.com/SaroGFX/capacitor-keyboard-bug

**Comment by farshidpg** [comment]
same issue even when try to typing in inputs page resized . I rollback to 4.1.0 to fix this

**Comment by inear** [comment]
I have the same issue. When having buttons fixed to the bottom it's important that the page is not overlapped by the keyboard. It only happens to me when I switch focus from one input field to another. I notice I get keyboardWillShow twice when it happens (height is 0 first time). Maybe a race condition there. Or that onKeyboardWillShow returns wrong values when the keyboard is already open.

**Comment by jonesdhtx** [comment]
Same issue. `keyboardHeight` reports as 0 when keyboard already visible and tapping on a 2nd input. Reverting to 4.1.0 fixed it for me as well.

**Comment by jonesdhtx** [comment]
This problem still exists in 5.x. This is trickier to revert back to 4.1.0 now that we've upgraded our project's dependencies to use capacitor @ v5. - is the only solution to fork this project and then revert the commit (bc0b787) Or is there an easier way?

**Comment by farshidpg** [comment]
Hello , the bug fix merged in ionic 7.0.9 and you can use and install ionic 7.0.9

**Comment by 7-plus-t** [comment]
I've created a fix (see PR). Would appreciate a review :)

**Comment by 7-plus-t** [comment]
@jcesarmobile why was my PR (https://github.com/ionic-team/capacitor-plugins/pull/1634) not considered? Did I miss something from the contribution guidelines? I've rewritten the plugin in Swift and corrected the height calculation more thoroughly, I think it's still worth to merge it. I've invested quite some effort in it, including manual testing on an array of devices.
