### ISSUE TITLE
Google Map marker SVG not showing in Android

### ISSUE THREAD

**Issue by zagham-nadeem** [ionic-team/capacitor-plugins#1426]
### Plugin(s)

"@capacitor/google-maps": "^4.4.0",

### Capacitor Version

```

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/ios: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0

[success] Android looking great! 👌
```

### Platform(s)

Andorid

### Current Behavior

Capacitor Google map marker svg not working in android app however it is working fine with web . i have used svg from link and from assets working on web but not in android 
is there any kind of error or bug

**Comment by jcesarmobile** [comment]
It's documented that svg are not supported in native platforms (not iOS, nor Android).
It's a limitation on the native SDKs
https://capacitorjs.com/docs/apis/google-maps#marker

**Comment by zagham-nadeem** [comment]
why? javascript and all third party plugins working than why capacitor is behind this feature

**Comment by jcesarmobile** [comment]
which third party plugins support this?

**Comment by zagham-nadeem** [comment]
angular google map AGM

**Comment by zagham-nadeem** [comment]
also javascript code

**Comment by zagham-nadeem** [comment]
do i share the code??? or any working example??

**Comment by zagham-nadeem** [comment]
hey you don't have to hyper or angry
 i have implemented and its working fine on android

**Comment by zagham-nadeem** [comment]
if you need i can share the code 
and you don't have to request google to add that feature

**Comment by zagham-nadeem** [comment]
by the way thanks for the answer,  response and the way you talked
