### ISSUE TITLE
Maybe: support for picking videos?

### ISSUE THREAD

**Issue by qliqdev** [ionic-team/capacitor-plugins#1432]
https://github.com/ionic-team/capacitor-plugins/blob/89d09cb1af52fc7263394e5365a57d475011eabe/camera/ios/Plugin/CameraPlugin.swift#L506

Why cant you make something like that?

```
        configuration.filter = .any(of: [.images, .videos]) 
```

and after return base64String of video?

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/229
