### ISSUE TITLE
On Ios Invalid FCM token Error!

### ISSUE THREAD

**Issue by prakash03yes** [ionic-team/capacitor-plugins#1438]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/77315058/222108753-5c86abb6-beb4-4f92-9889-9273310a08cc.png">

**Comment by jcesarmobile** [comment]
Capacitor returns APNS tokens, not FCM tokens, if you want to use FCM you'll have to use a FCM plugin or follow this guide about how to integrate FCM into your app
https://capacitorjs.com/docs/guides/push-notifications-firebase
