### ISSUE TITLE
@capacitor/screen-orientation: ScreenOrientation.lock({orientation: 'landscape'}) locks to portrait-primary

### ISSUE THREAD

**Issue by WIStudent** [ionic-team/capacitor-plugins#1452]
### Plugin(s)

@capacitor/screen-orientation@4.1.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/core: 4.7.0
  @capacitor/cli: 4.7.0
  @capacitor/ios: 4.7.0
  @capacitor/android: 4.7.0
```

### Platform(s)

- iOS
- Android

### Current Behavior

Calling
```typescript
ScreenOrientation.lock({orientation: 'landscape'})
```
locks the screen orientation to `portrait-primary`.

### Expected Behavior

Calling
```typescript
ScreenOrientation.lock({orientation: 'landscape'})
```
should lock the screen orientation to either `landscape-primary` or `landscape-secondary`.

### Additional Context

The [ScreenOrientation.lock() specification](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock) and the typescript type `OrientationLockType` allow the values
```typescript
"any" | "landscape" | "landscape-primary" | "landscape-secondary" | "natural" | "portrait" | "portrait-primary" | "portrait-secondary"
```

The current Android and iOS implementations of `@capacitor/screen-orientation@4.1.0` only handle `landscape-primary`, `landscape-secondary`, `portrait-primary` and `portrait-secondary`. In all other cases they fall back to `portrait-primary`:

```java
  private int fromOrientationTypeToEnum(String orientationType) {
      switch (orientationType) {
          case "landscape-primary":
              return ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
          case "landscape-secondary":
              return ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE;
          case "portrait-secondary":
              return ActivityInfo.SCREEN_ORIENTATION_REVERSE_PORTRAIT;
          default:
              // Case: portrait-primary
              return ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
      }
  }
```

```swift
  private func fromOrientationTypeToMask(_ orientationType: String) -> UIInterfaceOrientationMask {
      switch orientationType {
      case "landscape-primary":
          return UIInterfaceOrientationMask.landscapeLeft
      case "landscape-secondary":
          return UIInterfaceOrientationMask.landscapeRight
      case "portrait-secondary":
          return UIInterfaceOrientationMask.portraitUpsideDown
      default:
          // Case: portrait-primary
          return UIInterfaceOrientationMask.portrait
      }
  }
```

A `landscape` case should be added that locks the screen orientation to one of the landscape orientations.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
