### ISSUE TITLE
google-maps Unable to target markers with custom popover

### ISSUE THREAD

**Issue by martinglover** [ionic-team/capacitor-plugins#1482]
### Plugin(s)
@capacitor/google-maps: 4.5.0

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/ios: 4.7.0
  @capacitor/android: 4.7.0
```

### Platform(s)
Web/Android (not tested on iOS)

### Current Behavior
`setOnMarkerClick((data) => {})` returns a param markerId that is doesn't look to have any relevance to the marker, on web the value returned is an array index for the private array of markers, meaning we get no usable data to use a marker as the target for any custom popover to display.

### Expected Behavior
To be able to use the markerId (or any parameter) to target the marker with a custom popover

**Comment by DwieDima** [comment]
related: #1352

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
