### ISSUE TITLE
Capacitor 4 handling of Android light/dark themes is still buggy

### ISSUE THREAD

**Issue by moose4lord** [ionic-team/capacitor-plugins#1489]
## Bug Report
This is a repost of Capacitor issue #6400 [https://github.com/ionic-team/capacitor/issues/6400](https://github.com/ionic-team/capacitor/issues/6400), which didn't seem to get much traction. The commenter blamed the issue on WebView, but I'm not so sure. If I start the app on my computer with ```ionic serve --external``` and access it as a PWA on my phone, then the switching between light and dark themes works flawlessly. I can flip flop between light and dark themes all day, and the app and status bar both look the way they should. Seems like an Ionic Android integration problem to me. But aaaaanywaaaaay...

Part of my issue is with how the status-bar plugin behaves, so please read on....

### Plugin(s)
status-bar plugin

### Capacitor Version
```
Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.6.1
   @angular-devkit/build-angular : 15.2.2
   @angular-devkit/schematics    : 15.2.2
   @angular/cli                  : 15.2.2
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.13.0 (/usr/local/bin/node)
   npm    : 8.19.3
   OS     : macOS Catalina

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0

[capacitor] [info] Found 5 Capacitor plugins for android:
[capacitor]        @capacitor/app@4.1.1
[capacitor]        @capacitor/haptics@4.1.0
[capacitor]        @capacitor/keyboard@4.1.1
[capacitor]        @capacitor/preferences@4.0.2
[capacitor]        @capacitor/status-bar@4.1.1

Here is my userAgent string:
userAgent:Mozilla/5.0 (Linux; Android 12; Pixel 3a Build/SP2A.220505.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36
```

### Platform(s)
Android

### Current Behavior
Capacitor is still having issues with handling light/dark themes on Android.

If I start an app using the Android light theme, the screen shows the app with a light background, but the status bar is shown as white text on a gray background (instead of black text on a white background). Not a deal breaker, but it looks odd. If I use the StatusBar.getInfo() API to read back the state of the status bar, it shows the status bar color is #757575, but it's style is DARK (which is incorrect, it should be LIGHT).
![Screenshot1_light_theme](https://user-images.githubusercontent.com/15672113/225417651-409c43aa-8e1c-454c-aea2-ed7fd3429eed.png)
Then if I change to the Android dark theme, the app colors change to dark colors, as they should, but the status bar remains white text on a gray background (instead of white text on a black background).
![Screenshot2_light_to_dark_theme](https://user-images.githubusercontent.com/15672113/225417747-eedc73dc-f6fc-48f8-b78b-cfa621a41282.png)
Changing back to the Android light theme does nothing, the app remains stuck on the dark theme. You need to exit and restart the app to reset the theme.

Similarly, if I start an app using the Android dark theme, the screen shows the app with a dark background, and the status bar is show as white text on a black background. If I use the StatusBar.getInfo() API to read back the state of the status bar, it shows the status bar color is #000000 and it's style is DARK. Everything is working as it should.
![Screenshot3_dark_theme](https://user-images.githubusercontent.com/15672113/225417813-7a3fade3-174f-4548-976d-3fe607fcf05e.png)
Then if I change to the Android light theme, the app colors change to light colors, as they should, but the status bar remains white text on a black background (should be black text on a white background).
![Screenshot4_dark_to_light_theme](https://user-images.githubusercontent.com/15672113/225417886-629a3aeb-aa40-499e-bb0d-0216288265f1.png)
Again, changing the Android theme back to dark does nothing, the app seems to be stuck with the light theme.

So, I think this is highlighting three related issues:

1) changing the Android theme while an app is running only works the first time you do it. After that, changing the Android theme has no effect on the running app.
2) The capacitor status bar plugin is not updating the status bar properly when the theme changes, and displays an odd grey status bar when the light theme is in effect.
3) The capacitor status bar plugin's StatusBar.getInfo() API does not detect the light theme properly (says style=DARK).

These bugs are mentioned in issue #6100 ([https://github.com/ionic-team/capacitor/issues/6100](https://github.com/ionic-team/capacitor/issues/6100)), but that issue has been closed. @jcesarmobile made a comment about Capacitor 4 using Android's DayNight theme, and that was supposed to handle the light/dark theming automatically, but that doesn't seem to be the case.

### Expected Behavior
The status bar should be black text on a white background when the Android light theme is in use.
Also the status-bar plugin should update the coloring of the status bar when the Android theme changes.

### Code Reproduction
You can see the issue with any of the Ionic starter apps. My repo is here:
[https://github.com/moose4lord/myApp-6.6.1](https://github.com/moose4lord/myApp-6.6.1)

### Other Technical Details
NodeJS : v18.13.0 (/usr/local/bin/node)
npm : 8.19.3

**Comment by jcesarmobile** [comment]
Closing as invalid since it the same issue I already closed as invalid in capacitor repository.
I told you to create a feature request issue for the status bar plugin for automatically switching the style based on the device theme, not to repeat the same issue again,
And please, don’t ping me when you create issues.
