### ISSUE TITLE
feat: rename PermissionStatus interface

### ISSUE THREAD

**Issue by rbalet** [ionic-team/capacitor-plugins#1500]
### Description

Actually, `@capacitor/camera` and `@capacitor/push-notifications` uses both the `PermissionStatus` interface.

This made it impossible to be used in the same file. 

Feature: rename those `CameraPermissionStatus` and `NotificationsPermissionStatus`. 

### Platform(s)

* @capacitor/camera
* @capacitor/push-notifications

### Preferred Solution

rename those `CameraPermissionStatus` and `NotificationsPermissionStatus`. 

### Alternatives

using `any` '^^

### Additional Context

I'm creating an `authorization.service.ts` file that does contain every authorization logic.

**Comment by jcesarmobile** [comment]
Can you provide a sample app that presents that problem? 
I can use both plugins on the same file without any problems

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by rbalet** [comment]
> Can you provide a sample app that presents that problem? I can use both plugins on the same file without any problems

Sorry, I missed your comment.

Let say in your file you're giving type to 2 element, let say :

```typescript
Import { PermissionStatus } from '@capacitor/camera'
Import { PermissionStatus } from '@capacitor/push-notifications'

let cameraStarus?: PermissionStatus
let notificationsStarus?: PermissionStatus
```

How are you expecting the code to know which `PermissionStatus`status you're talking from.

My proposal 
```typescript
Import { CameraPermissionStatus } from '@capacitor/camera'
Import { NotificationsPermissionStatus } from '@capacitor/push-notifications'

let cameraStarus?: CameraPermissionStatus
let notificationsStarus?: NotificationsPermissionStatus
```
 Hope it help :)

**Comment by jcesarmobile** [comment]
You should be able to do
```
Import { PermissionStatus as CameraPermissionStatus } from '@capacitor/camera'
Import { PermissionStatus as NotificationsPermissionStatus } from '@capacitor/push-notifications'
```

**Comment by rbalet** [comment]
@jcesarmobile Thx, I'll go with that.

Just though it would be kind of Cleaner that way, since the library is using two time the same interface name that does not contains same values.

Thx for your help

I wish you a nice day
