### ISSUE TITLE
Keyboard web plugin throws no-op error

### ISSUE THREAD

**Issue by cornflakes** [ionic-team/capacitor-plugins#1511]
### Plugin(s)
Keyboard

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/ios: 4.4.0
  @capacitor/android: 4.4.0

```

### Platform(s)
Web

### Current Behavior
When using the Keyboard plugin, we get the following log in the console, for an app using Capacitor in a desktop web browser:
![image](https://user-images.githubusercontent.com/767700/218044244-c83cafa6-4697-4771-984f-496a47c01dc6.png)
`Error: Uncaught (in promise): Error: "Keyboard" plugin is not implemented on web`

### Expected Behavior
Error should not be thrown

### Code Reproduction
use the keyboard plugin in a webcontext

**Comment by cornflakes** [comment]
I have made a PR solving this issue:
https://github.com/ionic-team/capacitor-plugins/pull/1416

**Comment by cornflakes** [comment]
@ltm - Please take a look at this :-)

**Comment by cornflakes** [comment]
@IT-MikeS - Please take a look at this :-)

**Comment by jcesarmobile** [comment]
This is by design, when plugins don't have a web implementation they throw that error and Keyboard plugin doesn't have a web implementation, so it's not a bug.
