### ISSUE TITLE
Filesystem permissions not working for Android 13 

### ISSUE THREAD

**Issue by RB-Hippo** [ionic-team/capacitor-plugins#1512]
### Plugin(s)

 - @capacitor/camera@5.0.0-nightly-20230329T152052.0
 - @capacitor/filesystem@5.0.0-nightly-20230329T152052.0

### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 5.0.0-nightly-20230329T151455.0

[success] Android looking great!
```

### Platform(s)

Android 13

### Current Behavior

When the user presses the relevant button on our app, the Android camera is opening but the photo that the user takes is not displayed on the page in the app.
<hr>
When we have the `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions in the `AndroidManifest.xml` file, the following error message is logged:

```
E/Capacitor/Console: File: http://localhost/vendor.js - Line 175229 - Msg: ERROR Error: Uncaught (in promise): Error: Unable to do file operation, user denied permission request
    Error: Unable to do file operation, user denied permission request
        at returnResult (http://localhost/:767:32)
        at win.androidBridge.onmessage (http://localhost/:742:21)
```
With these permissions in the manifest, the required permissions do not show up in the app's settings to manually turn on either.
<hr>
When we instead have the new `READ_MEDIA_IMAGES`, `READ_MEDIA_AUDIO` and `READ_MEDIA_VIDEO` permissions for Android 13 (as detailed [here](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions)) in the `AndroidManifest.xml` file, then the following error message is logged instead:

```
E/Capacitor/Console: File: http://localhost/vendor.js - Line 175229 - Msg: ERROR Error: Uncaught (in promise): Error: Missing the following permissions in AndroidManifest.xml:
    android.permission.READ_EXTERNAL_STORAGE
    android.permission.WRITE_EXTERNAL_STORAGE

 

    Error: Missing the following permissions in AndroidManifest.xml:
    android.permission.READ_EXTERNAL_STORAGE
    android.permission.WRITE_EXTERNAL_STORAGE

 

        at returnResult (http://localhost/:767:32)
        at win.androidBridge.onmessage (http://localhost/:742:21)
```
With these permissions in the manifest, the required permissions do show up in the app's settings to manually turn on, but turning them on does not make any difference to the error message.
<hr>
When we have all five of the permissions (`READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE`, `READ_MEDIA_IMAGES`, `READ_MEDIA_AUDIO` and `READ_MEDIA_VIDEO`) in the `AndroidManifest.xml` file, the following error message is logged (the same one as when we just have the `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions):

```
E/Capacitor/Console: File: http://localhost/vendor.js - Line 175229 - Msg: ERROR Error: Uncaught (in promise): Error: Unable to do file operation, user denied permission request
    Error: Unable to do file operation, user denied permission request
        at returnResult (http://localhost/:767:32)
        at win.androidBridge.onmessage (http://localhost/:742:21)
```

### Expected Behavior

When the user presses the relevant button on our app, the Android camera should open and the photo that the user takes should be displayed on the page in the app.

### Code Reproduction

https://github.com/RB-Hippo/ionic-capacitor-issue-reproduction

### Other Technical Details

 - Visual Studio Code version 1.76.2
 - Node v16.17.0
 - OS: Windows_NT x64 10.0.19045
 - Android Studio Electric Eel | 2022.1.1 Patch 2
 - Behind company proxy

### Additional Context

 - https://github.com/ionic-team/capacitor-plugins/issues/1334
 - https://github.com/ionic-team/capacitor-plugins/pull/1331
 - https://github.com/ionic-team/capacitor-plugins/pull/1276
 - https://github.com/ionic-team/capacitor-plugins/pull/1509
 - https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions
 - https://forum.ionicframework.com/t/target-android-13-sdk-33/231076
 - https://forum.ionicframework.com/t/filesystem-write-file-in-android-13/230599/4

**Comment by RB-Hippo** [comment]
Unfortunately, not yet.

**Comment by BurkusCat** [comment]
I think this should belong in the Capacitor 5 milestone (https://github.com/ionic-team/capacitor-plugins/milestone/12) since it breaks photos when targeting Android API 33

**Comment by jaknowakowski** [comment]
Android 13, MIUI 14.0.7, POCO F3 - plugin stopped working, not asking for permissions in runtime.
tested version: 5.0.2

**Comment by jcesarmobile** [comment]
`Directory.Documents` uses a native folder that has been deprecated since SDK 29, use another folder such as `Directory.Caches` or `Directory.Data`.

But we should fix the permission problem since the write/read permissions have no effect on Android 13.

**Comment by BurkusCat** [comment]
> Directory.Documents uses a native folder that has been deprecated since SDK 29

The documentation for Ionic says this folder isn't accessible on Android 11 or newer. But up until Capacitor 5, I think it was working on Android 11/12. I think if the new `READ_IMAGES` etc. permissions were implemented in this plugin, it should still be possible to save/read images outside of the app directory into the `Documents` folder.

**Comment by pranavagiligar** [comment]
I tried Directory.Caches or Directory.Data instead. But it is still giving the same error

**Comment by RB-Hippo** [comment]
The details in #1666 will be useful for anyone trying to fix this issue.

**Comment by jcruzrg** [comment]
I have the same error

**Comment by dimitrivalax** [comment]
I have replace "Directory.Documents" by "Directory.Library" and it's work fine.

**Comment by klaurtar** [comment]
Can we get some eyes on this by the Capacitor team? This is effecting a large number of my android users. They can't download any files from my app since v5 update

**Comment by josuelmm** [comment]
Workaround is to use Directory.Library

**Comment by klaurtar** [comment]
> Workaround is to use Directory.Library

I tried it and no errors occured, but I also could not find the file. Where exactly does Directory.Library save?

**Comment by BurkusCat** [comment]
> > Workaround is to use Directory.Library
> 
> I tried it and no errors occured, but I also could not find the file. Where exactly does Directory.Library save?

["The Library directory On iOS it will use the Library directory. On Android it's the directory holding application files. Files will be deleted when the application is uninstalled."](https://capacitorjs.com/docs/apis/filesystem)

`Directory.Library` is meant for saving in the local application files. It won't let you save to a public `Documents` folder that is accessible by other apps. `Directory.Documents` is still important for some use cases.

**Comment by klaurtar** [comment]
> > > Workaround is to use Directory.Library
> > 
> > 
> > I tried it and no errors occured, but I also could not find the file. Where exactly does Directory.Library save?
> 
> ["The Library directory On iOS it will use the Library directory. On Android it's the directory holding application files. Files will be deleted when the application is uninstalled."](https://capacitorjs.com/docs/apis/filesystem)
> 
> `Directory.Library` is meant for saving in the local application files. It won't let you save to a public `Documents` folder that is accessible by other apps. `Directory.Documents` is still important for some use cases.

Yeah. I need to save to the Documents folder. I unfortunately need a fix for this ASAP. My users have a lot of government documents they need to access.

**Comment by Anexo** [comment]
I also having this issue with v5.0.4 (latest at the timo of writing).

Anyone has been able to find a fix or workaround?

**Comment by dgreasi** [comment]
Same issue here

**Comment by Cyri1** [comment]
same problem here

**Comment by MLazarevic36** [comment]
Help us Lord! 🙏

**Comment by st3fus** [comment]
We need a fix for this ASAP...

**Comment by abdunnahid** [comment]
I am doing an workaround for now by sharing immediately after writing the file to `Directory.Cache`. At least the users will be able to share the files in a persistent place.

``` typescript
import { Filesystem, Directory, Encoding, FilesystemPlugin, WriteFileOptions } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';

public async saveFile(data: string, fileNameWithExtension: string, type: string): Promise<boolean> {

  if (typeof data != 'string') {
    data = JSON.stringify(data);
  }

  // Browser
  if (this._platform.is('mobileweb') || this._platform.is('desktop')) {
    const blob = new Blob([data], { type });
    this._saveFileBrowser(blob, fileNameWithExtension);
    return true;
  }

  // Native
  try {
    const fileConfig: WriteFileOptions = {
      path: `Exports/${fileNameWithExtension}`,
      data: data,
      directory: Directory.Cache,
      encoding: Encoding.UTF8,
      recursive: true
    };
    const writeFileResult = await this._nativeFileSystem.writeFile(fileConfig);
    await this._nativeShare.share({ url: writeFileResult.uri });

    return true;
  }
  catch (error) {
    console.error("Error creating file: ", JSON.stringify(error));
    return false;
  }
}
```

Need a fix asap!

**Comment by klaurtar** [comment]
Why have you forsaken us Capacitor team 😫

**Comment by st3fus** [comment]
@jcesarmobile @IT-MikeS @ItsChaceD 

help
