### ISSUE TITLE
[Local Notifications] [Android] v4.1.5 requestPermissions doesn't bring up permission prompt in Android 13

### ISSUE THREAD

**Issue by richacodesofficial** [ionic-team/capacitor-plugins#1525]
### Plugin(s)

@capacitor/local-notifications

```
### Capacitor Version
@capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/ios: 4.0.1
```

### Platform(s)

Android

### Current Behavior

Describe how the bug manifests. Be specific.
LocalNotifications Permission returns denied on android but should return the actual promt result.
I see the bug has been fixed as part of https://github.com/ionic-team/capacitor-plugins/pull/1189 but i dont see the code on downloading npm i @capacitor/local-notifications (4.1.5)

### Expected Behavior
LocalNotifications Permission returns denied on android but should return the actual promt result.
I see the bug has been fixed as part of https://github.com/ionic-team/capacitor-plugins/pull/1189 but i dont see the code on downloading npm i @capacitor/local-notifications (4.1.5)

### Code Reproduction
npm i @capacitor/local-notifications (4.1.5)
LocalNotifications Permission returns denied on android.

### Other Technical Details
I see the bug has been fixed as part of https://github.com/ionic-team/capacitor-plugins/pull/1189 but i dont see the code on downloading npm i @capacitor/local-notifications (4.1.5)

### Additional Context
Please let me know if its in a specific version of @capacitor/local-notifications

**Comment by jcesarmobile** [comment]
This has been fixed for capacitor 5 and  local notifications 5 (still in beta) and won’t be back ported to capacitor 4 since it’s s a breaking change.
