### ISSUE TITLE
MarkerId is returned in a different format after click

### ISSUE THREAD

**Issue by flotrugliocoffice** [ionic-team/capacitor-plugins#1526]
https://github.com/ionic-team/capacitor-plugins/blob/d53b649da594ee7e30d7cff4f7cdb87ba6a436b5/google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift#L712

As you can see on AddMarker and AddMarkers function the markerId is returned as String 
In these functions markerId is returned as Int, please add the String casting like in the add functions.

simply this:                 "markerId": String(marker.hash.hashValue),

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by flotrugliocoffice** [comment]
> This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> 
> Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> 
> Thanks! Ionitron 💙

Yes.
For example if you create a map item in an app, 
- firstly add a lot of markers and wait for the markerIds list.
- then click on a marker (from iOS simulator - os v. 15. or greater) and you will see the result.

Look the attached screenshot (taken from a debug session on iOS):
![image](https://user-images.githubusercontent.com/25480241/231162036-84b5ef96-d393-47d1-8865-793d5cc93068.png)
As you can see, before sending to Js the markerID is 6438618702276968258, but the Capacitor core will receive the event with markerID: 6438618702276968000.

If you change the returned json preventing a String casting, the issue will be solved: 
![image](https://user-images.githubusercontent.com/25480241/231163420-bf8fc263-ed87-401e-89a9-179588b83533.png)

**Comment by jcesarmobile** [comment]
please, provide a sample app where the issue can be reproduced (no google keys are required, we will use our own)

**Comment by flotrugliocoffice** [comment]
> please, provide a sample app where the issue can be reproduced (no google keys are required, we will use our own)

Ok, I've  to create an app for this scope. I need more time to do this!

**Comment by chrisweb** [comment]
This issue has already been raised in the ticket https://github.com/ionic-team/capacitor-plugins/issues/1139

There is also a 6 month old PR with a fix waiting for review https://github.com/ionic-team/capacitor-plugins/pull/1222

**Comment by chrisweb** [comment]
I have created a repository with a code reproduction: https://github.com/chrisweb/capacitor_google_maps_ticket_1526

I have added an indepth explanation in the readme but will do a recap here:

you need to run the app on an **iOS device**

then open safari developer tools and look at the **console** tab

now in the app click on the **add marker** button, then click on the marker that has appeared on the map itself

then look at the **console**, you will see that I printed out the marker ID at creation time and a second time when the onMarkerClick got triggered, both marker IDs are **NOT** the same, they are often similar but **NOT** equal, also the type is different

**Comment by jcesarmobile** [comment]
thanks for the sample app, it's really well explained and I could reproduce

**Comment by chrisweb** [comment]
thank you for your feedback and for accepting the PR with some of your own changes

**Comment by flotrugliocoffice** [comment]
Thanks @chrisweb for your sample app! and thanks to every body for the Accepted PR!
