### ISSUE TITLE
How to use Clipboard to copy images?

### ISSUE THREAD

**Issue by gabyzenack** [ionic-team/capacitor-plugins#153]
### Description
In the documentation it never explains how to copy an image, only text.

Clipboard.write({ string: "Hello World!"});

And specify the following:
"The Clipboard API enables copy and pasting to/from the clipboard. On iOS this API also allows copying images and URLs"

### Platform(s)

Ionic-React

**Comment by hinddeep** [comment]
Following is the code snippet I've written in Ionic Angular:
`const dataurl = this.canvas.toDataURL();`
` Clipboard.write({image:dataurl})`

You can draw an image from img tag onto canvas and then get a data url from that canvas. Pass the data url thus obtained to Clipboard's write function. It should do the trick.

**Comment by jcesarmobile** [comment]
yeah, to copy an image, pass the images's data url like hinddeep explaineded

we have an example on our sample app
https://github.com/ionic-team/capacitor-testapp/blob/main/src/pages/Clipboard.tsx#L51
