### ISSUE TITLE
Add instructions on how to fork a plugin

### ISSUE THREAD

**Issue by davidisaaclee** [ionic-team/capacitor-plugins#1539]
### Plugin
All

### Description
Does anyone have a way to make changes to a plugin and then use that modified plugin in their own project? Ideally, I could then push those changes into a PR. The solution can be messy; I just want to use this project and easily contribute.

I'd like to contribute to these plugins, but it's difficult to make and test changes. I can't figure out how to use a plugin that I've forked (due to monorepo + `prepublishOnly` build step + use of pod trunk?). I can copy-and-paste files to a new plugin project, but then I can't easily collect my changes into a PR to contribute here.

### Platform(s)
n/a (I guess I'm using yarn + forking via github + ios/web app)

### Preferred Solution
Documentation in contributing guide on how to make changes to a single plugin and then use that plugin in a real application (without completely copying code to a new repo). 

As for _how to actually use a forked plugin in a Capacitor app_, I don't really know; I'd love to hear if someone has a good solution. some ideas:

- install from subdirectory of fork
  1. fork capacitor-plugins monorepo as normal
  2. use https://gitpkg.vercel.app/ to install a specific subdirectory of the fork as a package in my app (adding a custom postinstall script to build)
- turn each plugin into a git submodule
- use a github action on a fork to build tgz of each plugin and push to github packages
- `yarn link` (I don't love this approach because it means I need to set up and maintain the linking on each dev machine)
- break apart monorepo :| (I don't think that this little issue will trigger such a large change, but I don't see the benefit of this being a monorepo)

**Comment by jcesarmobile** [comment]
Have you checked the Local Setup section of the contributing guide?
https://github.com/ionic-team/capacitor-plugins/blob/main/CONTRIBUTING.md#local-setup
Step 6:
```
cd my-app/
npm install ../path/to/capacitor-plugins/<plugin>
```
`my-app` is your app where you want to test the plugin
`<plugin>` is the folder name of the plugin you want to to install
i.e. `npm install ../path/to/capacitor-plugins/device`
What is not mentioned and maybe should be is that you have to run `npm run build` from the plugin repository to build the dist folder, and every time you make any changes on the types or web code run it again.

**Comment by davidisaaclee** [comment]
Thank you - that's a helpful pointer.

I did read that, but I didn't consider it because it requires a specific directory setup (e.g. in `npm install ../path/to/capacitor-plugins/device`, it requires `../path/to/capacitor-plugins` to exist on each dev machine). If there's no better way, I guess I can use a git submodule in my project to achieve this (e.g. within `my-project`, have `my-project/capacitor-plugins` be a forked `capacitor-plugins`; then do `npm install `./capacitor-plugins/dev`).

**Comment by jcesarmobile** [comment]
Well, yeah, usually when doing changes only the person doing the changes have the local code changed. If that person sends a pull request, to test the changes, the person testing needs to get that branch and install the local copy.

if you want to share with more people, you can run npm pack, that creates a tar file that everybody can use, but you still need to distribute it somehow. Even if you commit it to the repository, people would need to clone to get the tar.
