### ISSUE TITLE
pushNotificationReceived event is triggered only when app is in foreground. Not when app is in background

### ISSUE THREAD

**Issue by ChandraKAV** [ionic-team/capacitor-plugins#1554]
I have an app developed with Ionic 6, Capacitor 4.1.x and Angular 14. In the Push Notifications implementation, **pushNotificationReceived** event is trigged only when app is in foreground, on iPhone. I am getting the notification when app is in background or in foreground, but this event is NOT triggered when app is in background. Here is the code sample ...

```
await PushNotifications.addListener('pushNotificationReceived', async (notification: PushNotificationSchema) => {
      // update the app badge count
      const badgeCount = await this.getDeliveredNotifications();
      Badge.set({ count: badgeCount });
    });

private getDeliveredNotifications = async () => {
    const notificationList: DeliveredNotifications = await PushNotifications.getDeliveredNotifications();
    console.log('delivered notifications', notificationList);
    return notificationList.notifications.length;
  }
```
 

Background Mode -> Remote Notifications is turned on in iOS. 

Is this an issue in the plugin? How does the application receive push notifications when the app is in background or when not running?

Question raised on stackoverflow ... https://stackoverflow.com/questions/76055957/capacitor-push-notifications-pushnotificationreceived-event-is-triggered-only

Please help. Thanks in advance. Chandra

**Comment by josuelmm** [comment]
I use this

`await PushNotifications.addListener(
      'pushNotificationReceived',
      (notification: PushNotificationSchema) => {
        console.log('notification ' + JSON.stringify(notification));
        this.zone.run(() => {
          this.notificationsSchema.push(notification);
          setTimeout(()=>{
            //this.showNotification(notification);
            if (Capacitor.getPlatform() === 'android') {        
              this.showLocalNotification(notification.title,notification.body,notification);
            }
          },2000);
        });
      }
    );
    
    await PushNotifications.addListener('pushNotificationActionPerformed',
      (notification: ActionPerformed) => {
        console.log('Push action performed: ' + JSON.stringify(notification));
        let navigationExtras: NavigationExtras = {
          queryParams: {
            data: JSON.stringify(notification.notification.data),
          },
        };
        this._nav.navigateForward(['notification-map'], navigationExtras);
      }
    );`

**Comment by ChandraKAV** [comment]
@josuelmm does pushNotificationReceived event get triggered when app is in background? I will try it out as well and see if it will work! Thanks.

**Comment by josuelmm** [comment]
In My app all work fine

**Comment by ChandraKAV** [comment]
Which version of the plugin are you using?

Sent with Spark

**Comment by josuelmm** [comment]
"@capacitor/push-notifications": "^4.1.2",
 
and I use this
"@capacitor-community/fcm": "^3.0.2",

For connect to topic

**Comment by ChandraKAV** [comment]
I moved to @capacitor-firebase/messaging plugin and that resolved the issue. This issue can now be closed, from my end, unless the author wants to investigate / comment and close.
