### ISSUE TITLE
@capacitor/share on iOS - should present using topmost ViewController

### ISSUE THREAD

**Issue by oshevans** [ionic-team/capacitor-plugins#1560]
### Plugin
@capacitor/share
@capacitor/toast

### Description
These plugins are currently presented using the root ViewController. But when the root view is not the current topmost view, these plugins appear behind the topmost view (not visible). e.g. when using Cordova InAppBrowser.

### Platform(s
iOS

### Preferred Solution
The plugin should find and present on the topmost ViewController.
The plugin should also support presentation on iPad (e.g. popoverPresentationController.sourceView).

### Alternatives
None

### Additional Context
None

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
