### ISSUE TITLE
[@capacitor/google-maps] Android app crash caused by addMarkers

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/capacitor-plugins#1570]
### Plugin(s)
@capacitor/google-maps: 4.5.0

### Capacitor Version
@capacitor/cli: 4.7.0
@capacitor/core: 4.7.0
@capacitor/ios: 4.7.0
@capacitor/android: 4.7.0

### Platform(s)
Android

### Current Behavior
When many markers are added by addMarkers, it takes some seconds in my case till they are rendered. When I destroy the map in this process (in my case I just navigated back, where I call the destroy method on the map instance) and the addMarkers hasnt finished, the app crashes some moments later.

### Expected Behavior
Handle null exceptions to prevent app crash.

### Code Reproduction
- Route to a page that shows the map
- Add many markers so the addMarkers method has work to do
- Navigate back and destroy the map before addMarkers is finished
- Some moments later the app will crash because of a nullpointer exception

### Additional Context
https://github.com/ionic-team/capacitor-plugins/blob/c39d84fbae464fc8984e26f970e85fd1862ff2ac/google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt#L183-L191
`markerIds.add(googleMapMarker.id)`: googleMapMarker can be null here

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by AE1NS** [comment]
Please have a look at the referenced pull request, that fixes the issue. I dont get the error anymore in my application with it.

**Comment by jcesarmobile** [comment]
Please, provide a sample app where the issue can be reproduced, if we can't reproduce we can't verify the pull request fixes the issue.

**Comment by AE1NS** [comment]
https://github.com/AE1NS/capacitor-maps-markers-exception

**Comment by jcesarmobile** [comment]
thanks for the sample app, I could reproduce and verify that the proposed changes fixed the issue
