### ISSUE TITLE
Camera.pickImages(...) scope is getting expanded and showing all photos, though we had set photos permission to limited.

### ISSUE THREAD

**Issue by sen-soumyadip** [ionic-team/capacitor-plugins#1583]
### Plugin(s)
```
"@capacitor/camera": "4.1.4"
```

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0
```
```
[success] iOS looking great! 👌
```

### Platform(s)
- iOS

### Current Behavior
If the user only allows access to specific images in the app's permissions, all images on the device will still appear in Photo Picker ```(Camera.pickImages(...))```. I have used ```pickLimitedLibraryPhotos()``` but it only allows the user to pick the
 selected photos of their choice and ```getLimitedLibraryPhotos()``` only returns the array of selected photos, which doesn't work like ```(Camera.pickImages(...))```.

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-05-08 at 13 08 24](https://user-images.githubusercontent.com/94684012/236785810-0f910dd0-67ed-4d1c-afdb-987948b29056.png)

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-05-08 at 13 09 12](https://user-images.githubusercontent.com/94684012/236785942-aa0e4dcb-adf1-4fdb-82f9-8439180cc463.png)

### Expected Behavior

I expect the Photo Picker to display only the images for which the user has given permission.

### Other Technical Details
-iOS Version: 15.0

**Comment by jcesarmobile** [comment]
That's how Apple provided image pickers work, they allow to pick from all the pictures, not only from the ones the user allowed access to. What the user allows access to is to the sensitive data in the pictures, not to the pictures themselves, all the pictures are always available to pick. If you pick one that the user didn't allow to access you'll get a copy of the image without exif information.

Apple doesn't provide a picker where they only show the images selected by the users, if you want a picker like that you have to create it yourself by using `getLimitedLibraryPhotos()`, that returns all the photos selected by the user.
