### ISSUE TITLE
[@capacitor/google-maps] Refactor options and extend a method to update the map options

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/capacitor-plugins#1617]
### Plugin
@capacitor/google-maps

### Description
This feature request has 2 topics

#### Refactor options
- As styles also exists in `google.maps.MapOptions` it could be removed from `GoogleMapsConfig`. I think you added it here, to show it in the documentation, but I would rather write a comment above the class, which properties from `google.maps.MapOptions` are supported
- To prevent overhead, the `MapType` class could be deleted, because its documented in `google.maps.MapOptions`
- The following methods could be removed and implemented within the options object (this would require to have a `update` method, see below):
   - getMapType
    - setMapType
    - enableIndoorMaps
    - enableTrafficLayer
    - enableAccessibilityElements
    - enableCurrentLocation
    - setPadding
- There should be some additional options in `GoogleMapsConfig` like:
    - isCompassEnabled
    - isRotateGesturesEnabled
    - isTiltGesturesEnabled
    - isToolbarEnabled
    - isZoomGesturesEnabled
- Some more properties of `google.maps.MapOptions` should be handled by the native code like:
    - gestureHandling
    - restriction

#### Add an update method for map options
The above defined changes should also be appliable by an update method, to change them after the map instantiation.

### Platform(s)
Android
iOS
Web

**Comment by djabif** [comment]
Adding to this issue, I think it would be really nice to be able to update the map options as @AE1NS suggests.

In my case I need to set [setMyLocationButtonEnabled](https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/UiSettings#public-void-setmylocationbuttonenabled-boolean-enabled)  to false. 

My problem is that if I set [enableCurrentLocation](https://capacitorjs.com/docs/apis/google-maps#enablecurrentlocation) to true, on Android the default geolocation button is shown, even if I set `disableDefaultUI: true` in the map config options. On iOS it works fine. 

<img width="437" alt="Screenshot 2023-08-27 at 22 05 53" src="https://github.com/ionic-team/capacitor-plugins/assets/1735814/45be1974-512a-424e-9c06-8059f2f34746">

**Comment by matbravob** [comment]
The "disableDefaultUI" is only available for web.  For iOS and Android only the config options declared on GoogleMapConfig are available.

**Comment by ngmiduc** [comment]
Are there any updates on this?

**Comment by AE1NS** [comment]
Moved https://github.com/ionic-team/capacitor-google-maps/issues/25
