### ISSUE TITLE
[@capacitor/google-maps] Add method fitBounds

### ISSUE THREAD

**Issue by heykanna** [ionic-team/capacitor-plugins#1625]
### Plugin
@capacitor/google-maps

### Description
Add method fitBounds which would move and zoom map so it would display all supplied points.

### Platform(s)
Android
iOS

### Preferred Solution
`map.fitBounds({
  points: [],
  animation: true,
  animationDuration: 1000
})`

**Comment by jcesarmobile** [comment]
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1346
