### ISSUE TITLE
Camera Pick Images returns unsafe url

### ISSUE THREAD

**Issue by HarryB15** [ionic-team/capacitor-plugins#1626]
### Plugin(s)
@capacitor/camera

### Capacitor Version

```
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1
```

### Platform(s)
ios

### Current Behavior
When using the pickImages method from capacitor camera the webpath results give Failed to load resource: unsupported URL and the images are not usable, all of the webpaths returned begin with ":unsafe".

### Expected Behavior
The webpaths returned should not be unsafe or there should be an option to return the data url for all of the images

### Code Reproduction
async pickImages(){
    var permissions: PermissionStatus = await Camera.checkPermissions();
    if(permissions.photos == 'denied'){
      this.commonService.DisplayToast("We couldn't access your camera roll, please check the app settings.", "middle")
    }
    else{
      await Camera.pickImages({
        quality: 50,
        limit: 5
      }).then(async (res) => {
        const photos = res.photos;
        for (let i = 0; i < photos.length; i++) {
          this.newPost.images.push({image: photos[i].webPath, fileName: null});
        }
      }).catch(e => {
        if(e == 'Error: Error loading image'){
          this.commonService.DisplayToast("Could not load image successfully", "top")
        }
      })
    }
  }

**Comment by jcesarmobile** [comment]
The `:unsafe` is being added by your framework, not by Capacitor. Capacitor apps on iOS use `capacitor://` as scheme and some frameworks consider that unsafe and you have to configure the framework to trust that scheme or tell it that the url is safe.

We used to have docs about it for angular, but the guide was removed and replaced with another one that doesn't include DomSanitizer https://github.com/ionic-team/capacitor-site/pull/6/files
