### ISSUE TITLE
[@capacitor/push-notifications] requestPermissions()-Call is blocked indefinitely when permissions are already granted on Android 12 or later.

### ISSUE THREAD

**Issue by boomer41** [ionic-team/capacitor-plugins#1628]
### Plugin(s)
Push-Notifications v5.0.2

### Capacitor Version
```
   Capacitor Doctor   

Latest Dependencies:       
                           
  @capacitor/cli: 5.0.4    
  @capacitor/core: 5.0.4   
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4    
                           
Installed Dependencies:    

  @capacitor/cli: 5.0.3    
  @capacitor/android: 5.0.3
  @capacitor/core: 5.0.3   
  @capacitor/ios: 5.0.4    
```

### Platform(s)
Android

### Current Behavior
See https://github.com/ionic-team/capacitor-plugins/blob/2e883f39329626062bcf876fe7d424432617229d/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java#L96

When the Android Version is >= 12, the async call to requestPermissions is not resolved (`call.resolve(...)`) when the permission has already been granted, blocking the Promise on the TypeScript side indefinitely.

### Expected Behavior
Resolve the async call.

### Code Reproduction
- Create an app targeting Android 12 or later.
- Call requestPermissions(). The device should ask the user for permission. The call eventually gets resolved.
- Call requestPermissions() a second time. The await-Call will never return.

Repro Example: https://github.com/boomer41/capacitor-plugins-issue-1628
Click the "Run issue repro" button.
This *should* yield two messages, but only shows one, because the second call to requestPermissions() won't return.
When the button is clicked a second time, no message will show up because the first call to requestPermissions() won't return either.

The code in question:
https://github.com/boomer41/capacitor-plugins-issue-1628/blob/bb0ed1dd7b02c00202a8da7b28ace50f8c37e3e2/src/js/capacitor-welcome.js#L98

### Other Technical Details
Possible fix:

```diff
--- 	Wed May 31 09:06:17 2023 UTC
+++ 	Wed May 31 09:06:17 2023 UTC
@@ -7,6 +7,10 @@
         } else {
             if (getPermissionState(PUSH_NOTIFICATIONS) != PermissionState.GRANTED) {
                 requestPermissionForAlias(PUSH_NOTIFICATIONS, call, "permissionsCallback");
+            } else {
+                JSObject permissionsResultJSON = new JSObject();
+                permissionsResultJSON.put("receive", "granted");
+                call.resolve(permissionsResultJSON);
             }
         }
     }
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by davidemerritt** [comment]
Any update on this?

**Comment by boomer41** [comment]
> Any update on this?

If you need a quick workaround, check whether the permission has already been granted manually.
If it already says yes, don't call the broken method.

**Comment by davidemerritt** [comment]
thanks - I'll try that
