### ISSUE TITLE
Add a package to manage the Navigation Bar 

### ISSUE THREAD

**Issue by loicparent** [ionic-team/capacitor-plugins#1631]
### Plugin
- @capacitor/android

### Description
Hello,
It could be very useful to add in the Official plugins of Capacitor a plugin that allow us to manage the Navigation Bar.
- methods to design the bar (set a color, transparency, etc.).
- methods to show and hide the bar.
- method to get the status of the visibility of the bar (visible or hidden).
- trigger event on the status change (typically, if the bar is visible following a user swipe up).
- etc.

Something similar to [this plugin](https://github.com/hugotomazi/navigation-bar) but with additional features.

### Platform(s)
Android

_Have a nice day,
Loïc_

**Comment by jcesarmobile** [comment]
there is a proposal for a community plugin
https://github.com/capacitor-community/proposals/issues/51

**Comment by loicparent** [comment]
Hello,

Yes, this is correct but this package is not compatible with Capacitor v5.
