### ISSUE TITLE
Mapview overlays Webview at height:100%;

### ISSUE THREAD

**Issue by jonasphp** [ionic-team/capacitor-plugins#1633]
### Plugin(s)
- Google Maps Plugin

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/core: 5.0.3
  @capacitor/ios: 5.0.3
  @capacitor/cli: 5.0.3
  @capacitor/android: 5.0.3

### Platform(s)
iOS

### Current Behavior
On height 100% the mapview overlays webview and makes it impossible to get dom elements to overlay. 

### Expected Behavior
DOM elements should be able to overlay the mapview.

**Comment by ngmiduc** [comment]
I am also having this issue. As a workaround it use the height 99,99%.

Good that this will get fixed soon !
