### ISSUE TITLE
http web: exception on response with http 204 (no-content)

### ISSUE THREAD

**Issue by dartzki** [ionic-team/capacitor-plugins#1635]
### Plugin(s)

capacitor/core": "4.6.2"

### Capacitor Version

```
PASTE OUTPUT HERE
```

### Platform(s)

Web

### Current Behavior

The web implementation tries to parse the response as json (if responseType: json was given as HttpOption) which results in a "SyntaxError: Unexpected end of JSON input" Error.

### Expected Behavior

The web implementation should return a successful empty response when a 204 is encountered.

**Comment by jcesarmobile** [comment]
This was fixed in Capacitor 5.0.0
https://github.com/ionic-team/capacitor/pull/6266
