### ISSUE TITLE
[@capacitor/google-maps] Migration from v4 to v5 erroring

### ISSUE THREAD

**Issue by co-dax** [ionic-team/capacitor-plugins#1636]
### Plugin(s)
@capacitor/google-maps v5.0.0

### Capacitor Version
5.0.0

```
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "GoogleMaps":
        In Podfile:
        CapacitorGoogleMaps (from `../../node_modules/@capacitor/google-maps`) was resolved to 5.1.0, which depends on
        GoogleMaps (~> 7.3)
        
        None of your spec sources contain a spec satisfying the dependency: `GoogleMaps (~> 7.3)`.
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.
        
        [!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use
        TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of
        choice.
```

### Platform(s)
iOS

### Current Behavior
I am getting the log from above when running `npx cap sync ios` after migrating from capacitor v4->v5

### Expected Behavior
It should update plugin without generating the error.

### Code Reproduction

1. `ionic start`
2. `ionic capacitor add ios`
3. `npx cap update ios`
At this point it generates the error from above
I have attached a zipped project for reproduction

[maps.zip](https://github.com/ionic-team/capacitor-plugins/files/11644130/maps.zip)

**Comment by jcesarmobile** [comment]
Your sample app is working fine for me, try running `pod repo update` as the error says and try again, that needs to be run from time to time to get latest CocoaPods libraries.

**Comment by co-dax** [comment]
Thanks @jcesarmobile that seems to have been the issue.
