### ISSUE TITLE
[@capacitor/filesystem] iOS accessing security scoped resources not working

### ISSUE THREAD

**Issue by drefrajo** [ionic-team/capacitor-plugins#1639]
### Plugin(s)
@capacitor/filesystem: 5.0.2

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
iOS

### Current Behavior
I'm trying to open a file inside my capacitor app when the file is opened through the iOS files app (i.e. file app -> click on file -> open my app -> automatically load file inside my app).

Reading the file url with `Filesystem.read` gives the error: `The file "test.ncert" couldn't be opened because you don't have the permission to view it.`

with `url = "file:///private/var/mobile/Containers/Shared/AppGroup/D2B6AB11-8149-49DD-8C19-44F7E4ABC0B1/File%20Provider%20Storage/test.ncert"`

### Expected Behavior
The file should be read without errors.

### Code Reproduction
```
App.addListener("appUrlOpen", async (data) => {
  // get url
  const url = data.url;

  // read file
  const file = await Filesystem.readFile({
    path: url
  });
})
```

This code is in App.vue inside my Capacitor/Ionic/Vue project, though that shouldn't matter.

### Other Technical Details
iOS 16.3.1 iPhone 12 Pro

### Additional Context
[This](https://github.com/ionic-team/capacitor/issues/3492) might be related, but the proposed solution didn't work for me.

After some research, it seems like `url.startAccessingSecurityScopedResource()` needs to be called before and `url.stopAccessingSecurityScopedResource()` after accessing this file url.
See [here](https://developer.apple.com/forums/thread/108323) or [here](https://stackoverflow.com/questions/72287168/the-file-couldn-t-be-opened-because-you-don-t-have-permission-to-view-it-real-d).

Some quick tests showed that modifying `@capacitor/filesystem/ios/Plugin/Filesystem.swift` like so solved my issue:

```
...
public func readFile(at fileUrl: URL, with encoding: String?) throws -> String {
    fileUrl.startAccessingSecurityScopedResource()
    if encoding != nil {
        let data = try String(contentsOf: fileUrl, encoding: .utf8)
        fileUrl.stopAccessingSecurityScopedResource()
        return data
    } else {
        let data = try Data(contentsOf: fileUrl)
        fileUrl.stopAccessingSecurityScopedResource()
        return data.base64EncodedString()
    }
}
...
```

However, I didn't have the time to properly test this solution in multiple scenarios, also I don't have any experience working with swift.

**Comment by mareikewe** [comment]
I'm facing the same issue. No solution has worked for me, except calling these two functions before and after accessing scoped resources like you did.

**Comment by ralphcode** [comment]
+1 -  [#1660](https://github.com/ionic-team/capacitor-plugins/pull/1660) fixes it for us

**Comment by jamesh38** [comment]
Any word on this PR going in? Blocking me badly.

**Comment by drefrajo** [comment]
It's currently in review, 2 out of 6 approved (see the PR).

**Comment by jamesh38** [comment]
> 

Thanks @drefrajo so all six of those folks need to approve for it to be merged?

**Comment by drefrajo** [comment]
Yeah, I think so.
