### ISSUE TITLE
bug?: inconsistent behaviour of respecting sound option across iOS and Android

### ISSUE THREAD

**Issue by tafelnl** [ionic-team/capacitor-plugins#1641]
### Plugin(s)
`@capacitor/push-notifications` (`v4.1.2`)

### Capacitor Version
```
  @capacitor/cli: 4.8.0
  @capacitor/ios: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/core: 4.8.0
```

### Current Behavior
If you send a push notification (either through the Firebase Dashboard 'GUI' or using their API) with the sound enabled, both iOS and Android will generate a sound. At least assuming you've configured the `presentationOptions` to allow so:

```ts
const config: CapacitorConfig = {
  // ...
  plugins: {
    PushNotifications: {
      presentationOptions: ['sound'],
    },
  },
  // ...
};
```

So that's good!

If you specify that no sound should be played, iOS will respect that setting, but Android will still play a sound.

### Expected Behavior
Both iOS and Android should respect the provided sound option. In this case it means that Android is wrong, and it should be adjusted accordingly.

### Code Reproduction
Basic app + `@capacitor/push-notifications` installed

Send a push notification either through the Firebase dashboard or by using their API

**Comment by jcesarmobile** [comment]
Sadly since Android 8 notifications use channels for some configurations such as the sound and some channel configurations can't be modified after creation (like the sound), so if the channel was created with sound the developers can't change the sound nor remove the sound later on.

**Comment by tafelnl** [comment]
Thanks for clarifying, didn't know that. Might be worth to make a note of that in the docs. Although it's not related to Capacitor of course, but it's always nice to make life of developers a tiny bit easier
