### ISSUE TITLE
[@capacitor/google-maps] ZIndex for marker in Android not set

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/capacitor-plugins#1644]
### Plugin(s)
@capacitor/google-maps

### Platform(s)
Android

### Current Behavior
The Android implementation has the zIndex not applied to the markerOptions. In web and iOS its set.

### Expected Behavior
Marker option 'zIndex' should also be set in Android.

### Code Reproduction
Web: https://github.com/ionic-team/capacitor-plugins/blob/main/google-maps/src/web.ts#L647
iOS: https://github.com/ionic-team/capacitor-plugins/blob/main/google-maps/ios/Plugin/Map.swift#L571
Android: https://github.com/ionic-team/capacitor-plugins/blob/main/google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt#L755

**Comment by jcesarmobile** [comment]
Thanks for the issue, we were already aware of it and tracking it internally
It was spotted here https://github.com/ionic-team/capacitor-plugins/pull/1474#pullrequestreview-1341696167
