### ISSUE TITLE
Camera.getPhoto unexpected multi select for the first time

### ISSUE THREAD

**Issue by mahendraHegde** [ionic-team/capacitor-plugins#1656]
### Plugin(s)
Camera Plugin v4.1.4

### Capacitor Version
```
  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
```

### Platform(s)
iOS

### Current Behavior
on iOS 14 & above when ios shows permission  prompt, if you choose `select photos...`  user can select more than 1 images from gallery, however clicking on done after selecting multiple images(or none) will just open another gallery popup and this time user can select only 1 image.

### Expected Behavior
since getPhoto is expected to return single image only 1 image selection should be allowed and double popup should be avoided. 

### Code Reproduction
```
await Camera.getPhoto({
     width: 1600, 
      height: 1600, 
      quality: 40
      resultType: CameraResultType.DataUrl,
      source:CameraSource.Photos
    });
```

### Other Technical Details
NA

### Additional Context
NA

**Comment by jcesarmobile** [comment]
The first prompt is for selecting the images the user gives full access to, the second prompt is the actual image selection.

I agree that it can be confusing, but the behavior is provided by the native component, not by us, so if you want it to change you should report it to Apple.

**Comment by mahendraHegde** [comment]
@jcesarmobile  got it thanks,  is there any way to use the photo picker without this behaviour at all.. different methods or anything? or there is no way to avoid it?

**Comment by jcesarmobile** [comment]
No, if you choose "select photos", a prompt for selecting photos will appear, the only way of not showing it is if you don't choose "select photos", but you can't control what users will choose.

**Comment by mahendraHegde** [comment]
@jcesarmobile  thanks for the answer,  cant we capture the images from 1st prompt, cant we not set limit as 1 and avoid second prompt?

**Comment by davidmack00** [comment]
@jcesarmobile I think the behavior @mahendraHegde described is slightly different than what I am seeing, but I am wondering if there is an alternative solution:

After the initial native iOS behavior where it prompts the user to select multiple images ("select photos" option), is it possible to upload all of the images the user selects? I assume access has just been granted to the multiple items. Currently what I am seeing is that after the user selects multiple images and taps "done," the prompt simply closes and no images are uploaded at all. Only after trying to upload a second time does an image actually get uploaded. Thanks for your help.
