### ISSUE TITLE
[@capacitor/clipboard] Clipboard.read and Clipboard.write doesn't work on Android

### ISSUE THREAD

**Issue by gustavotoyota** [ionic-team/capacitor-plugins#1663]
### Plugin(s)

@capacitor/clipboard@5.0.4

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/ios: 5.0.5

I also tried with Capacitor 3 and 4

### Platform(s)

Tested on Android 12 and 13

### Current Behavior

In my Android 12 phone, Clipboard.write doesn't work, and Clipboard.read always returns { value: '', type: 'text/plain' }, even if I have something in my clipboard.

When emulating in Android Studio, the clipboard works on Android 13 and above.
On Android 12 emulation the same thing happens as in my phone. I keep receiving { value: '', type: 'text/plain' } from Clipboard.read. And something weird happens: the message "[My app name] pasted from the clipboard" is displayed several times after I try to paste.

Another weird thing is that I just updated my phone to Android 13 and clipboard still doesn't work on it.

### Expected Behavior

Clipboard.write and Clipboard.read working normally.

### Code Reproduction

```ts
import { Clipboard } from '@capacitor/clipboard';

await Clipboard.write({ string: text }); // Doesn't work

const result = await Clipboard.read(); // Always returns { value: '', type: 'text/plain' }
```

### Additional Context

Using Capacitor from Quasar Framework.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by gustavotoyota** [comment]
@capacitor/clipboard is working correctly. It was an error on my part.

Basically this is what I learned: `navigator.clipboard` functions "work" on emulation, but throw "Permission denied" on real devices. I didn't know that. This made it so that the code never reached the @capacitor/clipboard code on real devices. This also made the results inconsistent between emulator and real device, so I couldn't trust the emulator in order to debug this problem.
