### ISSUE TITLE
[help]: google maps camera animation

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/capacitor-plugins#1668]
### Plugin(s)
capacitor/google-maps

### Google Maps

There is this configuration in the documentation: 

https://capacitorjs.com/docs/apis/google-maps#cameraconfig

`animationDuration | number | This configuration option is not being used.`

### Plattforms
- web

### Question

I was wondering if there is a possibility to animate the camera in the google maps plugin or if this is something that the capacitor team is planing to implement in the future? I noticed that it is working on IOS but not in the web version. Maybe there are somewhere more clear information about how to use the animation attribute.

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository.

But answering your question, `setCamera` uses `moveCamera`, and that API doesn't doesn't provide a way of animating according to their docs.

> Immediately sets the map's camera to the target camera options, without animation.

https://developers.google.com/maps/documentation/javascript/reference/map#Map.moveCamera
