### ISSUE TITLE
Google Maps: Support to update styles after creating the map

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/capacitor-plugins#1670]
### Plugin
Google Maps

### Description
Update the styles of the map after is was created

### Platform(s)
iOS, Android

### Preferred solution
https://developers.google.com/maps/documentation/android-sdk/styling?hl=de#pass_a_json_style_object_to_your_map

`googleMap.setMapStyle(...)`

**Comment by AE1NS** [comment]
https://github.com/ionic-team/capacitor-plugins/issues/1617 This is a generic solution for updating options, including styles, like:
```
map.update({
    styles: { ... }
});
```
Im already using it in production. Unfortunately I dont get any response to my map optimizations here.

**Comment by paulstelzer** [comment]
@AE1NS I like your PR https://github.com/ionic-team/capacitor-plugins/pull/1618 - this is looking very good. I do not know why nobody check the PRs (there are many open ones)

**Comment by paulstelzer** [comment]
Closed as duplicate of #1617

**Comment by AE1NS** [comment]
You should not ping him. He reads everything here. When the time has come, we will get an answer ;)
