### ISSUE TITLE
Browser.open support in electron.js

### ISSUE THREAD

**Issue by rfarko** [ionic-team/capacitor-plugins#1681]
### Plugin
Browser

### Description
Browser.open does not work in electron.js apps

### Platform(s)
electron.js

### Preferred Solution
Since Browser.open works seamlessly in web, iOS, and Android, it would be very helpful to make it also work in electron.js apps too.
Looks like for electron they recommend to use shell.openExternal, but that would need to import shell in ionic app which not possible.

**Comment by jcesarmobile** [comment]
Capacitor plugins in this repository only support iOS, Android and web, not electron.
