### ISSUE TITLE
Splash Screen is squeezed on Android

### ISSUE THREAD

**Issue by muhammadosmanali** [ionic-team/capacitor-plugins#1689]
### Plugin(s)

@capacitor/splash-screen": "^5.0.5"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

Installed Dependencies:

  @capacitor/cli: 5.1.1
  @capacitor/core: 5.1.1
  @capacitor/android: 5.1.1
  @capacitor/ios: 5.1.1

```

### Platform(s)

Android

### Current Behavior

The splash screen is squeezed in android 11 and below when we use new splash screen api.
![Screenshot (40)](https://github.com/ionic-team/capacitor-plugins/assets/38491660/aa421536-4923-433c-befc-fab418ebda1b)
while normal splash screen look like this 
![image](https://github.com/ionic-team/capacitor-plugins/assets/38491660/749ed8be-c574-428a-b916-acdce4e2619f)

### Expected Behavior

It should be normal just like when we build app using capacitor 3.

### Code Reproduction

It can be reproduce when we create new project with capacitor 5.

**Comment by jcesarmobile** [comment]
The splash screen is now displayed by Google's Android 12 splash screen compat library and it doesn't work well with full screen splash images.
You can report the issue to Google, but they will most likely close it and recommend you to move to splash screen icons (`windowSplashScreenAnimatedIcon`).
https://developer.android.com/develop/ui/views/launch/splash-screen/migrate

**Comment by muhammadosmanali** [comment]
OK thanks for your answer
