### ISSUE TITLE
Bug, Error in push notifications, sound, alert, badge

### ISSUE THREAD

**Issue by josuelmm** [ionic-team/capacitor-plugins#1691]
### Plugin(s)
Push notifications

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

Installed Dependencies:

  @capacitor/core: 5.2.1
  @capacitor/cli: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

### Platform(s)
Apple iOS

### Current Behavior
In Capacitor 4, notifications in iOS were automatically applied to "strip", "globe" and "sound"
Now in 5, only "balloon", "strip" and "sound" are enabled, they do not appear in the notification segment of the app, nor in the notification settings of the application

### Expected Behavior
Capacitor 4
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-07-18 at 12 58 14](https://github.com/ionic-team/capacitor-plugins/assets/12968781/272d963a-14f8-4b2c-8398-d4ecb9467c71)

Capacitor 5
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-07-18 at 12 58 25](https://github.com/ionic-team/capacitor-plugins/assets/12968781/b3d7165e-bb4b-405d-a519-1e8d5f6605a3)

**Comment by josuelmm** [comment]
Any help?

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by josuelmm** [comment]
I got the error.. the problem is
@capawesome/capacitor-badge

It happens that this plugin requests permission from notifications... in apple the notification is divided into 4 types... (sound, badge, banner, list)
That plugin asks for the badge-only permission, before the notifications ask for all types of permissions.
