### ISSUE TITLE
FileDownload catch issue

### ISSUE THREAD

**Issue by justingel** [ionic-team/capacitor-plugins#1698]
### Plugin(s)
@capacitor/filesystem

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

### Platform(s)
iOS

### Current Behavior

When starting a download on iOS (via. Filesystem.downloadFile) and a non-existing url is given, catch is not being thrown.
When i start the same process on android (with the same url), the catch is being thrown.

### Expected Behavior

Same behaviour on both systems.

### Code Reproduction
![image](https://github.com/ionic-team/capacitor-plugins/assets/83697697/c9251866-b1ac-495b-a9af-07b1770985dd)

### Other Technical Details
iPhone 13 Pro - iOS 16.3.1

### Additional Context
https://github.com/capacitor-community/http/issues/224 - sounded a bit like it?

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by justingel** [comment]
I don't think this needs further reproduction.

Just take a non-existent URL, for example "https://capacitorjs.com/test/test.zip" and start the download.
On Android, the catch is being thrown - on iOS no error whatsoever. 

Even tho the URL is not existent, something is being saved to the filesystem
![image](https://github.com/ionic-team/capacitor-plugins/assets/83697697/d85b169e-b799-41e4-8e5f-fad0946d0102)

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by justingel** [comment]
I mean, i hope it helps?
Did it in a few minutes, if you need further elaboration, just tell me

As i said, if the url leads to a 404 page, it should catch the error.

https://github.com/justingel/capacitor-fs-test/tree/master

**Comment by TheRealPingWin** [comment]
Bump
I got fooled by this, I thought there's something wrong with the FileDownload function, because it downloaded something successfully, but only a 175 bytes file instead of the actual file I wanted to.
