### ISSUE TITLE
feat: Make 'id' optional when creating a Google Map - Native Static and Dynamic Maps (without id) are charged 0.00 USD

### ISSUE THREAD

**Issue by amymarsh4work** [ionic-team/capacitor-plugins#1708]
### Description
According to [Google's Billing documentation for maps](https://developers.google.com/maps/billing-and-pricing/pricing#maps-product-skus), we would NOT accrue charges when using the Google Maps SDKs for Native Static and Dynamic maps, IF we created our maps without an ID. Currently, the 'id' property is required for the CreateMapArgs type. Making the id optional could result in lowering costs.

### Platform(s)
Only applies to Android and iOS. When a dynamic map is created with the Maps JavaScript API, it results in charges regardless.

### Preferred Solution
Being able to call this code without an id:
async createMap() {
   this.googleMap = await GoogleMap.create({
      id: 'myFavMap', // <== this is optional
      element: this.mapRef.nativeElement,
      apiKey: environment.mapsApiKey,
      config: this.config
    });
}

### Alternatives
I tried setting id to empty string, and tested. This is what happens on the platforms:
Browser: the map gets created
Android: ‘Error: Missing or invalid map id.’ and the map is not created
iOS: No error. Logs say the map is created, but I don’t see the map. I wasn’t seeing the map before either, so this is likely due to a separate problem.

We have also implemented our map features with @angular/google-maps. It works, but we would be charged, since it wraps the Maps API for JavaScript.

### Additional Context
Our app has relatively basic needs for maps functionality, but map creation is somewhat frequent. Example: displaying a map on detail pages of all buildings, bus stops, parking lots, dining locations at a large university. A couple features require multiple markers and drawing polylines. The dynamic maps functionality has met all of our requirements. Our use-case seems like it would be pretty common.

**Comment by markemer** [comment]
I moved it - everything should be cool now. I think this is a new-ish feature, I don't remember it being possible to avoid charges before.
