### ISSUE TITLE
@capacitor/google-maps - allow hiding orientation compass

### ISSUE THREAD

**Issue by ma-hab** [ionic-team/capacitor-plugins#1709]
### Plugin
@capacitor/google-maps

### Description
When map orientation is changed in Android, a compass icon is shown in the upper left corner. This icon cannot be moved or removed which causes certain problems in my specific use case.

I think that this feature would be useful to many people.

### Platform(s)
Android (I'm not aware if compass exists or not in IOS)

### Preferred Solution
* [GoogleMapOptions](https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/GoogleMapOptions#compassEnabled(boolean)) in Android SDK has `compassEnabled` method.
* Android SDK also allows us to [manually hide compass](https://developers.google.com/maps/documentation/android-sdk/controls) by calling `UiSettings.setCompassEnabled(boolean)`
 * [Old cordova plugin](https://github.com/mapsplugin/cordova-plugin-googlemaps) also has this functionality by calling `controls': {'compass': false}` when creating map so this should probably be something similar.

We could add `compassEnabled` to `GoogleMapConfig` to enable/disable this and `disableDefaultUI` should probably also disable compass as well when set to false.

**Comment by ngmiduc** [comment]
Yes! And it also occurs with the location icon.

![image](https://github.com/ionic-team/capacitor-plugins/assets/22853830/30df3761-c13a-42ad-aa2b-497ed1330113)

**Comment by AE1NS** [comment]
https://github.com/ionic-team/capacitor-plugins/issues/1617
