### ISSUE TITLE
[google-maps]: changing map type will reset map styles

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/capacitor-plugins#1711]
### Plugin(s)
`"@capacitor/google-maps": "^5.1.2",`

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
Ios, android 

### Reproduction
https://github.com/ngmiduc/issue-google-map-style

1. download repo
2. install dependencies and ionic
3. add google maps API key in `/src/app/home/home.page.ts::261`
4. run `npm run build`
5. run `ionic capacitor run ios --livereload --external`
6. select emulator
7. see map with dark styling and minimal styling
8. click on terrain button to change to terrain map type and click back to hybrid to change back to hybrid

### current behavior 

When changing the map type programmatically via setMapType, it will reset the styles that where used to create the map.

### expected behavior

When changing the map type it should remain the the initial styles to create the map.

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment]
Thanks for the sample app.
I've been testing and the problem is not that the styles will get reset, is that the native maps won't show styles for map types other than normal, if you set the type to normal again it will still have the styles.
On web there are a few other map types that still allow styles, but still not all.
If you want styles in other map types you should report the feature request to google.
