### ISSUE TITLE
Device.getInfo() - Failed to read localStorage 

### ISSUE THREAD

**Issue by pechisworks** [ionic-team/capacitor-plugins#172]
### Plugin(s)
Device

### Capacitor Version
```
Capacitor 2.4.2
```

### Platform(s)
Web - when **localStorage** is not allowed, like Facebook Instant Games.

### Current Behavior
`await Device.getInfo()` gives following error message.

> SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
> Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

This error occurs because capacitor is [trying to save the generated uuid to localStorage](https://github.com/ionic-team/capacitor-plugins/blob/e0264256532624d5892e9b5468be89cd400cf823/device/src/web.ts#L175).

### Expected Behavior
Capacitor should check whether localStorage is available and writeable.
It should return the DeviceInfo without an uuid.

### Code Reproduction

1. [Disable localStorage](https://stackoverflow.com/questions/6600754/how-can-i-browse-with-localstorage-disabled)
2. Run `await Device.getInfo()`

**Comment by jcesarmobile** [comment]
this has been fixed in 4.0.0 beta 0
