### ISSUE TITLE
@capacitor/status-bar sometimes work, sometimes not

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/capacitor-plugins#1720]
Hi! I struggle with `@capacitor/status-bar`

In my Ionic Angular App i added to app.component this code:

```ts
ngOnInit() {
  this.appStart();
}

appStart() {
    if (isPlatform('capacitor')) {
      console.log('App is running on Capacitor!');
      this.platform.ready().then(() => {
        console.log('Platform ready');
        StatusBar.setStyle({style: Style.Light}).then(r => console.log(r));
        StatusBar.setBackgroundColor({color: '#F2D492'}).then(r => console.log(r));
        setTimeout(() => {
          console.log('1 sec is done');
          // StatusBar.setStyle({style: Style.Light}).then(r => console.log(r)); With a timeout it works better
          // StatusBar.setBackgroundColor({color: '#F2D492'}).then(r => console.log(r)); With a timeout it works better
        }, 1000);
      });
    }
  }
  ```
  
For some reason in the emulator it works mostly well. but when i create a build with android studio and upload the app to my real android device, the statusbar dont change anything. When i add a TimeOut of 1 second, then it is also working in my builded App on my real device.
  
I debugged with my chrome inspector tool and saw that my real android device returns undefined

![image](https://github.com/ionic-team/capacitor-plugins/assets/4930169/21ddffe2-1e46-497b-a99c-90f08858dbc4)

This is my versioning:
### @capacitor
- **app@5.0.6**
- **browser@5.0.6**
- **camera@5.0.6**
- **haptics@5.0.6**
- **keyboard@5.0.6**
- **splash-screen@5.0.6**
- **status-bar@5.0.6**
### @angular-devkit
- **build-angular@16.1.6** - (Latest 16.1.8)
### @angular-eslint
- **builder@16.1.0**
- **eslint-plugin@16.1.0**
- **eslint-plugin-template@16.1.0**
- **schematics@16.1.0**
- **template-parser@16.1.0**
### @angular
- **animations@16.1.7** - (Latest 16.1.8)
- **cdk@16.1.6** - (Latest 16.1.7)
- **cli@16.1.6** - (Latest 16.1.8)
- **common@16.1.7** - (Latest 16.1.8)
- **compiler@16.1.7** - (Latest 16.1.8)
- **compiler-cli@16.1.7** - (Latest 16.1.8)
- **core@16.1.7** - (Latest 16.1.8)
- **forms@16.1.7** - (Latest 16.1.8)
- **language-service@16.1.7** - (Latest 16.1.8)
- **material@16.1.6** - (Latest 16.1.7)
- **platform-browser@16.1.7** - (Latest 16.1.8)
- **platform-browser-dynamic@16.1.7** - (Latest 16.1.8)
- **router@16.1.7** - (Latest 16.1.8)
### @capacitor
- **android@5.2.2**
- **cli@5.2.2**
- **core@5.2.2**
### @directus
- **sdk@11.0.1**
- **types@10.1.3**
### @ionic
- **angular@7.2.1** - (Latest 7.2.2)
- **angular-toolkit@9.0.0** - (Latest 10.0.0)
### @types
- **jasmine@4.3.5**
- **node@12.20.55** - (Latest 20.4.8)
### @typescript-eslint
- **eslint-plugin@5.3.0** - (Latest 6.2.1)
- **parser@5.3.0** - (Latest 6.2.1)
### Other Dependencies
- **eslint@7.32.0** - (Latest 8.46.0)
- **eslint-plugin-import@2.22.1** - (Latest 2.28.0)
- **eslint-plugin-jsdoc@30.7.6** - (Latest 46.4.6)
- **eslint-plugin-prefer-arrow@1.2.2** - (Latest 1.2.3)
- **eslint-plugin-simple-import-sort@10.0.0**
- **ionicons@7.1.2**
- **jasmine-core@4.6.0** - (Latest 5.1.0)
- **jasmine-spec-reporter@5.0.2** - (Latest 7.0.0)
- **karma@6.4.2**
- **karma-chrome-launcher@3.2.0**
- **karma-coverage@2.2.1**
- **karma-coverage-istanbul-reporter@3.0.3**
- **karma-jasmine@5.1.0**
- **karma-jasmine-html-reporter@2.0.0** - (Latest 2.1.0)
- **rxjs@7.8.1**
- **tailwindcss@3.3.3**
- **ts-node@8.10.2** - (Latest 10.9.1)
- **tslib@2.6.1**
- **typescript@5.0.4** - (Latest 5.1.6)
- **zone.js@0.13.1**

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by SvenBudak** [comment]
how should i provide a example? the statusbar works only natively.

I can copy paste the code from my opening post into a new app, build a apk and send you the file if you want.
but i am not sure if this will help you.

I saw on discord 2 other people they have the same problem.

**Comment by jcesarmobile** [comment]
Most likely it's the same problem as https://github.com/ionic-team/capacitor-plugins/issues/1160
On Android 13 you can't do any device UI changes during the splash screen is being shown, or if you do them, they get restored once the splash is hidden.
So the setTimeout will work if it's longer than the time the splash is being displayed.

You can also try adding `launchFadeOutDuration` config option with 0 value so there is no animation as that's what seem to be messing with the device UI changes.
https://capacitorjs.com/docs/apis/splash-screen#configuration
