### ISSUE TITLE
Enhance Geolocation Plugin with Location Details(including location provider information for mock locations)

### ISSUE THREAD

**Issue by IbrahimElkhatib** [ionic-team/capacitor-plugins#1721]
### Plugin
@capacitor/geolocation

### Description
I would like to propose an enhancement for the @capacitor/geolocation plugin that includes a new property in the location object returned by the plugin's API. This property, named locationDetails, will provide comprehensive information about the origin of the location data and whether it is simulated or produced by software or an accessory. This consolidated property will simplify the handling of location information for developers and help differentiate between different sources of location data.

### Platform(s)
Android and iOS

### Preferred Solution
Add a new property, locationDetails, to the location object retrieved from the plugin's API on both Android and iOS. The locationDetails property should be an object containing the following information:
origin: A string indicating the origin of the location. Possible values: "produced_by_the_device", "from_mock_provider", "simulated_by_software", "produced_by_accessory".

### Alternatives
An alternative approach could involve separate properties for each piece of information (e.g., locationOrigin, isSimulatedBySoftware, isProducedByAccessory). However, consolidating this information into a single locationDetails property provides a more streamlined and user-friendly experience for developers.

### Additional Context
No additional context at the moment. This feature request is aimed at enhancing the existing functionality of the @capacitor/geolocation plugin by providing valuable information about different sources of location data and their authenticity.

**Comment by jcesarmobile** [comment]
We discussed internally some time ago about adding a `isMock` property to the returned position, but it was discarded because there is no real way of detecting it on iOS, and seemed to not be very accurate on Android.
