### ISSUE TITLE
capacitor-filesystem: stat return inconsistent return types

### ISSUE THREAD

**Issue by jansgescheit** [ionic-team/capacitor-plugins#1723]
## Bug Report

Filesystem.stat returns `ctime` and. `mtime` as `string` but definition says `number`.

### Plugin(s)

capacitor-filesystem

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/ios: 5.2.2

[success] iOS looking great! 👌
```

### Platform(s)

iOS

(android and web not testet)

### Current Behavior

```ts
    const { ctime, mtime } = await Filesystem.stat({
      path:'path/to/file.mp4',
      directory: Directory.Cache,
    });

console.log(typeof ctime === 'string'); // true
console.log(typeof mtime === 'string'); // true
```

### Expected Behavior

```ts
    const { ctime, mtime } = await Filesystem.stat({
      path:'path/to/file.mp4',
      directory: Directory.Cache,
    });

console.log(typeof ctime === 'number'); // true
console.log(typeof mtime === 'number'); // true
```

### Other Technical Details

See https://capacitorjs.com/docs/apis/filesystem#statresult `ctime` and `mtime` is defined as `number`

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
