### ISSUE TITLE
[google-maps] MapType.Normal doesn't work on web

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/capacitor-plugins#1726]
### Plugin(s)
 `@capacitor/google-maps": "^5.3.0"`

### Platform(s)
Web

### Current Behavior
When changing map types on web, the type `MapType.Normal` doesn't work on web. It works on native devices but not on web sites.

### Expected Behavior
The map type on the web platform can be set to normal.

### Code Reproduction
https://stackblitz.com/edit/angular-yz24zb?file=src%2Fapp%2Fexample.component.ts

1. Set google_api_key in  `example.component.ts` line21:  `const apiKey = 'API KEY';`

**Comment by jcesarmobile** [comment]
please, can you provide a github repository or zip file containing a full sample app?
stackblitz urls are not valid reproductions as we use the reproductions to verify the fix

**Comment by ngmiduc** [comment]
> please, can you provide a github repository or zip file containing a full sample app? stackblitz urls are not valid reproductions as we use the reproductions to verify the fix

I think you can just download the code and files from stackblitz.
Here the files:
[angular-yz24zb.zip](https://github.com/ionic-team/capacitor-plugins/files/12359127/angular-yz24zb.zip)

**Comment by jcesarmobile** [comment]
thanks, I'm not familiar with stackbliz and didn't see the download button
