### ISSUE TITLE
Share multiple images at once

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor-plugins#173]
> React Native can share multi urls (https://github.com/react-native-share/react-native-share)

Original discussion: https://github.com/ionic-team/capacitor/discussions/4005

**Comment by basvdijk** [comment]
@dwieeb When I share an image using:

    const shareRet = await Share.share({
      title: 'See cool stuff',
      text: 'Really awesome thing you need to see right meow',
      url: imageUrl,
      dialogTitle: 'Share with buddies'
    });

Then the image url is shared as plain text. Did you manage to share it as an image? For my app I need to share an image as a real image so the user can post it on Whatsapp, Instagram, Facebook etc.

**Comment by rasheeek** [comment]
Much needed feature

**Comment by jcesarmobile** [comment]
Since 4.1.0 version of @capacitor/share, there is a new `files` array that can be used for sharing multiple files.
