### ISSUE TITLE
GoogleMap.setOnBoundsChangedListener() inconsistent

### ISSUE THREAD

**Issue by psy0rz** [ionic-team/capacitor-plugins#1731]
In the webview this listener is called WHILE dragging and zoom.

However, in android native it only fires when the dragging/zooming has stopped.

For my app i need to update the map while dragging and zooming. (calculating grids/getting data from database etc)
Is there a way to do this?

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
