### ISSUE TITLE
[@capacitor/motion] Do I need oreintation listener if I use acceleration listener?

### ISSUE THREAD

**Issue by FreePhoenix888** [ionic-team/capacitor-plugins#1746]
https://github.com/ionic-team/capacitor-plugins/tree/main/motion#accellistenerevent contains all the data and rotationRate. Does it actually contains rotationRate? Can I use only acceleration event to get all the data? Do I need oreintation listener if I use acceleration listener?

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository.

The plugin just uses the web `devicemotion` event for `accel` and the `deviceorientation` for `orientation`, `accel` returns the `rotationRate`, but not sure if it would include the information you need or expect from `orientation`.
