### ISSUE TITLE
[browser] Not able to open link if link is host entry in AndroidManifest

### ISSUE THREAD

**Issue by NisStrom** [ionic-team/capacitor-plugins#1754]
### Plugin(s)
* @capacitor/browser

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.1.1
  @capacitor/android: 5.1.1
  @capacitor/ios: 5.1.1

[success] Android looking great! 👌
[error] Xcode is not installed

```
### Platform(s)
* Android

### Current Behavior
We use Deeplinks to share specific states of our app. For example, marking a position on a map. Like https://our-server.com?pos=123,234. If you share this link, it should open our app with the marked position (if installed).

Additionally we use the Browser Plugin to open documents which are stored on the server. For example https://our-server.com/ressources/demo-image.png.

Now, on some Android devices if you try to open a document, nothing will happen. This, because it tries to open the deeplink instead of opening the in-app browser.

### Expected Behavior
With the function Browser.open it should not try to open the app itself. In the cordova plugins this is controlled:

_Opens the intent, providing a chooser that excludes the current app to avoid circular loops._

### Code Reproduction
\-

### Other Technical Details
Tested on Samsung Galaxy A7 (Android 12) and Pixel 4a (Android 13)

```
// AndroidManifest.xml
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="https"/>
    <data android:host="our-server.com"/>
</intent-filter>
```

### Additional Context
Neither the web console nor the logs in logcat return errors. On some devices it asks the user if it should open chrome or the app.

**Comment by jcesarmobile** [comment]
Thanks for the issue, but the problem is the deep links and custom tabs not playing nicely together, you should report the issue to google.
