### ISSUE TITLE
Add "CriticalAlert" in the option of "requestAuthorization" of push notification

### ISSUE THREAD

**Issue by mickjol** [ionic-team/capacitor-plugins#1759]
### Plugin
PushNotifications

### Description
The plugin should be able to request authorization for "criticalAlert".

### Platform(s)
iOS

### Preferred Solution
Ask authorization if the option is activated in the "PresentationOption" or a new configuration.

### Alternatives
Anything you like

**Comment by jcesarmobile** [comment]
closing as https://github.com/ionic-team/capacitor-plugins/issues/659 exists, it's not exactly the same but should be implemented together
