### ISSUE TITLE
Failed to execute 'share' on 'Navigator'

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor-plugins#1767]
### Plugin(s)

- Share

### Capacitor Version

```
Latest Dependencies:
  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0
Installed Dependencies:
  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3
```

### Platform(s)

- Web

### Current Behavior

When using share on web in chrome (flag enabled) and you share to notes app on mac or discard the dialog, you get the following error.

```
DOMException: Failed to execute 'share' on 'Navigator': An earlier share has not yet completed.
```

### Expected Behavior

Should properly complet sharing.

### Code Reproduction

> https://github.com/muuvmuuv/Issues-Ionic-Angular

1. Run dev
2. Go to tab 1767
3. Click Share
4. Discard
5. Click again

**Comment by jcesarmobile** [comment]
That error is coming directly from the `navigator.share` API. 
You should report the issue to Google on Chrome's issue tracker, it's an experimental API that you had to manually enable, so bugs are expected.
