### ISSUE TITLE
Splash Screen is squeezed on Android #2

### ISSUE THREAD

**Issue by Martin-Eckleben** [ionic-team/capacitor-plugins#1769]
Hi everyone and thank you for your hard work!

The Splash Screens are still distorted on older android devices.

There already was an issue for that:
https://github.com/ionic-team/capacitor-plugins/issues/1689

It was closed with this conclusion:
https://github.com/ionic-team/capacitor-plugins/issues/1689#issuecomment-1638107905

But I don't really understand what I have to do now to solve it.
If this
> "You can report the issue to Google, but they will most likely close it and recommend you to move to splash screen icons (windowSplashScreenAnimatedIcon).
> https://developer.android.com/develop/ui/views/launch/splash-screen/migrate"

is the baseline then the Capacitor splash screen plugin has to move to splash screen icons right?
Is that already a goal?
Are PR's welcome?

I probably get something horrendously wrong :)

**Comment by jcesarmobile** [comment]
You can already use splash screen icons, but they won't work for the programmatic `SplashScreen.show()` method call, only for the initial splash screen.
If you don't want the squeezed image you can use the icons or you can choose to not use the Android 12 Splash Screen API on Android 11 and older by disabling the google compatibility library as explained in the docs:
> The compatibility library can be disabled by changing the parent of `AppTheme.NoActionBarLaunch` from `Theme.SplashScreen` to `AppTheme.NoActionBar` in `android/app/src/main/res/values/styles.xml`
https://capacitorjs.com/docs/apis/splash-screen#android-12-splash-screen-api

**Comment by Martin-Eckleben** [comment]
> or you can choose to not use the Android 12 Splash Screen API on Android 11 and older by disabling the google compatibility library as explained in the docs:

This does not change anything.
Still distorted.
Tested in a new Ionic Capacitor project - which has a preconfigured splash screen:

<img src="https://github.com/ionic-team/capacitor-plugins/assets/1571683/28e2fdf3-4bd1-416b-b77d-6cc36386f2bb" width="30%">

![image](https://github.com/ionic-team/capacitor-plugins/assets/1571683/7d0dddd3-92fe-4574-9b5e-f9a182fede27)

**Comment by Martin-Eckleben** [comment]
If I would choose to use the new icons (as last resort) I'd have to add / change stuff in activities and build.gradle's

I currently would not even be sure in which ones.
(sure I'll be able to find out but that should be streamlined as it regards all Android 11 down devices?)
There's three modules that I'd consider possibly involved:

- capacitor-android
- capacitor-app
- capacitor-splash-screen

![image](https://github.com/ionic-team/capacitor-plugins/assets/1571683/787e5dff-cf9d-45e1-a7ed-fff119da924d)

How to do this should be documented somewhere / the plugin should offer an API / config for that?

**Comment by jcesarmobile** [comment]
You don't have to change anything in the code or gradle files on capacitor or plugins.
You only need to remove the `<item name="android:background">@drawable/splash</item>` entry which is what uses the full screen image on Android 11 and older and add the `windowSplashScreenAnimatedIcon` entry as explained on the official google docs about the andoid 12 splash screen API and `windowSplashScreenBackground` if you also want to change the background. But both the plugin and capacitor-android have the needed changes to support the Android 12 splash screen API and the core-splashscreen support library for older devices.

**Comment by Martin-Eckleben** [comment]
Ah perfect!
This finally works!

Thank you a lot for your time and effort!

Hopefully the documentation in form of this thread will save you a lot of future questions :)
