### ISSUE TITLE
@capacitor/filesystem downloadFile() not working as expected

### ISSUE THREAD

**Issue by KevinHetzelGFL** [ionic-team/capacitor-plugins#1774]
### Plugin(s)
 "@capacitor/filesystem": "^5.1.3"

### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 5.3.0    
  @capacitor/core: 5.3.0   
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0    

Installed Dependencies:    

  @capacitor/cli: 5.2.2    
  @capacitor/core: 5.2.2   
  @capacitor/ios: 5.2.2    
  @capacitor/android: 5.2.2
```

### Platform(s)
All

### Current Behavior
I try to download and open a file from an api. Either the documentation is not up to date or there is a bug in the code. DownloadFileOptions should have the properties path, directory, progress and recursive. But Inside my source code i have to add also url. This is not mentioned in de docs. 

### Expected Behavior

after the successful download I expected some kind of visual feedback. There should be a notifiation for the user that a file was downloaded.

### Code Reproduction

Filesystem.downloadFile({ path: Directory.Data, url: url, directory: Directory.Data }).then((res) => {
     console.log('finished');
 });

**Comment by Galileon-venta** [comment]
You can create the notification yourself with a dialogue, snack bar or whatever; as for documentation, I agree that the function is documented so poorly.

**Comment by KevinHetzelGFL** [comment]
> You can create the notification yourself with a dialogue, snack bar or whatever; as for documentation, I agree that the function is documented so poorly.

But is the file realy downloaded? I think it is just inside the app and not on the file system.

**Comment by Galileon-venta** [comment]
Yes it is; if you want to access it from the file Browser on your device download it to Directory.Documents on both ios and android.

If youre testing in the web tho, afaik there is no real download you can access in the download folder at the moment.

**Comment by KevinHetzelGFL** [comment]
Ok, I try. Is my downloadFile() call correct? My url is an api adress. Can you explain the difference between path and directory?

**Comment by Galileon-venta** [comment]
That is actually documented kind of OK: https://capacitorjs.com/docs/apis/filesystem#directory

Path is a subfolder Starting from the Directory Entrypoint

**Comment by RobSchilderr** [comment]
> Yes it is; if you want to access it from the file Browser on your device download it to Directory.Documents on both ios and android.
> 
> If youre testing in the web tho, afaik there is no real download you can access in the download folder at the moment.

Shouldn't there be an issue created for that, then? At version 5.1.1 we were still able to 'see' the download happening in Chrome. Now at 5.1.3 it just gives a 200 but there is no download. That's why I have to stay at 5.1.1..

**Comment by dallastjames** [comment]
Closing in favor of #1789
