### ISSUE TITLE
bug: capacitor PushNotificationsPlugin getPushNotificationsInstance returns null in Android OS

### ISSUE THREAD

**Issue by HosseinKurd** [ionic-team/capacitor-plugins#1775]
### Plugin(s)
capacitor-push-notifications

### Capacitor Version

💊 Capacitor Doctor 💊

Latest Dependencies:

@capacitor/cli: 5.3.0
@capacitor/core: 5.3.0
@capacitor/android: 5.3.0
@capacitor/ios: 5.3.0

Installed Dependencies:

@capacitor/cli: 5.0.5
@capacitor/android: 5.0.5
@capacitor/core: 5.0.5
@capacitor/ios: 5.0.5

[error] Xcode is not installed

### Current Behavior
capacitor PushNotificationsPlugin.getPushNotificationsInstance() returns null when app is closed in Android OS
Because of that notifications wouldn't be handled.

### Expected Behavior
It should return an instance of PushNotificationsPlugin

### Code Reproduction

> com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java:

```
public static void sendRemoteMessage(RemoteMessage remoteMessage) {
    PushNotificationsPlugin pushPlugin = PushNotificationsPlugin.getPushNotificationsInstance();// It it null
    If (pushPlugin != null) {
        pushPlugin.fireNotification(remoteMessage);
    } else {
        lastMessage = remoteMessage;
    }
}

```

**Comment by jcesarmobile** [comment]
If the app is closed, every capacitor related class is null, so even if we made `PushNotificationsPlugin.getPushNotificationsInstance();` not null, there won't be a WebView to handle the notification anyway, and it's not possible to keep the WebView alive if the app is closed.

If you send notifications with notification payload, they will be shown by the Android OS even if the app is closed.
But if you need "silent" data notifications you'll need to handle them natively without relying in a plugin class, or maybe the [background runner plugin ](https://github.com/ionic-team/capacitor-background-runner) could help you.
