### ISSUE TITLE
How can I change Dynamic Drag-on-Drop in Ionic App

### ISSUE THREAD

**Issue by ionicsiva** [ionic-team/capacitor-plugins#1782]
I am interested in designing a dynamic drag-and-drop feature to modify the database in an Ionic app. I am seeking guidance on how to implement a drag-and-drop functionality in Ionic Angular. Currently, I am using Ionic with Angular and attempting to use the Ionic Reorder feature, but it is not functioning as expected.

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
