### ISSUE TITLE
Unable to Close Camera Interface through 'X' Button on Pixel 7

### ISSUE THREAD

**Issue by llendi** [ionic-team/capacitor-plugins#1792]
### Plugin(s)
@capacitor/camera

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
OS: Android 13
Device: Pixel 7

Seems to be device specific

### Current Behavior
Clicking the 'X' button does not close the camera interface. The interface remains open, with the only method of exit being the utilization of the Android back button.

### Expected Behavior
Clicking the 'X' button should close the camera interface.

### Other Technical Details
As mentioned it seems to be device specific. The pixel 7 offers such a 'X' Button whereas the Pixel 4 does not (both with Android 13)
![Screenshot 2023-09-12 at 10 45 15](https://github.com/ionic-team/capacitor-plugins/assets/89970901/dcefc347-63bd-4051-a02f-b06c92cd13d7)

**Comment by jcesarmobile** [comment]
The plugin uses an intent to the camera app, that UI belongs to the camera app, not the capacitor app. If the camera app has buttons that don’t work you should report the problem to Google.
The plugin has no control over the camera UI.
