### ISSUE TITLE
Filesystem downloadFile doesn't include URL property as DownloadFileOptions​

### ISSUE THREAD

**Issue by mcfarljw** [ionic-team/capacitor-plugins#1804]
### Plugin(s)
@capacitor/filesystem: 5.1.4

### Capacitor Version
```
@capacitor/cli: 5.4.0
@capacitor/core: 5.4.0
@capacitor/ios: 5.4.0
@capacitor/android: 5.4.0
```

### Platform(s)
- Android
- iOS

### Current Behavior
Typing errors are thrown when trying to specify the download URL with the `downloadFile` function.

### Expected Behavior
The options allow for a url property to be passed with the `downloadFile` options.

### Code Reproduction
```ts
// something.ts
await downloadFile({ url: 'something' })
```

### Other Technical Details
https://github.com/ionic-team/capacitor-plugins/blob/main/filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/Filesystem.java#L308 does show a url property is accessed but https://github.com/ionic-team/capacitor-plugins/blob/main/filesystem/src/definitions.ts#L485-L515 doesn't include it in the definition typings.

https://capacitorjs.com/docs/apis/filesystem#downloadfileoptions

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mcfarljw** [comment]
It's just an issue with TypeScript typings. `downloadfileoptions` doesn't include the `url` param which is required to download a file.

Here are the params currently listed in the docs: https://capacitorjs.com/docs/apis/filesystem#downloadfileoptions

Here are the params as they currently exist in the definitions file: https://github.com/ionic-team/capacitor-plugins/blob/main/filesystem/src/definitions.ts#L485C1-L515C1

Maybe I'm mistaken on how to use the `downloadFile` method?
