### ISSUE TITLE
how can i send email otp using ionic and firebase in an android app?

### ISSUE THREAD

**Issue by ionicsiva** [ionic-team/capacitor-plugins#1808]
I have the question: How can I send email OTP using Ionic and Firebase in an Android app? Like many others here, I want to create a system where an OTP is sent when a  on the frontend. I've searched everywhere for a solution. 

I'm using Ionic with Angular and the Capacitor plugin for this

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
