### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/Messaging"

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor-plugins#181]
## Bug Report

Trying to test out the new push notifications, but it seems there is not matching version for its firebase dependency.

### Plugin(s)

- push-notifications

### Capacitor Version

```
  @capacitor/cli: 3.0.0-alpha.12
  @capacitor/ios: 3.0.0-alpha.12
  @capacitor/core: 3.0.0-alpha.12
```

### Platform(s)

- ios

### Current Behavior

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Messaging":
  In Podfile:
    CapacitorPushNotifications (from `../../node_modules/@capacitor/push-notifications`) was resolved to 0.0.1, which depends on
      Firebase/Messaging (~> 7.3)
```

**Comment by muuvmuuv** [comment]
`pod repo update` did it. Maybe Capacitor `cap ios update` should do that?

**Comment by dwieeb** [comment]
@muuvmuuv I don't think so, personally. We want to make sure `sync` runs as fast as possible. I'll think about this more, though.

**Comment by muuvmuuv** [comment]
In case of Angular, this could be a migration step I think, but I have to less knowledge about pods just found that fix somewhere. Idk for React tho…
