### ISSUE TITLE
Update deployment target of push notifications plugin

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor-plugins#182]
### Plugin(s)

- push-notifications

### Capacitor Version

```
3x
```

### Platform(s)

- ios

### Current Behavior

Does not work with capacitor 3 in build process:

```
Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0: .../Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework/Modules/Capacitor.swiftmodule/arm64-apple-ios.swiftmodule
```

### Expected Behavior

Works with capacitor 3

### Code Reproduction

Test with a capacitor 3 ionic angular app.

**Comment by dwieeb** [comment]
Thanks for the report!
