### ISSUE TITLE
File Write with Capacitor not possible

### ISSUE THREAD

**Issue by hendriknitsche** [ionic-team/capacitor-plugins#1831]
I am doing an workaround for now by sharing immediately after writing the file to `Directory.Cache`. At least the users will be able to share the files in a persistent place.

``` typescript
import { Filesystem, Directory, Encoding, FilesystemPlugin, WriteFileOptions } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';

public async saveFile(data: string, fileNameWithExtension: string, type: string): Promise<boolean> {

  // Browser
  if (this._platform.is('mobileweb') || this._platform.is('desktop')) {
    const blob = new Blob([data], { type });
    this._saveFileBrowser(blob, fileNameWithExtension);
    return true;
  }

  // Native
  try {
    const fileConfig: WriteFileOptions = {
      path: `Exports/${fileNameWithExtension}`,
      data: data,
      directory: Directory.Cache,
      encoding: Encoding.UTF8,
      recursive: true
    };
    const writeFileResult = await this._nativeFileSystem.writeFile(fileConfig);
    await this._nativeShare.share({ url: writeFileResult.uri });

    return true;
  }
  catch (error) {
    console.error("Error creating file: ", JSON.stringify(error));
    return false;
  }
}
```

Need a fix asap!

_Originally posted by @abdunnahid in https://github.com/ionic-team/capacitor-plugins/issues/1512#issuecomment-1618867640_
            
______________

I tried this but I receive:

Error: "Share" plugin is not implemented on android.

How can I solve this? Or how can I save a File on Android with capacitor?

**Comment by jcesarmobile** [comment]
please, create a proper report filling the whole template and provide a sample app instead of creating the issue from a comment that is not related to your own problem.

common causes of plugin not implemented are described here 
https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented
