### ISSUE TITLE
Google Maps is not visible when dark mode is enabled on Android

### ISSUE THREAD

**Issue by alice39** [ionic-team/capacitor-plugins#1834]
### Plugin(s)
`"@capacitor/google-maps": "^5.3.3"`

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1

[success] Android looking great! 👌
```

### Platform(s)
`Android`

### Current Behavior
Google Maps is not visible when dark mode is enabled in android system

### Expected Behavior
Show Google Maps either dark mode is enabled or disabled

### Code Reproduction
[Repository with minimal reproduction](https://github.com/alice39/ionic-capacitor-googlemaps)

### Additional Context
The only issue that I found about this bug was #1788, but it was closed. The only reason that I could say why Google Maps is not visible when dark mode is enabled, it's because this style is applied in src/theme/variables.scss
```css
// styles ...

@media (prefers-color-scheme: dark) {
  // styles ...

  .md body {
    --ion-background-color: #121212;
  
    // styles ...
  }
}
```
[as Google Maps is rendered behind of WebView](https://capacitorjs.com/docs/apis/google-maps#:~:text=On%20Android%2C%20the,thing%20you%20check), which if dark mode is enabled, then the HTML body is not transparent anymore, blocking the view to Google Maps. This is exactly [the same problem](https://forum.ionicframework.com/t/capacitor-google-map-not-showing-on-android/228390) when trying to render Google Map in ion-content (even if dark mode is disabled), it's needed to set ion-content background style as transparent.

Some temporal solution, that I could think for this until Google Map could be rendered directly into WebView, are

1. Commenting/deleting that CSS style to the HTML body
2. Forcing light mode only for app itself

While first solution seems nice to keep dark mode for app, there will be some places that won't be dark, and it would require manual intervention to set it dark again. I'm currently using second solution, I disabled dark mode for commenting the whole dark style and adding this option to tailwind `darkMode: 'class'` so `dark:<something>` won't be triggered. I would hope that this can be useful to someone else when dealing with this problem as well.

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by alice39** [comment]
Added minimal sample app

**Comment by jcesarmobile** [comment]
You are not setting the body background to transparent color, only the `ion-content` and that doesn't seem to work when using dark mode, probably because ionic sets the body to black.

You can set the body to transparent in your app using javascript
```
if (Capacitor.getPlatform() === 'android') {
    document.body.style.background = 'transparent';
}
```

or editing the background color in `variables.scss`, search for ` .md body` and change the first line to `--ion-background-color: transparent;`

It's mentioned in the docs that the views have to be transparent "all the way through the layers to the very bottom".

> On Android, the map is rendered beneath the entire webview, and uses this component to manage its positioning during scrolling events. This means that as the developer, you must ensure that the webview is transparent all the way through the layers to the very bottom. In a typically Ionic application, that means setting transparency on elements such as IonContent and the root HTML tag to ensure that it can be seen. If you can't see your map on Android, this should be the first thing you check.

https://capacitorjs.com/docs/apis/google-maps#usage
