### ISSUE TITLE
[Android][Google Maps] Marker Is Not Draggable With Draggable Value True

### ISSUE THREAD

**Issue by Ryan-Rante** [ionic-team/capacitor-plugins#1836]
### Plugin(s)
`@capacitor/google-maps`

### Capacitor Version

```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Dragging marker is not working with marker declaration already have `draggable: true`. The preview is available at the repo example code.

### Expected Behavior

User can drag the marker and return the appropiate event value for setMarkerOnDragEnd listener at Android.

### Code Reproduction

[Click here for the code](https://github.com/Ryan-Rante/capacitor-app-maps-bug-report)

### Other Technical Details

```
Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.4.3
   @angular-devkit/build-angular : 16.2.5
   @angular-devkit/schematics    : 16.2.5
   @angular/cli                  : 16.2.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.2
   @capacitor/android : 5.4.2
   @capacitor/core    : 5.4.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.3

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10
```

### Additional Context

I only try it at Android and web platform. The web platform is working as expected (with `ionic serve`).

**Comment by alice39** [comment]
I had thought the same when I was trying to drag a marker on Android some days ago, but you have to long process and then star dragging the marker and you'll be able to drag it. Like this

https://github.com/ionic-team/capacitor-plugins/assets/20363359/3f623dea-aac0-4dcd-9842-ef43c4a68802

**Comment by Ryan-Rante** [comment]
> I had thought the same when I was trying to drag a marker on Android some days ago, but you have to long press and then start dragging the marker and you'll be able to drag it. Like this
> 
>  Screen.Recording.2023-10-10.at.14.20.01.mov

Thank you for the explaination and preview. It is working as you said 🫡

**Comment by jcesarmobile** [comment]
On native the markers need long press to drag, see official android docs
https://developers.google.com/maps/documentation/android-sdk/marker#make_a_marker_draggable
