### ISSUE TITLE
Use JSObject vs. assuming values are serializable

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor-plugins#184]
It is safer to use the `JSObject` type when declaring the result container to check possible serialization errors at compile time.

```diff
 @objc func echo(_ call: CAPPluginCall) {
   let value = call.getString("value") ?? ""
-  call.resolve(["value": value])
+  let result: JSObject = ["value": value]
+  call.resolve(result)
 }
```

> if your results are simple, or if you know what you’re doing, it’s not a problem. it’s only going to bite you if, say, you stick some enum value or a custom data object into the dictionary

**Comment by jcesarmobile** [comment]
Most plugins do it this way, and the others are serializable, so closing
