### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by narianangel** [ionic-team/capacitor-plugins#1841]
## Bug Report

I migrated from Capacitor 4 to Capacitor 5 yesterday, and I have the same problem...

### Capacitor Version
@capacitor/cli: 5.0.0
@capacitor/core: 5.0.0
@capacitor/android: 5.0.0
@capacitor/ios: 5.0.0

### Platform(s)
iOS

### Current Behavior
Installing a new version with old data and old version installed, like updating from TestFlight, for example, or building from XCODE itself) I get the error: "Failed to load resource" with files that I could see with the old version

If I delete the app from my ipad and install again, I can see all files and images. But if I update that app or install another version with that installed... I got the error mentioned before and I cant see nothing...

I checked the "device container " from XCODE and the files aree there... But console show that error...

**My capacitor.config:**

> ...
server: {
    androidScheme: 'http',
    cleartext: true
  },
  plugins: {
    CapacitorSQLite:
    {
      electronIsEncryption: false,
      electronWindowsLocation: 'xxxxx',
      electronMacLocation: 'xxxxx', 
      electronLinuxLocation: 'xxxxx',
      androidIsEncryption: false,
      androidBiometric: {
        biometricAuth: false,
        biometricTitle: "Biometric login for capacitor sqlite",
        biometricSubTitle: "Log in using your biometric"
      },
      iosDatabaseLocation: 'Library/xxxxx',
      iosIsEncryption: false,
      iosKeychainPrefix: 'database-key',
      iosBiometric: {
        biometricAuth: false,
        biometricTitle: "Biometric login for capacitor sqlite"
      },
    }
...

I have this path files saved in a **_sqlite3_** and physicaly the device using **_Filesystem_**.

**File path example:**
`capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/APLICATION_ID/Documents/folder/image.jpg`

It seems as if with each reinstall it assigns a different UUID, something I can't control, since the paths are created with Filesystem, and it try to search the files in the path not exist...

**Comment by narianangel** [comment]
I notices that when I saved images with first instalation I saved this with this ID **AB31CA9B-DF6F-4202-B950-6E4579690C65**:

`capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/ABX334B-DF6F-4302-B950-6E4579690C65/Library/folder/9788468073286.jpg`

But after reinstall app from XCode keeping data in Sqlite3, with that path, if I got the UUID device, I got another one:

**C5714F2B-A635-413A-B5A6-DBXX3YY3C328B**

How is this possible? With this... Its impossible recover old data after update app...

**Comment by narianangel** [comment]
Ok... I solved this saving relative path instead absolute path. Windows / Linux / Mac / Android works fine with absolute paths, but iOS to generate a new ID each time install app...

**Comment by jcesarmobile** [comment]
Yeah, on iOS the paths change on every Xcode run.
Once it's in production they shouldn't change, but still I wouldn't rely on that, don't store absolute paths.
