### ISSUE TITLE
Add function to push notifications to get FCM for cloud message tests

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor-plugins#185]
### Plugin

- push-notifications

### Description

In order to use Firebase Cloud Messaging "send test notification" it is required to pass an FCM which we are not able to get atm. Also, we are saving both, the FCM and APNS, into our DB for testing. Before the new push plugin we just ignored the APNS (because our API just needs the FCM) but in the future we would like to be able to access both for compatibility reasons. It would be great if the `PushNotifications.addListener('registration'...` function could return both.

I can't really tell how the new plugin handles the Firebase FCM at the moment on iOS because I could not find and import of it somewhere. OR the docs are just missing something :)

> Read here: https://firebase.google.com/docs/cloud-messaging/ios/first-message?authuser=0#fetching-the-current-registration-token

### Platform(s)

- ios
- android maybe too

### Preferred Solution

Callback an object with both values instead of just `value` and add a more descriptive name.

### Alternatives

A separate function to receive both separately.

### Additional Context

I think this way it is correct:

```swift
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    FirebaseApp.configure()
    
    return true
  }

  func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Messaging.messaging().apnsToken = deviceToken

    Messaging.messaging().token { token, error in
      if let error = error {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
      } else if token != nil {
        print(token!)
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
      }
    }
  }
```

**Comment by jcesarmobile** [comment]
push-notifications plugin uses APNS on iOS and will not support FCM, if you want FCM on iOS there are 3rd party plugins available.

Or if you don't want to use a plugin, you can add FCM support to your app like this
https://capacitorjs.com/docs/v3/guides/push-notifications-firebase

It includes instructions for getting the FCM token.

**Comment by muuvmuuv** [comment]
Could you help me return both to Ionic? I am not very familiar with Swift but would that work?

```swift
NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: {
  token, deviceToken
})
```
