### ISSUE TITLE
when you change parent of AppTheme.NoActionBar from  Theme.SplashScreen to AppTheme.NoActionBar the splash screen does not cover the status bar

### ISSUE THREAD

**Issue by michaelnjuguna** [ionic-team/capacitor-plugins#1850]
### Capacitor Version

```

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/core: 4.7.3
```

### Code Reproduction

<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
    <item name="android:background">@drawable/splash</item>
</style>

**Comment by jcesarmobile** [comment]
close as it's missing all the information and sample app

also, as far as I remember that was the default behavior as there are configuration options to hide the status bar and the navigation bar
https://capacitorjs.com/docs/apis/splash-screen#configuration
