### ISSUE TITLE
@capacitor/camera uvc usb camera not recognized

### ISSUE THREAD

**Issue by bratello** [ionic-team/capacitor-plugins#1860]
### Plugin(s)
Camera

### Capacitor Version
Capacitor 5

### Platform(s)
Android

### Current Behavior
I'm using the MediaDevices Web API for accessing camera and streaming the video on canvas through getUserMedia. Everything works fine. I can see all cameras through enumerateDevices and select relevant camera for streaming. But when I plug usb camera - the device is not presented in MediaDevices list. I tested my application through electron for vue plugin on my PC, everythings works sharm, the uvc usb camera available in MediaDevices list and can provide media stream. I know that this issue not related so much for capacitor camera plugin itself, but probably camera experts who developed this plugin, can suggest me something. Probably the issue related to some specific permissions or whatever (camera2).

### Expected Behavior
USB UVC camera device should be presented in MediaDevices list.

### Code Reproduction
navigator.mediaDevices.enumDevices

**Comment by jcesarmobile** [comment]
We don't do anything for making `MediaDevices` API work on Android WebView, other than requesting the needed permissions. If the usb camera doesn't appear, might be an Android OS problem or a WebView problem.
There is nothing we can do about it.
If the camera works on Android's Chrome then it's a WebView problem, if it doesn't work even on Android's Chrome, then looks like a Android bug. 
Try it and report it to the appropriate team (Chromium if it's a WebView problem or Android if it's an Android problem)

**Comment by bratello** [comment]
> We don't do anything for making `MediaDevices` API work on Android WebView, other than requesting the needed permissions. If the usb camera doesn't appear, might be an Android OS problem or a WebView problem. There is nothing we can do about it. If the camera works on Android's Chrome then it's a WebView problem, if it doesn't work even on Android's Chrome, then looks like a Android bug. Try it and report it to the appropriate team (Chromium if it's a WebView problem or Android if it's an Android problem)

Hi, 
Please don't close this issue for few days, maybe other developers will see this ticket and can suggest something.
Thanks

**Comment by jcesarmobile** [comment]
Issues are for actual issues with Capacitor project, for questions or help you can try [discussions section](https://github.com/ionic-team/capacitor/discussions) of Capacitor repository, [Capacitor section](https://forum.ionicframework.com/c/capacitor/26) of Ionic forums, or Capacitor channels of[ Ionic discord ](https://discord.com/invite/UPYYRhtyzp)

**Comment by bratello** [comment]
> Issues are for actual issues with Capacitor project, for questions or help you can try [discussions section](https://github.com/ionic-team/capacitor/discussions) of Capacitor repository, [Capacitor section](https://forum.ionicframework.com/c/capacitor/26) of Ionic forums, or Capacitor channels of[ Ionic discord ](https://discord.com/invite/UPYYRhtyzp)

I tested the camera on USB Camera for Android application, it works fine. So the capacitor camera plugin still not support video streaming, and the MediaDevice WEB API workaround is also unavailable on Capacitor - what the reason to use capacitor for android development?
