### ISSUE TITLE
allowEditing is not working as intended in IOS

### ISSUE THREAD

**Issue by agarshan** [ionic-team/capacitor-plugins#1874]
### Plugin(s)

"@capacitor/camera": "^4.1.5"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 4.8.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.3
  @capacitor/android: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

IOS

### Current Behavior

After taking a picture using camera editing option is not available

### Expected Behavior

The user should see the options to edit the image

### Code Reproduction

const options: ImageOptions = {
					allowEditing: true,
					resultType: CameraResultType.Uri,
					source: CameraSource.Camera,
					quality: 90
	};

Camera.getPhoto(options).then(
					(imageData) => {
						// show image
					},
					(err) => {
						if (err != this.IMAGE_NOT_SELECTED) {
							this.emittError(err);
						}
					}
				);

### Additional Context

Any thoughts, about what is going wrong?

Thanks
Agarshan

**Comment by kentora** [comment]
From the documentation for the camera plugin, it says that it is only supported for CameraSource.Camera. 

<html>
<body>


allowEditing | boolean | Whether to allow the user to crop or make small edits (platform specific). On iOS 14+ it's only supported for CameraSource.Camera, but not for CameraSource.Photos. |   | 1.0.0
-- | -- | -- | -- | --



</body>
</html>

**Comment by agarshan** [comment]
> From the documentation for the camera plugin, it says that it is only supported for CameraSource.Camera.
> allowEditing 	boolean 	Whether to allow the user to crop or make small edits (platform specific). On iOS 14+ it's only supported for CameraSource.Camera, but not for CameraSource.Photos. 	  	1.0.0

currently testing in an ipad 2 - ios version is 15.1

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by agarshan** [comment]
For iOS, it seems that this plugin only provides the capability to crop images taken with the camera and does not offer other forms of image editing like Markup. Hence closing this issue.
