### ISSUE TITLE
bug(google-maps): jvm target compatibility should be set to the same Java version

### ISSUE THREAD

**Issue by wk-mihai** [ionic-team/capacitor-plugins#1882]
### Plugin(s)

- @capacitor/google-maps": "^5.0.0

### Capacitor Version

-  @capacitor/cli: 5.0.0
-  @capacitor/core: 5.0.0
-  @capacitor/android: 5.5.1
-  @capacitor/ios: 5.0.0

### Platform(s)

- Android

### Current Behavior
After upgrading the capacitor version from 4 to 5, I've got the following error message when I run the **ionic cap run android** command:

> Execution failed for task ':capacitor-google-maps:compileDebugKotlin'.
> [capacitor]         > 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 19) jvm target compatibility should be set to the same Java version.
> [capacitor]         Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

This is not happening when I build the app from Android Studio.

### Expected Behavior
Should be able to run the **ionic cap run android** command without the error.

### Code Reproduction
Just install the capacitor 5 and @capacitor/google-maps@5.0.0 and run the **ionic cap run android** command
https://github.com/wk-mihai/capacitor-google-maps-test

### Other Technical Details
N/A

### Additional Context
This is happening for the latest capacitor version as well (@5.5.1) and latest @capacitor/google-maps version (@5.3.3)

**As a temporary fix, I had to change the JavaVersion.VERSION_17 to JavaVersion.VERSION_19 in @capacitor/google-maps/android/build.gradle file**

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by wk-mihai** [comment]
I've set the link to the demo app in the main comment.
https://github.com/wk-mihai/capacitor-google-maps-test

**Comment by jcesarmobile** [comment]
I can't reproduce with the provided app.
If it works when building from Android Studio, but not from `ionic` command it might be an Ionic CLI bug.
Also could be some problem on your system, maybe if you have a global gradle installation that is overriding the Capacitor's 5 default gradle version, which is 8.0.0.
Or you have java 19 installed and gradle is using that version, instead of 17, which is what it should be using, as java 19 is not officially supported for Android development yet, despite it can compile if you change the values, it could cause issues.

**Comment by wk-mihai** [comment]
You're right. The Java version was 19 instead of 17. Thanks @jcesarmobile
