### ISSUE TITLE
Google maps: Auto Show Title on Marker Without User Click

### ISSUE THREAD

**Issue by IbrahimElkhatib** [ionic-team/capacitor-plugins#1902]
### Preferred Solution
I suggest introducing a configuration option or method that enables the automatic display of marker titles upon loading the map, without the need for a user click.

**Comment by dallastjames** [comment]
Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
template in order to gather more information and further assist you. Please create a new issue and ensure the
template is fully filled out.


Thank you for using Capacitor!
