### ISSUE TITLE
@capacitor/browser - add support for a desktop app (designed for iPad) for Mac OS with M1/M2 processor.

### ISSUE THREAD

**Issue by edshkliaruk** [ionic-team/capacitor-plugins#1906]
Develop the capability to open external links within the application without redirecting the user to a browser, similar to how it's implemented for mobile devices. Currently, this functionality is not working, and it is not documented.

**Comment by jcesarmobile** [comment]
Capacitor doesn't officially support development of macOS apps.

I've tested out of curiosity and it looks like a bug on the SFSafariViewController, it opens the modal window but then a message appears that says that the link was opened in Google Chrome. That looks like a bug to me, you should report it to Apple.
