### ISSUE TITLE
Capacitor camera editing for gallery images returns original image

### ISSUE THREAD

**Issue by siranjeevimurugesan** [ionic-team/capacitor-plugins#1974]
## Bug Report
while choosing gallery image and editing image it returns original image instead of edited image. However it working as expected for camera picking images.
### Plugin(s)

"@capacitor/camera": "^5.0.6",

### Capacitor Version

Latest Dependencies:       

  @capacitor/cli: 5.6.0    
  @capacitor/core: 5.6.0   
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0    

Installed Dependencies:    

  @capacitor/cli: 5.2.2    
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.3    
  @capacitor/core: 5.2.2

```
PASTE OUTPUT HERE
```

### Platform(s)

Android, iOS

### Current Behavior

While choosing gallery image and editing image it returns original image. However, it working as expected for camera picking images.

### Expected Behavior

while choosing gallery image and editing it should return edited image.

### Code Reproduction

```
camera() {
    localStorage.setItem('setGiftcardSelectImage', 'false');
    localStorage.setItem('setUploadReceiptImage', 'true');
    Camera.requestPermissions({ permissions: ["camera"] }).then(
      async (status) => {
        console.log("status: " + status.camera);
        await Camera.getPhoto({
          resultType: CameraResultType.Base64,
          source: CameraSource.Prompt,
          quality: 100,
          allowEditing: true
        }).then(
          (imageData) => {
            this.presentCropModal(
              "data:image/jpeg;base64," + imageData.base64String
            );
          },
          (err) => {
            this.alertService.errorSnackbar("err: " + err);
            // Handle error
          }
        ).catch((error) => {
          this.alertService.errorSnackbar("Error taking photo: " + error);
        });
      },
      (err) => {
        this.alertService.errorSnackbar("err146: " + err);
        // Handle error
      }
    );
  }
```

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
