### ISSUE TITLE
[Camera] All photos are available when picking even though only some photos are allowed to access

### ISSUE THREAD

**Issue by hieunguyen2211** [ionic-team/capacitor-plugins#1975]
### Plugin(s)
**@capacitor/camera**: 5.0.6

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.2.0
  @capacitor/android: 5.2.0
  @capacitor/core: 5.2.0
  @capacitor/ios: 5.2.0

```

### Platform(s)
IOS

### Current Behavior
When accessing the gallery, if the user already chose "Select more photos..." in the permission dialog, he/she should only be able to see selected photos instead of seeing all photos, even importing them into the application. => Granting read access for some photos does not work.

### Expected Behavior
When the user selects photos in the gallery to import to his/her application, only some photos, that are granted access, will be displayed.

### Code Reproduction
Running IOS application in the test app repo: https://github.com/ionic-team/capacitor-testapp

### Other Technical Details
Tested on Iphone 14 (IOS 16.6).

**Comment by jcesarmobile** [comment]
That's how the picker that Apple provides work, it can access all photos, when they make you choose some images is to give full access to those image (to get privacy related metadata such as exif), so you can always get all images, but only the exif information from the images selected on the first chooser.
I agree that it's confusing, but it's how Apple made it, only they can change the behavior.
