### ISSUE TITLE
 capacitor/camera plugin if we go back to the Home Screen and tap again our app icon in Home Screen it is not showing the camera screen

### ISSUE THREAD

**Issue by vamsi3293** [ionic-team/capacitor-plugins#1983]
Hi Team, 

After opening camera, if we go back to the Home Screen and tap again our app icon in Home Screen it is not showing the camera screen instead it showing last navigated screen in android but in iOS it is working fine.
May I know how to handle this.

Thanks 
Vamsi

**Comment by jcesarmobile** [comment]
Capacitor apps have `android:launchMode="singleTask"` by default.
Camera plugin launches an intent to the Camera app, so it shows the Camera app on top of your own app.
But if you open your app from the icon, the icon launches your app again and closes any pending intent screens such as Camera.
You can try changing `singleTask` to something else, but then you might have problems with push/local notifications
https://developer.android.com/guide/topics/manifest/activity-element
