### ISSUE TITLE
plugin dependency issue on androidx.emoji2:emoji2-views-helper:1.4.0 

### ISSUE THREAD

**Issue by Aksoom-Hussain** [ionic-team/capacitor-plugins#1994]
### Plugin(s)
    "@capacitor/android": "^5.6.0",
    "@capacitor/app": "^5.0.6",
    "@capacitor/app-launcher": "^5.0.6",
    "@capacitor/assets": "^3.0.4",
    "@capacitor/camera": "^5.0.8",
    "@capacitor/core": "^5.6.0",
    "@capacitor/device": "^5.0.6",
    "@capacitor/geolocation": "^5.0.6",
    "@capacitor/google-maps": "^5.4.0",
    "@capacitor/ios": "^5.6.0",
    "@capacitor/keyboard": "^5.0.7",
    "@capacitor/local-notifications": "^5.0.6",
    "@capacitor/preferences": "^5.0.6",
    "@capacitor/push-notifications": "^5.1.0",
    "@capacitor/splash-screen": "^5.0.6",
    "@capacitor/status-bar": "^5.0.6",

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[success] Android looking great! 👌

### Platform(s)
android

### Current Behavior
unable to run app or get the app build successfully after updating form 5.0.0 to 5.0.6

### Other Technical Details

```
2 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.emoji2:emoji2-views-helper:1.4.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 8.0.0 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdk of at least 34.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.emoji2:emoji2:1.4.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 8.0.0 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdk of at least 34.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

```

**Comment by inorganik** [comment]
I was able to resolve this error but updating the SDK version in variables.gradle

```
...
    compileSdkVersion = 34
    targetSdkVersion = 34
...
```

**Comment by inorganik** [comment]
@Aksoom-Hussain thanks! What version did you put @capacitor-community/stripe at? Seems like we should file a bug there

**Comment by Aksoom-Hussain** [comment]
the version i was using "@capacitor-community/stripe": "^5.4.2",

already raised issue 

[https://github.com/capacitor-community/stripe/issues/331](https://github.com/capacitor-community/stripe/issues/331)

**Comment by inorganik** [comment]
@Aksoom-Hussain do you know what version to roll back @capacitor-community/stripe to?

**Comment by Aksoom-Hussain** [comment]
@inorganik  currently i roll back to [v5.2.0](https://github.com/capacitor-community/stripe/releases/tag/v5.2.0) and pushed the update to store
