### ISSUE TITLE
Preserve aspect ratio

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-plugins#2]
### Plugin

Camera

### Description

Originally requested by @zyniq82 (https://github.com/ionic-team/capacitor/discussions/1952) with an unfinished implementation by @sandstrom (https://github.com/ionic-team/capacitor/pull/2050).

The Camera plugin has strange default behavior when using `width` and `height`:

> * if I specify both `width` and `height`, I'm sure no side is too long, but then the aspect ratio of the resulting image is changed.
> * if I specify only `width` or `height`, the aspect ratio is retained, but then I don't know if my prescribed value is applied to the longer or shorter side of the image, since I don't know beforehand if the image is in portrait or landscape format.
> 
> -- @zyniq82 

The default behavior should be to preserve the aspect ratio, even if both `width` and `height` are given (this is a breaking change from the core plugin). There can be an option to disable the default behavior, for example `preserveAspectRatio` (which would default to `true`).

### Platform(s)

iOS, Android

**Comment by sandstrom** [comment]
I just want to add that not preserving the aspect ratio is a bug and I don't know of any camera plugin/sdk (native, cordova or otherwise) that wouldn't want to preserve aspect ratio of photos when resizing. I think adding a `preserveAspectRatio` option is a bad idea.

Thanks for opening the issue though, and for your work on Capacitor. I really like capacitor! 😄

**Comment by zyniq82** [comment]
With the inclusion of https://github.com/ionic-team/capacitor/pull/3309 in Capacitor `2.4.0`, I say this is now fixed :slightly_smiling_face:
Thank you all for the participation! :pray:

**Comment by dwieeb** [comment]
Thanks! I created https://github.com/ionic-team/capacitor-plugins/issues/24 to track the planned `preserveAspectRatio` default value change.
