### ISSUE TITLE
Screen Orientation: not implemented on Android

### ISSUE THREAD

**Issue by asivaneswaran** [ionic-team/capacitor-plugins#2014]
### Plugin(s)
Screen orientation

I get this error: `"ScreenOrientation.lockScreenOrientation()" is not implemented on android` when I run this:
```
await ScreenOrientation.lockScreenOrientation({
        orientation: 'portrait',
    });

```

**Comment by jcesarmobile** [comment]
The correct syntax is:
```
ScreenOrientation.lock({
    orientation: 'portrait',
});
```
Where did you see the `lockScreenOrientation` syntax? Are you using typescript?
