### ISSUE TITLE
bug(@capacitor/screen-orientation): iOS landscape lock using incorrect mappings 

### ISSUE THREAD

**Issue by brian-weasner** [ionic-team/capacitor-plugins#2022]
### Plugin(s)

@capacitor/screen-orientation@5.0.6

### Capacitor Version

```text
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/android: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/ios: 5.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

- iOS 14.5  **SEE NOTE in technical details below**
- iOS 16.2, and 17.1

### Current Behavior

1. Rotate iOS device to be in landscape.
2. Query the orientation
3. Lock to that orientation.
4. See the screen rotate 180 degrees in the other landscape position.

### Expected Behavior

1. Rotate iOS device to be in landscape.
2. Query the orientation
3. Lock to that orientation.
4. Screen orientation should lock to the current orientation and not rotate.

### Code Reproduction

I verified that this is also an issue in the repo <https://github.com/WIStudent/capacitor-screen-orientation-issue-reproduction-app> made by @WIStudent

#### iOS 14.5

After the screen is locked to the current orientation and the screen rotates 180 degrees, if you query for the current location again, it still shows that the current orientation is **NOT THE SAME** as the original.

#### iOS 16.2 & 17.1

After the screen is locked to the current orientation and the screen rotates 180 degrees, if you query for the current location again, it still shows that the current orientation is **THE SAME** as the original.

### **What is the issue**

Issue lies in the difference between `LandscapeLeft` and `LandscapeRight` in `UIDeviceOrientation` and `UIInterfaceOrientation`

- [`UIDeviceOrientation.landscapeLeft`](https://developer.apple.com/documentation/uikit/uideviceorientation/landscapeleft) is **NOT** the same as [`UIInterfaceOrientation.landscapeLeft`](https://developer.apple.com/documentation/uikit/uiinterfaceorientation/landscapeleft)
- [`UIDeviceOrientation.landscapeRight`](https://developer.apple.com/documentation/uikit/uideviceorientation/landscaperight) is **NOT** the same as [`UIInterfaceOrientation.landscapeRight`](https://developer.apple.com/documentation/uikit/uiinterfaceorientation/landscaperight)

In UIDeviceOrientation, the focus for left and right is based on the position of the **camera**, while in UIInterfaceOrientation, the focus for left and right is based on the position of the **home button**. Both of which, camera and home button, are on opposite sides of the phone.

### **How to fix**

Either:

1. Change mappings in [`fromOrientationTypeToMask`](https://github.com/ionic-team/capacitor-plugins/blob/d5483ce9f666f1a38c25a11e63899fd35701ca45/screen-orientation/ios/Plugin/ScreenOrientation.swift#L83) and [`fromOrientationTypeToInt`](https://github.com/ionic-team/capacitor-plugins/blob/d5483ce9f666f1a38c25a11e63899fd35701ca45/screen-orientation/ios/Plugin/ScreenOrientation.swift#L99) so that
    - `landscape-primary` maps to `UIInterfaceOrientationMask.landscapeRight` and `UIInterfaceOrientation.landscapeRight.rawValue` respectfully
    - `landscape-secondary` maps to `UIInterfaceOrientationMask.landscapeLeft` and `UIInterfaceOrientation.landscapeLeft.rawValue` respectfully

2. Change mapping in [`fromDeviceOrientationToOrientationType`](https://github.com/ionic-team/capacitor-plugins/blob/d5483ce9f666f1a38c25a11e63899fd35701ca45/screen-orientation/ios/Plugin/ScreenOrientation.swift#L69C18-L69C56) so that
    - `UIDeviceOrientation.landscapeRight` maps to `landscape-primary`
    - `UIDeviceOrientation.landscapeLeft` maps to `landscape-secondary`

**1. IS PREFERRED** because it will align the `landscape-primary` value on iOS and Android devices by having the camera/top of the device on the left, and the home button/bottom of the device on the right. Currently they are in sync on both devices when retrieving current orientation, but not when locking to a specific landscape orientation.

**Comment by IT-MikeS** [comment]
Tracking in #2039

**Comment by brian-weasner** [comment]
This is not completed and the linked ticket does not describe the same problem.

**Comment by IT-MikeS** [comment]
Ah I see now what you mean. Okay I'm going to reopen this and add it as a bug.

**Comment by brian-weasner** [comment]
@IT-MikeS  Is there any eta for when my pr can get looked at, merged and released?
I ask because it has been a couple of months since the issue has been opened, and over a month since the fix was submitted for review.

**Comment by IT-MikeS** [comment]
It hasn't made it to the work board yet but I will personally take a look in the next couple days either way 👍

**Comment by brian-weasner** [comment]
Looks like my Pr has been merged into the 5.x branch! Thank you @IT-MikeS 
If you don't mind me asking how long until a new version is published? I assume that version bumping was not something I was supposed to do in the pr?
