### ISSUE TITLE
@capacitor/browser: browser.addeventlistener throw error

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/capacitor-plugins#2027]
### Plugin(s)
`@capacitor/browser `

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/android: 5.0.5
  @capacitor/cli: 5.6.0
  @capacitor/core: 5.0.5
  @capacitor/ios: 5.0.5

 "@capacitor/browser": "^5.2.0",
```

### Platform(s)
Not platform related

### Current Behavior
I've installed the plugin and called the .open function and the site opens well.
I want to add a listener on browserFinished so I wrote this code

```
    async openPaymentGateway() {
        await Browser.open({ url: 'mysite.it' });
        Browser.addListener('browserFinished', (event) => {
            console.log('Browser has been closed');
        });
    }
```

but the entire Brower.addlistener code block gives me an error "no overload match this call".
So I cant use this code.
I've already checked the documentation and some videos and I don't see the problem.

### Expected Behavior
I expect that the code works as the doc says

### Code Reproduction
Install @capacitor/browser
Write this function and you will see the error
```
    async openPaymentGateway() {
        await Browser.open({ url: 'mysite.it' });
        Browser.addListener('browserFinished', (event) => {
            console.log('Browser has been closed');
        });
    }

```

**Comment by JEricaM** [comment]
Still stuck here :(

**Comment by IT-MikeS** [comment]
You may have the same issue outlined here: #2036

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
