### ISSUE TITLE
@capacitor/preferences handling things async instead of sync

### ISSUE THREAD

**Issue by BridgeAR** [ionic-team/capacitor-plugins#2029]
### Plugin
@capacitor/preferences

### Description

Right now the preferences module only contains sync code while all operations return promises. This is a minor overhead while executing this and it makes the usage more complicated than it has to be (awaiting otherwise sync code).

### Platform(s)

All

### Preferred Solution

Since there is no actual async operation, I suggest to rewrite the code by removing all `async` keywords from the code and publishing it in the next major version accordingly.

**Comment by jcesarmobile** [comment]
Capacitor plugins are all async because the communication from javascript to native and back is async.
That's also true for Preferences plugin, except on web that uses localStorage, which is sync, but it has to be made async to match the native platforms.
