### ISSUE TITLE
bug: Camera - Cannot pick images shot in Apple ProRAW

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-plugins#2030]
### Capacitor Version

```
   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- iOS 15.4

### Current Behavior

When you try to pick a photo from the gallery, which was shot in "Apple ProRAW" format (iPhone 13 Pro Max) an exception with this message is thrown: `Error loading image`

For your convenience I have uploaded such an image for you here:
https://bico.app/DEMO_APPLE_RAW_PICTURE.DNG

### Expected Behavior

The image should be pickable and converted to the target format.
If that is not possible, the image picker should grey those images out or not show them at all.

### Code Reproduction

```typescript
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
async uploadImage() {
    await Camera.getPhoto({
	    quality: 75,
	    allowEditing: false,
	    source: CameraSource.Photos,
	    resultType: CameraResultType.Base64
    }).then(async image => {
                          console.log(image);
    }).catch(err => {
	    console.log(err)
    });

}

```

### Other Technical Details

`npm --version` output:
8.5.0

`node --version` output:
v16.14.2

`pod --version` output (iOS issues only):
1.11.3

### Additional Context

This issue was already submitted in 2021, but it was closed because the reporter didn't respond.
See: https://github.com/ionic-team/capacitor/issues/4989

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
