### ISSUE TITLE
bug(@capacitor/share): Issue while sharing an image via Whatsapp

### ISSUE THREAD

**Issue by facumartig** [ionic-team/capacitor-plugins#2034]
### Plugin(s)
@capacitor/share: 5.0.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/android: 5.6.0
  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS (didn't try in Android yet)

### Current Behavior

When sharing a text and an image by Whatsapp, only the text is shared. For other services it works fine (e.g. Telegram).

### Expected Behavior

Both the text and image should be shared.

### Code Reproduction

```
await Share.share({
  title: "QR Code",
  text: "Scan this QR code",
  url: qrImageUri,
}).catch(console.error);
```
1. Click on share button
2. Selecting a Whatsapp contact
3. The preview doesn't show the image. When sending it, it only appears the text ("Scan this QR code").

**Comment by qliqdev** [comment]
Any solutions?

**Comment by OS-ricardomoreirasilva** [comment]
This is a limitation of WhatsApp. You can share both text and images but not simultaneously.
