### ISSUE TITLE
Please provide marker rotation in google maps plugin

### ISSUE THREAD

**Issue by rcherukuri-sta** [ionic-team/capacitor-plugins#2053]
### Plugin

@capacitor/google-maps

### Description

I use this plugin in an app where vehicle tracking is required and unable to rotate the marker(vehicle) using this plugin. Please provide the capability to set the marker rotation. 

### Platform(s)

Both Android and iOS

**Comment by IT-MikeS** [comment]
This is a duplicate of #1428
