### ISSUE TITLE
[splash-screen] Make docs usable for iOS app

### ISSUE THREAD

**Issue by bluepuma77** [ionic-team/capacitor-plugins#2055]
### Plugin
@capacitor/splash-screen

### Description
Trying to use the [@capacitor/splash-screen](https://capacitorjs.com/docs/apis/splash-screen) plugin, but everything is about Android. EVERYTHING IS ABOUT ANDROID. The word iOS is mentioned once in text for spinner style. But even the image to show is referred to by `androidSplashResourceName`.

### Platform(s)
iOS

### Preferred Solution
Have a simple example for iOS which shows parameters to use and how to refer to the image resource - on iOS.

### Alternatives
n/a

### Additional Context
n/a

**Comment by IT-MikeS** [comment]
All of the documentation applies to both platforms except for [this part](https://capacitorjs.com/docs/apis/splash-screen#android-12-splash-screen-api) and [the bit at the end for config](https://capacitorjs.com/docs/apis/splash-screen#android) 

Is there a particular issue you are having? If you are just looking to use a custom image you will need to generate a new or edit the current imageset for your iOS project (See image below) and there are tools to help with this like [capacitor-assets](https://github.com/ionic-team/capacitor-assets) 

![Screenshot 2024-04-09 at 11 11 40 AM](https://github.com/ionic-team/capacitor-plugins/assets/20338451/a22e7e7a-e7ac-4de1-a59b-4240bbb54781)

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
