### ISSUE TITLE
Add Capacitor Webview

### ISSUE THREAD

**Issue by ptlmay25** [ionic-team/capacitor-plugins#2058]
### Plugin

Capacitor- Browser 

### Description

Add Fully customizable webview for capacitor js

**Comment by IT-MikeS** [comment]
Going to need a fair bit more info on what it is you are looking for here. What things do you want customizable, what form do you want those settings to take, etc.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
