### ISSUE TITLE
Add map events to be handled at client side

### ISSUE THREAD

**Issue by eduardojmrosa** [ionic-team/capacitor-plugins#2059]

**Comment by IT-MikeS** [comment]
Unfortunately a title will not be enough to consider this request. Please provide a more detailed description of what you'd like to see and please fill out the request form.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
