### ISSUE TITLE
@capacitor/share not working with capacitor v6

### ISSUE THREAD

**Issue by CoooWeee** [ionic-team/capacitor-plugins#2085]
### Plugin(s)
capacitor

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/android: 6.0.0

### Platform(s)
- android tried sdkVersion 33 and 34

### Current Behavior
Cannot resolve symbol 'UPSIDE_DOWN_CAKE'
Cannot resolve symbol 'FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT'

````
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
                flags = flags | PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT;
            }
````

### Expected Behavior
complies without errors

### Code Reproduction
- just add the plugin to your project
- sync
- rebuild in android studio

**Comment by djonmayer** [comment]
Please, have a look at last comment to this [pull request](https://github.com/ionic-team/capacitor-plugins/pull/1849)
You have to change target SDK to 34

**Comment by bobibt** [comment]
npx cap migrate
