### ISSUE TITLE
Google Maps availability in v6

### ISSUE THREAD

**Issue by alexp25** [ionic-team/capacitor-plugins#2135]
## Feature Request

I see there is no google-maps folder in v6, even though it was in v5. What is the motivation behind leaving it out? Google Maps is a fundamental and make or break plugin for many apps and should be at least mentioned in the documentation (how to find it) so that people who want to switch to Capacitor for the first time would not get discouraged by the apparent lack of support in the latest Capacitor release.
Moreover, I have added a significant number of methods and improvements that were lacking in the latest version, but I don't know what is the status of the current release and where should I make a pull request.

### Plugin

Google Maps

**Comment by jcesarmobile** [comment]
It's explained in https://github.com/ionic-team/capacitor-google-maps/issues/5

We wanted to update the plugin to use the SDK 8 of google maps, but we are waiting for the google-maps-ios-utils dependency to be updated to use SDK 8, which has been pending for over a year (on Google side).

You can install latest RC with `npm install @capacitor/google-maps@next`, there won't be any changes on Android Side, the missing updates are for iOS, but we can't do them until google releases google-maps-ios-utils with SDK 8 support.

**Comment by alexp25** [comment]
@jcesarmobile Is updating to SDK 8 mandatory in order to work with Capacitor 6? That would be the only case to justify waiting for a dependency that may take another year or may never be shipped (as Google currently doesn't seem to care about updates to their own SDKs that don't directly bring more money). And that might delay the adoption of Capacitor by seemingly lack of support for a major plugin.

**Comment by alexp25** [comment]
Because my last comment was "marked as abuse", I would like to point out and have a clear understanding about this, in order to justify upgrading to Capacitor 6 in the near future. Is updating to SDK 8 (or 9) mandatory in order to work with Capacitor 6?
