### ISSUE TITLE
@capacitor/app-launcher canOpenUrl always returns false (iOS 17.5.1, Capacitor 6, Ionic 7)

### ISSUE THREAD

**Issue by AndrewBargan** [ionic-team/capacitor-plugins#2143]
### Plugin(s)
@capacitor/app-launcher

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0
```

### Platform(s)
iOS 17.5.1, Capacitor 6, Ionic 7, XCode 15.4

### Current Behavior
I'm getting false for all installed apps on my iPhone

### Expected Behavior
I should receive true for the commands specified in the next section

### Code Reproduction
I've got bunch of messengers installed on my iPhone and when I check if they are installed I'm getting false for all of them:

```
    console.log(await AppLauncher.canOpenUrl({url: 'org.telegram.messenger'}));
    console.log(await AppLauncher.canOpenUrl({url: 'com.whatsapp'}));
    console.log(await AppLauncher.canOpenUrl({url: 'com.facebook.orca'}));
    console.log(await AppLauncher.canOpenUrl({url: 'com.viber.voip'}));
    console.log(await AppLauncher.canOpenUrl({url: 'com.skype.raider'}));
```

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
