### ISSUE TITLE
iOS ONLY --> FCM error 400 - The registration token is not a valid FCM registration token

### ISSUE THREAD

**Issue by wwwguy** [ionic-team/capacitor-plugins#2178]
We have been using @capacitor/push-notifications in our app with everything working fine for years. We just updated to Capacitor 6 and rebuilt the app, reinstalling the plugin and configuring the various project files. Everything is working great on Android. But on iOS we get the following error when attempting to send push notifications:

> HTTP/1.1 400 Bad Request
Vary: Origin
Vary: X-Origin
Vary: Referer
Content-Type: application/json; charset=UTF-8

> {
"error": {
"code": 400,
"message": "The registration token is not a valid FCM registration token",
"status": "INVALID_ARGUMENT",
"details": [
  {
    "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
    "errorCode": "INVALID_ARGUMENT"
  }
]
}
}

Here are our Capacitor details:

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Nothing is different on the server side in terms of how we are sending the notification, so it's clearly something wrong with our iOS configuration (since it works fine on Android). So with that in mind, here are the file configurations we've done in xCode.

In the Podfile:

> target 'App' do
>   capacitor_pods
>   pod 'Firebase/Messaging'
> end

In AppDelegate:

> import Firebase

> @UIApplicationMain
> class AppDelegate: UIResponder, UIApplicationDeletage {
> func application(_ application: UIApplication, didFinishLaunchingWithOptions
>     launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
>     FirebaseApp.configure()
>     return true
> }

> func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
>   NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
> }

> func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
>    NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
> }

When running the app from xCode on a local device it appears to be working fine and logs the following as the app registers and obtains a token:

> [log] FCM - register: granted
> [log] FCM - registration: {"value":"7A868F9E49853DA0F175ABDCE683310CC279306B4B00B579DA94690273CE7A3A"}

When checking the server side to ensure that same token is being used (which was obtained just seconds before), it is indeed the same.

When we uninstall the updated app and reinstall the old app, then trigger the test notification from the server everything works fine (confirming there's something going on locally in the new iOS app). I did notice the device token changes when switching between apps but that is probably normal behavior (i.e. since FCM is creating a different token each time). Is there some additional configuration step I am missing here? Clearly it is able to successfully register a token but then it's acting like it's invalid when attempting to send message to it?

**Comment by wwwguy** [comment]
We have now updated 3 additional apps to Capacitor 6 and all of them are experiencing the same problem (on iOS only, Android is working fine). Looking closer at the registration tokens the format doesn't look quite right? (see above). Normally there is a mixture of upper/lowercase letters but the value being returned on iOS using this plugin is now in all caps.

Is there an additional configuration we are missing or is this a new bug?

**Comment by wwwguy** [comment]
After a lot more trial and error and research I was able to determine that the official @capacitor/push-notifications docs at https://capacitorjs.com/docs/apis/push-notifications for iOS configuration are wrong. Specifically, the additional code for AppDelegate.swift (which worked fine as outlined there for earlier versions of the plugin) does not work because the current functionality actually retrieves and Apple APN token.

This is the code in the docs that does not work:

> func application(_ application: UIApplication, 
> didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
> NotificationCenter.default.post(name: 
> .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
> }
> 
> func application(_ application: UIApplication, 
> didFailToRegisterForRemoteNotificationsWithError error: Error) {
> NotificationCenter.default.post(name: 
> .capacitorDidFailToRegisterForRemoteNotifications, object: error)
> }

Instead use the following:

> func application(_ application: UIApplication, 
> didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
> Messaging.messaging().apnsToken = deviceToken
> Messaging.messaging().token(completion: { (token, error) in
> if let error = error {
> NotificationCenter.default.post(name: 
> .capacitorDidFailToRegisterForRemoteNotifications, object: error)
> } else if let token = token {
> NotificationCenter.default.post(name: 
> .capacitorDidRegisterForRemoteNotifications, object: token)
> }
> })
> }

> func application(_ application: UIApplication, 
> didFailToRegisterForRemoteNotificationsWithError error: Error) {
> NotificationCenter.default.post(name: 
> .capacitorDidFailToRegisterForRemoteNotifications, object: error)
> }

That will retrieve the correct token. Hopefully this saves someone else some time!

**Comment by AnkithaC25** [comment]
I'm facing the similar issue for IOS with capacitor push notifications plugin. I tried you code. "Xcode throws error cannot find messaging in scope".  How do I import Messaging?

**Comment by AnkithaC25** [comment]
We are also stuck very badly. Please let me know what I can do to fix this?

**Comment by AnkithaC25** [comment]
Got it working by following this doc and installing Firebase/Messaging [https://capacitorjs.com/docs/guides/push-notifications-firebase#add-the-firebase-sdk-via-cocoapods](url)
