### ISSUE TITLE
IOS: Unlock Screen Orientation is not working, and screen is not auto rotating "unlock()"

### ISSUE THREAD

**Issue by Manasa16kasam** [ionic-team/capacitor-plugins#2180]
### Plugin(s) 
"@capacitor/screen-orientation": "^6.0.0",

### Capacitor Version

Installed Dependencies:
  @capacitor/cli: ^6.0.0
  @capacitor/android: ^6.0.0
  @capacitor/core: ^6.0.0
  @capacitor/ios: ^6.0.0

```
PASTE OUTPUT HERE
```

### Platform(s)

IOS

### Current Behavior

When I locked the orientation to portrait/landscape and trying to unlock the screen orientation it didn't work as expected (auto screen orientation).
Its working only in iPhone 13(IOS-15.0)

### Expected Behavior

When the Unlock orientation, the screen should be released from the lock orientation, and screen should be auto oriented. 

### Code Reproduction

Service call function:
  screenOrientationService.unlockOrientation()
  
  Capactior unlock function:
  unlock()

**Comment by Manasa16kasam** [comment]
Screen orientation (unlock ()) issue works fine only in iPhone 13. It seems to be an issue in iPhone 14, 15 
Please can someone help me with the fix for the above issue.

**Comment by SAISUDHEERREDDY** [comment]
Hello,

I'm currently facing a similar issue and would greatly appreciate any immediate help or workaround. The problem arises when I lock the screen orientation to either portrait or landscape mode; once locked, I'm unable to unlock **"unlock()"** and switch back to the other orientation. Despite my efforts to unlock the orientation, it remains stuck.

Could anyone please assist me in finding a quick solution to this problem?

Thank you in advance!

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
