### ISSUE TITLE
LocalNotifications.getPending() not working on Android with recurring timers

### ISSUE THREAD

**Issue by khromov** [ionic-team/capacitor-plugins#2181]
## Bug Report

Using `@capacitor/local-notifications`, we schedule a recurring `every` timer using:

```ts
  await LocalNotifications.schedule({
    notifications: [
      {
        id: 1,
        title: `Hello world`,
        body: `...`,
        schedule: { every: 'minute' },
        extra: { id: 123 }
      }
    ]
  });
```

Before it runs the first time, we can see the timer with `LocalNotifications.getPending()`, however, after first invocation, it disappears from getPending() **on Android only**. The timer still runs at the given time but it's no longer possible to find using `getPending()`. Any ideas on how to resolve this? It works as expected on iOS, even past the first execution the timer still shows in getPending().

The problem on Android is we don't know if the timer exists or not, and whether it needs to be deleted, updated or scheduled again (for example following an app reinstall)

### Plugin(s)

```
 @capacitor/local-notifications@6.1.0
```

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2
  @capacitor/android: 6.1.2
```

### Platform(s)

Android 13

### Current Behavior

See above

### Code Reproduction

-

### Other Technical Details

-

### Additional Context

Here's an example of how it can look 

<img width="1154" alt="Screenshot 2024-08-21 at 01 15 14" src="https://github.com/user-attachments/assets/2e629bb1-4e9f-42c4-8ae3-7f73fd11e003">

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
