### ISSUE TITLE
@capacitor/live-updates changelog

### ISSUE THREAD

**Issue by medfx** [ionic-team/capacitor-plugins#2182]
Since this plugin was removed from the repo: Where can I find the changelog?
I want to know what changed between version `0.2.1` and `0.3.1`.

Thanks!

**Comment by IT-MikeS** [comment]
The plugin you mentioned was never available in this repository, as it’s a paid option specifically for enterprise customers. 

To access the changelog and get detailed information about the changes between versions 0.2.1 and 0.3.1, please contact your Customer Success Manager. They’ll be able to provide you with the necessary details and any additional support you might need.
