### ISSUE TITLE
Unable to Sync Google Maps Plugin with iOS

### ISSUE THREAD

**Issue by dewald-els** [ionic-team/capacitor-plugins#2185]
### Plugin(s)

- @capacitor/google-maps

### Capacitor Version

- "@capacitor/app": "6.0.1",
- "@capacitor/core": "6.1.2",
- "@capacitor/haptics": "6.0.1",
- "@capacitor/ios": "6.1.2",
- "@capacitor/keyboard": "6.0.2",
- "@capacitor/status-bar": "6.0.1",
-  "@capacitor/google-maps": "^6.0.1",

### Platform(s)

- iOS

### Current Behavior

Unable to run npx cap sync. It gives the following error: 

```
[capacitor] [error] Analyzing dependencies
[capacitor]         [!] CocoaPods could not find compatible versions for pod "CapacitorGoogleMaps":
[capacitor]         In Podfile:
[capacitor]         CapacitorGoogleMaps (from `../../node_modules/@capacitor/google-maps`)
[capacitor]         
[capacitor]         Specs satisfying the `CapacitorGoogleMaps (from `../../node_modules/@capacitor/google-maps`)` dependency were found, but they required a higher minimum deployment target.
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
```

As a side note, I am unable to find CapacitorGoogleMaps on the CocaoPods repository. 

### Expected Behavior

It should sync the plugins to iOS using ionic cap sync or npx cap sync. 

### Code Reproduction

Sample application provided: https://github.com/dewald-els/dogspot-ionic

Run npm install and npx cap sync

### Other Technical Details

- I have tried running pod repo update.
- I added the required entry into the Podfile according to the guide at https://github.com/googlemaps/google-maps-ios-utils

See podfile contents below:

```
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorGoogleMaps', :path => '../../node_modules/@capacitor/google-maps'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'GoogleMaps', '9.0.0'
  pod 'Google-Maps-iOS-Utils', '6.0.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end

```

Running on macOS 14.6.1 (23G93)

### Additional Context
 N/A

**Comment by dantheman2865** [comment]
In order to get this working, I had to update `platform :ios, '13.0'` -> `platform :ios, '14.0'`

**Comment by dewald-els** [comment]
@dantheman2865 Thanks for the tip! This did indeed resolve the issue. 

I removed the `App/Pods` folder and the ran `pod install` inside the iOS folder.
