### ISSUE TITLE
Camera Prompt Landscape 

### ISSUE THREAD

**Issue by andrybany** [ionic-team/capacitor-plugins#2224]
### Plugin(s)
Camera

### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.7.8
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

As described by an other user in the https://github.com/ionic-team/capacitor-plugins/issues/1643, when device is in landscape mode, Camera.getPhoto() prompt/menu options is not correctly visualized. Only the "Photo" label is visible, the other two "From Photos" and "Take picture" labels are visible only after scrolled up the tab.

### Expected Behavior

The same behaviour of the portrait mode, with all the tab visible.

### Code Reproduction

https://github.com/andrybany/CapacitorCamera

### Other Technical Details

The app that I included in the above repo is very simple: it has only a button that call the getPhoto() method. 
To run the app on a pysical or emulated android device, I added a README.md file on the repo with the basic commands to do.

### Additional Context

JAVA_HOME jdk 20.0.2
node 16.16.0
npm 7.5.6
angular 12.0.4
capacitor 6

**Comment by alexgerardojacinto** [comment]
@andrybany we have just released [@capacitor/camera@6.1.2](https://github.com/ionic-team/capacitor-plugins/releases/tag/%40capacitor%2Fcamera%406.1.2) which fixes the reported issue.
