### ISSUE TITLE
[CapacitorFilesystem] None of your spec sources contain a spec satisfying the dependency: `CapacitorFilesystem (= 6.0.1)`.

### ISSUE THREAD

**Issue by valeriomazzeo** [ionic-team/capacitor-plugins#2236]
### Plugin(s)
CapacitorFilesystem (= 6.0.1)
CapacitorFilesystem (= 6.0.0)
CapacitorFilesystem (= 6.0.0-rc.1)
CapacitorFilesystem (= 6.0.0-rc.0)
CapacitorFilesystem (= 6.0.0-beta.1)
CapacitorFilesystem (= 6.0.0-beta.0)
CapacitorFilesystem (= 6.0.0-alpha.2)
CapacitorFilesystem (= 6.0.0-alpha.1)
CapacitorFilesystem (= 5.2.2)
CapacitorFilesystem (= 5.2.1)
CapacitorFilesystem (= 5.2.0)

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.0.0
```

### Platform(s)
iOS

### Current Behavior
Can't `pod install` a plugin which depends on `CapacitorFilesystem 6.0.1`
```
None of your spec sources contain a spec satisfying the dependency: `CapacitorFilesystem (= 6.0.1)`.
```

### Expected Behavior
We should be able to natively `pod install` any released version of `CapacitorFilesystem`.

### Other Technical Details
Podspec for `CapacitorFilesystem` has not been published since version `5.1.4` as visible here https://github.com/CocoaPods/Specs/tree/master/Specs/2/e/a/CapacitorFilesystem

All listed versions are unable to be installed, because missing.

Please publish the podspec for each release.

**Comment by jcesarmobile** [comment]
Thanks for the report, latest version is now published.
