### ISSUE TITLE
bug: Notifications do not occur or persist if app is closed.

### ISSUE THREAD

**Issue by thomasgrz** [ionic-team/capacitor-plugins#225]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed
```

### Platform(s)
Android Pie (API: 28, ABI: x86)

### Current Behavior
Notifications are ephemeral--they are not persisting as expected.

I would like to schedule notifications that occur in the future. In the code reproduction below I am creating a button that, when clicked, schedules a the notification to occur ten seconds in the future.
- This technique does **not** work when the app is closed within the ten second window prior to the notification appearing.
- This technique **will** work when the app is running either in the foreground or in the background.
   - However, if the user closes the app (swipes the app up and away when backgrounded) the notification disappears then as well.

### Expected Behavior
Notifications, when scheduled in the future, appear at the scheduled persist beyond the lifetime of the application.

### Code Reproduction
```
import React, { useState } from 'react';
import { Plugins } from '@capacitor/core';

async function AppScreen() {
  const { LocalNotifications } = Plugins;

  const [action, setAction] = useState(null);

  await LocalNotifications.requestPermission();

  const addNotification = async () => {
    const seconds = 10;

    const tenSecondsFromNow = new Date(Date.now() + 1000 * seconds);

    await LocalNotifications.schedule({
      notifications: [
        {
          title: 'Event driven notification',
          body: 'I am a scheduled notification and I would like to stick around!',
          schedule: { at: tenSecondsFromNow },
          id: Math.random(),
        },
      ],
    });

  };

  return (
      <Button
        onClick={() => addNotification()}
      >
        Add notification
      </Button>
  );
```

### Other Technical Details

`npm --version` output: 7.0.3

`node --version` output: v15.0.1

`pod --version` output (iOS issues only): N/A

### Additional Context
I've also looked into the CapacitorJS BackgroundTasks API but that does not seem to resolve this issue as the process must, at maximum, be triggered within 3 minute of the app being closed.

**Comment by dwieeb** [comment]
We are actively looking at issues with the notification plugins to fix for the Capacitor 3 release. I'll transfer this issue to the plugins repo.

**Comment by digaus** [comment]
> We are actively looking at issues with the notification plugins to fix for the Capacitor 3 release. I'll transfer this issue to the plugins repo.

Thanks for the info.

I just did some tests myself and on my Samsung it is related to the battery optimization (see https://dontkillmyapp.com/)

Another restriction is "Doze" mode in android. I got the best results with using `setExactAndAllowWhileIdle` instead of `setExtact`.
Maybe we could make this an option to configure.

https://medium.com/@igordias/android-scheduling-alarms-with-precise-delivery-time-using-alarmmanager-75c409f3bde0

**Comment by digaus** [comment]
@dwieeb @theproducer  will this be merged into Capacitor V2 aswell? Do not want to upgrade production app to the V3 Beta yet....

**Comment by digaus** [comment]
Any info about the fix being merged into V2 or an ETA of a stable capacitor V3 release?

**Comment by remikel** [comment]
Still not working on V2 or I have another issue ?

**Comment by digaus** [comment]
> Still not working on V2 or I have another issue ?

It's sadly not merged into V2... but you can try to disable all battery optimization and replace `setExact` with `setExactAndAllowWhileIdle`
