### ISSUE TITLE
feat: Camera select multiple photos

### ISSUE THREAD

**Issue by Kepro** [ionic-team/capacitor-plugins#227]
# Feature Request

## Describe the Feature Request
I want to be able to select multiple photos from the gallery

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution
create method getPhotos same as getPhoto just return an array

**Comment by amrmsccs** [comment]
Kindly Make this feature available I am trying my best to be not use other options other than ionic Please consider this Enhancement and thanks in advance.

**Comment by florianmonfort** [comment]
+1, this feature is important.

**Comment by armanhadifatah** [comment]
We are near the end of 2021 and this simple and needed feature is not added , i can use <input > tag but why we have camera plugin that do not have this simple feature

**Comment by arogggh** [comment]
Currently, I'm working on a new hybrid application, and this feature is very important for it.

**Comment by bazuka5801** [comment]
> Currently, I'm working on a new hybrid application, and this feature is very important for it.

Also for me, this is so important, now I must using third-party plugins

**Comment by RaphL** [comment]
+1
With the <input type="file" multiple> "solution" we have some image rotation issues

**Comment by harikvpy** [comment]
+1

**Comment by jcesarmobile** [comment]
@capacitor/camera 1.2.0 included a new pickImages function that allows to pick multiple images on iOS 14+, web and Android
https://capacitorjs.com/docs/apis/camera#pickimages

**Comment by cihakmar** [comment]
In version 1.3.1 is still not possible select multiple images from gallery by pickImages function.
