### ISSUE TITLE
Document `<reference>` additions in TS config files for relevant plugins

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor-plugins#236]
Some plugins have definitions for the CLI configuration files: 

- Keyboard: https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/src/definitions.ts#L5-L28
- Splash Screen: https://github.com/ionic-team/capacitor-plugins/blob/main/splash-screen/src/definitions.ts#L4-L114
- Local Notifications: https://github.com/ionic-team/capacitor-plugins/blob/main/local-notifications/src/definitions.ts#L6-L42
- Push Notifications: https://github.com/ionic-team/capacitor-plugins/blob/main/push-notifications/src/definitions.ts#L8-L26

We should document in each plugin's README how to use these definitions in `capacitor.config.ts` files:

```typescript
/// <reference types="@capacitor/splash-screen" />

const config: CapacitorConfig = { ... }

export default config;
```

**Comment by adamdbradley** [comment]
Step 1 should be ready: https://github.com/ionic-team/capacitor-docgen/commit/3511c54490444a15fd49585afbfde1e66b946d07

Next step is to take the parsed data and generate the markdown.
