### ISSUE TITLE
remove `preserveAspectRatio` option

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor-plugins#24]
`preserveAspectRatio` is deprecated and not really used, remove before @capacitor/camera 2.0.0 is released

**Comment by sandstrom** [comment]
Thanks for creating this issue @dwieeb 

I'd even consider removing it, because I'd say there is ~0% use for resize without preserved aspect ratio. Less code to maintain.

**Comment by dwieeb** [comment]
I think you're right. @jcesarmobile What do you think?

**Comment by jcesarmobile** [comment]
It has been removed on 4.0.0 beta 0
