### ISSUE TITLE
Camera file input not cleaned up when clicking cancel

### ISSUE THREAD

**Issue by mauriceackel** [ionic-team/capacitor-plugins#259]
### Plugin(s)
Camera Plugin in Capacitor 2.4.6

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/core 2.4.6
  @capacitor/android 2.4.6
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    @dutchconcepts/capacitor-barcode-scanner (1.1.1)
[success] iOS looking great! 👌
```

### Platform(s)
Web

### Current Behavior
When the camera plugin invokes the `fileInputExperience` function.  A file input is added to the DOM (more precisely, to the `body` element). Then, the code "clicks" this input, leading browsers to open a file picker. If a file is selected, the `cleanup` method is invoked. However, most file pickers also have a "cancel" button. If this button is clicked. The `cleanup` function is not invoked as the handler only listens for `change` events on the file input.

This leads to the case where the created `input` element remains in the DOM. As the file input is not styled to be invisible, it will be visible to the user.

### Expected Behavior
If the cancel button is clicked, the cleanup function should also be invoked.
Alternatively, the created input element should have a style property of `display: none` to make it invisible.

**Comment by mikeapr4** [comment]
I see this also, when I trigger the `fileInputExperience`, cancel the dialog, then trigger it again and choose a file, now the 2nd file is returned twice.

If I do it 3 times I get 3 copies of the last file. The promises are staying unresolved and end up all resolved with the same value when a final successful file upload is performed.

**Comment by puopg** [comment]
Yup happening on my end too. Seems like there just isn't a handler for the "abort" event or something.

`
if (options.resultType === 'dataUrl' || options.resultType === 'base64') {
        const reader = new FileReader();

        reader.addEventListener('load', () => {
          if (options.resultType === 'dataUrl') {
            resolve({
              dataUrl: reader.result,
              format,
            } as Photo);
          } else if (options.resultType === 'base64') {
            const b64 = (reader.result as string).split(',')[1];
            resolve({
              base64String: b64,
              format,
            } as Photo);
          }

          cleanup();
        });

        reader.readAsDataURL(file);
      } else {
        resolve({
          webPath: URL.createObjectURL(file),
          format: format,
        });
        cleanup();
      }
`

**Comment by jcesarmobile** [comment]
sadly there is no event fired when the user clicks cancel

I've made the input hidden on https://github.com/ionic-team/capacitor-plugins/pull/484
And also fixed the multiple results on https://github.com/ionic-team/capacitor-plugins/pull/486
