### ISSUE TITLE
Github Login Plugin

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor-plugins#269]
### Plugin

Github Login (Login via Github using github oAuth)

### Description

Github oAuth Plugin using Github's OAuth API same as facebook login. 

### Platform(s)

[x] Android
[x] IOS

**Comment by jcesarmobile** [comment]
Sorry, we are not adding any more plugins.

You can create a proposal on the capacitor-community organization
https://github.com/capacitor-community/proposals
