### ISSUE TITLE
[Cap 3 beta] Splash Screen: Splash no longer automatically appears on app launch

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor-plugins#270]
### Plugin(s)
Splash Screen v0.3.3

### Capacitor Version
```
Core: v3.0.0-beta.2
CLI: same
```

### Platform(s)
iOS, Android

### Current Behavior
In Cap 3's Splash Screen plugin, launchShowDuration value now defaults to 0 (in Cap 2, it was 3000 which caused apps to potentially be “slower” to load if they in fact loaded faster than 3 seconds). The consequence is that the Splash Screen no longer automatically appears on app launch.

Why? In the code ([see here](https://github.com/ionic-team/capacitor-plugins/blob/main/splash-screen/ios/Plugin/SplashScreen.swift#L21)), if 0 is found, the `showOnLaunch()` method exits without doing anything. in SplashScreenConfig (iOS), launchShowDuration defaults to 0.

If that's intentional, we should document this change in the upgrade guide because if you’re like me, you never called the Show method, just Hide. According to Dan, this could be a bug though.

To see the splash screen, I added this to the Cap config:
"launchShowDuration": 1000,
"launchAutoHide": false

### Expected Behavior
If the Splash screen plugin is installed, on ios/android app launch the screen should display, and no configuration (in capacitor.config.json) is required.

### Code Reproduction
Pull Cap 3 branch: https://github.com/ionic-team/ionifits/tree/cap-3

Currently, the splash _will show_ since I've set launchShowDuration to 1000 (aka anything but 0). So, delete `launchShowDuration` entry from Cap config, or set it to zero.

### Open question: What is the best configuration for fast loading apps?
From [this in the Cap 3 docs](https://capacitorjs.com/docs/v3/apis/splash-screen#hiding-the-splash-screen), we mention hiding the splash to manually provide the fastest experience to users. With this new launch duration change in mind, what is the best practice for fast loading apps?**What recommendation can we make to users?**

I _think_ we want to recommend **showing the splash screen for as long as it takes until the app is ready**. That would mean in Cap config, setting `launchAutoHide` to false, then calling `Hide()` on app startup. In Angular, this would be:

```
export class AppComponent {
constructor() {
  if (Capacitor.isNativePlatform()) {
    SplashScreen.hide();
  }
}
```

**Comment by jcesarmobile** [comment]
It was documented on https://github.com/ionic-team/capacitor/issues/3320 (check last edit), but looks like it wasn't added when the information was moved to the official doc page.

But since Capacitor 2.1.0, all new projects included `launchShowDuration: 0` in the `capacitor.config.json`, so it's really only breaking if it was created before that or if the entry was removed.

**Comment by dotNetkow** [comment]
Updated my description with more detail. It's not about whether it's a breaking change or not, just pointing out that the Splash doesn't appear on launch anymore because that launch duration value now defaults to 0.

If that's intentional (aka not a bug), I'd like to know what values to set then, as part of my "open question" thing. thanks.

**Comment by eric-horodyski** [comment]
Using Capacitor `3.0.0-beta.6`, this appears to prevent the ability for a splash screen to be shown for an indeterminate amount of time in cases where developers want to "set the stage" of their application "before pulling back the curtain". 

Given two branches of the same application, both containing the same `SplashScreen` plugin configuration:

```
  plugins: {
    SplashScreen: {
      launchAutoHide: false,
    },
  },
```

- [The project using Capacitor 2.4.7](https://github.com/ionic-team/tea-taster-react/tree/test/splash-never-dismiss) will never dismiss the splash screen
- [The project using Capacitor 3.0.0-beta.6](https://github.com/ionic-team/tea-taster-react/tree/chore/cap3-beta-6) will always dismiss the splash screen

**Comment by dennisameling** [comment]
@eric-horodyski could you try if [this](https://github.com/ionic-team/capacitor-plugins/issues/300#issuecomment-792874339) works for you? Explicitly setting a `launchShowDuration` seems to do the trick if `launchAutoHide` is false, which looks like a bug to me though

**Comment by dennisameling** [comment]
Looks like this is the culprit:

https://github.com/ionic-team/capacitor-plugins/blob/72be326c651929b58911eca96ad87ad2b3107b23/splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java#L45-L47

Just did a quick check and I think it should be this instead:

```
if (config.getLaunchShowDuration() == 0 && config.isLaunchAutoHide()) {
  return;
}
```

Will check on both Android and iOS and provide a PR later today 👍🏼

**Comment by EinfachHans** [comment]
Additional (iOS): **launchAutoHide** seems to do nothing currently?

https://github.com/ionic-team/capacitor-plugins/blob/72be326c651929b58911eca96ad87ad2b3107b23/splash-screen/ios/Plugin/SplashScreen.swift#L26-L27
I think here the `settings.autoHide` should be set to `config. launchAutoHide `
