### ISSUE TITLE
Documentation not updated v3

### ISSUE THREAD

**Issue by mishrasatyam** [ionic-team/capacitor-plugins#281]
### Plugin(s)

@capacitor/filesystem

### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
Documentation is not updated, documentation given is for version 2. please update.

**Comment by jcesarmobile** [comment]
On the top left there is a version chooser

![Screenshot 2021-03-02 at 13 26 46](https://user-images.githubusercontent.com/1637892/109648475-f1dd0900-7b5a-11eb-8692-e7190c8ca683.png)

direct link to v3 docs
https://capacitorjs.com/docs/v3

**Comment by mishrasatyam** [comment]
HI, I am talking about v3 docs [Link](https://capacitorjs.com/docs/v3/apis/filesystem). \
The example given shows `import { Filesystem, FilesystemDirectory, FilesystemEncoding } from '@capacitor/core';`  instead of 
`@capacitor/filesystem` [Example](https://capacitorjs.com/docs/v3/apis/filesystem#example)  is not updated

**Comment by jcesarmobile** [comment]
will be updated on next
