### ISSUE TITLE
bug: Failed to construct 'Notification': Illegal constructor

### ISSUE THREAD

**Issue by theproducer** [ionic-team/capacitor-plugins#284]
Using LocalNotification on Android Chrome fails when attempting to build a notification:

```
Unhandled Rejection (TypeError): Failed to construct 'Notification': Illegal constructor.  Use ServiceWorkerRegistration.showNotification() instead.
```

**Comment by jcesarmobile** [comment]
related
https://bugs.chromium.org/p/chromium/issues/detail?id=481856

**Comment by theproducer** [comment]
Yes - I don't think we are going support using Service Workers in right now (I could be wrong?) so the plan is just to check for `new Notification()` support and return unavailable if not.
