### ISSUE TITLE
feat(splash-screen): support different splash screens for different targets on ios

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor-plugins#298]
### Plugin
**splash-screen**

### Description
We are branding our app with different logos and different splash screens. On IOS for what we know we have to create different targets where we select different name space and different app name and anything we have to do.

Under the build settings we can select a custom icon but we can not select the splash screen to use
![image](https://user-images.githubusercontent.com/3778892/110138596-6d94bb00-7dd2-11eb-96c5-75ee86f9ed77.png)

We have created different Icons and splash screens but it is not selectable in the build
![image](https://user-images.githubusercontent.com/3778892/110138762-9ddc5980-7dd2-11eb-9406-de55a1dd521c.png)

This all is working out of the box in android which copies always the required file as **Splash** file name

You have also a TODO in the code
```
// Find the image asset named "Splash"
// TODO: Find a way to not hard code this?
image = UIImage(named: "Splash")
```

So I assume we can not do this by ios configuration files like on android, you have to resolve this by your own?

### Platform(s)
**ios**

**Comment by jcesarmobile** [comment]
I've not tried to run, but you can create another asset catalog and assign it to the other target

![Captura de pantalla 2021-03-05 a las 19 13 04](https://user-images.githubusercontent.com/1637892/110156087-d423d400-7de6-11eb-9020-efd0c70b8dbe.png)
![Captura de pantalla 2021-03-05 a las 19 13 24](https://user-images.githubusercontent.com/1637892/110156127-e00f9600-7de6-11eb-8722-a0a869284abd.png)

**Comment by mburger81** [comment]
Yes this worked for me thx
