### ISSUE TITLE
bug(splash-screen): splash seems to not hide

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor-plugins#300]
### Plugin(s)
Splash Screen

### Capacitor Version

```
  @capacitor/cli: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/ios: 3.0.0-beta.6
```

### Platform(s)
android, not sure for ios

### Current Behavior
As you can see from this video https://www.youtube.com/watch?v=P_9r-bAcVJ4 the Splash Screen seems to be hidden a few ms before the app is shown the login page. But as you can see show and hide the keyboard shows the splash screen in the background.

auto hide is enabled by default, what we are do we are still as on ionic/cordova hide the splash screen after platform ready, is this still the best approach?

```
this.platform.ready().then(() => {
            if (Capacitor.isPluginAvailable('SplashScreen')) {
                SplashScreen.hide();
            }
        });
```

### Expected Behavior
hide splash screen

**Comment by dennisameling** [comment]
I just had the EXACT same issue. In your `capacitor.config.json`, make sure you have the following:

```
{
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false,
      "launchShowDuration": 3000
    }
  }
}
```

Having to set the `launchShowDuration` even when `launchAutoHide` is false sounds like a bug to me. I'll have at Capacitor's plugin code later today or tomorrow

**Comment by dennisameling** [comment]
Think I found the code that is causing this behavior, will check more and provide a PR later today: https://github.com/ionic-team/capacitor-plugins/issues/300#issuecomment-792887123

**Comment by mburger81** [comment]
This is something we have already tested previously and tested it again today, this is `capacitor.config.ts` file

i```
mport { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.lanthings.iot.client',
  appName: 'Lanthings IoT',
  webDir: 'www',
  bundledWebRuntime: false,
  plugins: {
		"SplashScreen": {
			"launchShowDuration": 3000,
			"launchAutoHide": true
		}
	}
};

export default config;
```

The thing is, we also call **hide** in the code, which is hiding immediately the splash screen, but the bug with the keyboard and the shown splash screen is always there

**Comment by NunoSav** [comment]
I'm also having some issues with this, having the following config:
```
plugins: {
    SplashScreen: {
      launchAutoHide: false,
      launchShowDuration: 3000,
    },
  }
```
on my side results on SplashScreen hiding after 3s on iOS (not expected) and not hiding on Android (expected).

Then with this config:
```
plugins: {
    SplashScreen: {
      launchAutoHide: false,
    },
  }
```
and without calling `SplashScreen.hide()` the SplashScreen hides automatically on both platforms when i expected it not to hide at all.

### Capacitor Version
  ```
@capacitor/cli: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/ios: 3.0.0-beta.6
```

**Comment by kazlauskis** [comment]
Any progress with this? We are also experiencing the issue when the keyboard is opened or closed on Android with default capacitor settings. Also, if the device's recent-apps view is opened whilst the keyboard is showing the current app card in the view shows the splashscreen:

<img width="356" alt="Screenshot 2021-03-17 at 21 43 34" src="https://user-images.githubusercontent.com/7383162/111542587-d5032100-8769-11eb-8c01-4618217febe2.png">

**Comment by WIStudent** [comment]
I am still seeing this issue on android in the latest capacitor version
```
@capacitor/cli: 3.0.2
@capacitor/android: 3.0.2
@capacitor/core: 3.0.2
@capacitor/ios: 3.0.2
```
```
"plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
 }
```
Calling `SplashScreen.hide()` did not fix it either.

Looking at the layout inspector in Android Studio it seems that the splash screen image is being set on a layer that is not squashed by the keyboard. That's why it is briefly visible when the keyboard opens.
![2021-06-28 18_52_52-Window](https://user-images.githubusercontent.com/2707930/123676246-faf99080-d843-11eb-95f6-fc74e1382ff5.png)
I don't know why the splash screen icon is set on two layers though.

**Comment by claudiotrenca** [comment]
I also keep seeing the same problem, opening the keyboard you can see the splash screen in the background

**Comment by t4tapas** [comment]
Recently updated to Capacitor 3.1.1. Same issue.

**Comment by gultyaev** [comment]
Having this problem on Capacitor 3.1.1 too. Why is this issue closed while still not resolved?

**Comment by pbowyer** [comment]
This appears to be fixed in `"@capacitor/android": "^3.1.2"`. I see a black flash when opening the keyboard, but no longer my splash screen.

**Comment by kazlauskis** [comment]
We are still experiencing this issue, can you please reopen it or should we create a new one?

**Comment by mozhn** [comment]
I have Capacitor 3.2.3. Same issue.

**Comment by fhouenou** [comment]
You have to remove launchAutoHide from capacitor.config.ts to hide splash screen.
