### ISSUE TITLE
Compiler error - iOS

### ISSUE THREAD

**Issue by gigallo** [ionic-team/capacitor-plugins#304]
https://github.com/ionic-team/capacitor-plugins/blob/f625bd28bc00dbd0b51d7bdecf5e6f3077dcc7a9/storage/ios/Plugin/StoragePlugin.swift#L46

Hi

Xcode raises an error in this line: value of optional type String? must be unwrapped to a value of type String

**Comment by jcesarmobile** [comment]
can you provide a sample app? I don't see any errors

**Comment by gigallo** [comment]
Simply create a new project, add the library and try to compile. Xcode will raise that error. If i'll find some times I'll try to upload a sample project for you

**Comment by jcesarmobile** [comment]
Well, I ask for the sample project because I can’t reproduce on my sample project.

what’s your Xcode version?

**Comment by gigallo** [comment]
Hi

Xcode 12.4

Uploaded the project with the problem

Thanks
[TestStore3.zip](https://github.com/ionic-team/capacitor-plugins/files/6129479/TestStore3.zip)

**Comment by jcesarmobile** [comment]
Capacitor 3 is moving plugins out, this plugin (and all plugins in this repo) are for Capacitor 3, but you are still using Capacitor 2.
If you are still using Capacitor 2, the Storage plugin was part of `@capacitor/ios` package, you don't have to install this plugin.
