### ISSUE TITLE
App: unexpected behavior of Android back button in combination with Ionic

### ISSUE THREAD

**Issue by dennisameling** [ionic-team/capacitor-plugins#314]
### Plugin(s)

- @capacitor/app: 0.3.6

### Capacitor Version

```
npx cap doctor
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

`@ionic/angular` [adds an event listener](https://github.com/ionic-team/ionic-framework/blob/e4bf052794af9aac07f887013b9250d2a045eba3/core/src/utils/hardware-back-button.ts#L29) for `backbutton`:

```JS
doc.addEventListener('backbutton', () => {...})
```

This event listener is _not_ registered until we use one or more functions from `@capacitor/app`. Let me try to explain:

1. Create a repo with Capacitor 3 and `@ionic/angular` which also has `@capacitor/app` and `@capacitor/android` installed ([example repo here](https://github.com/RaphaelWoude/ionic-capacitor-example)).
1. Run `npm run build && npm run sync && npm run android` to open Android Studio. Start the app in debugging mode.
1. Press the back button on the Android device. Notice that you **will not** see `Notifying listeners for event backButton` in the Android Studio debug log.
1. In `app.component.ts`, uncomment the `App.getInfo()` line (this can be any method from `App` by the way, as long as it's not `App.addListener('backButton', ...)` for now!)
1. Run `npm run build && npm run sync && npm run android` to open Android Studio. Start the app in debugging mode.
1. Press the back button on the Android device. Notice that you **will now see** `Notifying listeners for event backButton` in the Android Studio debug log. That's weird, right? We haven't configured any listener for the back button just yet! This is because of Ionic's event listener which is mentioned above.

### Expected Behavior

We expect Ionic's event listener to be registered, even if we don't explicitly call any methods from `App.*`

### Code Reproduction

Example repo: https://github.com/RaphaelWoude/ionic-capacitor-example

### Other Technical Details

We also created a demo repo with only Angular + Capacitor (so not Ionic). There, the issue doesn't apply. So the problem is somewhere in the interaction between Ionic and Capacitor (the `doc.addEventListener('backbutton', () => {...})` mentioned above)

### Additional Context

We implemented the following workaround to our code for the time being:

```TypeScript
App.addListener('backButton', () => {
  window.history.back();
});
```

**Comment by jcesarmobile** [comment]
I can't reproduce on the provided test app after updating android/cli/core to 3.0.1 and app plugin to 1.0.1
