### ISSUE TITLE
Storage plugin prefix documentation

### ISSUE THREAD

**Issue by 8eecf0d2** [ionic-team/capacitor-plugins#325]
### Plugin(s)

 - Storage 2.4.7 (built in)

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.4
  @capacitor/android 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/core 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    @capacitor-community/http (0.2.1)
[success] iOS looking great! 👌
```

### Platform(s)

- iOS
- Android(?)

_I didn't try Android but assume the behaviour is the same._

### Current Behavior

Documentation for Capacitor Storage plugin states
> This plugin will use UserDefaults on iOS

which is inaccurate, only keys within `UserDefaults` that have a specific prefix will be used and so existing keys within `UserDefaults` or those managed outside of the Capacitor Storage plugin (eg, Settings bundle) may not be accessible.

### Expected Behavior

Expect that I can access any `UserDefaults` key as implied in the documentation _or_ that documentation is more clear about the functionality of the Capacitor Storage plugin and how it consumes the `UserDefaults` API.

### Code Reproduction

`swift`
```swift
UserDefaults.standard.setValue("bar", forKey: "foo")
UserDefaults.standard.value(forKey: "foo") // "bar"
```

`typescript`
```typescript
import * as Capacitor from "@capacitor/core";

await Capacitor.Plugins.Storage.keys(); // []
```

### Other Technical Details

n/a

### Additional Context

I have limited experience with native apps, after a while of searching for how to setup user settings in iOS and Capacitor (very little discussion or documentation) I finally realised the connection between iOS Settings bundle > UserDefaults > Capacitor Storage plugin..

I think it'd be very helpful to add documentation or a small how-to on the Settings Bundle, UserDefaults and Capacitor Storage plugin - it seems like a pretty common thing people might want to use.

**Comment by jcesarmobile** [comment]
In this plugin you can use the `NativeStorage` group that uses no prefix.
