### ISSUE TITLE
In @capacitor/local-notifications can add support for newline on body message?

### ISSUE THREAD

**Issue by togro** [ionic-team/capacitor-plugins#328]
## Feature Request

newline on body message

### Plugin
@capacitor/local-notifications 

### Description
It's possible had , like on cordova, newline on body from message ? ( Some like body : "Hello \n Line2" )

### Platform(s)
android

**Comment by jcesarmobile** [comment]
Body is single line, but you can use largeBody, which supports multiple lines.
