### ISSUE TITLE
Keyboard: does not always respect ResizeMode (Android)

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor-plugins#330]
### Plugin(s)

    "@capacitor/keyboard": "^0.5.5",

### Capacitor Version

```
sharktop:topdecked-unified lincoln$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6
  @capacitor/ios: 3.0.0-beta.6

[success] iOS looking great! 👌
[success] Android looking great! 👌
sharktop:topdecked-unified lincoln$ 

```

### Platform(s)

Android

### Current Behavior

When opening the capacitor app. The keyboard resize mode will only sometimes use the configured values in capacitor.config.json. The following two screenshots were taken with the same configuration & built application, but different launches of the app:

Here the body is not resized, per the specified ResizeMode (correct behavior):
![image](https://user-images.githubusercontent.com/362329/113169318-7af76680-9213-11eb-81f3-5f7cf8c11bab.png)

Here you can see the body has been resized (Incorrect behavior):
![image](https://user-images.githubusercontent.com/362329/113168675-dffe8c80-9212-11eb-87ee-4ee21da15d76.png)

Net result (we expect ResizeMode.None, but are receiving ResizeMode.Native behavior)
![image](https://user-images.githubusercontent.com/362329/113168514-bcd3dd00-9212-11eb-8308-c8d21086f744.png)

### Expected Behavior

The ResizeMode.None value should be consistently applied.

### Code Reproduction

```{
  "plugins": {
    "Keyboard": {
      "resize": "none",
      "style": "dark"
    },
}
```

### Other Technical Details

Reproducible on all simulators and test devices I've tried. 

### Additional Context

No errors seem to be reported in the logs.
![image](https://user-images.githubusercontent.com/362329/113168421-a62d8600-9212-11eb-9933-b27e45757cc2.png)

**Comment by lincolnthree** [comment]
Unfortunately this issue is incredibly inconsistent and difficult to track down. I wish I could give more information. Please let me know what else I can do.

**Comment by jcesarmobile** [comment]
The resize modes are not implemented for Android, so the weird thing is that it works sometimes.

**Comment by lincolnthree** [comment]
@jcesarmobile Wait really? What is the resize mode on Android WebView supposed to be? I thought it just wasn't possible to set the ResizeMode at runtime vs. cap.config.json?

**Comment by lincolnthree** [comment]
Unless I'm mistaken, Android does support these, right?

```
          android:windowSoftInputMode=["stateUnspecified",
                                       "stateUnchanged", "stateHidden",
                                       "stateAlwaysHidden", "stateVisible",
                                       "stateAlwaysVisible", "adjustUnspecified",
                                       "adjustResize", "adjustPan"] > 
```

**Comment by lincolnthree** [comment]
Wait, there is also an `adjustNothing` setting that's not in the docs I was just looking at. It seems this is probably the place to set this. Forgive me I know you probably already know all this, but posting for others and just in case.

**Comment by lincolnthree** [comment]
Summary of behaviors via trying them:

```
<activity android:windowSoftInputMode="stateUnchanged
   |adjustPan --> Height of webview unchanged.
   |adjustResize --> Height of webview unchanged.
   |adjustUnspecified --> Height of webview unchanged.
   |adjustNothing --> Height of webview unchanged and keyboard events not fired.
">
```
I have no idea how the behavior of this was/is breaking sporadically. I'm at a loss. I'll try to debug more next time it happens.

**Comment by jcesarmobile** [comment]
Yeah, you can configure a few things from the AndroidManifest.xml, but the Keyboard plugin doesn't allow to change the value programmatically, nor reads the config from `capacitor.config.json`

**Comment by michalsisak** [comment]
Have you found any solution? @lincolnthree 

In my example - I have Android 10 & 11. In 10 the view puts keyboard on top (keyboard resize scenario '**none**') hiding input while in 11 the view shrinks and the input stays visible - scenario '**native**'.


I can work with either of those scenarios by either moving input to visible part of the page or just leaving things as they are when in 'native' but not with both of them at the same time. @jcesarmobile can you please give me some suggestion as what to do?

**Comment by jcesarmobile** [comment]
As I said, it's not implemented at all, if you see different behavior they are not related to keyboard plugin.

We have an issue for tracking the resizeMode implementation for Android, so going to close this one
https://github.com/ionic-team/capacitor-plugins/issues/416

**Comment by lincolnthree** [comment]
@michalsisak I've manually added listeners to keyboard height and add appropriate padding to key parts of the app when it's open. It's ugly, messy, and error prone, but it _mostly_ works.
