### ISSUE TITLE
Clipboard.read: `Unexpectedly found nil while unwrapping an Optional value`

### ISSUE THREAD

**Issue by baptisteArno** [ionic-team/capacitor-plugins#333]
### Plugin
Clipboard

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/android 2.4.6
  @capacitor/core 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/electron not installed
```

### Platform(s)
iOS

### Current Behavior
Crash when calling `Clipboard.read()`. I think it happens when the clipboard is empty.

### Expected Behavior
No crash

### Code Reproduction
Difficult to reproduce? The Clipboard needs to be empty so maybe a reboot does the trick.

**Comment by jcesarmobile** [comment]
Your Capacitor doctor output says you are using Capacitor 2, but this plugin is for Capacitor 3.

The Clipboard plugin in this repository checks if the Clipboard has a value instead of unwrapping the Optional value, so shouldn't be a problem anymore.

**Comment by baptisteArno** [comment]
> but this plugin is for Capacitor 3.

We're talking about the [official Clipboard plugin](https://capacitorjs.com/docs/apis/clipboard), right?

```swift
    if UIPasteboard.general.hasStrings {
      call.success([
        "value": UIPasteboard.general.string!, // This throws the mentioned error
        "type": "text/plain"
      ])
      return
    }
```
It looks like `UIPasteboard.general.hasStrings` checks if the clipboard contains a string but still, it managed to pass this condition with one of my user.

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/capacitor-plugins/blob/main/clipboard/ios/Plugin/Clipboard.swift#L49
