### ISSUE TITLE
Background Geolocation on Google Play Store

### ISSUE THREAD

**Issue by ElRochito** [ionic-team/capacitor-plugins#343]
### Plugin(s)
I used @capacitor/geolocation from @capacitor/core 2.4.7

### Capacitor Version

```
npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

### Platform(s)

- Android

### Current Behavior
When I submitted my application on Google Play Store, I am informed that my application uses geolocation in background.
However, this is not true.

I have in my AndroidManifest file, only 2 permissions : 
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
Does the geolocation plugin run in the background by default ?

Here you find the message from Google : 
```
Background location access not declared
We detected that your app contains at least one feature that requests access to location in the background, 
however  your permission declaration form did not reflect this. 
Please log in to your Play Console to resubmit your location declaration form. 
You may either remove location in the background from your app or indicate that the usage is in the background.
```

I don't know how solve this issue

Thanks for your answer

**Comment by jcesarmobile** [comment]
Capacitor doesn’t use background geolocation, do you use some Cordova plugins?

**Comment by ElRochito** [comment]
I don't use Cordova plugins.

After researches this morning, I see that : 
```
Access granted automatically when targeting Android 9 or lower
If your app runs on Android 10 or higher but targets Android 9 (API level 28) or lower, the platform applies the following behavior:

- If your app declares a <uses-permission> element for either 
ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION, 
the system automatically adds a <uses-permission> element for ACCESS_BACKGROUND_LOCATION during installation.

- If your app requests either ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION, 
the system automatically adds ACCESS_BACKGROUND_LOCATION to the request."

```

I target API level 29 but I don't use ACCESS_BACKGROUND_LOCATION. If I understand correctly, ACCESS_BACKGROUND_LOCATION will be set automatically, so I don't understand how resolve it.

I don't use background geolocation but Google add it ...

Anyone has the same problem ?

**Comment by ElRochito** [comment]
In official Android doc, it says that we must declare this foreground service type location to use foreground geolocation.

We are agree that plugin don't use a foreground service ?

**Comment by jcesarmobile** [comment]
can you link the docs you mention?

**Comment by ElRochito** [comment]
https://developer.android.com/training/location/permissions#foreground

**Comment by jcesarmobile** [comment]
Can you try it in your app and if the warning goes away document it in the [Android section](https://github.com/ionic-team/capacitor-plugins/blob/main/geolocation/README.md#android) of the README?

**Comment by ElRochito** [comment]
Of course, a build processing on Google play store, I am waiting and I come back to you

**Comment by ElRochito** [comment]
FYI it's not a warning, it's an error ;)

**Comment by ElRochito** [comment]
I try but don't solve the issue. I think we've got this error when we have old apk/aab in the Google Play Console but we can't delete them ..
