### ISSUE TITLE
Ability to save to iOS phone's default Photo Library with Filesystem plugin?

### ISSUE THREAD

**Issue by askilondz** [ionic-team/capacitor-plugins#345]
### Plugin(s)
Filesystem

### Capacitor Version
@capacitor/core: 2.4.2

### Platform(s)
iOS

### Current Behavior
I have images in my app's assets folder I want the user to be able to save to their phone's public photo gallery. Currently the `FilesystemDirectory` options do not provide this as they only save to directories under the app's storage location on iOS. 

### Expected Behavior
User should be able to save an in-app image to their phone's photos library on iOS. When they exit the app and go to their default Photo's app they should see the image they saved.

**Comment by jcesarmobile** [comment]
Photo Library is not a Filesystem directory, can't be accessed through paths, only through certain APIs, so it's out of the scope of Filesystem plugin.
There are plugins out there to save files to the Photo Library.
In example https://github.com/capacitor-community/media
and a bunch of cordova ones
