### ISSUE TITLE
bug(camera) File input when selecting image is not hidden when using iOS presentingElement-style modal

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/capacitor-plugins#353]
### Plugin(s)

- `@capacitor/camera:^0.4.3`

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 3.0.0-rc.0
  @capacitor/electron not installed
```

### Platform(s)

- iOS Web

### Current Behavior

When using the `camera` plugin to initiate a "photo select", capacitor adds a "hidden" `_capacitor-camera-input`. This works great until using Ionic's iOS style `presentingElement` modal which "stacks" the modals on top of each other. This leaves a gap of space at the top of the page, and does not hide the "hidden" input for selecting photos:

![image](https://user-images.githubusercontent.com/25097099/115519428-0cb82980-a23e-11eb-9459-2444bd89a005.png)

Video replication here: https://streamable.com/skudgw

### Code Reproduction

Repo to reproduce: https://github.com/uncvrd/capacitor-file-upload-button

- Click "Open Modal"
- Then click "Change Photo" button in the modal
- Observe how the file input shows in the top left.

### Other Technical Details

Please make sure you are testing on iOS Web browser (not native app build)

**Comment by jcesarmobile** [comment]
I've made the input hidden, will be fixed on next release
https://github.com/ionic-team/capacitor-plugins/pull/484
