### ISSUE TITLE
React - local notifications fail to build on iOS: type JSObject, NotificationHandlerProtocol not in scope

### ISSUE THREAD

**Issue by georgemuresan** [ionic-team/capacitor-plugins#359]
### Plugin(s)
@capacitor/local-notifications

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

  Found 1 Capacitor plugin for ios:
    @capacitor/local-notifications (0.6.0)

```
28 errors, amongst which:
Cannot find type 'NotificationHandlerProtocol' in scope
Cannot find 'JSObject' in scope
Method does not override any method from its superclass
Value of type 'LocalNotificationsPlugin' has no member 'shouldStringifyDatesInCalls'
alue of type 'CAPBridge' has no member 'notificationRouter'
Value of type 'CAPBridge' has no member 'localURL'
Cannot find 'JSTypes' in scope
```

### Platform(s)
iOS (have tried on normal project but also on fresh new project)

### Current Behavior
in the ionic environment - on any project - I run (in order):
ionic build
ionic cap copy
ionic cap sync

and after running:
ionic cap open ios

and trying to build the project, it shows up those 28 errors in LocalNotificationsPlugin.swift

### Expected Behavior
It should build successfully.

### Code Reproduction
have simply created a new project with the instructions here:
https://capacitorjs.com/docs/getting-started/with-ionic
using React - and have tried to install @capacitor/local-notifications and build on iOS only.

### Other Technical Details
XCode Version 12.4 
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.5

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.2

System:

   NodeJS : v14.15.3 (/usr/local/bin/node)
   npm    : 7.5.3
   OS     : macOS Big Sur

### Additional Context
n/a
<img width="247" alt="Screenshot 2021-04-22 at 21 34 58" src="https://user-images.githubusercontent.com/22757542/115780415-cee40e00-a3c1-11eb-9d8f-ae8b3d773317.png">

**Comment by jcesarmobile** [comment]
This plugins are for capacitor 3, they don’t work on capacitor 2 and are not needed because capacitor 2 had the plugins integrated.
