### ISSUE TITLE
feat: Local notifications getById()

### ISSUE THREAD

**Issue by JumBay** [ionic-team/capacitor-plugins#36]
### Plugin

Local notifications

### Description

It will be nice to be able to retrieve the content of a notification by its ID. We can retrieve all the pending notifications IDs via ` getPending(): Promise<LocalNotificationPendingList> ` but then we are not able to see the content of these notifications. 

### Platform(s)

- iOS
- Android

**Comment by jcesarmobile** [comment]
as per https://github.com/ionic-team/capacitor-plugins/pull/211, getPending now returns more information about the notifications and not just the id, so can be closed
