### ISSUE TITLE
Push Notifications break an application after calling `.register()` because of BillingClient v3

### ISSUE THREAD

**Issue by michalsisak** [ionic-team/capacitor-plugins#360]
## Bug Report
Hello, I tried to update **BillingClient** from v2 to v3. We are using RevenueCat to handle subscriptions, products, payments etc. We were running a **cordova-plugin-purchases**: 1.2.0 and tried to update to 2.1.1. That should have updated Google's BillingClient to v3.

And it did. When I inspected **AndroidManifest.xml** in android/app/build/intermediates/merged_manifests/debug and different places where BillingClient is referenced I saw a bump from v2.0.3 to v3.0.2. 
It also updated version in capacitor.build.gradle com.revenuecat.purchases:purchases-hybrid-common:1.6.2 from 1.2.0.

I did not make any other change to my code which was working well until that point. And the app is working well on web and ios but on Android when I call `.register()` on **PushNotifications** the app breaks with `Serious error executing plugin` and some reference to PushNotifications and _Google Play Services_.

![2021-04-27 at 09 53](https://user-images.githubusercontent.com/55797176/116217454-f0d6eb00-a749-11eb-84f9-6385598faf8c.png)

### Plugin(s)
```
Push Notifications v?: 
cordova-plugin-purchases: 2.1.1
capacitor/android: 2.4.2,
capacitor/core: 2.4.2,
ionic-native/core: 5.29.0,
ionic-native/purchases: 5.29.0
```

### Capacitor Version
```
Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/core 2.4.2
  @capacitor/electron not installed
```

### Platform(s)
Android

### Code Reproduction
Can try to create a simple repo if needed. 
Minimum reproduction would be installing `cordova-plugin-purchases: 2.1.1` and calling `.register()` for PushNotifications.

**Comment by jcesarmobile** [comment]
You are reporting the issue on capacitor-plugins repository, which hosts capacitor 3 plugins, but you are using capacitor 2 and not using the push plugin in this repository.
Can you try to migrate to capacitor 3 and use @capacitor/push-notifications?

**Comment by michalsisak** [comment]
Upgrading to Capacitor 3 solved the issue! 

Feel free to close the issue if you find it appropriate.
