### ISSUE TITLE
getCurrentPosition returning multiple times

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#376]
### Plugin(s)
geolocation

### Capacitor Version
3
### Platform(s)
android

### Current Behavior
getCurrentPosition returns multiple calls 

### Expected Behavior
should return only once

### Code Reproduction
In the sample app click get location
then click watch location and let it run for a while
then click stop watching location
then click get location again
it should return a single result, but will continue returning results and can't be stopped

**Comment by Anicspo** [comment]
This also happpens if you call getCurrentPosition a single time. The Geolocation is determined every subsequent 10s instead of only once
