### ISSUE TITLE
feat: Browser - Add option to hide toolbar and footer on mobile platforms

### ISSUE THREAD

**Issue by gabides** [ionic-team/capacitor-plugins#377]
### Plugin
Browser

### Description
Provide options similar to those of `cordova-plugin-inappbrowser` to hide the toolbar and footer of the browser

### Platform(s)
Android
iOS

### Preferred Solution
Add to the `OpenOptions` the following options based on the [cordova equivalent plugin](https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-inappbrowser/) : 
- location
- hidenavigationbuttons
- hideurlbar
- fullscreen
- footer

### Alternatives
Using the cordova-plugin-inappbrowser instead of the capacitor Browser (not ideal as it does not get much maintenance and a capacitor equivalent would be better)

### Additional Context
issue referenced a few times (github, SO, ionic forum):
- https://forum.ionicframework.com/t/how-to-create-ionic-4-5-capacitor-browser-without-header-bar/183774
- https://stackoverflow.com/questions/63402850/cordova-inappbrowser-in-capacitor-not-rotating-on-iphone
- https://github.com/ionic-team/capacitor/issues/1803
- https://github.com/ionic-team/capacitor-site/issues/218

**Comment by jcesarmobile** [comment]
It's not possible because the native components that the plugin use (Safari view controller on iOS and Chrome custom tabs on Android) don't allow to hide the toolbar and footer
