### ISSUE TITLE
feat: Library directory on iOS

### ISSUE THREAD

**Issue by phpfs** [ionic-team/capacitor-plugins#38]
### Plugin
Filesystem

### Description
Since the target of `cordova-plugin-file`'s `dataDirectory` used to be the [library folder on iOS](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/#ios-file-system-layout), it would great to also have the library directory as option to read from with the filesystem plugin.

### Platform(s)
iOS

### Preferred Solution
For implementation, one would have to add the new directory to the definitions file and add a case to the switch statement within the native swift code. For android, a fall-back to the files folder would do the trick.

### Alternatives
x

### Additional Context
x

**Comment by mtb3** [comment]
Using the existing plugin, is there currently _any_ way to access the `Library` folder on iOS? I also have the use case of needing to access a file that was placed there by a Cordova plugin.

**Comment by phpfs** [comment]
Not to my knowledge - an adaption of the plugin would be necessary.

In my case, I ended up using a different folder that was mapped equally on cordova an capacitator with an additional cordova release to move the data from library over.

All the best!

**Comment by mtb3** [comment]
@phpfs Thanks for the input... I'm considering the options... I'm still hoping to go "all-in" with Capacitor as soon as it's feasible.
