### ISSUE TITLE
Some fields in StatResult docs are incomplete documened

### ISSUE THREAD

**Issue by lr0pb** [ionic-team/capacitor-plugins#380]
### Plugin(s)

@capacitor/filesystem

### Capacitor Version

3

### Platform(s)

Docs

### Current Behavior

Next fields in StatResult are incomplete documened:
`size` - its unit is unknown. Is this bytes or something else?
`type` - which types are in?

### Expected Behavior

Specify this in docs. Maybe if types are enum, they need interface

**Comment by brian-g** [comment]
I would say that a greater problem is that the StatResult is not normalized across devices as well. So we have code that looks like:

```
if (stat.type === 'file' || stat.type === 'NSFileTypeRegular') {
    // Do stuff with normal file
} else if (stat.type === 'directory' || stat.type === 'NSFileTypeDirectory') {
    // Do stuff for a directory
}

**Comment by jcesarmobile** [comment]
4.0.0 beta 0 documented those fields, they will be on the beta docs page shortly
