### ISSUE TITLE
feat: Support data URLs in browser plugin

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor-plugins#388]
### Plugin

`@capacitor/browser`

### Description

Right now, there is no way to open a base64 encoded URI using the Browser plugin. It would be very useful to support this to allow opening images, PDFs, and other content using the system browser, directly.

### Platform(s)

ios/android & supported native devices. This is already possible when running in the web context.

### Preferred Solution

Passing a data URI to the browser plugin:

```
      const dataURL = 'data:text/jpeg;base64,' + jpeg;
      const dataURL = 'data:text/pdf;base64,' + pdfData;
      console.warn(dataURL)
      this.open({ url: dataURL, windowName: '_system' });
```

### Alternatives

None. There is no way to open a data URI using the Browser plugin.

**Comment by jcesarmobile** [comment]
Browser plugin can only open http/https urls, that's a limitation of the native components used in the browser plugin (Safari View Controller on iOS and Chrome custom tabs on Android).

You can try to open the data urls with the [app-launcher](https://capacitorjs.com/docs/apis/app-launcher) plugin
