### ISSUE TITLE
bug(splash-screen) status bar shows then hides using `splashImmersive`

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/capacitor-plugins#392]
### Plugin(s)

`@capacitor/splash-screen`

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.2
  @capacitor/android: 3.0.0-rc.2
  @capacitor/core: 3.0.0-rc.2
```

### Platform(s)

Android

### Current Behavior

When setting `splashImmersive: true` in `capacitor.config.json` then running the application, Android's status bar is visible for a few moments before dismissing.

### Expected Behavior

The status bar should not be displayed at all until the splash screen is dismissed, if technically possible.

### Code Reproduction

https://github.com/ramseyfeng/splash-screen

**Comment by jcesarmobile** [comment]
Sadly what happens or gets displayed on the app before the app launches is not under capacitor's control.

As user you can add `<item name="android:windowFullscreen">true</item>` to the `AppTheme.NoActionBarLaunch` in `styles.xml` to hide the status bar on the initial image
