### ISSUE TITLE
bug: The method Camera.getPhoto() doesn't return any data or error.

### ISSUE THREAD

**Issue by ghonche-yqr** [ionic-team/capacitor-plugins#397]
### Plugin(s)
`@capacitor/camera  0.4.7`

### Capacitor Version

```
Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.0.0-rc.3
  @capacitor/cli: 3.0.0-rc.3
  @capacitor/android: 3.0.0-rc.3

```

### Platform(s)
android

### Current Behavior
The method Camera.getPhoto() doesn't return any data or error.

### Expected Behavior
An Object of type `Photo` is expected.

### Code Reproduction
```
import {Camera, CameraDirection, CameraResultType} from '@capacitor/camera';

        Camera.getPhoto({
            quality: 90,
            allowEditing: false,
            resultType: CameraResultType.Uri
        }).then(data => {
            console.log('success: ', JSON.stringify(data));
        }, error => {
            console.log('error: ', error);
        });
```

### Other Technical Details
The method Camera.getPhoto() doesn't return any data or errors on first call after application startup. 
but when its called for the second time, proper data is returned!

### Additional Context
As far as I figured out,  ActivityCallback method (processPickedImage() or processCameraImage()) isn't called after closing the activity.

I guess it's related to [this issue](https://github.com/ionic-team/capacitor/issues/1044) reported on Capacitor Core , but unfortunately it's not resolved.
No result is returned after lunching a native activity.
Due to the discussion on [the issue](https://github.com/ionic-team/capacitor/issues/1044), it must be related to saveCall(call) method which is deprecated and  Bridge.saveCall(PluginCall) is suggested instead.
I tried using bridge.saveCall(call) but it didn't help.

I'm using     
"@capacitor/camera": "^0.4.7"
"@capacitor/core": "^3.0.0-rc.3"

I think this is a critical issue. any help is appreciated.

**Comment by jcesarmobile** [comment]
can you try updating to capacitor 3.0.0 final and @capacitor/camera 1.0.0?
If the problem persists, can you provide a sample app?

**Comment by ghonche-yqr** [comment]
I upgraded capacitor and camera to latest stable. now it works properly.
thanks.
