### ISSUE TITLE
Push plugin is always showing the notification in foreground

### ISSUE THREAD

**Issue by kamekaioken** [ionic-team/capacitor-plugins#402]
## Bug Report
On iOS The Push plugin version 0.3.10 is always showing (again?) the notification alert when the App is in foreground. Sound is mute, but the alert is shown ignoring the [configuration](https://capacitorjs.com/docs/v3/apis/push-notifications#push-notifications-appearance-in-foreground). I noticed that any kind of configuration is ignored, e. g. I can also not manage to enable sound when in foreground (I don't want this to happen, but this assumes config is beeing left out).
I am using the Plugin on iOS with Firebase as described [here](https://capacitorjs.com/docs/v3/guides/push-notifications-firebase).

### Plugin(s)
Push@0.3.10

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/android: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-beta.6

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
Open App. Trigger push notification from outside (via Firebase dashboard for example). Push notification is shown even though the App is in the foreground.

### Expected Behavior
Notification should not be shown when not explicitly configured.

### Code Reproduction
```
    // On success, we should be able to receive notifications
    PushNotifications.addListener('registration',
      (token: Token) => {
        alert('Push registration success, token: ' + token.value);
      }
    );

    // Some issue with our setup and push will not work
    PushNotifications.addListener('registrationError',
      (error: any) => {
        alert('Error on registration: ' + JSON.stringify(error));
      }
    );

    // Show us the notification payload if the app is open on our device
    PushNotifications.addListener('pushNotificationReceived',
      (notification: PushNotificationSchema) => {
        alert('Push received: ' + JSON.stringify(notification));
      }
    );

    // Method called when tapping on a notification
    PushNotifications.addListener('pushNotificationActionPerformed',
      (notification: ActionPerformed) => {
        alert('Push action performed: ' + JSON.stringify(notification));
      }
    );

    // iOS will prompt user and return if they granted permission or not
    // Android will just grant without prompting
    PushNotifications.requestPermissions().then(result => {
      if (result.receive === 'granted') {
        // Register with Apple / Google to receive push via APNS/FCM
        console.log('granted push');
        PushNotifications.register();
      } else {
        console.log('push not granted: ', result.receive);
        // Show some error
      }
    });
```

### Additional Context
_Originally posted by @kamekaioken in https://github.com/ionic-team/capacitor-plugins/issues/208#issuecomment-841516840_

**Comment by jcesarmobile** [comment]
I can't reproduce con capacitor 3.0.1 and @capacitor/push-notifications@1.0.1 on [our test app](https://github.com/ionic-team/capacitor-testapp), try updating and if you still face the issue create a new one and provide a sample app.
