### ISSUE TITLE
bug: Motion API is not working in iOS13

### ISSUE THREAD

**Issue by kxc0re** [ionic-team/capacitor-plugins#415]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/android 1.2.1

  @capacitor/ios 1.2.1

  @capacitor/core 1.2.1

  @capacitor/cli 1.2.1


[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    cordova-plugin-ble-central (1.2.2)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
No output from the eventlisteners shown in the example, no error message whatsoever

## Expected Behavior
output from the eventlisteners

## Sample Code or Sample Application Repo
https://github.com/kxc0re/testmotion

## Reproduction Steps
1. deploy to iOS device 

## Other Technical Details
iOS version 13.1.2

`yarn --version` output: 1.12.3
`node --version` output: v11.6.0
`pod --version` output (iOS issues only): 1.8.3

**Comment by matadorhernan** [comment]
it wont work with live reload either

**Comment by izeryab** [comment]
since you have to get permission on user input so you do something like this:

 window.document.onclick = function () {
          if (
            typeof (DeviceMotionEvent as any).requestPermission()
              .requestPermission === "function"
          ) {
            (DeviceMotionEvent as any)
              .requestPermission()
              .then((permissionState) => {
                if (permissionState === "granted") {
                 //do something
                }
              })
              .catch(console.error);
          } else {
            // handle regular non iOS 13+ devices
           //do something 
          }
        };

**Comment by jcesarmobile** [comment]
I've created a new issue for using native code in motion plugin, so I'm going to close this one in favor of the other one since the only way of not needing to request the permission would be to use native code
https://github.com/ionic-team/capacitor-plugins/issues/1192
