### ISSUE TITLE
Browser is not supported on Android

### ISSUE THREAD

**Issue by ultimate-tester** [ionic-team/capacitor-plugins#419]
### Plugin(s)
"@capacitor/browser": "^1.0.0",

### Capacitor Version
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0
  @capacitor/android: 3.0.0

[success] Android looking great! 

### Platform(s)
Android

### Current Behavior
I just implemented the Browser plugin for the first time. Upon triggering the Browser plugin, I get the following error in the console:

Line 211 - Msg: Uncaught (in promise) Error: "Browser" plugin is not implemented on android

### Expected Behavior
As I see code for the android platform and the documentations also describe android, I expect the Browser plugin to be supported on Android.

### Code Reproduction
`await Browser.open({url: target.href});`

### Other Configuration
androidxBrowserVersion = '1.3.0'
No custom code in the Android app, no manual modifications to AndroidManifest, or anything.

**Comment by Sealvin** [comment]
Hello ultimate-tester,

I had the same issue after updating capacitor to the version 3 with the camera plugin.

You need to remove your platforms and run those commands : 

`
npm install @capacitor/core@next @capacitor/cli@next

npx cap init

npm install @capacitor/android@next

npx cap add android

`

See this link : https://stackoverflow.com/questions/67226076/capacitor-3-0-upgrade-plugins-not-implemented-exception-nx-monorepo

**Comment by jcesarmobile** [comment]
No, you should never remove android platform, never.

You probably missed this step on the migration guide
https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading
