### ISSUE TITLE
Why the official plugin "Permissions" is not present in Capacitor 3?

### ISSUE THREAD

**Issue by ramoncarreras** [ionic-team/capacitor-plugins#422]
### Plugin
Permissions

### Description
In Capacitor V2, permissions plugin was one of the official plugins:
https://capacitorjs.com/docs/v2/apis/permissions

Now, in Capacitor V3, it doesn’t appear in the documentation:
https://capacitorjs.com/docs/apis

### Preferred Solution
Split v2 permissions plugin to their own v3 package.

**Comment by jcesarmobile** [comment]
permissions plugin was very limited, it only allowed to query the status, but not to request permissions

now every capacitor plugin that needs permissions has methods to query and to request the permissions

**Comment by ramoncarreras** [comment]
OK. Thank you @jcesarmobile.
