### ISSUE TITLE
bug: local-notifications - group not working

### ISSUE THREAD

**Issue by PhilippRoessner** [ionic-team/capacitor-plugins#426]
### Plugin(s)
local-notifications 1.0.0

### Capacitor Version
3.0.0

### Platform(s)
android

I was expecting the local notifications on Android to group under one notification banner when I set the 'group' property of LocalNotificationSchema like this:

`        let x =  <LocalNotificationSchema>{
              
          title: notification.title,
          body: notification.body,
          id:Math.floor(Math.random() * 999999999999999),              
          //schedule: { at: new Date(Date.now() + 1000 * 5) },
          threadIdentifier:"mygroup",
          sound: 'iphonesound.wav',
          iconColor:"#29C87A",
          channelId: 'heytimiChat',
          group:"mygroup",          
          smallIcon:'ic_stat_notification',
          largeIcon:'ic_stat_notification',
          attachments: null,
          actionTypeId: "",
          extra: null
        }`

Unfortunately I always get a new banner.

![grafik](https://user-images.githubusercontent.com/6959716/119482880-ab133f80-bd54-11eb-8ba6-62b643a081ce.png)

**Comment by jcesarmobile** [comment]
To properly group notifications, one of the notifications you want to group should have `groupSummary` property set to `true`. That one won't show its title or body, will just group the other notifications. You can also add a text on the group by adding `summaryText` property with the text you want to show.
