### ISSUE TITLE
bug:   sound property of LocalNotificationSchema ignored when firing LocalNotifications.schedule()

### ISSUE THREAD

**Issue by PhilippRoessner** [ionic-team/capacitor-plugins#428]
### Plugin(s)
local-notifications

### Capacitor Version
3.0.0

### Platform(s)
Android (on configured channel not working)
iOs (no sound at all)

### Current Behavior
sound property of LocalNotificationSchema ignored when firing LocalNotifications.schedule()

### Expected Behavior
Playing wave soundf from res/raw - directory (see [docs](https://capacitorjs.com/docs/apis/local-notifications#localnotificationschema) )

### Code Reproduction
 ```
let x =  <LocalNotificationSchema>{
              
          title: notification.title,
          body: notification.body,
          id:Math.floor(Math.random() * 999999999999999),              
          //schedule: { at: new Date(Date.now() + 1000 * 5) },
          threadIdentifier:"mygroup",
          sound: 'iphonesound.wav',
          iconColor:"#29C87A",
          channelId: 'heytimiChat',
          group:"mygroup",          
          smallIcon:'ic_stat_notification',
          largeIcon:'ic_stat_notification',
          attachments: null,
          actionTypeId: "",
          extra: null
        };
        console.log('local Notification: ',x);
        const notifs = LocalNotifications.schedule({
          notifications: [
           x
          ]
        });
```

### Other Technical Details
Also the settings from capacitor.config.json is ignored:

```
"LocalNotifications": {
      "smallIcon": "ic_stat_notification",
      "sound": "iphonesound.wav",
      "iconColor": "#29C87A"
    }

```

**Comment by PhilippRoessner** [comment]
@jcesarmobile thanks for clarification! But your solution also doesn't work. Another thing to mention, there is no sound at all on iOS, no matter where I put the soundfile or it's configuration. I will change the bug description and add iOS to the platforms

**Comment by PhilippRoessner** [comment]
It seems like the notification sound has to be triggerd from the pushnotofication plugin. After following the instructions from this SO Post it's working as expected https://stackoverflow.com/a/51048292

**Comment by jcesarmobile** [comment]
Local notifications is a separate plugin and doesn’t need push notifications to work

**Comment by joshuaGnol** [comment]
just a question on the id of LocalNotification for [LocalNotificationSchema](https://capacitorjs.com/docs/apis/local-notifications#localnotificationschema) and PushNotification for [PushNotificationSchema](https://capacitorjs.com/docs/apis/push-notifications#pushnotificationschema)

Any reason on why the **id**(the notification identifier) is **number** for LocalNotificationSchema and **string** for PushNotificationSchema ?

**Comment by jcesarmobile** [comment]
It’s because on Android the local notification id has to be an int

https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#notify(int,%20android.app.Notification)

but for push notifications the id comes from the server and there are no restrictions
