### ISSUE TITLE
bug: show time of when the notifications is launched and not when it was scheduled

### ISSUE THREAD

**Issue by MayKikuchiThrive** [ionic-team/capacitor-plugins#433]
## Describe the Bug

The problem I am having is that when I schedule a local notification for a future date, the notification will be displayed with the time the local notification was created as the timestamp, not the time the notification was scheduled.

## Platform 

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

**Comment by wrzr123** [comment]
Question, I'm having the same problem as described. So is it still not resolved? Using latest version of @capacitor/local-notifications, v1.1.0.
I'm using schedule at.

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4
  @capacitor/core: 3.3.4

**Comment by Splitomania** [comment]
Hi, is there any update on this? I'm using 

"@capacitor/android": "^4.0.1",
"@capacitor/app": "^4.0.1",
"@capacitor/core": "^4.0.1",
"@capacitor/local-notifications": "^4.0.1",

and it seems to be still the above mentioned behaviour.

I would really appreciate any info on this.
