### ISSUE TITLE
The method of removing delivered notifications does not work

### ISSUE THREAD

**Issue by marwilc** [ionic-team/capacitor-plugins#439]
## Bug Report
Currently I have a project which I need to delete certain notifications delivered, but when using the removeDeliveredNotifications method of the push notification plugin it does not seem to work.
### Plugin(s)

 "@capacitor/android": "^2.4.6",
 "@capacitor/cli": "^2.4.6",
 "@capacitor/core": "^2.4.6",

### Capacitor Version
$ npx cap doctor
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/electron: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌

### Platform(s)
PushNotifications

### Current Behavior
Currently I have a project which I need to delete certain notifications delivered, but when using the removeDeliveredNotifications method of the push notification plugin this seems not to work, the notifications keep appearing in the notification tray of the android system.

### Expected Behavior
It is expected that when passing the array of notifications to be deleted, they will not appear in the notification tray.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
