### ISSUE TITLE
Attempted import error: 'registerPlugin' is not exported from '@capacitor/core'

### ISSUE THREAD

**Issue by gcorreaalves** [ionic-team/capacitor-plugins#442]
### Plugin(s)
- @capacitor/push-notifications

### Capacitor Version
 - "@capacitor/core": "^2.4.7"
 - "@capacitor/push-notifications": "^1.0.0"
 
```
[0] Failed to compile.
[0] 
[0] node_modules/@capacitor/push-notifications/dist/esm/index.js
[0] Attempted import error: 'registerPlugin' is not exported from '@capacitor/core'.
```

### Platform(s)
- Android

**Comment by jcesarmobile** [comment]
This plugins are for Capacitor 3, Capacitor 2 had the plugins integrated, no need for additional packages, in fact they don't work as you have experienced.

If you want to upgrade to Capacitor 3, follow [the upgrade guide ](https://capacitorjs.com/docs/updating/3-0)
If you don't want to upgrade yet, then follow [Capacitor 2 docs](https://capacitorjs.com/docs/v2/apis/push-notifications)
