### ISSUE TITLE
bug: Status bar not displayed on Android

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor-plugins#450]
### Plugin(s)

- Status Bar

### Capacitor Version

```
$ npx cap doctor
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0

[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

As soon as the Status Bar plugin is used, the Status Bar is no longer displayed on Android.

Device: Pixel 5 (Android 11)

### Expected Behavior

The status bar should be displayed.

### Code Reproduction

https://github.com/robingenz/capacitor-plugins-issue-450

See [`app.component.ts`](https://github.com/robingenz/capacitor-plugins-issue-450/blob/main/src/app/app.component.ts):
```ts
import { Component } from '@angular/core';
import { StatusBar, Style } from '@capacitor/status-bar';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
})
export class AppComponent {
  constructor(private readonly platform: Platform) {
    this.init();
  }

  private async init(): Promise<void> {
    await this.platform.ready();
    await StatusBar.setStyle({ style: Style.Light });
  }
}
```

### Other Technical Details

```
@capacitor/status-bar: 1.0.0
```

### Additional Context

![Screenshot_20210601-092800](https://user-images.githubusercontent.com/13857929/120283851-eca76b80-c2bb-11eb-8312-ba69637a72e6.png)

**Comment by David-Brehm** [comment]
I had the same issue - it worked without the setStyle
await StatusBar.setStyle({ style: Style.Light });

Maybe this helps with tracking down the bug

**Comment by robingenz** [comment]
Works with:
```ts
await StatusBar.setStyle({ style: Style.Light });
await StatusBar.setBackgroundColor({ color: '#ffffff' });
```
