### ISSUE TITLE
↕️ Splash Screen image is stretched.

### ISSUE THREAD

**Issue by opuu** [ionic-team/capacitor-plugins#459]
### Plugin(s)
Splash Screen

### Platform(s)
Android

### Current Behavior
Image is stretched when gesture based navigation bar is enabled.

Adding this line to config helps but still it is stretched at first 
     `"androidScaleType": "CENTER_CROP",`

![Screenshot_20210604-015059_oone](https://user-images.githubusercontent.com/77793409/120704341-4ab09a80-c4d8-11eb-88ee-267509847d35.png)

### Expected Behavior
Show image without stretching.

**Comment by DwieDima** [comment]
i was able to fix this issue by providing paramters to `capacitor.config.json`:

```

		"SplashScreen": {
			"showSpinner": false
			"launchAutoHide": false,
			"androidScaleType": "CENTER_CROP",
			"showSpinner": false,
			"splashFullScreen": false,
			"splashImmersive": false
		}
```

also had to replace style `NoActionBarLaunch` inside `android/app/src/main/res/values/styles.xml`

```

  <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
    <item name="android:background">@drawable/splash</item>
    <item name="android:windowNoTitle">false</item>
    <item name="android:windowActionBar">false</item>
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:windowFullscreen">false</item>
  </style>
```

this solution should be seen more as a workaround, since the splashscreen is not fullscreen and a black bar is visible at the top.
I would appreciate an official fix.

**Comment by iamart** [comment]
It doesn't seem to affect Pixel_3a_API_31_arm64-v8a. Not sure if that's the aspect ratio or API level comes to play.

What I found is, removing `android:theme="@style/AppTheme.NoActionBarLaunch"` from AndroidManifest.xml fixes the issue.
