### ISSUE TITLE
Camera requestPermissions() does not fire if someone has denied permissions

### ISSUE THREAD

**Issue by floifyed** [ionic-team/capacitor-plugins#461]
### Plugin(s)
@capacitor/camera

### Capacitor Version

```
    Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/cli: 3.0.0
  @capacitor/ios: 3.0.0
```

### Platform(s)
iOS

### Current Behavior
I have an action sheet that allows users to either 
a) Take a photo or
b) Upload a photo from the gallery

Prior to this, I check to see if the user has provided permissions to allow the upload. If not, I try to trigger a new prompt to ask them to allow it. If a user has previously denied permission, the prompt does not trigger.

### Expected Behavior
I would expect that calling `Camera.requestPermissions()` would always trigger the permissions popup, even if a user has previously denied it.

### Code Reproduction
```
    const cameraPermissions = await Camera.checkPermissions();
    console.log('camera permissions are', cameraPermissions.photos);

    if (cameraPermissions.photos === 'denied') {
      console.log('prompt for permission');
      await Camera.requestPermissions();
      return false;
    } else {
      console.log("user has granted permission")
      return true;
}
```

**Comment by elylucas** [comment]
Hello @floifyed,

If the user denies the permissions initially, the app will not show the dialog again. This is a part of the operating system. The call to requestPermissions will return the status, which will let you know that it was denied. You can use that info to inform the user that they can go into the settings app and manually turn on the permission if they want to use the functionality.
