### ISSUE TITLE
Geolocation: "Origin does not have permission to use Geolocation service" on iOS

### ISSUE THREAD

**Issue by gerritvanaaken** [ionic-team/capacitor-plugins#471]
### Plugin(s)

@capacitor/geolocation 1.0.1"

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

### Platform(s)

iOS

### Current Behavior
````
  const pos = await Geolocation.getCurrentPosition({enableHighAccuracy: true, timeout: 5000, maximumAge: 60000});
````
throws only an promise error "Origin does not have permissions to use Geolocation service"

### Expected Behavior

should deliver lat/lng coords

### Code Reproduction

see above, code is within an async function.
Android works fine with the same codebase.

### Other Technical Details

I surely added all three privacy entries in Info.plist:
````
<key>NSLocationAlwaysUsageDescription</key>
<string>Um Fahrzeuge in Ihrer Nähe anzeigen zu können.</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>Um Fahrzeuge in Ihrer Nähe anzeigen zu können.</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>Um Fahrzeuge in Ihrer Nähe anzeigen zu können.</string>
````
App is running on "capacitor://scouter.de" – but changing to "localhost" or "ionic://localhost" does not work either. I tried every possible combination for iOS.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by gerritvanaaken** [comment]
Thank for your answer. I tried to reproduce. Of course, in a minimal setup on a fresh project, everything works fine ;-)

The problem in my real app, however, is the platform. If I output the current platform, Capacitor.getPlatform() tells me "web", although I’m clearly running the app in the iOS simulator. In the minimal test app, it says correctly "ios"

How can I force the correct platform so that this plugin works? I did not find this information.

**Comment by gerritvanaaken** [comment]
It seems like we have a vueclient/webpack related problem here...

in my "dist" folder, the build script references only the web version of the geolocation plugin:

./node_modules/@capacitor/geolocation/dist/esm/web.js

Here is the full content of this file:

````
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[0],{

/***/ "./node_modules/@capacitor/geolocation/dist/esm/web.js":
/*!*************************************************************!*\
  !*** ./node_modules/@capacitor/geolocation/dist/esm/web.js ***!
  \*************************************************************/
/*! exports provided: GeolocationWeb, Geolocation */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"GeolocationWeb\", function() { return GeolocationWeb; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Geolocation\", function() { return Geolocation; });\n/* harmony import */ var _capacitor_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @capacitor/core */ \"./node_modules/@capacitor/core/dist/index.js\");\n\nclass GeolocationWeb extends _capacitor_core__WEBPACK_IMPORTED_MODULE_0__[\"WebPlugin\"] {\n    async getCurrentPosition(options) {\n        return new Promise((resolve, reject) => {\n            navigator.geolocation.getCurrentPosition(pos => {\n                resolve(pos);\n            }, err => {\n                reject(err);\n            }, Object.assign({ enableHighAccuracy: false, timeout: 10000, maximumAge: 0 }, options));\n        });\n    }\n    async watchPosition(options, callback) {\n        const id = navigator.geolocation.watchPosition(pos => {\n            callback(pos);\n        }, err => {\n            callback(null, err);\n        }, Object.assign({ enableHighAccuracy: false, timeout: 10000, maximumAge: 0 }, options));\n        return `${id}`;\n    }\n    async clearWatch(options) {\n        window.navigator.geolocation.clearWatch(parseInt(options.id, 10));\n    }\n    async checkPermissions() {\n        if (typeof navigator === 'undefined' || !navigator.permissions) {\n            throw this.unavailable('Permissions API not available in this browser');\n        }\n        const permission = await window.navigator.permissions.query({\n            name: 'geolocation',\n        });\n        return { location: permission.state };\n    }\n    async requestPermissions() {\n        throw this.unimplemented('Not implemented on web.');\n    }\n}\nconst Geolocation = new GeolocationWeb();\n\n//# sourceMappingURL=web.js.map\n\n//# sourceURL=webpack:///./node_modules/@capacitor/geolocation/dist/esm/web.js?");

/***/ })

}]);
````

I have to convince the script to include the full version of the geolocation script, if I see this right:

./node_modules/@capacitor/geolocation/dist/esm/index.js

**Comment by gerritvanaaken** [comment]
Fixed it for me. I had to completely remove "WKAppBoundDomains" from the Info.plist – now the platform is correctly regcognized as "ios" and Geolocation works as intended.
