### ISSUE TITLE
CocoaPods could not find compatible versions for pod "CapacitorSplashScreen"

### ISSUE THREAD

**Issue by tonyclemmey** [ionic-team/capacitor-plugins#473]
### Plugin(s)

@capacitor/splash-screen (1.0.1)

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/electron: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/android 2.4.6
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 3 Capacitor plugins for ios:
    @capacitor/splash-screen (1.0.1)
    @capacitor/status-bar (1.0.1)
    cordova-plugin-inappbrowser (5.0.0)
[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

$ npm install @capacitor/splash-screen
$ npx cap sync 
$ npx cap update ios

```
✔ Copying web assets from www to android/app/src/main/assets/public in 752.60ms
✔ Copying native bridge in 2.04ms
✔ Copying capacitor.config.json in 3.05ms
⠦ copy  Found 1 Cordova plugin for android
    cordova-plugin-inappbrowser (5.0.0)
✔ copy in 836.89ms
✔ Updating Android plugins in 27.62ms
  Found 2 Capacitor plugins for android:
    @capacitor/splash-screen (1.0.1)
    @capacitor/status-bar (1.0.1)
  Found 1 Cordova plugin for android
    cordova-plugin-inappbrowser (5.0.0)
✔ update android in 89.00ms
✔ Copying web assets from www to ios/App/public in 437.56ms
✔ Copying native bridge in 578.17μp
✔ Copying capacitor.config.json in 635.13μp
  Found 1 Cordova plugin for ios
    cordova-plugin-inappbrowser (5.0.0)
✔ copy in 456.01ms
✔ Updating iOS plugins in 18.57ms
  Found 2 Capacitor plugins for ios:
    @capacitor/splash-screen (1.0.1)
    @capacitor/status-bar (1.0.1)
  Found 1 Cordova plugin for ios
    cordova-plugin-inappbrowser (5.0.0)
✖ Updating iOS native dependencies with "pod install" (may take several minutes):
✖ update ios:
[error] Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "CapacitorSplashScreen":
  In Podfile:
    CapacitorSplashScreen (from `../../node_modules/@capacitor/splash-screen`)

Specs satisfying the `CapacitorSplashScreen (from `../../node_modules/@capacitor/splash-screen`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by leonardoj6** [comment]
I'm encoutering the same problem, @tonyclemmey could you please tell me what the solution is?

**Comment by EdByrnee** [comment]
@leonardoj6 @tonyclemmey did you find a solution?

**Comment by tonyclemmey** [comment]
@EdByrnee @leonardoj6 I updated all my project packages at the time and that resolved the issue

**Comment by fabbioamaral** [comment]
go to **node_modules/@capacitor/CapacitorSplashScreen**, then go to the **CapacitorSplashScreen.podspec** file and change the _s.ios.deployment_target_ parameter to a lower version.

to find out which lower version you should set, i'd recommend checking a plugin that could be installed fine and use the same version for the splash screen. 

in my case for some reason, default ios deployment target was set as 13.0 but i had to change to 12.0. hope it helps!

**Comment by rosman21** [comment]
> go to **node_modules/@capacitor/CapacitorSplashScreen**, then go to the **CapacitorSplashScreen.podspec** file and change the _s.ios.deployment_target_ parameter to a lower version.
> 
> to find out which lower version you should set, i'd recommend checking a plugin that could be installed fine and use the same version for the splash screen.
> 
> in my case for some reason, default ios deployment target was set as 13.0 but i had to change to 12.0. hope it helps!

this works however when using ionic appflow to deploy it fails again
