### ISSUE TITLE
Status bar not working in iOS

### ISSUE THREAD

**Issue by jeshwanthsaravanan** [ionic-team/capacitor-plugins#482]
### Plugin(s)

-@capacitor/status-bar@1.0.1
-@capacitor/splash-screen@1.0.1

### Capacitor Version

3.0
```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

android
ios

### Current Behavior

and saying it is not support in ios
app screen overlaid the status bar 

### Expected Behavior

app screen should not overlay the status bar

**Comment by jcesarmobile** [comment]
It’s how status bar works on iOS, there is no real status bar, to avoid the status bar area of your app you should use css
https://webkit.org/blog/7929/designing-websites-for-iphone-x/
