### ISSUE TITLE
LocalNotifications.requestPermission() doesn't work on android 10

### ISSUE THREAD

**Issue by MELAS007** [ionic-team/capacitor-plugins#490]
## Bug Report

LOCAL NOTIFICATIONS DOESN'T WORK ON ANDROID 10 BUT WORK PERFECTLY ON IOS.

ANY HELP WILL BE APPRECIATED!

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/electron: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/android 2.4.7
  @capacitor/core 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 29 Capacitor plugins for ios:
    cordova-android-support-gradle-release (3.0.1)
    cordova-plugin-advanced-http (3.1.0)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-geolocation (4.0.1)
    cordova-plugin-inappbrowser (5.0.0)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (5.0.0)
    cordova-plugin-networkinterface (2.0.0)
    cordova-plugin-request-location-accuracy (2.2.3)
    cordova-plugin-splashscreen (5.0.4)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
    cordova-plugin-x-socialsharing (5.6.8)
    cordova.plugins.diagnostic (6.0.1)
    es6-promise-plugin (4.2.2)
    ionic-plugin-deeplinks (1.0.22)
    cordova-plugin-add-swift-support (2.0.2)
    cordova-plugin-device (2.0.3)
    cordova-plugin-googlemaps-sdk (3.9.0)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-ionic-webview (5.0.0)
    cordova-plugin-nativegeocoder (3.4.1)
    cordova-plugin-splashscreen (5.0.4)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
    cordova-sqlite-storage (5.1.0)
[success] iOS looking great! 👌
```

**Comment by jcesarmobile** [comment]
this repository is for Capacitor 3 plugins, you are using Capacitor 2, so I recommend you to upgrade.

`requestPermission()` method has been removed in the new plugin, it doesn't really do anything on Android, there is no permission for notifications, they should just work.

**Comment by MELAS007** [comment]
> this repository is for Capacitor 3 plugins, you are using Capacitor 2, so I recommend you to upgrade.
> 
> `requestPermission()` method has been removed in the new plugin, it doesn't really do anything on Android, there is no permission for notifications, they should just work.

I need to upgrade to 3, will it change code in my ionic app?

**Comment by jcesarmobile** [comment]
There are a few codes required, check the upgrade guide
https://capacitorjs.com/docs/updating/3-0

**Comment by MELAS007** [comment]
> There are a few codes required, check the upgrade guide
> https://capacitorjs.com/docs/updating/3-0

I did today upgrade to v3 and stil not working on android 10
what can I do ?
