### ISSUE TITLE
Default aspect ration for camera

### ISSUE THREAD

**Issue by anthonyolli** [ionic-team/capacitor-plugins#496]
### Plugin
Camera

### Description
Possibility to set a default aspect ratio for android cameras (3:4 or 16:9). Right now, when I open the camera through my ionic app, its aspect ratio is 3:4, even though my native camera app is set to 16:9.

### Platform(s)
Android

### Preferred Solution
The camera plugin has an "options" property, I wish I'd be able to set the defaultAspectRatio to "16:9", "3:4" or "1:1"

### Alternatives
None, changing the aspect ratio manually is a hard user setting.

### Additional Context
Pictures:

![Screenshot_2021-06-23-15-10-52-515_com android camera](https://user-images.githubusercontent.com/70762230/123261702-74545480-d4cd-11eb-92f2-f6294b0e80a5.jpg)
![Screenshot_2021-06-23-15-11-01-560_com android camera](https://user-images.githubusercontent.com/70762230/123261710-75858180-d4cd-11eb-8531-3e3529cbb628.jpg)

**Comment by jcesarmobile** [comment]
as far as I know there is no documented way of providing the aspect ratio to the camera intent

https://developer.android.com/reference/android/provider/MediaStore#ACTION_IMAGE_CAPTURE
