### ISSUE TITLE
Camera Plugin - Android - Camera.getPhoto() is saving a permanent copy that can't be deleted, even with saveToGallery set to false

### ISSUE THREAD

**Issue by pabloservin** [ionic-team/capacitor-plugins#497]
### Plugin(s)
@capacitor/camera: 1.0.1

### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 3.0.2    
  @capacitor/core: 3.0.2   
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2    

Installed Dependencies:    

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.1    
  @capacitor/android: 3.0.1
  @capacitor/core: 3.0.1
```

### Platform(s)
Android

### Current Behavior
When you use the Camera.getPhoto() function with the options:
```
  quality: 50,
  source: CameraSource.Camera,
  saveToGallery: false,
  resultType: CameraResultType.Uri,
```
The returned photo object contains the "path" property: _file:///data/user/0/io.ionic.starter/cache/JPEG_20210624_085255_5425877611720472711.jpg_

This path I use to delete the file, when needed, using the Filesystem.deleteFile(), which indeed deletes the file. But if I check my DCIM/Camera folder the image is still there and showing in my gallery. 

### Expected Behavior
If the option saveToGallery is set to false, then it shouldn't save the image, or it shouldn't create a permanent copy.

### Code Reproduction
I created a simple repo ionic + capacitor: https://github.com/pabloservin/capacitor-camera-test
There's a button in the home page that takes a picture and after 2.5 seconds the image is deleted using Filesystem.

### Additional Context
Related or similar issues:
https://github.com/ionic-team/capacitor-plugins/issues/431
https://github.com/ionic-team/capacitor-plugins/issues/212
https://stackoverflow.com/questions/63398598/ionic-capacitor-camera-delete-image

**Comment by jcesarmobile** [comment]
I've sent a PR that deletes unneeded images https://github.com/ionic-team/capacitor-plugins/pull/563, but not sure if it would solve your problem, looks like that on some devices the camera app creates a copy of the file.

**Comment by pabloservin** [comment]
@jcesarmobile ok, bit late, but thanks anyway!
