### ISSUE TITLE
Camera - android - Image has wrong orientation

### ISSUE THREAD

**Issue by WIStudent** [ionic-team/capacitor-plugins#503]
### Plugin(s)

@capacitor/camera@1.0.2

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2
```

### Platform(s)

android

### Current Behavior

When taking a picture with 
```typescript
Camera.getPhoto({
  source: CameraSource.Camera
  quality: 50,
  saveToGallery: false,
  correctOrientation: true,
  resultType: CameraResultType.Uri
})
```
and setting that image as a src of an `<img>` element, that image is not orientated correctly.

### Expected Behavior

Image should have correct orientation.

### Additional Context

This is probably caused by the changes made in https://github.com/ionic-team/capacitor-plugins/pull/480. My best guess is that the final image now contains the exif orientation returned by the camera. But `correctOrientation: true` rotated the image without also updating the exif orientation. So the exif orientation in the final image is incorrect. [Chrome then rotates the image using the exif orientation](https://www.chromestatus.com/feature/6313474512650240).

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by WIStudent** [comment]
Here's the reproduction repo: https://github.com/WIStudent/capacitor-camera-orientation-issue

**Comment by jcesarmobile** [comment]
And what are the steps to reproduce?
I've been testing in a few different devices taking pictures in portrait, landscape left, landscape right and upside down and I don't see any issue

**Comment by WIStudent** [comment]
I am seeing this issue on my Pixel 3a (Android 11, Android System WebView 91.0.4472.120)
Using the demo app I am taking a picture while holding the device in portrait orientation. After I took the picture, its rotated by 90 degrees clockwise in the web view.
When I am holding the device in landscape orientation (rotated clockwise) while taking the picture, the picture will be rotated 180 degrees in the web view.

**Comment by jcesarmobile** [comment]
ah, yeah, could reproduce on Pixel 4, will work on a fix
