### ISSUE TITLE
Plugins not installing for v2

### ISSUE THREAD

**Issue by latch-admin** [ionic-team/capacitor-plugins#504]
### Plugin(s)

All plugins, especially:
@capacitor/keyboard

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/electron: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed
```

### Platform(s)

All: iOS and Android

### Current Behavior

Unable to install plugins.

### Expected Behavior

npm install @capacitor/keyboard should install Keyboard

### Additional Context

After upgrading to v3 and realizing there is no web implementation, I downgraded to version 2. Now I can't install any plugins, especially my keyboard.

**Comment by jcesarmobile** [comment]
This plugins are for capacitor 3, capacitor 2 has the plugins built in.
