### ISSUE TITLE
State change in 'browserFinished' listener is not updated in app

### ISSUE THREAD

**Issue by atelierJVA** [ionic-team/capacitor-plugins#506]
Bug Report
### Capacitor Version
```
Latest Dependencies:
  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:
  @capacitor/android: not installed
  @capacitor/core: 3.0.2
  @capacitor/cli: 3.0.2
  @capacitor/ios: 3.0.2

[success] iOS looking great! 👌
```

### Platform(s)
* iOS
* Android

### Current Behavior
In an angular project,  in the `'browserFinished'` listener after closing the app browser,  the results of executing any code that changes state are not reflected until some other JS code is executed outside the listener. 
In our case changing a reactive value or refreshing an observable, do not work.

### Expected Behavior
In an angular project, in the `'browserFinished'` listener after after closing the app browser,  the results of executing any code that changes state are reflected immediately , or at least when the listener returns.

### Code Reproduction
see [GitHub - atelierJVA/capacitor-browser-issue: Minimal sample application that demonstrates browser module issue in callback when closing the browser](https://github.com/atelierJVA/capacitor-browser-issue.git), the relevant code is in `src/app/tab1/tab1.page.ts`:
```
export class Tab1Page {
  booleanValue = false;
  
  constructor() {
    Browser.addListener('browserFinished', () => {
      this.booleanValue = true;
    });
  }

  async openBrowser(urlInput) {
    this.booleanValue = false;
    await Browser.open({url: urlInput});
  }

  toggleValue() {
    this.booleanValue = !this.booleanValue;
  }

  do_something() {
     const ignored = 1;
  }
}
```

### Steps to reproduce
1. Build and run: `ionic build && cap run ios --target=[device-id]`
2. When the app runs, click button "Open App Browser"
3. Click "Done" to close the browser (this triggers the listener and set this.booleanValue = True)
4. Observe that the "Boolean value" is still false
5. Click "Do something" button  (this just  runs a simple JS statement), and now "Boolean value" shows the correct value
6. The same result is achieved by clicking any of the buttons in the bottom and returning to "Tab 1"

### Other Technical Details
```
Ionic:
   Ionic CLI                     : 6.13.1
   Ionic Framework               : @ionic/angular 5.6.10
   @angular-devkit/build-angular : 12.1.0
   @angular-devkit/schematics    : 12.0.4
   @angular/cli                  : 12.1.0
   @ionic/angular-toolkit        : 4.0.0
```

`npm --version` output: `6.14.12`

`node --version` output:  `v14.16.1`

`pod --version` output (iOS issues only): `1.9.3`

Tested in macOS 10.15.7/ iOS 14.3 and macOS 11.4 / iOS 14.5

### Additional Context
* Fails both in iOS and Android, in simulators and in real devices
* Also happens in  capacitor 2.4.7

**Comment by jcesarmobile** [comment]
it's not a bug, but an angular "feature", it's documented here how you can use zonejs to make it work
https://capacitorjs.com/docs/v2/apis#angular-notes
