### ISSUE TITLE
Localization or Translation strings for Camera plugin

### ISSUE THREAD

**Issue by kamekaioken** [ionic-team/capacitor-plugins#51]
First of all: thank you guys for doing a great job with Ionic and Capacitor.

## Feature Request
Localization / custom strings for Camera Plugin

### Plugin
Camera

### Description
In the past the camera plugin was modified by providing custom strings (see [https://github.com/ionic-team/capacitor/pull/2631](https://github.com/ionic-team/capacitor/pull/2631)).

But in iOS the camera itself still contains hard-coded english strings 'Photo' and 'Cancel'. My iOS-device language is set to german but still the two button labels are in english.
Is it possible to use the current system language or make this configurable?

### Platform(s)
iOS

### Preferred Solution
Set the native Camera Plugin language to the current system language. 

### Alternatives
Add additional properties to the class `CameraOption` like `cameraButtonLabelCancel` and `cameraButtonLabelPhoto`.

### Additional Context
![IMG_F7FBF0DB047E-1 2](https://user-images.githubusercontent.com/29948577/94261015-759e2400-ff31-11ea-8830-1403b728bc61.jpeg)

**Comment by jcesarmobile** [comment]
Those messages are automatically translated by the OS, but only if your project support that language.

You can add supported languages on the Localizations section of the project
![Captura de pantalla 2020-09-25 a las 14 43 08](https://user-images.githubusercontent.com/1637892/94268437-7341c700-ff3d-11ea-9430-23457eb84a02.png)

**Comment by code-by** [comment]
I have added German language and switch language to German in iPhone settings - that didn't help, labels still in English (

**Comment by kamekaioken** [comment]
@code-by I can't relate. Adding the German Language support in App > Info in Xcode did work for me.

**Comment by code-by** [comment]
may be because I have use cordova, not capactior

**Comment by code-by** [comment]
may be because I have use cordova, not capactior

**Comment by kamekaioken** [comment]
How can you use the Capacitor Camera Plugin with Cordova? I'm not sure if this is possible. Maybe you are using the Cordova Camera Plugin.

**Comment by code-by** [comment]
yes, I have use cordova and cordova camera plugin, so may be it is not translated when I added German in xCode
