### ISSUE TITLE
Android: PushNotifications.register() Kill the app => (E/Capacitor: Serious error executing plugin     java.lang.reflect.InvocationTargetException)

### ISSUE THREAD

**Issue by kingdox** [ionic-team/capacitor-plugins#514]
### Plugin(s)
       **@capacitor/push-notifications@1.0.0**

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.0.0

[success] Android looking great! 👌
```

### Platform(s)

- **Android**

### Current Behavior

Each time when it do the check as expect and reach to the line **PushNotification.register** shows an error on the Android studio logcat (using the 'Run' app option with a USB mobile conection) and then close the app itself !

that occurs when it pass after **PushNotifications.requestPermissions().then** promise and checking if it is a 'granted' in the return response

Currently it was tested on this android devices:
1.   HUAWEI GRA-L09 (Close the App, tested in 'Run' app option and release)
2.  5048Y_EEA (Close the App, tested in 'Run' app option and release)
3.  SM-G935F (First attemp 'stop working', the followings works right, tested only in release)

### Expected Behavior

As the PushNotifications plugin works, it should start to do the request and then if is right to be registered (by the promise response with a 'granted' value) and next register it.

### Other Technical Details

Possible details to know:

- Using Visual Studio Code
-   npm: '6.14.13',
-   node: '14.17.1',
-   "capacitor-firebase-auth": "^3.0.0-rc.0",
-   "@capacitor/push-notifications": "^1.0.0",

### Additional Context

the following images shows the Android studio logcat  within 'HUAWEI GRA-L09' device:

![Captura de pantalla 2021-07-11 a las 12 36 20](https://user-images.githubusercontent.com/44328679/125191805-9aefea80-e244-11eb-94fa-18dea31d5eec.png)

And this is the Plugin, why so many things appears Deprecated? am I missing a new version and if is it, how can I update it?:
![Captura de pantalla 2021-07-11 a las 12 36 57](https://user-images.githubusercontent.com/44328679/125191822-b0651480-e244-11eb-9903-0101f38577c9.png)

**Comment by medida** [comment]
@kingdox  i've having the same issue - have you managed to solve it all?

**Comment by medida** [comment]
@kingdox  i don;t know how / why but i have managed to get past this issue.
I added  import { Capacitor } from '@capacitor/core'; to my file and then checked if the platform was 'web' or not....

 if (Capacitor.getPlatform() !== 'web') {
            PushNotifications.register();
          }

But i removed the import and code - and it still works.. no idea why, but i have managed to get pas thtis which is great.

hope it helps you as well

**Comment by kingdox** [comment]
> @kingdox i've having the same issue - have you managed to solve it all?

Yes I did it, in my case of desesperation just redo  with npx cap init android in a new android project and adding one by one the things that I know it needs

My conclusion after that is it might be some libraries or another internal element who keeps obsoletes but it wasn't cleared at all after a update of a plugin or any other thing what Android manages 🤔 

I'll close this thread, I'll hope that my response can solve your problem 🚀
