### ISSUE TITLE
Share plugin not showing title and link on iOS and android native share widget

### ISSUE THREAD

**Issue by wajeshubham** [ionic-team/capacitor-plugins#518]
### Plugin(s)

@capacitor/share v1.0.0

### Platform(s)

iOS and Android

### code
```
await Share.share({
  title: 'My title',
  text: 'my description/text',
  url: 'https://abcd.intro.ooo',
  dialogTitle: "Share your Intro",
});
```

### Current Behavior

Not showing title and url link on native share widget

Image:
![Image from iOS](https://user-images.githubusercontent.com/62889697/125956324-f3f114b6-c3d8-4769-a129-0b1a91e6eebd.png)

As you can see in image its only showing description and not title and url

### Expected Behavior

It should show description(text), title and url all

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by wajeshubham** [comment]
updated issue kindly look into it!

**Comment by jcesarmobile** [comment]
Sorry, that's how the native dialogs look like, can't be configured. If you want to be able to configure it, you should request it to Apple.

The title is only used as subject is sharing by mail.
Android allows to have a title for the sharing sheet with `dialogTitle`, that is working fine, but android doesn't show anything else.
iOS shows the text or the icon and url of the web you are sharing.
