### ISSUE TITLE
Camera Plugin - android - FileNotFoundException when using source: CameraSource.Photos

### ISSUE THREAD

**Issue by WIStudent** [ionic-team/capacitor-plugins#524]
### Plugin(s)

@capacitor/camera@1.0.3

### Capacitor Version

```
@capacitor/cli: 3.1.1
@capacitor/ios: 3.1.1
@capacitor/core: 3.1.1
@capacitor/android: 3.1.1
```

### Platform(s)

Android

### Current Behavior

Selecting a portrait photo from gallery on a Pixel 3a results in a FileNotFoundException exception

### Expected Behavior

The plugin should return the image instead of throwing an exception.

### Code Reproduction

```typescript
import { CameraSource, Camera } from '@capacitor/camera';

Camera.getPhoto({
  source: CameraSource.Photos
});
```

### Additional Context

See also discussion here for more details: https://github.com/ionic-team/capacitor-plugins/pull/510

**Comment by sozonome** [comment]
Hope this temporary workaround helps
https://github.com/ionic-team/capacitor/issues/2060#issuecomment-890355682

**Comment by WIStudent** [comment]
@sozonome You basicly revert the changes made in https://github.com/ionic-team/capacitor-plugins/pull/510. You could also just downgrade to `@capacitor/camera@1.0.2`. But keep in mind this reintroduces issue https://github.com/ionic-team/capacitor-plugins/issues/503, which https://github.com/ionic-team/capacitor-plugins/pull/510 tried to fix in the first place.

**Comment by sozonome** [comment]
True...🤦😅 Sorry

Then we would need another new fix that can tackle both of it...
Hopefully a proper fix comes soon
