### ISSUE TITLE
SetOverlaysWebview might have been implemented wrong

### ISSUE THREAD

**Issue by creativiii** [ionic-team/capacitor-plugins#525]
### Plugin
Status Bar Plugin

### Description
There have been a couple of reports about the issue like ionic-team/capacitor#3088 which have reported the [SetOverlaysWebView API](https://capacitorjs.com/docs/apis/status-bar#setoverlayswebview) sets the Android view in such a way where the keyboard renders on top of most of the app when open.

How far I can usually scroll down:
![Screenshot 2021-07-21 at 09 29 40](https://user-images.githubusercontent.com/23533178/126457855-d44d5b5a-a85f-4d62-b781-5139b97f9447.png)

How far I can scroll down with SetOverlaysWebView true:
![Screenshot 2021-07-21 at 09 26 21](https://user-images.githubusercontent.com/23533178/126457980-8dd07e5a-d78f-439e-b0db-b22a77e8bb65.png)

People have reported this as a bug but I think it's actually just been implemented wrong from the beginning.

If we go have a look at the Plugin [implementation for OverlaysWebView](https://github.com/ionic-team/capacitor-plugins/blob/main/status-bar/android/src/main/java/com/capacitorjs/plugins/statusbar/StatusBar.java#L67), it's essentially just setting a fullscreen flag.

```
            uiOptions = uiOptions | View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN;
            decorView.setSystemUiVisibility(uiOptions);
```

If you've ever played a game that asked to type your name in on Android then this is the exact same way it's done. This works for games, but for apps its obviously not the implementation you'd want.

I've talked to a couple of other Capacitor developers who have worked around this and the accepted workaround seems to use [Capacitor Keyboard plugin](https://capacitorjs.com/docs/apis/keyboard#setresizemode) to hack some padding at the bottom of the page when the keyboard is open:

```
const { isOpen, keyboardHeight } = useKeyboardState()
// other stuff ...
{isOpen && os === 'android' && (
   <div style={{ height: keyboardHeight }}></div>
)}
```

I realise there's wasn't  a lot of interest in fixing this in the past as Capacitor v3 was about to be released, but this API has been in Capacitor for a very long time and as far as I understand it **it has never worked**. 

### Platform(s)
Android

### Preferred Solution
I'm currently looking into alternative ways this can be implemented. I have **close to zero knowledge** of Android development but there has to be a better way to do this out there so I'm just going to Google my way through it until I finally manage to figure it out.

So far I've found [LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS) which I think is what I'm looking for. I still have no idea how to use it in Android but I assume I'll eventually figure it out.

Any suggestions from people that actually know what they're doing is very much appreciated. In the meantime I'd like to use this thread to post whatever I find in the hope an actual Android developer can find it.

**Comment by creativiii** [comment]
So I thought this could be fixed by doing

```
            activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
```

Unfortunately the documentation says:

```
If the window's layout parameter flags include FLAG_FULLSCREEN, this value for softInputMode will be ignored; the window will not resize, but will stay fullscreen
```

So I guess literally anything relating to Fullscreening the window will cause the Keyboard to break.

I've also found this thread of people using [WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES](https://stackoverflow.com/questions/49190381/fullscreen-app-with-displaycutout), but they're either also setting the Fullscreen flag or I just can't replicate their results.

**Comment by creativiii** [comment]
The Display Cutout API is definitely the way to go:

- https://android-developers.googleblog.com/2018/07/supporting-display-cutouts-on-edge-to.html
- https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES

Despite the documentation I haven't been able to properly get it to work. I've added the following to `public void SetOverlaysWebView`:

```
activity.getWindow().getAttributes().layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
```

Don't know if that's the correct way to set it, hopefully someone with more experience than me knows what to do with this?

**Comment by jcesarmobile** [comment]
It has not been implemented wrong, what setOverlaysWebView does is to make the app full screen and the status bar transparent. It's the only way of showing the status bar and the app content behind it.

The problem you mention is actually an Android bug that prevents the WebView from resizing when the app is in full screen.
For that @capacitor/keyboard added a config option called [resizeOnFullScreen](https://capacitorjs.com/docs/apis/keyboard#configuration) that if set to true, will resize the WebView even when the app is in full screen.
