### ISSUE TITLE
Filesystem Write to Files on iOS

### ISSUE THREAD

**Issue by allidoisace** [ionic-team/capacitor-plugins#526]
### Plugin

Filesystem

### Description

I'm assuming this isn't possible, but a file/image cannot be downloaded to the iOS's "Files". The only way I have found is to use `File Opener` to open the file in the native app and then choose to save to files by accessing the share button on the top right.

### Platform(s)

iOS

### Preferred Solution

Not exactly sure since I originally assumed that the `Documents` was the location accessible outside of the App's Internal Documents.

### Alternatives

x

### Additional Context

x

**Comment by jcesarmobile** [comment]
Files in `Documents` folder are not exposed by default, if you want them to appear in Files app you need to add this to your Info.plist

```
<key>UIFileSharingEnabled</key>
<true/>
<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>
```

**Comment by mwmw7** [comment]
> Files in `Documents` folder are not exposed by default, if you want them to appear in Files app you need to add this to your `Info.plist`
> 
> ```
> <key>UIFileSharingEnabled</key>
> <true/>
> <key>LSSupportsOpeningDocumentsInPlace</key>
> <true/>
> ```

I think this configuration for iOS should be added to [here](https://capacitorjs.com/docs/apis/filesystem)
