### ISSUE TITLE
"E/PostureManager: fail to get service" when selecting a photo from library

### ISSUE THREAD

**Issue by visiblesoft-org** [ionic-team/capacitor-plugins#527]
### Plugin(s)

@capacitor/camera: 1.0.3

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
```

### Platform(s)

Android

### Current Behavior

After upgrading to latest camera plugin version, when I try to select a photo from gallery, I'm receiving the error "Unable to process image" in chrome console and "E/PostureManager: fail to get service" in Android Studio logcat (this error is displayed every time I tried to get a photo from gallery. I'm not sure if it's related to my issue).
The app is saving photos to Pictures album by default. The error only occurs when I select a photo from Camera album. If I select a photo from Pictures album it's working fine.

### Expected Behavior

Return a photo from gallery.

### Code Reproduction

```
const options: ImageOptions = {
          quality: 90,
          allowEditing: false,
          resultType: CameraResultType.Base64,
          saveToGallery: true,
          promptLabelHeader: 'CCR Vela Mobile',
          promptLabelPhoto: 'De la biblioteca',
          promptLabelPicture: 'Hacer una foto',
          presentationStyle: 'popover'
        };
const image = await Camera.getPhoto(options);
```

### Other Technical Details

Tested in LG K40S and Samsung devices.

**Comment by visiblesoft-org** [comment]
Hi guys, another issue with the previous settings (options) is the picture is saved to the library rotated. I take the photo portrait but is saved into the library landscape.

**Comment by mattmilan-dev** [comment]
Hey @visiblesoft-org. Can you see if https://github.com/ionic-team/capacitor/issues/2060#issuecomment-890225244 helps you with this issue? Your issue looks suspiciously close to what people have been talking about here?

**Comment by jcesarmobile** [comment]
It's probably fixed by https://github.com/ionic-team/capacitor-plugins/pull/545
