### ISSUE TITLE
bug(local-notifications): Value of type 'LocalNotificationsPlugin' has no member 'shouldStringifyDatesInCalls'

### ISSUE THREAD

**Issue by jlebras** [ionic-team/capacitor-plugins#531]
### Plugin(s)
@capacitor/local-notifications@1.0.3

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.2
  @capacitor/core: 3.0.0-beta.2
  @capacitor/android: 3.0.0-beta.2
  @capacitor/ios: 3.0.0-beta.2
```

### Platform(s)

iOS

### Current Behavior

After installing the plugin, it's not possible to build with xcode. 
The following error occurs:  
```
/<PROJECT PATH>/node_modules/@capacitor/local-notifications/ios/Plugin/LocalNotificationsPlugin.swift:34:14:  
Value of type 'LocalNotificationsPlugin' has no member 'shouldStringifyDatesInCalls'
```

### Expected Behavior

The plugin does not impact the app compilation

### Code Reproduction

No particular code required, just use the plugin.

**Comment by jcesarmobile** [comment]
You are using beta 2, it was probably added in a following beta, you should update to latest capacitor (3.1.2 at the moment)

**Comment by jlebras** [comment]
> 
> 
> You are using beta 2, it was probably added in a following beta, you should update to latest capacitor (3.1.2 at the moment)

Indeed, I didn't realize it could be defined in other releases of capacitor...
Looks like it was added in beta 3, gonna update to latest capacitor, thank you !
