### ISSUE TITLE
Browser: Ability to hide location just like InAppBrowser from cordova

### ISSUE THREAD

**Issue by itsMustafa** [ionic-team/capacitor-plugins#533]
### Plugin
Browser

### Description
Please add an option to hide the location bar, just like the cordova InAppBrowser has, I'm facing some difficulties in my project as I have to download files from the webview, capacitor browser can download it, but its showing the url which is not exactly what i wanted, so plz help me get it work

### Platform(s)
Android and iOS

### Preferred Solution
Implement options similar to InAppBrowser

### Alternatives
cordova InAppBrowser

**Comment by jcesarmobile** [comment]
That's technically not possible as the native components used by the plugin (Safari View Controller on iOS and Chrome Custom Tabs on Android) don't allow that.
