### ISSUE TITLE
feat: splash screen storyboard name

### ISSUE THREAD

**Issue by sebge2emasphere** [ionic-team/capacitor-plugins#534]
### Plugin
Splash-Screen

### Description
Currently the storyboard displaying the splash screen is hardcoded to 'LaunchScreen', would it be possible to make it configurable? for instance via the info.plist. I'm not an expert at all, but I think about the property 'UILaunchStoryboardName'. 

In my case, based on build properties, the name of this splash screen changes.

### Platform(s)
iOS

**Comment by epzee** [comment]
+1  ❤️ 
We build multiple apps from the same codebase (using different targets). Would be great if capacitor could read `UILaunchStoryboardName` from the current `.plist` file being used

**Comment by sebge2emasphere** [comment]
Thanks!
