### ISSUE TITLE
PushNotifications plugin is not implemented on android

### ISSUE THREAD

**Issue by metalllus** [ionic-team/capacitor-plugins#535]
Hi, I think I am getting this message because I have the init() method in MainActivity.java and if I want to keep it there I need to add the plugin manually via the add() method. I just do not know where to find the proper name for the PushNotifications plugin symbol to use in the add(). Can you help me out here please?

I am using Ionic Capacitor 3 with the @capacitor/push-notifications @ 1.0.3

**Comment by jcesarmobile** [comment]
Should be `com.capacitorjs.plugins.pushnotifications.PushNotificationsPlugin`.

But you should remove the init method, it will probably go away in a future release.
