### ISSUE TITLE
(push notifications plugin) app crash on push notification received

### ISSUE THREAD

**Issue by metalllus** [ionic-team/capacitor-plugins#536]
### Plugin(s)
"@capacitor/push-notifications": "^1.0.3",
"@capacitor-community/fcm": "^2.0.0",

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.1.2
  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2

```
PASTE OUTPUT HERE
```

### Platform(s)
Ionic 5 
Capacitor 3 
Angular 12 
Firebase
Android native

### Current Behavior
I am testing on Android simulator API 30, no iOS at this point. I use await PushNotifications.register(), then I get the FCM token with @capacitor-community/fcm": "^2.0.0 method FCM.getToken(). Everything works fine, I get the FCM token, no problems here. I can use the token to subscribe to FCM topics, no problem, everything works. But then if I use the token to send a test push from the Firebase console the app instantly crashes (somewhere in the process of receiving the notification I guess). It does not matter if the app is in the foreground, in the background or closed, it always crashes upon receiving the notification and Android states the application keeps stopping. I have no idea how to debug this. Any ideas?

**Comment by metalllus** [comment]
fixed by removing this piece of redundant code from AndroidManifest.xml
`<service
            android:name=".java.MyFirebaseMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>`

**Comment by jcesarmobile** [comment]
Not sure where that came from, but doesn't look like it's from our push plugin, so closing.
