### ISSUE TITLE
Documentation or feature on how to share files from different source types (data uri / blob / b64)

### ISSUE THREAD

**Issue by Lxstr** [ionic-team/capacitor-plugins#539]
### Plugin
Share

### Description
I have returned a pdf via makePdf in my PWA and it can return blob, data uri or b64. What is the best way to share this please?

How do I share a file that doesn't exist on file system ie from blob or data uri or b64 and have share plugin recognise the file type?

So far it is coming up as a localhost or generic object.

Have tried many combinations or types and adding file:// even to the front but no results. Have tried 

Would appreciate any help. 

Even URL.createObjectURL(blob) doesn't seem to work.

### Platform(s)
All

### Preferred Solution
Documentation or different file input options.

Kind regards, Lex

**Comment by jcesarmobile** [comment]
there is another issue open for documenting how to share files
https://github.com/ionic-team/capacitor-plugins/issues/194

At the moment it's only possible by using the url fields, which would only work if it's a file:// url of a file on the filesystem, won't work with base64 images or blob urls. You could use the Filesystem plugin to write the PDF to disk and then use the returned url to share.
