### ISSUE TITLE
Can't do transparent status bar on ios

### ISSUE THREAD

**Issue by igoreznik** [ionic-team/capacitor-plugins#540]
### Plugin(s)
@capacitor/status-bar

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2
```

### Platform(s)
ios

### Current Behavior
Can't do transparent background on status bar



### Expected Behavior
Like in android, transparent status bar

**Comment by jcesarmobile** [comment]
iOS status bar is always transparent
