### ISSUE TITLE
Support multi-language / i18n

### ISSUE THREAD

**Issue by florianmonfort** [ionic-team/capacitor-plugins#542]
### Plugin

Camera mainly.

### Description

We need multi-language support for plug ins, now after integrating the plug ins for Capacitor 3 we find they don't support multi-language. Our app support Simplified Chinese, Cantonese and Japanese, so this looks awkward:

![lADPDhmOwdlR0FfNDIDNBaA_1440_3200](https://user-images.githubusercontent.com/1446429/128826751-eaee6058-0d04-4bf7-92b9-0effd31d68f2.jpg)

We have tried looking for something about this topic in the documentation or issues in this github but found nothing.

### Platform(s)

iOS/Android

### Preferred Solution

Ideally the plug ins come with translations out of the box.

### Alternatives

Alternatively provide an easy way to add our own translation strings with corresponding documentation.

**Comment by jcesarmobile** [comment]
We don't offer translations for plugins, but you can use the options that start with "label" to translate all those texts

https://capacitorjs.com/docs/apis/camera#imageoptions
