### ISSUE TITLE
Browser plugin can not open url inside app on Android just like IOS

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/capacitor-plugins#544]
### Plugin(s)

@capacitor/browser

### Capacitor Version

latest
```
PASTE OUTPUT HERE
```

### Platform(s)

Android

### Current Behavior

Use Browser plugin to open a url on Android, it is not opened inside app , just open out of app,

### Expected Behavior

open url can inside app instead of outside of app , like IOS,

**Comment by jcesarmobile** [comment]
Browser plugin opens the url in chrome custom tabs. It’s possible that if you don’t have chrome installed, then it would use an installed browser, but that’s out of the plugin control.

**Comment by AlwaysLoveme** [comment]
> Browser plugin opens the url in chrome custom tabs. It’s possible that if you don’t have chrome installed, then it would use an installed browser, but that’s out of the plugin control.

 
but i installed Chrome, and it is still open outside of app

**Comment by AlwaysLoveme** [comment]
Solved, the Chrome browser needs to be set as the default browser
