### ISSUE TITLE
How to upload new plugin @capacitor/zip for capacitor?

### ISSUE THREAD

**Issue by Shin-Tachibana** [ionic-team/capacitor-plugins#547]
Hi i wrote a zip/unzip file manipulation plugin for capacitor. I wonder if i can upload it as @capacitor/zip?

**Comment by tripodsgames** [comment]
https://github.com/capacitor-community

**Comment by jcesarmobile** [comment]
You can't publish it as `@capacitor/zip` in npm as we own the `@capacitor` org and it's reserved for the official plugins, platforms and tooling.

If you want to transfer the plugin ownership to capacitor-community then you could publish it as `@capacitor-community/zip`, if you want to keep the ownership you can publish with your own organization name or user name or just a plugin name such as capacitor-zip (with no `@`)

To transfer it to capacitor-community you can create an issue here https://github.com/capacitor-community/proposals/issues
