### ISSUE TITLE
bug(splash-screen, android): splash incorrectly hidden on Android

### ISSUE THREAD

**Issue by pbowyer** [ionic-team/capacitor-plugins#549]
This is a re-flagging of #300 because it was closed with a partial (iOS) fix but no Android fix, and the Android problem remains.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by pbowyer** [comment]
@Ionitron OK, challenge accepted

**Comment by f1ght4fun** [comment]
Experiencing exactly same behaviour. 
On double tapping the input in android - Splash is opened over everything.

Is there any fix for that ?

**Comment by pbowyer** [comment]
This appears to be fixed in "@capacitor/android": "^3.1.2". I see a black flash when opening the keyboard, but no longer my splash screen.

**Comment by mozhn** [comment]
The problem still continues. Why was it closed?
