### ISSUE TITLE
Filesystem: undefined is not a constructor (evaluating 'new Cap.Exception('')') on filesystem operation exception

### ISSUE THREAD

**Issue by b-huessner** [ionic-team/capacitor-plugins#553]
### Plugin(s)
@capacitor/filesystem: 1.0.2

### Capacitor Version
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2
```

### Platform(s)
ios, android

### Current Behavior
When a filesystem operation failes, for example creating a file in a directory that doesnt exist, catch blocks do not work, because there is an exception happening in the native-bridge.js file.
It is tried to create a new Cap.Exception, but Cap.Exception is undefined, so this throws an exception, which is not handled and the code execution is stopped.

### Expected Behavior
My try {} catch (){} blocks should work

### Additional Context
Here is the code that throws the exception in the native-bridge.js, marked with <----:
```javascript
cap.fromNative = result => {
                var _a, _b;
                if (cap.isLoggingEnabled && result.pluginId !== 'Console') {
                    cap.logFromNative(result);
                }
                // get the stored call, if it exists
                try {
                    const storedCall = callbacks.get(result.callbackId);
                    if (storedCall) {
                        // looks like we've got a stored call
                        if (result.error) {
                            // ensure stacktraces by copying error properties to an Error
                            result.error = Object.keys(result.error).reduce((err, key) => {
                                // use any type to avoid importing util and compiling most of .ts files
                                err[key] = result.error[key];
                                return err;
                            }, new Cap.Exception('')); <----
                        }
                        if (typeof storedCall.callback === 'function') {
.
.
.
```
If I replace new Cap.Exception('') with an empty Object ({}), it works fine. But since the file is not committed to git, this is not a workable solution.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by b-huessner** [comment]
Okay, while trying to reproduce the issue in a fresh project I figured out what the problem was.
Apparently I somehow los the import for the capacitor.js file from my index.html.

Kinda curious, that that only effects some properties of the global Capacitor Object, but here we go.
Closing the Issue
