### ISSUE TITLE
Push Notification body missing in pushNotificationReceived and pushNotificationActionPerformed

### ISSUE THREAD

**Issue by sectort** [ionic-team/capacitor-plugins#558]
### Plugin(s)
push-notifications

### Capacitor Version
3.1.2

### Platform(s)
Android

### Current Behavior
In `PushNotifications.addListener` `pushNotificationReceived` and `pushNotificationActionPerformed` we receive object `PushNotificationSchema` and `ActionPerformed` with the push notification data.
For Android, both the object does not have field `body`.
The data of `body` is displayed properly in the notification bar but I cannot read it in the app.

### Expected Behavior
The data of field `body` should come in object `PushNotificationSchema` and `ActionPerformed` like I get in IOS

### Code Reproduction
```
PushNotifications.addListener('pushNotificationReceived',
      (notification: PushNotificationSchema) => {
        console.log(notification.body);
      }
    );
```

**Comment by jcesarmobile** [comment]
That's an OS limitation, if you use notification payload and the app is in the background then the OS will handle the notification, and when you tap the notification, the OS doesn't send the title nor body back to the app.
If the app is open when the notification is received, then the notification is not displayed by the OS and both the title and body are available.

https://firebase.google.com/docs/cloud-messaging/concept-options#notifications
