### ISSUE TITLE
Migrate to Splash Screen API

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#561]
### Plugin
splash-screen

### Description
When targeting Android SDK 31, a new Splash Screen API can be used

https://developer.android.com/about/versions/12/splash-screen-migration?hl=es

Some features might not be possible with that API.

### Platform(s)
android

**Comment by mcfarljw** [comment]
I just got a new device with Android 12 (Samsung Galaxy S22) and thought I was going crazy when seeing two splash screens. Does anybody know of any quick and relatively painless ways of disabling the Ionic Capacitor splash screen for SDK 31+ devices while this plugin gets updated?

**Comment by maxcodefaster** [comment]
There seems to be a workaround, at least for the cordova plugin: https://github.com/apache/cordova-plugin-splashscreen/issues/311#issuecomment-938598941

**Comment by mster81** [comment]
Full disclosure, I don't know if this is the correct solution here but doing some testing and adding this to the 'styles.xml' 

<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@drawable/splash</item>
        <item name="android:windowIsTranslucent">false</item>
        <item name="android:colorBackground">#ff0000</item>
    </style>

Allows me to control the first splash, from a background color that is. If you don't want to have the first splash screen ( one where the icon shows up ) then you can set windowistranslucent to true. 

If its an acceptable approach, then baking it into the plugin might be nice to 

1) Have the option to 'show' icon splash 
2) Set icon splash bg-color 

If this wildly incorrect and should not be done this way I apologies :D

**Comment by bhandaribhumin** [comment]
For capacitor project this is the fix :)

![Screenshot 2022-04-29 at 8 05 38 PM](https://user-images.githubusercontent.com/3336047/165966619-4d22853a-da7d-42cb-982c-190040e76bf7.png)
