### ISSUE TITLE
Msg: Error: "Camera" plugin is not implemented on android

### ISSUE THREAD

**Issue by jeremyrajan** [ionic-team/capacitor-plugins#562]
### Plugin(s)
![image](https://user-images.githubusercontent.com/2890683/130563758-661c0745-d653-41ba-a7d8-10f9e37d9f9d.png)

### Capacitor Version
![image](https://user-images.githubusercontent.com/2890683/130563814-dddc38b8-17e3-4873-bdd9-a76e1185fc3f.png)

### Platform(s)
Android

### Current Behavior
Initiating `Camera.getPhoto` gives `Msg: Error: "Camera" plugin is not implemented on android`.  This works fine on web.

### Expected Behavior
Camera view

### Code Reproduction
![image](https://user-images.githubusercontent.com/2890683/130563980-33535d66-236f-479e-9efc-1ee1f988273a.png)

I have upgraded to capacitor 3 and I am not registering in MainActivity.

### Other Technical Details
Using Android Studio and running on Samsung Note 10.

### Additional Context
![image](https://user-images.githubusercontent.com/2890683/130564092-4159ee8c-cf7e-4cba-b15f-cc1b9ac5a45e.png)

I have added capacitor core in main.ts. I am using Ionic. Followed the steps here: https://stackoverflow.com/questions/67226076/capacitor-3-0-upgrade-plugins-not-implemented-exception-nx-monorepo

Please let me know, if I am missing anything :)

Thanks! :)

**Comment by jcesarmobile** [comment]
check the troubleshooting guide, there is a section about things that can cause the "plugin not implemented"

https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented

**Comment by tigohenryschultz** [comment]
Also  getting this error after updating my Capacitor to version 3
