### ISSUE TITLE
Plugin Filesystem not working on WebWorker Android

### ISSUE THREAD

**Issue by tachibana-shin** [ionic-team/capacitor-plugins#564]
Hi ionic team,

I a'm using Capacitor 3

I am trying to use Filesystem in Webworker but it only works on web neend.  Doesn't work on Android

No error

What happend?

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by tachibana-shin** [comment]
Tôi đã tìm ra giải pháp tạm thời là sử dụng [capacitor-fs](https://npmjs.org/package/capacitor-fs) và [workercom](https://npmjs.org/package/workercom) để đặt các hàm hệ thống trên client và tạo proxy cho webworker gọi nó

**Comment by jcesarmobile** [comment]
Not sure if it could be related to plugins not working in service workers, it's documented with another workaround
https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented

**Comment by danbaechtold** [comment]
> Not sure if it could be related to plugins not working in service workers, it's documented with another workaround
> https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented

**Yes! You where right, I'd missed that one - thank you so much!! :)**

(removing the PWA's service worker registration and when isNative did it).
