### ISSUE TITLE
Deeplink issue on Facebook, Twitter, Youtube etc

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor-plugins#567]
### Plugin(s)
https://capacitorjs.com/docs/apis/app

### Capacitor Version

```
@capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.0.2
  @capacitor/cli: 3.0.2
  @capacitor/android: 3.0.2

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Deeplinks are NOT working from Facebook, Twitter, Hangouts, Youtube etc. But they are working from Gmail and Some other Apps. 

### Expected Behavior
Deeplinks Should Be working from ALL apps. 

### Code Reproduction
```
App.addListener('appUrlOpen', (event: URLOpenListenerEvent) => {
      this.zone.run(() => {
        const slug = event.url.split("/tabs").pop();
        if (slug) {
          this.general.goToPage('/tabs' + slug);
        }
      });
    });
```

### Other Technical Details
I have testing it on Android Currently. No idea About IOS but I will test it on IOS soon.

**Comment by pencilcheck** [comment]
What should we do to listen to if the app was already opened and people launch the app with redirect url?
