### ISSUE TITLE
@capacitor/keyboard iOS resizing not working

### ISSUE THREAD

**Issue by shu-harmoney** [ionic-team/capacitor-plugins#580]
### Plugin(s)

@capacitor/keyboard

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0
```

### Platform(s)

iOS

### Current Behavior

Since the move I did from ionic plugin (`cordova-plugin-ionic-keyboard`) to capacitor 3 (`@capacitor/keyboard`), the resize native isn't working anymore on iOS. The resize is not happening at all, meaning that the web view isn't resizing. 

### Expected Behavior

Resize is working as it was previously using the ionic plugin

### Code Reproduction

https://github.com/sebastien-A256/ionic-capacitor-keyboard-bug

### Additional Context

Here is an error that I can see in the Xcode console the first time that the keyboard is opened:
```
2021-08-30 18:14:34.989657+0200 App[86433:15896467] API error: <_UIKBCompatInputView: 0x105418470; frame = (0 0; 0 0); layer = <CALayer: 0x281d3f8c0>> returned 0 width, assuming UIViewNoIntrinsicMetric
2021-08-30 18:14:34.989762+0200 App[86433:15896467] API error: <_UIKBCompatInputView: 0x105418470; frame = (0 0; 0 0); layer = <CALayer: 0x281d3f8c0>> returned 0 width, assuming UIViewNoIntrinsicMetric
```

Here is a copy of my capacitor.config.ts file:

```
import {CapacitorConfig} from '@capacitor/cli';

const config: CapacitorConfig = {
    appId: 'xxxxxx',
    appName: 'xxxxxx',
    bundledWebRuntime: false,
    webDir: 'www',
    plugins: {
        SplashScreen: {
            launchShowDuration: 100,
            launchAutoHide: true,
        },
        Keyboard: {
            style: 'dark'
        }
    },
    cordova: {}
};

// @ts-ignore
export = config;
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sebastien-A256** [comment]
You can find here a public repo with the issue in it. 
in the Tab One of the App you'll see that the view isn't scrolling, there is the error in the Xcode console. 

https://github.com/sebastien-A256/ionic-capacitor-keyboard-bug

**Comment by jcesarmobile** [comment]
The resize is working as expected, what you are describing has nothing to do with the resizing.

Capacitor has never moved the input fields to make them visible when the keyboard appears, that's up to the developer, they can use the keyboard events that contain the keyboard size to reposition or scroll their fields and make them visible.

It works automatically for ion-input and ion-textarea fields as ionic contains code that listen for the keyboard events and reposition the fields for you, but doesn't work for regular html fields.

iOS by default moves the input fields, but it does it by moving the whole WebView up, which in Ionic apps makes the header to disappear and the tab bar to be visible, which is not desired.

So, if you can, move to ion-input, or if you can't listen for the keyboard events and reposition your fields or scroll your page to make it visible.

**Comment by sebastien-A256** [comment]
That honestly doesn't look to be a satisfying answer and a major regression...
Previously using Ionic and Cordova lib this was working very well and automatically without the need for the developer to handle this, including in regular input and not ion-input. Why did you decide to change this ?

**Comment by jcesarmobile** [comment]
As far as I know it has always worked like this, even in Cordova apps if using cordova-plugin-ionic-keyboard, as it's the plugin what creates this behaviour and Capacitor Keyboard plugin is based on that plugin.

**Comment by sebastien-A256** [comment]
I've got 1 app in front of me that is doing the auto scroll with regular input, using latest ionic version and the cordova-plugin-ionic-keyboard. I do get your point that it's the problem of the developer although as it was working previously I was hoping that this will also work using Capacitor. 
I will try to change to ion-input and see if that improve the things. 

Thanks for the answers already, and if you plan to make this happen in the future, don't hesitate to ping me 🙂

**Comment by jcesarmobile** [comment]
I enabled cordova on the sample app you provided and it doesn't scroll, so your other app might be doing something else.

**Comment by sebastien-A256** [comment]
I moved to ion-input, it was a very minor change that only required in my app a tiny css update. So thank you for your assistance. 
I won't elaborate more as I consider my issue as solved. Thanks again !
