### ISSUE TITLE
Android Geolocation.getCurrentPosition() throws 'location unavailable' error

### ISSUE THREAD

**Issue by vanessag** [ionic-team/capacitor-plugins#588]
### Plugin(s)
Geolocation 1.0.2

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android (both device and emulator)

### Current Behavior
Call Geolocation.getCurrentPosition() and say yes enable location permissions and observe the response is 'location unavailable' error. Plugin fails here in Geolocation.java

```
  public void onLocationAvailability(LocationAvailability availability) {
      if (!availability.isLocationAvailable()) {
          resultCallback.error("location unavailable");
          clearLocationUpdates();
      }
  }
```
availability.isLocationAvailable() always returns false even though I have Locations enabled on the device. I've tried toggling it off and on, restarting the device, etc. I've also noticed I have the same result on a simulator so I don't think the issue is related to specifically to my device. This is also functionality that used to work correctly.

I also have correct permissions in AndroidManifest
```
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-feature android:name="android.hardware.location.gps" />
```
What am I missing? How do I get the location to be available?

### Expected Behavior
Geolocation.getCurrentPosition() should return location without an error when location permission enabled.

### Other Technical Details
```
Ionic:

   Ionic CLI                     : 6.17.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.2.2
   @angular-devkit/schematics    : 12.0.3
   @angular/cli                  : 12.2.2
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : 3.2.0
   @capacitor/core    : 3.2.0
   @capacitor/ios     : 3.2.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.5 (/usr/local/Cellar/node@14/14.17.5/bin/node)
   npm    : 6.14.14
   OS     : macOS Big Sur
```

**Comment by jcesarmobile** [comment]
check https://github.com/ionic-team/capacitor/issues/4962
