### ISSUE TITLE
Camera (capacitor 3 @capacitor/camera) getPhoto() does not break promise on cancel (web)

### ISSUE THREAD

**Issue by arnotixe** [ionic-team/capacitor-plugins#596]
### Plugin(s)

@capacitor/camera 1.0.4

### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

[success] Android looking great! 👌
[error] Xcode is not installed

### Platform(s)

web

### Current Behavior

Web: cancelling the File Upload box yields neither image nor throws error. Seems the promise never returns at all.

### Expected Behavior

Web: Expected cancelling the File Upload box should return either a null/empty string image or throw an error.

### Code Reproduction

```
  this.spinner=true;
  Camera.getPhoto({options})
      .then((image) => {
        this.spinner=false;
      })
    .catch(error => {
       this.spinner=false;
   });
```
In this example, this.spinner never goes false when clicking Cancel in the file upload box.

### Other Technical Details

tested android and it DOES break the promise with error "No image picked"
(not tested ios yet)

**Comment by Sh1n1x** [comment]
You must use async:

```
async uploadImage() {
 this.spinner=true;
 await Camera.getPhoto({ options }).then(async image => { 
  this.spinner=false;
 }).catch(error => {
  this.spinner=false;
 });
}
```

**Comment by arnotixe** [comment]
yep. tried that too, but async + await makes no difference in my web tests anyway :/

(I'm not an expert, but think await more or less returns a Promise, right? The reason I prefer writing code as promises is I can choose to parallelize them with Promise.all([array of promises]). While I use await more for just "syncing" async calls here and there.

**Comment by jcesarmobile** [comment]
Sadly there is no event fired when the user clicks cancel on the input file dialog, so nothing we can really do about it.

On iOS and Android it doesn't use an input file, so the error is not present there.

**Comment by arnotixe** [comment]
ah ok I guess the bug can be canceled as it is not really depending on Capacitor code then. Seems to work fine for ios and android native anyway, and isn't a major problem for me. I have a spinner indicating the upload is in progress, and stop spinning it as soon as it has been uploaded 100% (or if the upload was cancelled). Since the promise neither succeeded nor failed, it is never stopped. But that can be worked around of course, no big deal.
![image](https://user-images.githubusercontent.com/500938/132348488-f166b489-3c52-480c-a118-34ab5562b85e.png)
