### ISSUE TITLE
Embedded WebPage directly in Ionic App

### ISSUE THREAD

**Issue by MelCCI** [ionic-team/capacitor-plugins#597]
Hi, I  would like to embed a WepPage directly in ionic without opening a new tab (I want to do exactly like iframe, but without using it because I have X-Frame-Options error and it is in addition very little recommended)
InAppBrowser have approximately the same problem that capacitor, but it's maybe better to do it ?

How can I do it simply ? (I've already tried to add allowNavigation on capacitor.config.json)

Thank you

**Comment by jcesarmobile** [comment]
Please, use the github issues only to report issues, if you have questions you can use the ionic forums or the discussions feature in capacitor repository.
