### ISSUE TITLE
[Android] Denying Camera permission returns wrong permission status

### ISSUE THREAD

**Issue by mmlodawskiLC** [ionic-team/capacitor-plugins#605]
### Plugin(s)

Camera v1.0.5

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/ios: 3.2.2

[success] iOS is looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android 11

### Current Behavior

When a user is for the first time asked to grant camera permission and denies it, the `PermissionStatus.camera` object is equal to a `prompt-with-rationale` text. After asking the second time and denying it, the status is correct and equals `denied`.

### Expected Behavior

After denying Camera permission, the `PermissionStatus.camera` should be `denied`.

### Code Reproduction

```
    import { Camera } from "@capacitor/camera";

    Camera.requestPermissions({ permissions: ['camera'] }).then(status => console.log('status: ' + status.camera));
```

### Other Technical Details

`npm --version` output: `6.14.15`

`node --version` output: `v14.17.6`

**Comment by jcesarmobile** [comment]
This is how Android permissions work, if you ask for permissions and the user denies it, then the next status is `prompt-with-rationale`, which means you should show some text to the user before requesting the permission again to try to convince them to grant the permission.

In Android 10 and older it will return `prompt-with-rationale` until the user grants the permission or chooses "Do not ask again", while in Android 11+ the second time it's denied acts as "Don't ask again" so it returns denied on the following requests.

**Comment by mmlodawskiLC** [comment]
Actually, it differs from Android SDK. On Android, you need to call `shouldShowRequestPermissionRationale()` to check if you need to show an educational UI to the user. Asking or checking for permission always returns `PERMISSION_GRANTED` or `PERMISSION_DENIED`. Here it looks like two separate methods combined into one.

Also, does the iOS behavior is the same? I mean, is `prompt-with-rationale` only for Android or it can be returned also in an iOS app?

**Comment by jcesarmobile** [comment]
Yeah, Capacitor internally uses `shouldShowRequestPermissionRationale` to return the `prompt-with-rationale` status.

On iOS `prompt-with-rationale` as there is no native equivalent for `shouldShowRequestPermissionRationale`, and most permissions will only be asked once.
