### ISSUE TITLE
feat: Web Device plugin should store the uid in a cookie instead of local storage?

### ISSUE THREAD

**Issue by dminkovsky** [ionic-team/capacitor-plugins#606]
### Description

A few months ago, Apple announced that Safari will expire localStorage entries for domains that are inactive for 7 days. 

Maybe device.ts should store the uid in a cookie instead of localStorage?

### Platform(s)

* web

**Comment by jcesarmobile** [comment]
By my understanding of the link, cookies are already wiped after a period of time (before this change), this will be an addition that will cause also localStorage to be wiped too. 
We won't be changing anything, if the current identifier is wiped the plugin will generate a new one, Apple does those things to prevent apps from tracking users, so if developers are using device plugin to track users they will have to deal with the fact that the id can change.
