### ISSUE TITLE
Improve Camera.getPhoto@capacitor/camera documentation 📸

### ISSUE THREAD

**Issue by rpavez** [ionic-team/capacitor-plugins#607]
### Plugin
@ionic/camera - Camera.getPhoto()

### Description
Spent a lot of time trying to figure out how to trigger the native camera and it wasn't until read through the source code and w3c input file specs that understood how use make `Camera.getPhoto()` to just trigger the native camera.

### Platform(s)
web

### Preferred Solution
Improve documentation (https://github.com/ionic-team/capacitor-plugins/tree/main/camera#imageoptions) to clearly explain that prop `source` should be anything but `CameraSource.Photos || CameraSource.Prompt`  to trigger the native camera (and not select from library) by using `capture` when using `webUseInput: true`. This is a non-documented behavior that can only be discovered by reading through the code here https://github.com/ionic-team/capacitor-plugins/blob/main/camera/src/web.ts#L146

**Comment by jcesarmobile** [comment]
Photos I thought CameraSource.Camera was clear enough to describe that it uses the camera, while CameraSource.Photos will let you pick an existing photo and CameraSource.Prompt will prompt you with both options, but will add little descriptions for each.

**Comment by rpavez** [comment]
It's not clear enough cause there is not option for camera only without
prompt by using `<input type="file" accept="image/*" capture>`
