### ISSUE TITLE
Remove all but newest notification and differences between removeAllDeliveredNotifications and removeDeliveredNotifications

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-plugins#610]
## Bug Report

Bug report for Capacitor Push Notifications plugin

### Plugin(s)

- Capacitor Push Notifications

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/ios: 3.2.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

Package JSON:

```
"dependencies": {
  "@capacitor/android": "3.2.2",
  "@capacitor/camera": "1.0.5",
  "@capacitor/core": "3.2.2",
  "@capacitor/ios": "3.2.2",
  "@capacitor/network": "1.0.3",
  "@capacitor/push-notifications": "1.0.4",
  "@capacitor/splash-screen": "1.1.2",
  "@capacitor/status-bar": "1.0.3",
  "@capacitor/storage": "1.1.0",
  "@nuxt/components": "2.2.1",
  "@nuxtjs/auth-next": "5.0.0-1624817847.21691f1",
  "@nuxtjs/axios": "5.13.6",
  "@nuxtjs/dayjs": "1.4.0",
  "@nuxtjs/dotenv": "1.4.1",
  "@nuxtjs/sentry": "5.1.3",
  "@robingenz/capacitor-badge": "1.2.0",
  "@sentry/capacitor": "0.4.0",
  "core-js": "3.16.2",
  "nuxt": "2.15.8",
  "vee-validate": "3.4.12",
  "vue-axios": "3.2.5",
  "vue2-touch-events": "3.2.2"
},
"devDependencies": {
  "@capacitor/cli": "3.2.2",
  "@nuxtjs/tailwindcss": "4.2.1",
  "@tailwindcss/forms": "0.3.3",
  "fibers": "5.0.0",
  "postcss": "8.3.6",
  "sass": "1.35.2",
  "sass-loader": "10.2.0"
}
```

### Platform(s)

- iOS
- Android

### Current Behavior

- When calling the `removeAllDeliveredNotifications` and `removeDeliveredNotifications` since they're both plural, implying that they're both going to remove all notifications. I'd like to remove all the notifications from a group apart from the newest one.

**Comment by jcesarmobile** [comment]
`removeDeliveredNotifications` will remove the notifications you pass to it, so you'll have to get the notifications first, then filter by group, and pass the result to `removeDeliveredNotifications`

**Comment by sts-ryan-holton** [comment]
@jcesarmobile Ok brilliant, I'm currently on iOS, have received a bunch of notifications to my device, they're in my notification centre, but when calling `getDeliveredNotifications` from a page, I'm not getting any results?

https://capacitorjs.com/docs/apis/push-notifications#getdeliverednotifications

**Comment by jcesarmobile** [comment]
Can you report a new issue about that and provide a sample app?
