### ISSUE TITLE
backButton event on iOS

### ISSUE THREAD

**Issue by wyattades** [ionic-team/capacitor-plugins#617]
### Plugin
@capacitor/app

### Description
The `backButton` event should be supported on iOS with the same [functionality as Android](https://capacitorjs.com/docs/apis/app#addlistenerbackbutton) i.e. subscribing to the listener in JS should enable "swipe left to go back" functionality and swiping left should emit the `backButton` event and prevent the default browser-back behavior.

### Platform(s)
iOS

### Preferred Solution
I don't really know Swift, but the below code seems to work. I'm just not sure how to emit the `backButton` event, and this functionality would ideally be part of the Capactor App plugin.

```swift
class MyViewController: CAPBridgeViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        let swipeRightRecognizer = UISwipeGestureRecognizer(target: self, action: #selector(handleSwipe(recognizer:)))
            
        swipeRightRecognizer.direction = .right

        webView?.addGestureRecognizer(swipeRightRecognizer)
    }
    
    @objc private func handleSwipe(recognizer: UISwipeGestureRecognizer) {
        // TODO: emit CapacitorApp `backButton` event here
    }
}
```

Downsides:
- you don't get a nice animation like you do with  `webview.allowsBackForwardNavigationGestures = true`. However, I'm not sure if it's possible to override the swipe actions with `webview.allowsBackForwardNavigationGestures = true`.
- Might not work on older iOS devices that don't support swipe? (I'm not very familiar with iOS). For these devices, maybe there could be a native back button in the status bar, or users could just implement their own button in HTML if they wanted.

### Alternatives
We tried overriding the `CAPBridgeViewController` controller ([docs](https://capacitorjs.com/docs/ios/viewcontroller)) but we aren't sure how to emit an event to JavaScript. Any help with that would be a good solution in the meantime.

**Comment by jcesarmobile** [comment]
Thanks for the issue, but I don't think something like this belongs to the App plugin.

Adding a custom `UISwipeGestureRecognizer` seems hacky and can cause problems to users that have enabled `allowsBackForwardNavigationGestures`.

You can create your own plugin that does that, instead of using `viewDidLoad` from a custom view controller, use the `load()` method of a `CAPPlugin`, and since it's a `CAPPlugin` you can call notifyListeners from that class.
