### ISSUE TITLE
Local Notifiaction at, repeates

### ISSUE THREAD

**Issue by mkrumboeck** [ionic-team/capacitor-plugins#619]
As explained here: [capacitor local notification](https://capacitorjs.com/docs/apis/local-notifications)
Undere the attribute you can see in the description: "Repeat delivery of this notification at the date and time specified by at. Only available for iOS and Android"
I have using at with repeats and it is not working.
Last time i got the answer it would not repeats if i have set a year in my date object but it is not possible do create a date object without a year.

I am not alone with this problem as you can see
https://forum.ionicframework.com/t/local-notification-does-not-repeats/215105

**Comment by jcesarmobile** [comment]
Please, don’t create duplicated issues, I already told you at takes a date as parameter, so can’t repeat unless you build a Time Machine and go back in time so the date is the same again.

**Comment by cytrics** [comment]
Hello,
so, an answer from the developer with time machine etc is absolutely not helpful and also not professional. I have the same problem with the plugin! 
And that it is a problem with the plugin shows yes that it works in IOS and just not under Android. And how should I create a scheduled notification if I should not or can not specify a date? Nonsense...
Until ionic, everything went stress-free, even under Android!!!
Now it is unfortunately not possible to use this on Android:

"schedule: { on: { hour: parseInt(this.hourPush) , minute: parseInt(this.minutePush) }, every: 'day', allowWhileIdle: true, repeats: true }," ... 

On IOS it works flawlessly. On Android just nothing happens...
Under ionic, as I said, the whole thing ran under both platforms:

@ionic-native/local-notifications/ngx

...

 this.localNotifications.schedule(
              { id: randomId,
                title: this.translate.instant('GLOBAL.PUSHMESSAGE_PART_3'),
                text: message,
                trigger: { every: { hour: parseInt(this.hourPush) , minute: parseInt(this.minutePush) } },
                badge: 0,
              },             
            ); 

So a rework of the plugin would be appropriate....

BR,

**Comment by cytrics** [comment]
I think I need to correct myself....
After retesting it now works on Android! Apparently has already been improved here!

**Comment by cytrics** [comment]
No, it does not work :-(
