### ISSUE TITLE
[@capacitor/push-notifications] analytics label and push title are not passed to the capacitor plugin on android

### ISSUE THREAD

**Issue by StErMi** [ionic-team/capacitor-plugins#625]
### Plugin(s)
@capacitor/push-notifications

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2
```

### Platform(s)
 - android

### Current Behavior

Both the Firebase `Analytics Label` and `Push notification title` are not passed to the `Notification Object`

### Expected Behavior

I should be able to get that info

### Additional Context

When I receive the notification I've dumped the JSON data that the plugin is passing back to me (`PushNotificationSchema`)

iOS

```
{
  "badge": 1,
  "body": "test push",
  "subtitle": "",
  "data": {
    "google.c.a.udt": "0",
    "google.c.a.e": "1",
    "google.c.a.c_id": "REDACTED",
    "google.c.sender.id": "REDACTED",
    "google.c.a.ts": "REDACTED",
    "gcm.n.e": "1",
    "google.c.a.c_l": "test push",
    "google.c.a.m_l": "test-analytics-label",
    "utm_medium": "medium_ios",
    "google.c.fid": "REDACTED",
    "aps": {
      "mutable-content": "1",
      "alert": {
        "body": "test push",
        "title": "test push"
      }
    },
    "gcm.message_id": "REDACTED",
    "utm_source": "source_ios",
    "title": "test subtitle",
    "utm_campaign": "campaign_ios"
  },
  "title": "test push",
  "id": "REDACTED"
}
```

it seems that on iOS the analytics label is inside `data['google.c.a.m_l']` and the title inside `title`. But on Android, I get this JSON

```
{
  "id": "REDACTED",
  "data": {
    "google.delivered_priority": "high",
    "google.sent_time": "REDACTED",
    "google.ttl": "REDACTED",
    "google.original_priority": "high",
    "utm_campaign": "campaign_ios",
    "from": "REDACTED",
    "collapse_key": "REDACTED",
    "utm_medium": "medium_ios",
    "utm_source": "source_ios"
  }
}
```

as you can see there's no info about the analytics label that should be `test-analytics-label` nor the title of the push that should be `test push`.

So, the question is, do you know if this problem is on the plugin side that has not been implemented correctly the part where it passes down the native information from the push to the react/javascript part, or if the source of the problem is directly Firebase that is not providing that information for the Android push notification?

**Comment by jcesarmobile** [comment]
The plugin just uses a for loop for every key on the object sent, so if it's not there it's probably some problem on Firebase and not in the plugin.

For title and body, it happens when the app is in background/closes, the system handles the notification to display it, but when tapped the information is not passed to native
https://github.com/ionic-team/capacitor-plugins/issues/558#issuecomment-921043483
