### ISSUE TITLE
bug: Keyboard overlaps ion-input when used with StatusBar.overlay as true

### ISSUE THREAD

**Issue by manishoswal** [ionic-team/capacitor-plugins#626]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.2.0

  @capacitor/core: 2.2.0

  @capacitor/android: 2.2.0

  @capacitor/electron: 2.2.0

  @capacitor/ios: 2.2.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/cli 2.1.2

  @capacitor/core 2.1.2

  @capacitor/android 2.2.0

[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

The android keyboard overlay the input on the screen when the StatusBar.overlay is set to true

### Expected Behavior
The screen should scroll to the focused input. 

### Example Code or Repo

1. Go to any screen with ion-inputs
2. Click on the input sometimes
3. See error

![image](https://user-images.githubusercontent.com/2525704/84349544-2b3ca580-abd5-11ea-91d9-40f25803ebd9.png)

### Additional Context
This has been resolved in the ionic cordova keyboard plugin by adding a resizeOnFullscreen preference. Do we have anything like this in capacitor keyboard.

**Comment by mayankkataria** [comment]
Same issue. Any update for capacitor?
