### ISSUE TITLE
Capacitor Browser - Universal link callback not triggered during auth flow 

### ISSUE THREAD

**Issue by sniii** [ionic-team/capacitor-plugins#628]
## Bug Report
We are deploying an Ionic iOS app and using MSAL.JS as a means to do SSO login towards Microsoft Azure services.
We have configured Azure to accept a universal link as redirect URI and have successfully implemented MSAL to work with a universal link redirect uri, such that it automatically closes the Safari system browser and returns back to our app and trigger the `appUrlOpen` method upon successfully authentication.

```
    App.addListener('appUrlOpen', ({ url }) => {
        if (isRedirectUri(url)) {
            const authCodeFragment = parseAuthCodeFragment(url)
            notifyMsalRedirectCallback(authCodeFragment)
        }
    })
```

The flow is as follows:

1. User starts app.
2. App detects user is not authenticated and opens an external Safari system browser in order to begin the SSO authentication flow.
3. The authentication completes on Microsoft's side.
4. Microsoft redirects to our redirect URI (a universal link).
5. The external link is recognised and focus is returned back to our app.
6. The `appUrlOpen` method is called with the authentication data as part of the URL fragment.

The issue however, is that we'd like to do this entire flow using the `@capacitor/browser` InAppBrowser (SFSafariViewController), such that the user will not experience the app temporarily losing focus by opening the external system browser.

We have tried to configures MSAL.JS to open the URL using `Browser.open({ url })`, and the SSO flow completes, but never triggers the `appUrlOpen` callback method in our app ?

### Plugin(s)
@capacitor/browser

### Capacitor Version
```
  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/ios: 3.2.3
  @capacitor/browser: 1.0.3
```

### Platform(s)
iOS

### Current Behavior
Using MSAL.JS, we configure the library to open the login URL using `Browser.open({ url })`.
The SSO login flow completes "successfully" inside the InAppBrowser, but stalls (and the InAppBrowser never closes) upon redirecting to our universal link redirect URI.

The `App.addListener('appUrlOpen', ({ url }) =>...` callback method is never triggered, and thus the app never receives the authentication data as part of the completed SSO auth flow, making the user unable to continue further on into the app.

### Expected Behavior
According to the Capacitor Browser documentation:

```
On iOS, this uses SFSafariViewController and is compliant with leading OAuth service in-app-browser requirements.
```

So we would expect Capacitor Browser plugin to behave in the same way as if opening an external Safari browser to complete an Azure SSO OAuth flow with a universal link as the redirect URI.

1. User starts app.
2. App detects user is not authenticated and opens an InAppBrowser in order to begin the SSO authentication flow.
3. The authentication completes on Microsoft's side.
4. Microsoft redirects to our redirect URI (a universal link).
5. **ERROR**: The InAppBrowser doesn't automatically close, like the external System browser does, but just displays a blank page (our universal link URL).
6. **ERROR**: The `appUrlOpen` method is never called with the authentication data as part of the URL fragment.

**Comment by jcesarmobile** [comment]
According to this Apple radar, that's how SafariViewController works https://openradar.appspot.com/32840565

If you register an app scheme and use it for the redirect, it should work, but universal links will navigate inside the browser instead of closing the app.
