### ISSUE TITLE
When using capacitor camera, requesting permissions on web fails.

### ISSUE THREAD

**Issue by hidegh** [ionic-team/capacitor-plugins#629]
## Bug Report
When using capacitor camera, requesting permissions on web fails.
**As IONIC and CAPACITOR is meant to support HYBRID apps, this is considered to be a bug!**

### Plugin(s)
"@capacitor/camera": "^1.0.5"

### Capacitor Version
"@capacitor/camera": "^1.0.5"

### Platform(s)
Windows, Chrome

### Current Behavior
When trying to request permission on a web, i get an error:
```
ERROR Error: Uncaught (in promise): Error: Not implemented on web.
Error: Not implemented on web.
    at CameraWeb.unimplemented (index.js:376)
    at web.js:187
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3)
```

### Expected Behavior
https://whatwebcando.today/permissions.html

### Code Reproduction
```
   import { Camera } from '@capacitor/camera';
   
   public isAvail(){
    const isCameraAvailable = Capacitor.isPluginAvailable('Camera');
    console.log("isAvail", isCameraAvailable)
  }

  public async request() {
    console.log("request",  await Camera.requestPermissions());
  }

  public async check() {
    console.log("check", await Camera.checkPermissions(/*{ permissions: ["photos", "camera" ]}*/));
  }
```

### Other Technical Details
N/A

### Additional Context
N/A

**Comment by jcesarmobile** [comment]
On web it’s not possible to request permissions yet, the only way is trying to use a feature that requires the permission, so if you try to take the picture it will request the permission the first time. But we won’t be adding calls to the APIs that request the permission just to trigger the permission call in request permission

**Comment by hidegh** [comment]
@jcesarmobile
May I ask why not? **I mean it is possible and it would remove an unnecessary if/then from the code - just to avoid error.**

**Comment by jcesarmobile** [comment]
All plugins request permissions when needed, so if you want to remove unnecessary ifs just don’t use code to request permissions, the plugin will request permissions if the plugin method you called needs the permissions and they are not requested yet.
