### ISSUE TITLE
@capacitor/filesystem doesn't allow me to access my filesystem with Electron

### ISSUE THREAD

**Issue by moltenice** [ionic-team/capacitor-plugins#632]
### Plugin(s)

    "@capacitor/filesystem": "^1.0.3"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
```

### Platform(s)

Electron (Mac OS in my example)

### Current Behavior

```typescript
await Filesystem.readdir({
  directory: Directory.ExternalStorage,
  path: "~"
})
```

Uncaught (in promise) Error: Folder does not exist.

### Expected Behavior

It runs readdir against my home folder.

### Code Reproduction

Make a standard Ionic Capacitor app. Install `@capacitor-community/electron`.

```html
<IonButton onClick={dir}>Run it</IonButton>
```

```typescript
const dir = async () => {
  const result = await Filesystem.readdir({
    directory: Directory.ExternalStorage,
    path: "~"
  })
  console.log(result)
}
```

Run it in Electron (so not as a sandboxed PWA)

### Additional Context

Some current workarounds are discussed here: https://github.com/capacitor-community/electron/issues/141

Ideally I would prefer if the official solution supported Electron out of the box for accessing the file system such as the `/` and `~` folders.

**Comment by jcesarmobile** [comment]
electron is a community platform and should has its own filesystem plugin, plugins in this repository are for iOS, Android and web only. In you use them on electron they will use the web version.

anyway, using `~` will never work if you also use `directory`, if you use `directory` then path is relative to directory, if you don't pass `directory` then `path` is absolute.
