### ISSUE TITLE
Failed to minify the bundle. Unexpected token: punc (:)

### ISSUE THREAD

**Issue by tristan-morris** [ionic-team/capacitor-plugins#635]
## Bug Report

Hi,

Really loving Capacitor!! It really is amazing. 

I've definitely spent way too much time trying to understand what is going on here, and getting in way too deep! 

The TLDR is, when the capacitor plugins are tree-shaken the dynamic imports appear to break (they're likely discarded) when built in production mode by React/React-Scripts (non-ejected). This issue could likely be resolved upstream, but I spent the majority of my time within this repo trying to debug what was going on and suspect others will look here first.

The root cause appears to be this code segment which is present in each of the plugin's `index.js` files. When this code is tree shaken (or minified possibly) by webpack, the `import().then..` is somehow broken and breaks the build.

```typescript
// From device/dist/esm/index.js (also in device/src/index.js)
const Device = registerPlugin('Device', {
    web: () => import('./web').then(m => new m.DeviceWeb()),
});
```

My workaround is described below, but it is essentially importing `DeviceWeb` and calling `new DeviceWeb()` just to indicate the module is indeed consumed.

### Plugin(s)
@capacitor/device
@capacitor/geolocation
Likely all plugins

### Capacitor Version
```bash
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.2.3
  @capacitor/ios: 3.2.3
  @capacitor/core: 3.2.3

[success] iOS looking great! 👌
```

### Platform(s)
* React with create-react-app (not ejected) and react-scripts 4.0.3.

### Current Behavior
 * Building, running and testing in development works fine.
 * Packing for prod deployment fails.
 * ??? Confusion sets in ???

```bash
% npm run

Compiled successfully!

You can now view ux in the browser.

  Local:            http://localhost:3000
```

```bash
% npm run build                                  

  > ux@3.0.0 build
  > react-scripts build

  Creating an optimized production build...
  Failed to compile.

  Failed to minify the bundle. Error: static/js/647.11ee551f.chunk.js from Terser plugin
  Unexpected token: punc (:) [static/js/647.11ee551f.chunk.js:3,9]
      at /ux/node_modules/react-scripts/scripts/build.js:188:23
      at finalCallback (/ux/node_modules/webpack/lib/Compiler.js:415:32)
      at /ux/node_modules/webpack/lib/Compiler.js:432:13
      at Hook.eval [as callAsync] (eval at create (/ux/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/ux/node_modules/tapable/lib/Hook.js:18:14)
      at onCompiled (/ux/node_modules/webpack/lib/Compiler.js:430:21)
      at /ux/node_modules/webpack/lib/Compiler.js:1106:17
      at eval (eval at create (/ux/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
  Read more here: https://cra.link/failed-to-minify
```

### Expected Behavior
* `npm run build` executes `react-scripts build` and yields a functional minified build.

### Code Reproduction
```typescript
import { Device } from '@capacitor/device';
import { DeviceWeb } from '@capacitor/device/dist/esm/web';

export class CapacitorIntegration {

    static async deviceOsInfo() {
        new DeviceWeb(); // Removing this line will break `npm run build`
        return await Device.getInfo()
    }
}



### Other Technical Details



### Additional Context

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
