### ISSUE TITLE
Add date key to getDeliveredNotifications function for filtering

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-plugins#636]
### Plugin

- Push Notifications

### Description

I'm currently working on an app that implements [Firebase notifications](https://github.com/laravel-notification-channels/fcm), which currently only seems to support a **title** and a **body** that's [compatible](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Notification) with both iOS and Android.

When I construct my notification on my server I provide a title, body and an image.

The problem I'm facing is that I need to clear out old notifications and only keep the newest notification possible, to do this I'd like to filter by the date & time.

I've checked the `getDeliveredNotifications` function, and it contains my title and body, but I would really like to be able for this to include a generated date & time of when the notification came through to the device in a unix timestamp format.

### Platform(s)

- iOS
- Android

### Preferred Solution

I came across this part of the code which seems to generate the data.

```java
Notification notification = notif.getNotification();
if (notification != null) {
    jsNotif.put("title", notification.extras.getCharSequence(Notification.EXTRA_TITLE));
    jsNotif.put("body", notification.extras.getCharSequence(Notification.EXTRA_TEXT));
    jsNotif.put("group", notification.getGroup());
    jsNotif.put("groupSummary", 0 != (notification.flags & Notification.FLAG_GROUP_SUMMARY));

    JSObject extras = new JSObject();

    for (String key : notification.extras.keySet()) {
        extras.put(key, notification.extras.get(key));
    }

    jsNotif.put("data", extras);
}
```

I'd like something like...

```java
jsNotif.put("date", some date here);
```

to be added.

### Additional Context

I did try utilising the `setChannelId`, listed [here](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification), didn't get any errors, but this never came through to the Capacitor app that I'm building.

A date would really be useful for situations like this.

**Comment by jcesarmobile** [comment]
that information is not provided by Firebase, so we can't made that up

Firebase allows to send data with any keys and values you want

**Comment by sts-ryan-holton** [comment]
@jcesarmobile Thanks for your reply. I've tried setting my own custom data, but it never shows up in the `getDeliveredNotifications` function when outputting it to the page, this is my Firebase config:

```php
/**
 * Get the Firebase representation of the notification.
 */
public function toFcm($notifiable)
{
    return FcmMessage::create()
        ->setData(['beam_id' => $this->beam->id])
        ->setToken($notifiable->fcm_token)
        ->setNotification(\NotificationChannels\Fcm\Resources\Notification::create()
            ->setTitle($this->beam->beam_data->notification)
            ->setBody($this->beam->title)
        ->setAndroid(
            AndroidConfig::create()
                ->setPriority(AndroidMessagePriority::HIGH())
                ->setNotification(
                    AndroidNotification::create()
                        ->setSticky(true)));
}
```

I do see `beam_id` inside of the push notification `pushNotificationActionPerformed` listener, but I need to be able to see this inside of `getDeliveredNotifications`, and I never see it there, all I see is the following:

![Screenshot_20210927-161032](https://user-images.githubusercontent.com/25177538/135049685-b89ca75d-9145-4c7f-a801-93a95f70b427.jpg)

Where would my Beam ID be here?
