### ISSUE TITLE
Add method to check if user has disabled geolocation services

### ISSUE THREAD

**Issue by squio** [ionic-team/capacitor-plugins#640]
### Plugin

@capacitor/geolocation

### Description

Currently the `checkPermissions()` and `requestPermissions()` only check for and enable the App permissions.
The device user can still have location services disabled - which is undetectable by this plugin.

On Android, location services are required to be enabled to do a Bluetooth scan request.
If location services are not available, the BLE stack does not generate any error messages but just
times out and discovers nothing (by design).

I want to be able to check whether location services have been disabled globally *without trying to get an actual location* because I actually don't want to request the user location at all.

### Platform(s)

- Android (primarily)
- iOS (could be useful as well?)

### Preferred Solution

Implement the solution from PR #589 as a callable plugin method, something along the lines of:

```java
public bool checkLocationServices()
{
    LocationManager lm = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);
    return (LocationManagerCompat.isLocationEnabled(lm));
}
```

A similar `requestLocatuinServices()` method - which requests the user to enable location services - could be helpful as well.

### Alternatives

As my use case is purely related to Bluetooth scanning, this could also be added in
plugin [@capacitor-community/bluetooth-le](https://github.com/capacitor-community/bluetooth-le) 
but the feature feels more at place in the actual geolocation plugin.

### Additional Context

It seems that similar functionality may exist in some (outdated?) cordova plugins but I'm very
hesitant to pollute my project with duplicate and potentially outdated functionality.
Alternative suggestions are welcome though!

**Comment by jcesarmobile** [comment]
I think the Bluetooth plugin would be a better fit for this feature, geolocation will return an error if the location services are disabled.
