### ISSUE TITLE
create getToken method for Push Notifications plugin to query current device token

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-plugins#641]
### Plugin

- Push Notifications

### Description

I'd like to be able to get the current device token stored on the device with some kind of method. Right now, a token is only provided when prompting the user to register, found here https://capacitorjs.com/docs/apis/push-notifications#addlistenerregistration, but I'd like a method to be able to query the current device token on the phone.

### Platform(s)

- iOS
- Android

### Preferred Solution

Extend the plugin and create a method such as `getDeviceToken()`

**Comment by jcesarmobile** [comment]
The way of getting the token is to listen for registration event, it will provide the token once the registration succeeds, and on android, also if the token changes after the registration event.
On iOS there is no programmatic way of getting the token other than the registration event, on android should be possible to use some native code to get the token on demand, but we won't be adding that feature just for Android.

**Comment by sts-ryan-holton** [comment]
Attempted -> https://github.com/ionic-team/capacitor-plugins/issues/642
