### ISSUE TITLE
await not wating for registration event in push notifications plugin

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-plugins#642]
### Plugin(s)

- Push Notifications

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/ios: 3.2.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

```
"@capacitor/android": "3.2.4",
"@capacitor/ios": "3.2.4",
"@capacitor/core": "3.2.4",
"@capacitor/push-notifications": "1.0.4",
```

### Platform(s)

- iOS
- Android

### Current Behavior

When awaiting the response of the `registration` event listener, the `await` is not waiting for a token to be retrieved.

### Expected Behavior

I need to be able to `await` the response of the registration event so that I can get my device's token before returning the value.

### Code Reproduction

The following is a Vue JS 2 method

```javascript
/*
** Get the device token
*/
async getDeviceToken () {
  try {
    alert('getting token...')
    let deviceToken = null
    await this.$CapacitorPushNotifications.addListener('registration', (token) => {
      alert(token.value)
      deviceToken = token.value
    })

    alert('token is...')
    alert(deviceToken)
    return deviceToken
  } catch (err) {
    alert(err)
    return null
  }
},
```

### Additional Context

I'm seeing my alerts in the following order...

1. `alert('getting token...')`
2. `alert('token is...')`
3. `alert(deviceToken)` <-- gives me null, because the `await` is not waiting.

Maybe I need to change it to...

```javascript
  const { token } = await this.$CapacitorPushNotifications.addListener('registration');
```

**Comment by jcesarmobile** [comment]
addListener doesn't return the token but a `PluginListenerHandle` that allows to remove the listener later on (if needed), so when it resolves doesn't mean that the token is there, just that you got the handler to remove the listener.

addListener takes a function that is executed when the native listener for the token is fired, so you can't create your function like you did.

Something like this might work: (didn't try)

```
async getDeviceToken () {
    new Promise(resolve => {
        await this.$CapacitorPushNotifications.addListener('registration', (token) => {
            alert(token.value)
            resolve(token.value);
        })
    })
},
```

still, registration is called when the native listener fires, so your `getDeviceToken()`will probably work only the first time you call it, subsequent calls will wait forever as the native event won't be called again, if you want to keep the token save to to localStorage or with Storage plugin or somewhere else.
