### ISSUE TITLE
iOS app rejected due to missing NSPhotoLibraryUsageDescription value

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-plugins#646]
### Plugin(s)

- Camera

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

When validation and submitting an app to the App store, I'm getting a rejection error due to the following:

> ITMS-90683: Missing Purpose String in Info.plist

More specifically, the:

> NSPhotoLibraryUsageDescription

does not contain a value

### Expected Behavior

The docs do not mention about filling out the **Value** field, so what options do I need here. [docs](https://capacitorjs.com/docs/apis/camera#ios)

### Additional Context

My info:

![Screenshot 2021-10-04 at 16 12 42](https://user-images.githubusercontent.com/25177538/135877106-db7dac50-f4b1-4a86-b31e-43f780c58c8f.png)

Will I need to set the others too?

**Comment by jcesarmobile** [comment]
Docs say "added and **filled out**", so yes, you have to fill the value field with the description about why your app needs that permission.
