### ISSUE TITLE
capacitor 3 storage plugin work in browser but not in devices

### ISSUE THREAD

**Issue by mdweyal** [ionic-team/capacitor-plugins#657]
### Plugin(s)

import { Storage } from '@capacitor/storage';

### Capacitor Version

3
```
PASTE OUTPUT HERE
```

### Platform(s)

android and ios

### Current Behavior

Hello friends,
I use capacitor 3 with storage plugin, it works with ionic serve in browser but not in android device.
import { Storage } from '@capacitor/storage';
can anyone face the same problem?

### Other Technical Details

Hello friends,
I use capacitor 3 with storage plugin, it works with ionic serve in browser but not in android device.
import { Storage } from '@capacitor/storage';
can anyone face the same problem?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
