### ISSUE TITLE
appUrlOpen not firing in the in-app browser when 302 redirect to a universal link happens

### ISSUE THREAD

**Issue by kazinov** [ionic-team/capacitor-plugins#675]
### Plugin(s)

"@capacitor/app": "^1.0.5"
"@capacitor/browser": "^1.0.5"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/ios: 3.2.5

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

iOS

### Current Behavior

I'm trying to implement SSO (third party log in) functionality in my app. 
What I did in preparation:
 - I setup universal link according the docs: https://capacitorjs.com/docs/guides/deep-links
   (it worked well)

The problem:
 - I call ```Browser.open(...)``` with the url of the SSO provider
 - In-app browser opens
 - If user does it the first time, then a login form on the SSO provider site shows up
 - user manually inputs the credentials and submits the form
  - SSO provider redirects to our site (universal link)
  - ```App.addListener('appUrlOpen'``` event triggered in my app code
  - I close the in app browser and log in the user. Success!
  **BUT**
  When user opens the app another time and starts logging in, the following happens:
  - I call ```Browser.open(...)``` with the url of the SSO provider
  - In-app browser opens
  - SSO provider server uses the cached data and immediately answers with **302 redirect** to our site (universal link)
  
 - **```App.addListener('appUrlOpen'``` is not called!** So I can't finish the flow.

### Expected Behavior

```App.addListener('appUrlOpen'``` called whenever the universal link is opened in the in-app browser, doesn't matter was it caused by redirect or not.

### Additional Context

This issue was already reported several times, for example here by @thoechtl
https://github.com/ionic-team/capacitor/issues/3255#issuecomment-663540706

and every time it was rejected because of some miscommunication. Please note: my problem is not that the in-app browser not closing. 
My problem is that **```App.addListener('appUrlOpen'``` is not firing in some very specific case** which prevents me and other  users of implementing the SSO flow.

P.S.:
Thank you for the amazing tools and thank you in advance for the help with this issue!

**Comment by jcesarmobile** [comment]
As far as I know it's a known issue of the `SFSafariViewController`, it loads the universal link instead of forwarding it to the app. And `SFSafariViewController` doesn't provide any information about the urls it's loading so we could intercept it, stop it and fire `appUrlOpen`.
People recommends using custom app schemes and redirecting to those instead of to universal links as  `SFSafariViewController` will never try to open urls that don't start by http or https.

In the past it didn't even work the first time, so Apple might have fixed it but missed the redirect, so try reporting it to Apple.

**Comment by kazinov** [comment]
Thank you, @jcesarmobile

For everyone who is looking into it. I see 3  possible ways to handle this problem:

1. Use a custom url scheme instead a universal link. I don't recommend this way because the same custom url scheme could be registered by another app. So your session token could be easily hijacked.

2. Use window.open('your-sso-provider-url', '_blank') + universal link. This way the sso login will happen in the out-of-app browser and the universal link will be handled properly. Downside: using the external browser could be inconvenient for users. Also the tab with the SSO provider page will stuck in Safari's open pages which could be considered as a security problem. 

3. You could use the old plugin cordova-plugin-inappbrowser.
This plugin uses WKWebView, when capacitor/browser uses SFSafariViewController.
(read about the difference here: https://developer.apple.com/news/?id=trjs0tcd)
Thus this plugins gives you a lot of control of what is happening in your in-app browser so you could easily implement any flow you want.
Downside: This plugin doesn't look like it actively supported. It has visual glitches and lots of open issues. So it can be considered only as a temporary solution.
