### ISSUE TITLE
Geolocation: Android 12 Approximate Location Treated as Location Permission Denied

### ISSUE THREAD

**Issue by KevinKelchen** [ionic-team/capacitor-plugins#676]
### Plugin(s)

`@capacitor/geolocation` plugin version `1.1.2`

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/core: 3.2.5

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Android 12 allows the user to only grant approximate location accuracy in the location permission prompt. See [here](https://developer.android.com/training/location/permissions#approximate-request) to learn more. Even if the app's target SDK is Android 11 (API 30) the approximate location option is present.

With Capacitor's Geolocation plugin, if a user selects approximate location accuracy, the plugin believes that location permission is denied when the user didn't actually deny it; they just chose approximate accuracy. It will work fine with precise location accuracy.

See the README in the Code Reproduction for steps to reproduce: https://github.com/KevinKelchen/capacitor-geolocation-android12-issue

### Expected Behavior

The Geolocation plugin on Android 12 would report that location permission has been granted when using approximate location accuracy.

### Code Reproduction

See the README in the Code Reproduction: https://github.com/KevinKelchen/capacitor-geolocation-android12-issue

### Additional Context

I am happy to provide further info!

Thank you so much! 😀

**Comment by KevinKelchen** [comment]
Thanks so much for fixing this, Julio! 🎉 😀

**Comment by jcesarmobile** [comment]
Thanks to you for the awesome bug report ;)
