### ISSUE TITLE
Camera.getPhoto unable to handle HDR photos

### ISSUE THREAD

**Issue by JarrodMFlesch** [ionic-team/capacitor-plugins#680]
### Plugin(s)
@capacitor/camera

### Capacitor Version
@capacitor/camera: ^1.1.2
@capacitor/core: ^3.1.2

### Platform(s)
iOS

### Current Behavior
When selecting a photo that is an HDR image, the getPhoto method throws a generic error.

### Expected Behavior
The image should be selected. If that is not possible, it would be nice to get a more specific error message so I can tell my users to select a photo that is not HDR.

### Code Reproduction
Boot up an app using the @capacitor/camera plugin and select the first image loaded onto xCode simulators (the pink flower one).

**Comment by jcesarmobile** [comment]
It’s a bug on the simulator, see https://github.com/ionic-team/capacitor-plugins/issues/587#issuecomment-910520180

**Comment by JarrodMFlesch** [comment]
> It’s a bug on the simulator, see https://github.com/ionic-team/capacitor-plugins/issues/587#issuecomment-910520180

Thanks for the info mate!
