### ISSUE TITLE
status-bar - WebView not behind status-bar on iOS

### ISSUE THREAD

**Issue by ludufre** [ionic-team/capacitor-plugins#682]
### Plugin
`@capacitor/status-bar`

### Description
I'm missing the option to make the WebView not behind the status-bar and background-color on iOS. Like on Cordova:

(Left, Cordova. Right, Capacitor)

![image](https://user-images.githubusercontent.com/4112077/140422405-ba5386a6-3255-46f9-b869-933bb387382b.png)

### Platform(s)
`iOS`

### Preferred Solution
A method to acomplish this.

### Alternatives
Manually resize the WebView?

### Additional Context
https://github.com/apache/cordova-plugin-statusbar/blob/master/src/ios/CDVStatusBar.m#L221-L243

**Comment by jcesarmobile** [comment]
That’s a hack that we didn’t want in the plugin. By the time it was done in Cordova plugin there weren’t other ways of handling the status bar space, but there are now, safe areas. Check this article apple wrote when they launched iPhone X

https://webkit.org/blog/7929/designing-websites-for-iphone-x/
