### ISSUE TITLE
Geolocation.getCurrentPosition never resolve on some android devices

### ISSUE THREAD

**Issue by cyril-colin** [ionic-team/capacitor-plugins#683]
### Plugin(s)
`"@capacitor/geolocation": "^1.1.0"`

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

Installed Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

[success] Android looking great!
```

### Platform(s)
android

### Current Behavior
On some devices (Google Pixel 3A) the method Geolocation.getCurrentPosition() never resolve.

### Expected Behavior
The Geolocation.getCurrentPosition() should resolve on all android devices.

### Code Reproduction
```typescript
    // In my service GelocationService:
    public static async getCurrentPosition() {
        const checkedPerms = await Geolocation.checkPermissions();
        console.log('Geolocation.checkPermissions()', checkedPerms);
        const perms = await Geolocation.requestPermissions();
        console.log('Geolocation.requestPermissions()', perms);

        console.log('START[accuracy=true]');
        Geolocation.getCurrentPosition({
            enableHighAccuracy: true,
            maximumAge: 0,
            timeout: 5000,
        }).then(res => console.log('RESULT[accuracy=true]', res));

        console.log('START[accuracy=false]');
        Geolocation.getCurrentPosition({
            enableHighAccuracy: false,
            maximumAge: 0,
            timeout: 5000,
        }).then(res => console.log('RESULT[accuracy=false]', res));
    }

   // In other class:
   await GeolocationService.getCurrentPosition()
```

The execution of getCurrentPosition never resolve on my Android Pixel 3A:
![image](https://user-images.githubusercontent.com/12231561/140481240-8042d9e9-935d-4ac6-90bb-18dfe6129d7d.png)

But it does on my Samsung Galaxy A51:
![image](https://user-images.githubusercontent.com/12231561/140482279-b76add38-1271-4eee-9676-ecd09f205c27.png)

> Note that the second call have not resolved. I think this is an other problem related to my double called of getCurrentPostion. So I have re run the second call "at runtime" by using `Capacitor.Plugins.Geolocation.getCurrentPosition({enableHighAccuracy: true, timeout: 0}).then(res => console.log(res));` directly in the console. The same operation doesn't work on my Pixel 3A.

### Other Technical Details
1. On android studio debbuger, I observe that the working case pass through this line: https://github.com/ionic-team/capacitor-plugins/blob/64df93225736e9dfad336562f5e53e5a2243052b/geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/Geolocation.java#L64, But not on my Pixel 3A
2. My Pixel 3A is under [LineageOS](https://lineageos.org/) and has google play services installed. This has never been a problem on capacitor 2 or other applications.
3. This problem occurs since I upgraded my app from capacitor 2 to capacitor 3.
4. Android versions :
    - Pixel 3a (not working case): 11
    - Samsung Galaxy A51: 10

### Additional Context
1. My GPS is enabled
2. I have these permissions  enabled in my manifest : 
    ```xml
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
    ```
3. I have checked existing issues, but none of them seems to fit my case.
    - https://github.com/ionic-team/capacitor-plugins/issues/571
    - https://github.com/ionic-team/capacitor/issues/4962
4. I found some [SO issues](https://stackoverflow.com/questions/52587361/fusedlocationclient-not-calling-onlocationresult) that seems to fit my case, but I don't this android API, so I am still studying this way...

Thank you for reading this !

**Comment by cyril-colin** [comment]
While I have google play services installed on my device, it has a problem. I can see this in my logcat: 
```
W/GooglePlayServicesUtil: com.example.dev requires the Google Play Store, but it is missing.
W/GoogleApiManager: The service for com.google.android.gms.internal.location.zzaz is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```

This can be an explanation but I still don't understand why Gelocation was working with capacitor 2 :/

**Comment by mirko77** [comment]
@cyril-colin We have the same problem with Lineage OS (16,17,18) but also stock Android.

`getCurrentPosition()` never resolves, never times out. If we put the phone in aeroplane mode and stay inside (no satellites in view), it never resolves.

We ended up using the web API for location and it is all good.

**Comment by danroot** [comment]
I'm seeing the same behavior on a vanilla Pixel 5.  A call like:

` async searchByLocation(event) {
    console.log('Search by location'); 
    this.isSearchingByLocation = true;
    var coordinates:Position;
    try{
      var permissions = await Geolocation.checkPermissions();
      if(permissions.coarseLocation != 'granted' || permissions.location != 'granted'){        
        permissions = await Geolocation.requestPermissions({permissions:['coarseLocation','location']});
        if(permissions.coarseLocation != 'granted' || permissions.location != 'granted')
        throw 'User does not allow geolocation services.';        
      }
     console.log('Permissions granted', JSON.stringify(permissions));
     coordinates = await Geolocation.getCurrentPosition({timeout:8000});
     console.log('Got location ', JSON.stringify(coordinates));
    }catch(ex){
      console.log('Error getting location: ', ex?.message, ex);
      await (await this.toastController.create({message:"Unable to get location.  Please ensure location services are enabled for this app.", duration:3000})).present();     
    }
    this.isSearchingByLocation = false;
    await this.doSearch(event, this.api.getGroupsByLatLng(coordinates.coords.latitude, coordinates.coords.longitude));
  }

Simply never returns or throws.  Logs show it hits and passes 'Permissions granted', but never logs 'Got location' or 'Error getting location'.  Unlike @cyril-colin , I do not see any GooglePlayServices or GoogleApiManager log entries.  I don't see any log entries that I think correlate, even in Verbose mode, though it is kind of noisy.  

I'm not clear on what is needed to upgrade google play services? I'm not getting any error to that effect, but could be related.  Is there some step I need to do in the app that's not covered in the readme?

**Comment by illinar** [comment]
We report similar problem on some Android devices. Disabling location services (aeroplan mode) then switching them back at _some_ point starts resulting in the described behavior (promise never resolves). This problem is then persists and switching location services back and forth has not effect. However enabling location services and then rebooting the device restores normal behavior.
