### ISSUE TITLE
Gallery support on web PWA

### ISSUE THREAD

**Issue by Odonno** [ionic-team/capacitor-plugins#686]
### Plugin

"@capacitor/core": "^3.3.1"
"@capacitor/camera": "^1.2.0"

### Description

I have upgraded to the latest version of Capacitor Camera and I'm using the new `pickImages` function. It works great on Android and it works well on desktop web (the input file selector). However, I tested on my Android device on Chrome (web) and it launched the Camera instead of a gallery selector. This is not the behavior I expected with this function.

I expect it to open a dialog similar to the one we have on Android native.

### Platform(s)

Android web
(and iOS web I suppose)

### Preferred Solution

Open a dialog where you can capture new photos using the camera and select multiple photos from the gallery.

### Alternatives

Open the gallery selector of Android.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Akaori** [comment]
I'm also facing a similar problem with `"@capacitor/camera": "^1.2.0"`. 

I'm trying to use the new `pickImages` function, but when I test on my real Android device, it opens the gallery, I click on a picture, the gallery closes, but the picture isn't selected.

**Comment by Odonno** [comment]
@Akaori Well, we do not have the same behavior. On Android (native), it works perfectly but on Chrome Android (web), it opens the Camera app directly and you can only take a new picture (no gallery opened).

So, obviously, as I can only take one picture,  one picture is generated on the callback.

So, there is no bug. Simply a misleading behavior on Chrome for Android.

**Comment by Akaori** [comment]
@Odonno, yeah, I misunderstood the issue, I'll delete my comment, 
because it's off topic. ;)
