### ISSUE TITLE
bug(share): App crash when targeting SDK 31

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#690]
### Plugin(s)
share

### Capacitor Version
3.3.1

### Platform(s)
Android

### Current Behavior
App crash when trying to share

### Expected Behavior
To not crash

### Code Reproduction
https://github.com/ionic-team/capacitor-testapp/blob/main/src/pages/Share.tsx

### Additional Context

> Caused by: java.lang.IllegalArgumentException: com.capacitorjs.app.testapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
>     Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by jayp0521** [comment]
This should fix the issue: https://github.com/ionic-team/capacitor-plugins/issues/690

**Comment by jcesarmobile** [comment]
this has been fixed in 4.0.0 beta 0
