### ISSUE TITLE
Consider using separate repositories for each plugin

### ISSUE THREAD

**Issue by barry-jones** [ionic-team/capacitor-plugins#698]
It is difficult to follow individual plugins and plugin versions for fixes and updates because all versions appear to be getting bumped at once, also, since it is a single repository it is hard to check the release/version history of a plugin. The plugin versions incrementing does not necessarily mean that any change has been made, and checking that there are changes and to ensure that no breaking changes have been made before an upgrade is too much work.

**Comment by jcesarmobile** [comment]
Thanks for the feedback.

We only release the plugins that have been changed, but sometimes we make changes that are (sort of) irrelevant for users (docs, dependency updates, etc.) and specifically the dependency updates are done on all plugins and that makes that the next release releases all plugins.

At the moment we use semver for the versioning (major.minor.patch), so
If the last digit is increased, it means one or more fixes were done (or doc/dependency changes)
If the middle digit is increased, it means there is at least a new feature on the plugin
If the first digit is increased, it means there was at least one breaking change.
At the moment all plugins are in version 1.x.y, which means no breaking changes have been introduced on any of them.

We always try to be extra careful with breaking changes (not introducing them by mistake), and if we ever do a breaking change without doing a major version bump we would revert the changes, do another release and then do the major release with the breaking changes.

we use [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) messages to automate the changelogs but also to make it easier for users to understand the changes, so if we do a fix, chore or doc, it will increment the patch version, if we do a feat it will increment the minor version, and when we do a breaking change the commit will have a ! and the description with start with BREAKING CHANGE. That supposedly will add the change to the changelog and document it as breaking and do a major bump, but we have not done any breaking change, so won’t know for sure until we try to release the first one.

Hope the explanation helped, you shouldn’t worry about breaking changes until you notice that any of the plugins is on version 2, you should be able to update without problems to minor and patch releases.

**Comment by jcesarmobile** [comment]
going to close this, if you have any other ideas, feel free to provide them in the discussions section of the capacitor repository
https://github.com/ionic-team/capacitor/discussions
