### ISSUE TITLE
@capacitor/geolocation doesn't error if google services are not installed

### ISSUE THREAD

**Issue by linhaihero** [ionic-team/capacitor-plugins#700]
### Discussed in https://github.com/ionic-team/capacitor/discussions/5251

<div type='discussions-op-text'>

<sup>Originally posted by **linhaihero** November 18, 2021</sup>
Hello everyone, I am using capacitor for the first time. I follow the steps of https://capacitorjs.com/solution/vue and want to try to make a Hello world. I have added permission in AndroidManifest.xml and allowed it in my phone. Then it didn't work properly, and I couldn't understand the error displayed on the console. Please help, Tell me why, what happened ？ thanks thanks thanks thanks~~

![image](https://user-images.githubusercontent.com/8591451/142440229-a41d9a68-00ea-45c6-9e33-48cba7fa497f.png)
![image](https://user-images.githubusercontent.com/8591451/142440188-820a13a3-b6fc-4d06-88bd-808aa87c60e7.png)
![image](https://user-images.githubusercontent.com/8591451/142443469-076f2dd5-a117-441a-a55a-5e64a6d404b8.png)
![image](https://user-images.githubusercontent.com/8591451/142440241-d1aab307-dcc1-42a0-802b-ce997ed8a5d9.png)
</div>

**Comment by linhaihero** [comment]
> A VPN won't help you in this case, the plugin needs this "app" to be installed (google play services) https://play.google.com/store/apps/details?id=com.google.android.gms
> 
> I thought it would error if it wasn't installed, but looks like it doesn't will look into it.

Probably not. The test phone already has a full Google service👇

![Screenshot_2021-11-23-21-14-23-815_com miui securitycenter](https://user-images.githubusercontent.com/8591451/143031060-80c06d2a-52ab-48e1-95e6-abc0217df94f.jpg)

When I click on the link in your reply 👇

![Screenshot_2021-11-23-21-15-30-121_com android vending](https://user-images.githubusercontent.com/8591451/143031098-8caa121e-33f0-4dcf-81b2-592efc28d399.jpg)

**Comment by linhaihero** [comment]
> A VPN won't help you in this case, the plugin needs this "app" to be installed (google play services) https://play.google.com/store/apps/details?id=com.google.android.gms
> 
> I thought it would error if it wasn't installed, but looks like it doesn't will look into it.

Probably not. The test phone already has a full Google service👇

![Screenshot_2021-11-23-21-26-31-255_com miui securitycenter](https://user-images.githubusercontent.com/8591451/143032945-444222e5-d2be-41dd-b78d-a4402c97385c.jpg)

When I click on the link in your reply 👇

![Screenshot_2021-11-23-21-26-40-420_com android vending](https://user-images.githubusercontent.com/8591451/143032969-57eb887b-54b2-400d-beb6-7adc448589a0.jpg)

**Comment by jcesarmobile** [comment]
can you update the plugin to the latest version and see if it returns an error or still hangs?

**Comment by jcesarmobile** [comment]
closing due to the lack of response, the plugin should error now if google Play Services are not available
