### ISSUE TITLE
Cannot select photos from Gallery on Samsung devices

### ISSUE THREAD

**Issue by Odonno** [ionic-team/capacitor-plugins#704]
### Plugin(s)

"@capacitor/android": "^3.3.1",
"@capacitor/app": "^1.0.6",
"@capacitor/camera": "^1.2.1",

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.1
  @capacitor/ios: 3.3.1
  @capacitor/core: 3.3.1
  @capacitor/android: 3.3.1

### Platform(s)

Android : Samsung Note 8

### Current Behavior

When using `pickImages` function on a Samsung device, the gallery is opened but I cannot select image. I can see a list of images but I can only open the image in fullscreen. There is no way to select an image, even one.

### Expected Behavior

Like any other gallery app, add ability to select multiple images.

**Comment by Odonno** [comment]
Seems like the react-native team already solved a similar issue here: https://github.com/react-native-image-picker/react-native-image-picker/issues/1739

**Comment by ThaierAlkhateeb** [comment]
Hey, 
I have got the same issue.
It shows me in console "{message: 'No images picked'}", but if I choose select image from Google photos it works.

**Comment by raykin** [comment]
Totally same issue on OPPO phone. I captured several screenshots of adb logs. I can upload them if it can help to locate issues.

**Comment by carlpoole** [comment]
I was able to confirm that multi-selecting is working when the Google Photos app is used as the source, but running into issues with the device/manufacturer gallery apps. I was testing the solution proposed #706 but I was still running into issues with the picker that displayed (see: https://github.com/ionic-team/capacitor-plugins/pull/706#issuecomment-981734589) and I was curious if this was the same experience on other devices. I was testing it on a Samsung Galaxy S9+ running Android 10

**Comment by carlpoole** [comment]
In the case with my test on my Galaxy S9+, single tapping an image caused it to immediately try and return that image to the app, instead of allowing me to select more and then confirm. The presence of only a single image causes the `processPickedImages` method to fail at the moment.

To select multiple images I had to press and hold in the device picker, and then it would let me choose more and confirm. This leads me to think we could modify the multi-select code to allow the return of single images and leave it to the users to make sure they are using the device picker correctly to pick multiple images vs. a single image.

**Comment by N0ctural** [comment]
> In the case with my test on my Galaxy S9+, single tapping an image caused it to immediately try and return that image to the app, instead of allowing me to select more and then confirm. The presence of only a single image causes the `processPickedImages` method to fail at the moment.
> 
> To select multiple images I had to press and hold in the device picker, and then it would let me choose more and confirm. This leads me to think we could modify the multi-select code to allow the return of single images and leave it to the users to make sure they are using the device picker correctly to pick multiple images vs. a single image.

Hello @carlpoole, I made an update on my PR to correct problem on Huawei / Oppo etc. on Android 9 with default gallery app and on Samsung devices.

**Comment by braincomb** [comment]
I can confirm I have the same issue with Samsung Gallery app on S8.

Running `"@capacitor/camera": "^1.2.0"` and `npx cap doctor` is below:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

[success] Android looking great! 👌
```
