### ISSUE TITLE
camera plugin save pictures to gallery when option saveToGallery is default or set to false

### ISSUE THREAD

**Issue by hschindler** [ionic-team/capacitor-plugins#714]
### Plugin(s)

camera

### Capacitor Version
```
  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 3.0.0
```

### Platform(s)

Android

### Current Behavior

camera plugin saves pictures to gallery when option saveToGallery is default or set to false.

### Expected Behavior

the pictures should not be saved.

### Code Reproduction

 Camera.getPhoto(
                {
                    quality: 50,
                    // allowEditing: true,
                    resultType: CameraResultType.Base64,
                    source: CameraSource.Camera,
                    saveToGallery: false
                }
            ).then(picture => {
                observer.next('data:image/jpeg;base64,' + picture.base64String);
                observer.complete();
            }, err => {});

### Other Technical Details

VS Code Version 1.62.3

@angular/core": "^11.2.4
@ionic/angular": "^5.6.0
@capacitor/camera": "^1.2.1

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app?

Also, can you provide more information about the devices where you tested?
Real device or emulator?
Android version?
Vendor?

There is a know issue that, as the plugin uses an intent to the Camera app, some devices make a copy of the image and that's what appears on the galleries, not sure if that could be your problem.

**Comment by hschindler** [comment]
Thanks for your answer. I have tested the camera plugin now on another device and it works correct on that Sony Android Smartphone. I have two Android devices: CAT S41 and i.safe is655.2. On this two devices the image is saved on gallery.
So in fact,  some devices save a copy of the image. But how can I prevent that?

**Comment by jcesarmobile** [comment]
I don't think it can be prevented, unless you use a different plugin that doesn't use intents to camera app. It's the camera app what creates and saves a copy and each vendor can implement the camera behavior the way they want.
