### ISSUE TITLE
device.getInfo().isVirtual not `true` in iOS Simulator

### ISSUE THREAD

**Issue by chrisspiegl** [ionic-team/capacitor-plugins#720]
### Plugin(s)

- @capacitor/device

### Capacitor Version

- capacitor cli 3.3 .2
- core 3.3.2

### Platform(s)

macOS / iOS

### Current Behavior

Trying to get if the app is running in the simulator or on real device with:

```js
const dev = await Device.getInfo()
const runningInSimulator= dev.isVirtual
```

But for some reason in the simulator it tells me that `dev.isVirtual` is `false`

I also tried if it shows the other info and it does.

### Expected Behavior

isVirtual should be `true` when running in iOS Simulator

**Comment by jcesarmobile** [comment]
I can't reproduce in our test app.
Which simulator did you choose?
are you on M1 mac?
is the platform value correct?

**Comment by chrisspiegl** [comment]
Hi, I will get more info and an output of all the info values.
But as a quick reply, yes, I am on a M1Max machine.
