### ISSUE TITLE
LocalNotification Sound Not Working On Android 10 

### ISSUE THREAD

**Issue by DzCorps** [ionic-team/capacitor-plugins#721]
### Plugin(s)

LocalNotification

### Capacitor Version

```
atest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
```

### Platform(s)

Android

### Current Behavior

On Android 9 and Below, the plugin works fine and as expected.

On Android 10, the notification is triggered but the sound is missing, and phone doesn't vibrate.

### Expected Behavior

Same behaviour as is Android 9, (Sound, Vibration, lighting, etc...)

### Code Reproduction

```
1- Package.json

"@capacitor/local-notifications": "^1.0.9"

2- Service

public async fireOrderReadyNotification(msg: Message) {
    const result = await LocalNotifications.listChannels();
    if (result.channels.find(ch => ch.id === 'mychannel') === undefined) {
      const channel1: Channel = {
        id: 'mychannel',
        name: 'channel',
        sound: 'bell.wav',
        lightColor: '#f49c21',
        importance: 3,
        visibility: 1,
        vibration: true,
        lights: true
      }
      await LocalNotifications.createChannel(channel1);
    }

    const notifs = await LocalNotifications.schedule({
      notifications: [
        {
          id: 1
          title: "Notification title",
          body: 'Short blablaaa',
          largeBody: "large blablaaaaa body",
          channelId: 'mychannel'
          sound: "bell.wav"
        }
      ]
    });
  }
```

I also have a default configuration in my capacitor.config.json but it’s optional.

### Other Technical Details

![IMG_20211204_233651](https://user-images.githubusercontent.com/19369953/144726712-cb8d7861-8004-4fcc-a99b-8d5e9149f249.jpg)

**Comment by jcesarmobile** [comment]
Have you tried deleting the app and reinstalling?

Android channels can't be edited, so if the channel was created without sound creating it later with the sound won't have any effect. That's a common cause of no sound on notifications.

Can you go to Settings -> Apps & Notifications and search for your app and double check that the channel is there and that the settings are correct?

You can also try setting the importance to 4, 3 should be enough for having sound, but just in case.

If everything is correct, can you provide a sample app?

**Comment by DzCorps** [comment]
Found the problem, the importance must be 5 so that the system consider it as a high and auto enable sound on channels.
I tried 3 and 4 but still in default params.
@jcesarmobile thanks for the help.
