### ISSUE TITLE
@capacitor/geolocation don't enforce Google Play Services

### ISSUE THREAD

**Issue by boldtrn** [ionic-team/capacitor-plugins#731]
### Plugin

@capacitor/geolocation

### Description

Android has native geolocation support and could work without the FusedLocationProvider. If you want to deploy an app to devices that don't have play services enabled or want to deploy to 3rd party stores like F-Droid, requiring Google Services is an issue.

### Platform(s)

Android

### Preferred Solution

Allow to either configure which implementation is used.

### Alternatives

Switch to the native Android solution.

**Comment by jcesarmobile** [comment]
Our first implementation didn't require Google Play Services, but didn't work quite well and there was [some discussion](https://github.com/ionic-team/capacitor/issues/379) about switching to Fused Location Provider, which requires Google Play Services, and we did switch. We are not switching back, sorry.

**Comment by boldtrn** [comment]
Thanks for the feedback. I am sorry to hear that. I still think that making this configurable would be the best option, but I can understand that this might not be that important as most apps will run on devices with Google Play Services.
