### ISSUE TITLE
No gallery option on PWA (Android 12, Samsung, etc)

### ISSUE THREAD

**Issue by dftd** [ionic-team/capacitor-plugins#739]
### Plugin(s)
@capacitor/camera@1.2.2

### Capacitor Version
```
@capacitor/cli: 3.1.1
@capacitor/core: 3.1.1
@capacitor/android: 3.1.1
```

### Platform(s)
Web

### Current Behavior
On Samsung devices, and other Android 12 devices, `Camera.pickImages()` always opens the Camera and never offers the user to upload images from gallery.

### Expected Behavior
Users should be presented with an option to pick images from gallery.

### Other Technical Details
This can be fixed by removing `input.capture = true;`

**Comment by jcesarmobile** [comment]
are you sure you are on latest version of the plugin? 
that was already removed 
https://github.com/ionic-team/capacitor-plugins/pull/687
