### ISSUE TITLE
Bug: Local notifications doesn't popup in Android 12 when app is in background

### ISSUE THREAD

**Issue by ndabAP** [ionic-team/capacitor-plugins#745]
### Plugin(s)
- @capacitor/local-notifications

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3

[success] Android looking great! 👌
```

### Platform(s)
- Android 12

### Current Behavior
A local notification doesn't popup when the app is in background. It only shows as a white dot in the top bar.

![Screenshot_20211218-221312](https://user-images.githubusercontent.com/8510570/147055457-681f789e-8b8c-4865-a484-78d4b6309c73.jpg)

### Expected Behavior
Show the local notification in the same way as when the app is in foreground.

![Screenshot_20211218-221340](https://user-images.githubusercontent.com/8510570/147055472-776057c9-e9d9-4c14-9183-d10a8477ff0c.jpg)

### Code Reproduction

Started from scratch.

```ts
const channel: Channel = {
  id: "pop-notifications",
  name: "channel",
  importance: 4, // Tried also 5
  visibility: 1,
};

PushNotifications.createChannel(channel);
LocalNotifications.createChannel(channel);

PushNotifications.addListener(
  "pushNotificationReceived",
  async (notification) => {
    await LocalNotifications.schedule({
      notifications: [
        {
          id: Date.now(),
          title: notification.title as string,
          body: notification.body as string,
          channelId: "pop-notifications",
          schedule: {
            at: new Date(Date.now() + 1000),
          },
        },
      ],
    });
  }
);
```

**Comment by jcesarmobile** [comment]
Are you sure pushNotificationReceived is being called?
It looks like what you see is the local notification shown by the OS, not the local notification you create inside `pushNotificationReceived` and it's using the default channel, which has an importance of 3.

You can assign the channel from the own notification payload with `android_channel_id`, see [docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref), or if using firebase console, there is a field for the channel too.
How does your push notification payload looks like?


I can't reproduce if I create a local notification to a channel with importance of 4, schedule it for later and background the app.

**Comment by ndabAP** [comment]
>You can assign the channel from the own notification payload with android_channel_id, see docs, or if using firebase console, there is a field for the channel too.

Thank you very much. I needed many days to figure that out ;) But now I found out that I need to set my channel ID in Firebase as well.
