### ISSUE TITLE
Share.canShare

### ISSUE THREAD

**Issue by Tobertet** [ionic-team/capacitor-plugins#747]
### Plugin

Share

### Description

Whenever I try to use the Share functionality from my laptop, I get an error saying that my browser does not support the share functionality. I have tried with chrome and firefox, and I'm using Linux Mint. Everything works fine on android. I cannot test in Windows. Could it be the OS?

Anyways, the user experience ends up being a button that does not do anything.

### Platform(s)

Web, android

### Preferred Solution

I would like to know if my customer will be able to share, and if not I would hide the share functionality.
Share.canShare : () => boolean

**Comment by jcesarmobile** [comment]
that's a great idea, just sent a PR implementing it

a few desktop browser don't support sharing yet, at the moment only safari, opera and edge support it according to mdn
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility
