### ISSUE TITLE
App.exitApp() should return promise

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#750]
### Plugin(s)
App

### Capacitor Version
any

### Platform(s)
types

### Current Behavior
exitApp returns never

### Expected Behavior
exitApp should return a promise

### Other Technical Details
On android exitApp kills the app, so doesn't matter what it returns, but on iOS and web it rejects the promise and can't be catch as it returns never, if it returns a promise users can catch the unimplemented error

**Comment by numerized** [comment]
if I'm not wrong, you cannot kill an app on iOS

**Comment by jcesarmobile** [comment]
Yeah, you can’t. But at the moment calling exitApp on iOS will return an error that can’t be catch because it doesn’t return a promise, so the issue is about fixing that.

**Comment by jcesarmobile** [comment]
this has been fixed in 4.0.0 beta 0
