### ISSUE TITLE
removeAllListeners has CAPPluginReturnNone on iOS

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#751]
### Plugin(s)
app
browser
keyboard
local-notifications
network
push-notifications
screen-reader

### Capacitor Version
3

### Platform(s)
iOS

### Current Behavior
removeAllListeners has CAPPluginReturnNone return type on iOS

### Expected Behavior
removeAllListeners should have CAPPluginReturnPromise return type on iOS as types say they return a promise

### Additional Context
it also needs
related to https://github.com/ionic-team/capacitor/issues/5357

**Comment by trackmyapp** [comment]
Does this mean removeAllListeners doesn't work on ios?
For me it seems not to work, push-notifications are still received and displayed by the device after calling ushNotifications.removeAllListeners()
The promise resolves with "-1".

**Comment by jcesarmobile** [comment]
no, it works, just won't be able to catch an error if it fails for some reason

the listener just allow you to get the push notification data, but removing the listener doesn't prevent the app from receiving push notifications

**Comment by jcesarmobile** [comment]
this has been fixed in 4.0.0 beta 0
