### ISSUE TITLE
Limit the maximum number of pictures the user can pick on ANDROID

### ISSUE THREAD

**Issue by ghonche** [ionic-team/capacitor-plugins#752]
### Plugin
@capacitor/camera

### Description
I need to limit the maximum number of pictures the user will be able to choose using this API: 
`pickImages(options: GalleryImageOptions) => Promise<GalleryPhotos>`

### Platform(s)
Android

### Additional Context
There is a `limit` option in `GalleryImageOptions`  but it's for IOS only.

**Comment by jcesarmobile** [comment]
It's iOS only because it's not technically possible on Android.
