### ISSUE TITLE
Conditional downcast from 'UIWindow?' to 'UIWindow' does nothing

### ISSUE THREAD

**Issue by shpasser** [ionic-team/capacitor-plugins#761]
https://github.com/ionic-team/capacitor-plugins/blob/3ec2008bc0311c837346ecbdd0afd105149b427a/splash-screen/ios/Plugin/SplashScreen.swift#L120

The line produces a warning while compiling an iOS application in Xcode 13.2.1.

**Comment by smorris1709** [comment]
im having an issue where splash screen is not being hidden on the latest version of ios it did work before the update

**Comment by shpasser** [comment]
I do not think it is related. This issue just produces a compilation warning (my application works just fine).

**Comment by smorris1709** [comment]
@shpasser I agree my issue was to do with appflow showing an old version
