### ISSUE TITLE
pushNotificationActionPerformed is not working in app background state at ios 

### ISSUE THREAD

**Issue by MarwaAbuEssa** [ionic-team/capacitor-plugins#764]
## Bug Report
when tap on push notification when ios app is closed everything is working and pushNotificationActionPerformed  is triggered and redirect to appropriate route but when ios app is minified (app shared is backgound) tapping push notification always opens current screen ,  pushNotificationActionPerformed   is not triggered or redirected to required route
### Plugin(s)
 Push Notification

### Capacitor Version
@capacitor/cli: 2.4.6
@capacitor/core: 2.4.6
@capacitor/ios: 2.4.6
@ionic/angular": 5.0.0

```
PASTE OUTPUT HERE
```

### Platform(s)
IOS

### Current Behavior
tap push notifiaction while app minimized or not active is not trigger  pushNotificationActionPerformed   and opens last visited page only . also pushNotificationReceived is not triggered at all

### Expected Behavior
pushNotificationActionPerformed   listener's occurs when tap on push notification as happens if the app completely closed  

### Other Technical Details

 PushNotifications.addListener(
        'pushNotificationActionPerformed',
        async (notification: PushNotificationActionPerformed) => {
            this.zone.run(async () => {
              alert('Push performed:');

              await this.router.navigate(['hub/make-call'],{queryParams :{actionId:notification.actionId,data:JSON.stringify(notification.notification.data)}});
            });
       
        });

**Comment by jcesarmobile** [comment]
I can't reproduce on capacitor 3, try updating. This repository is for Capacitor 3 plugins.
