### ISSUE TITLE
Local-Notification does not fire is app is closed (at least on Android)

### ISSUE THREAD

**Issue by hatsantos** [ionic-team/capacitor-plugins#766]
### Plugin(s)
"@capacitor/local-notifications": "^1.0.10",

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/cli: 3.3.4
  @capacitor/ios: 3.3.4

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
A local notification is schedule at a given time.
The notification only happens if the app is open or in the foreground.
If the app is closed the notification does not happen (no notification card).

### Expected Behavior
The local notification should occur at the schedule time even if the app is closed.

### Code Reproduction
I'm calling LocalNotifications.schedule with allowWhileIdle a true on the schedule prop.

```
const notifyIn10seconds = new Date(Date.now() + 10000);

await this.Schedule("Testing Local Push", "This is the message to the local notification body.", notifyIn10seconds);

async Schedule(title: string, message: string, date: Date, extra: ILocalNotificationsExtra = null)
{
    const schedule = await LocalNotifications.schedule(
    {
	    notifications: 
	    [
		    {
			    schedule: { at: date, allowWhileIdle: true },
			    id: Math.random() * (999999999- 1+ 1) + 1,
			    attachments: null,
			    actionTypeId: '',
			    title: title,
			    body: message,
			    largeBody: message,
			    extra: extra,
		    },
	    ]
    });
    
    return schedule;
}
```

As a result, the notification in schedule to happen in a 10 seconds time window, but if the app is closed there's no notification, only if the app is open on "minimized".

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

Did you take into account that if you use allowWhileIdle you can only fire once every 9 minutes? So it's possible that you are testing and not waiting the 9 minutes

**Comment by hatsantos** [comment]
Hello, @jcesarmobile thank you for your reply.

I started testing without the "allowWhileIdle" and it did not work.
I read the docs and noticed the limitation, and then I added the "allowWhileIdle" (if I understood correctly is best to add this prop if I want to make sure that the push is received while the app is in "stand by" mode or closed.

Does this limitation occurs even if the app is open? For instance:

1. The user receives a local notification when app is open, at 10:30h;
2. Another notification is scheduled to 10:35h and then the app is closed;

In this scenario the received notification while the app was open counts to the 9 minutes per notification delay and I will not receive the notification schedule to 10:35?

I need to schedule notifications 1 to 7 days ahead, one for each business day of the week, do you see any possible problem with this?

I will try to test with a 10 minutes time window between notifications.
If the problem persists I will create a testing repo and update my reply.

Thank you for your time.

**Comment by jcesarmobile** [comment]
Android docs don't really specify if the app being open would change the 9 minute limitation, but since the allowWhileIdle is used when the notification is scheduled and not when it's fired, I would guess the limitation will still be there even if one of them fire with the app open

**Comment by hatsantos** [comment]
I ended up creating a test app, with 3 possible options:
Schedules a notification: at this moment (1 sec. delay); in 1 minute or 10 minutes;

None of the available options work on my OnePlus 5T if the app is closed.
If the app is open or in the background, the notification is received at the end of the scheduled time. If I click on one of the options (now, 1 minute, 10 minutes) and close the application I don't receive any notification.

However, with the same test app, running on the Android emulator (Pixel 3 API30 and Pixel 4 XL API30) the notifications seem to work and I receive notifications with the app open or closed. : /

Is there anything else that could be done? Any other prop or configuration?
I don't know exactly what may be causing this issue or if it affects or not other devices.

If you have some spare time could you please test in your smartphone?
[CapacitorLocalNotifications.zip](https://github.com/ionic-team/capacitor-plugins/files/7890919/CapacitorLocalNotifications.zip)

Just unzip and:

1. npm install
2. ionic build --prod
3. npx cap sync
4. npx cap open android

Android platform is included. If you want to remove it, just "npx cap add android" before step 3.

**Comment by jcesarmobile** [comment]
I've been testing your sample app in a few devices without problems, including some onePlus devices (6T with Android 9, 7T with Android 10 and 8 with Android 10)

But apparently some device vendors have some battery optimizations that might prevent some functionalities from working when the app is close or even backgrounded for too long, and notifications are one of those features that might not work

There is more information in [this site](https://dontkillmyapp.com/) and includes things that users can do to make the OS to not kill/limit their apps (such as removing the app from the "battery optimization" list), but nothing that can be done programmatically from the app.

**Comment by hatsantos** [comment]
I also managed to test in a Samsung A31 and it worked without problems.
It's probably something wrong with my device or ROM (I use the official OnePlus ROM), as you suggested. :(

Thank you for your time and all the provided information.

**Comment by mpkasp** [comment]
I have this same problem on my Pixel 5. I did not have this problem with Cordova's Local Notification plugin, their implementation is shown [here](https://github.com/katzer/cordova-plugin-local-notifications/blob/caff55ec758fdf298029ae98aff7f6a8a097feac/src/android/notification/Notification.java#L230). 

I resolved this issue by changing the alarm manager's `setExactAndAllowWhileIdle` `type` parameter from `RTC` to [`RTC_WAKEUP`](https://developer.android.com/reference/android/app/AlarmManager#RTC_WAKEUP).

In LocalNotificationManager.java:

```java
private void setExactIfPossible(
    AlarmManager alarmManager,
    LocalNotificationSchedule schedule,
    long trigger,
    PendingIntent pendingIntent
) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && !alarmManager.canScheduleExactAlarms()) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && schedule.allowWhileIdle()) {
            alarmManager.setAndAllowWhileIdle(AlarmManager.RTC, trigger, pendingIntent);
        } else {
            alarmManager.set(AlarmManager.RTC, trigger, pendingIntent);
        }
    } else {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && schedule.allowWhileIdle()) {
            // CHANGE: AlarmManager.RTC to AlarmManager.RTC_WAKEUP
            alarmManager.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, trigger, pendingIntent);
        } else {
            alarmManager.setExact(AlarmManager.RTC, trigger, pendingIntent);
        }
    }
}
```

Are you open to this change?
