### ISSUE TITLE
Android: Error when setup push notification plugin on android

### ISSUE THREAD

**Issue by josprimasihombing** [ionic-team/capacitor-plugins#767]
### Plugin(s)

@capacitor/push-notifications 1.0.8

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5
```

### Platform(s)

Android

### Current Behavior

If execute PushNotifications.register(), will throw error in android:
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.InstanceIdResult" on path: DexPathList[[zip file "/data/app/-==/base.apk"],nativeLibraryDirectories=[/data/app/-==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass
```

and app will force close.

### Other Technical Details

I'm using `com.google.gms:google-services:4.3.10`.
This may be because of deprecation notice inside the push notification plugin :

<img width="717" alt="Screen Shot 2022-01-18 at 18 04 07" src="https://user-images.githubusercontent.com/57883217/149925697-709238b3-d4f7-4be4-b804-4051d7baa39e.png">

**Comment by jcesarmobile** [comment]
can you provide a sample app?
It's working fine in[ our test app](https://github.com/ionic-team/capacitor-testapp), but it uses `com.google.gms:google-services:4.3.3`

**Comment by josprimasihombing** [comment]
@jcesarmobile will try to provide a sample app later.

but, I have already tried to use the same Google services version, and still does not work.
Is this because I'm using kotlin?

**Comment by josprimasihombing** [comment]
update:

After trying debugging, this is because of one of the capacitor modules: android.capacitor-cordova-android-plugins
has set firebase messaging to '+'
If I set this to 21.0.1 manually, the error is gone.

Do you think that `android.capacitor-cordova-android-plugins` need to update?

**Comment by jcesarmobile** [comment]
what cordova firebase related plugins do you have installed? some of them allow to configure the firebase versions.

Using + is a bad practise and google recommends not doing it as it can break your app whenever an update comes out, but if the plugin doesn't allow to configure the version you'll have to update the plugin yourself

**Comment by josprimasihombing** [comment]
I think this is the plugin that caused that error:

https://ionicframework.com/docs/native/mixpanel

**Comment by Houdhey** [comment]
I had same problem
Like it said, FirebaseinstanceId is deprecated
https://stackoverflow.com/questions/51123197/firebaseinstanceidservice-is-deprecated

It has to be replaced by FirebaseMessaging.getInstance().token

I also had to add this implementation in my build.gradle (app) : implementation 'com.google.firebase:firebase-iid'

This depreciation is from 3 years ago, could you fix this problem

**Comment by jcesarmobile** [comment]
You can add FIREBASE_VERSION variable in the variables.gradle file with the version you want to use, then running npx cap sync should remove the + and put the variable instead

**Comment by josprimasihombing** [comment]
Thankyou @jcesarmobile 
The issue is solved.
