### ISSUE TITLE
Add a way to capture videos

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-plugins#78]
### Plugin

Camera

### Description

The Camera plugin has a way to take photos, but not videos.

### Platform(s)

- Android
- iOS
- Web

### Preferred Solution

Add a `getVideo()` method to the Camera plugin.

### Alternative Solution

It is possible to capture videos using `<input>` (see [this article](https://www.joshmorony.com/using-html-file-input-for-uploading-native-ios-android-files/)). But, it would still be nice to have a programmatic way.

### Additional Context

See this original comment: https://github.com/ionic-team/capacitor-plugins/pull/33#issuecomment-712741309
A request was also made for the Media plugin: https://github.com/capacitor-community/media/issues/9

**Comment by DURK** [comment]
I would love to have this feature as part of the Capacitor Camera API!

It feels nasty to add both `cordova-plugin-camera` (to select a video from the library) and `cordova-plugin-media-capture` (to capture a new video) to a Capacitor project.

**Comment by dwieeb** [comment]
Duplicate of https://github.com/ionic-team/capacitor-plugins/issues/229
