### ISSUE TITLE
feat: Provide a way to find out language variant of current locale

### ISSUE THREAD

**Issue by marcelklehr** [ionic-team/capacitor-plugins#799]
### Description
`Device.getLanguageCode()` only returns a two letter code, which is not enough in the case of chinese for example. 

### Platform(s)
- Android
- iOS

### Preferred Solution
Maybe a `Device.getLanguageVariant()` or `Device.getFullLanguageCode()` method. I'm not too particular about this.

**Comment by jcesarmobile** [comment]
as workaround you can use `navigator.language`, it returns the whole code, or also `navigator.languages`, this one returns an array of all the languages added to the device, in case the first one is not supported you can fallback to the following

**Comment by jcesarmobile** [comment]
4.0.0 beta 0 has a new getLanguageTag function available
