### ISSUE TITLE
PushNotification does not trigger pushNotificationReceived and pushNotificationActionPerformed

### ISSUE THREAD

**Issue by hembachrterran** [ionic-team/capacitor-plugins#800]
### Plugin(s)
@capacitor/push-notifications

### Capacitor Version

```
Capacitor Doctor
Latest Dependencies:
  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0
Installed Dependencies:
  @capacitor/android: 3.4.0
  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/ios: 3.4.0
```

### Platform(s)
[x] iOS

### Current Behavior
I followed this https://capacitorjs.com/docs/guides/push-notifications-firebase documentation, I would like to use this plugin with FCM. The PushNotifications.register() called properly and "registration" listener is triggered, returned a token.
By the token the test message arrive to the phone and show a notification with the proper title and body, but the "pushNotificationReceived " listener and after click on the notification the "pushNotificationActionPerformed" doesn't fire. I tried everything to figure out what's the problem, but I have no clue. In the listeners there is only a console log, I copy and paste the code from the example.

### Expected Behavior
The listeners print to the console, the notification data.

### Code Reproduction
The code is presented in the example of the following link: https://capacitorjs.com/docs/guides/push-notifications-firebase

### Other Technical Details
XCode 13.2.1
The phone is an iPhone 11 with latest updates.
The Push Notification capability is enabled.

### Additional Context
This problems seems related with https://github.com/ionic-team/capacitor-plugins/issues/200

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by josprimasihombing** [comment]
I try to debug, These two events are not fired, even though the notification showed. is there any update for this?

<img width="880" alt="Screen Shot 2022-03-04 at 19 09 58" src="https://user-images.githubusercontent.com/57883217/156761142-337f1906-2b94-47ac-926a-b654a0c5d051.png">

anyway, I cannot provide a reproducible app, because need to set up firebase, etc.

**Comment by hembachrterran** [comment]
@josprimasihombing Yes, same here.
@jcesarmobile The example code needs to set up Firebase as @josprimasihombing wrote, thats why I linked the example, I used the same code.

**Comment by jcesarmobile** [comment]
I can switch the configuration files to use my own once you provide the sample app, but without a sample app this can’t be reproduced, you probably missed some step.

**Comment by hembachrterran** [comment]
Okay, I will send you soon.

**Comment by spasma** [comment]
I've got the same issue, `pushNotificationActionPerformed` in my case. 

I'm still not certain about it, but It seems like this event is not triggering if the app is in a sleep state in the background. It does not occur directly after we move the app to the background, but after iOS has truncated memory (or put the app in a sleep state?).

**Comment by hembachrterran** [comment]
I made a sample application, the plugin work as expected, if the app is running in foregroung, it triggered the pushNotificationActionPerformed.
I have been skipped one step on Apple website with the signatures, the https://capacitorjs.com/docs/guides/push-notifications-firebase documentation is not as detailed as has to be in my opinion.

**Comment by josprimasihombing** [comment]
@hembachrterran 
`I have been skipped one step on Apple website with the signatures`

Can you give a reference website/docs for this?
Thankyou

**Comment by hembachrterran** [comment]
@jcesarmobile  I found out the differences. In the application I want to use this plugin also we use the "https://ionicframework.com/docs/native/background-geolocation" plugin. It seem the background geolocation plugin is incompatible with this push notification plugin. I have no more detail what part of the plugin caused the problem, but 100% sure this is why pushNotificationReceived and pushNotificationActionPerformed events has not been triggered, after uninstall the background geolocation plugin the events fires properly.

**Comment by jcesarmobile** [comment]
That plugin has its own UNUserNotificationCenterDelegate, that's what handles the notifications and apps can only have one, so when you install that plugin it sets itself as the notifications delegate and the events don't get propagated to Capacitor push/local-notification plugins.

**Comment by hembachrterran** [comment]
It would be nice if mention this in the documentation.
