### ISSUE TITLE
iOS autocomplete suggestions above keyboard overlaps part of input field

### ISSUE THREAD

**Issue by t0byman** [ionic-team/capacitor-plugins#803]
### Screenshot
https://i.imgur.com/f7Q4a0x.png

### Plugin(s)
@capacitor/keyboard 1.2.1

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/android: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/cli: 3.4.0
  @capacitor/ios: 3.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
When focusing on an input field and the input field is positioned low on the page, the app will scroll the page so the input field gets positioned above the keyboard and the keyboard won't overlap the input field. This is perfect. However, when iOS provides autocomplete suggestions above the keyboard, the autocomplete suggestions overlap with part of the input field.

### Expected Behavior
When iOS shows the keyboard **and** provides autocomplete suggestions, the page should be scrolled a little further than when **only** showing a keyboard so that the autocomplete suggestions won't overlap with part of the input field and the input field will be fully visible.

### Code Reproduction
```
<form>
  <ion-row>
    <ion-col size="12">
      <input type="text" name="street" autocomplete="address-line-1" placeholder="Street" required="true" style="margin-top: 1000px;">
    </ion-col>
  </ion-row>
</form>
```

### Other Technical Details
Used with ionic 6.0.4.
You can set your addresses to show in the autocomplete suggestions in the Phone App > My card > Edit

### Additional Context
This issue is not about the autocomplete suggestions but I'm going to share it anyway in case it might be related:
https://github.com/ionic-team/capacitor/issues/4858

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
Also, can you try with an ion-input instead of an input, ion-input has some code for scrolling to make fields visible, while that doesn't automatically work for regular input fields.

**Comment by t0byman** [comment]
Using ion-input instead of a regular input was the solution, thank you!
