### ISSUE TITLE
(camera) Permission not needed: WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by dragermrb** [ionic-team/capacitor-plugins#810]
## Bug Report
Starting in November 2021, GooglePlay app updates will be required to target API level 30 and `WRITE_EXTERNAL_STORAGE` permission doesn't have any effect on your app's access to storage.

Actually, Camera plugin requires `WRITE_EXTERNAL_STORAGE` but is not needed and **app submission to GooglePlay will be rejected** by "All Files Access Permission" policy if `WRITE_EXTERNAL_STORAGE` is present.

### Plugin(s)
- Camera

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0
```

### Platform(s)
Android

### Current Behavior
Camera plugin requires `WRITE_EXTERNAL_STORAGE` pick a photo from gallery, even if SaveToGallery is false.

### Expected Behavior
Camera plugin not require `WRITE_EXTERNAL_STORAGE` permissions, since it's not needed.

### Additional Context
- https://developer.android.com/google/play/requirements/target-sdk
- https://developer.android.com/about/versions/11/privacy/storage
- https://support.google.com/googleplay/android-developer/answer/9888170#all-file-access

**Comment by jcesarmobile** [comment]
the "All file access" permission is `MANAGE_EXTERNAL_STORAGE`, which is not requested by the plugin, so it's safe for play store publishing
https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE

but yeah, we should improve the code and not request `WRITE_EXTERNAL_STORAGE` when not needed

**Comment by dragermrb** [comment]
GooglePlay's docs about this is a mess...

As far as I know, If you need "**All file access**" you need to ask for `MANAGE_EXTERNAL_STORAGE` (and pass Google's review).

But if your app requests `READ_EXTERNAL_STORAGE` or `WRITE_EXTERNAL_STORAGE`, it will  be rejected and  Google tells you to ask for `MANAGE_EXTERNAL_STORAGE`.

I will confirm it and I will tell you when they answer me.

**Comment by dragermrb** [comment]
Hi!

Sorry for the error, the problem was not with the `WRITE_EXTERNAL_STORAGE` permission.

GooglePlay may refuse updates by "**All Files Access Permission**" policy if there is any other APK with `MANAGE_EXTERNAL_STORAGE` permission in any channel (Alpha, Beta, Production, ...). My app was rejected for this reason (old APK on production and new apk at 20% roll out).

For what it's worth: if you're having trouble with a launch because of "**All Files Access Permission**" policy, make sure to launch the update without `MANAGE_EXTERNAL_STORAGE` **on all channels and 100% roll out**.

Therefore, the `WRITE_EXTERNAL_STORAGE` permissions **must be kept in the camera plugin**, as they are required on devices with API 28 or lower to add photos to the gallery.

Thanks!
