### ISSUE TITLE
FirebaseInstanceId in com.google.firebase.iid has been deprecated

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#837]
### Plugin
push-notifications

### Description
FirebaseInstanceId in com.google.firebase.iid has been deprecated
InstanceIdResult in com.google.firebase.iid has been deprecated
import com.google.firebase.iid.InstanceIdResult;

### Platform(s)
android

### Preferred Solution
remove deprecation warnings

**Comment by epzee** [comment]
hey! are there any plans to get https://github.com/ionic-team/capacitor-plugins/pull/924 into cap 3?

**Comment by jcesarmobile** [comment]
this has been fixed in 4.0.0 beta 0
