### ISSUE TITLE
[App] Stop triggering `'backbutton'` event on JS 

### ISSUE THREAD

**Issue by diegood12** [ionic-team/capacitor-plugins#853]
### Plugin
App

### Description
Currently, when handling a back button, App plugin triggers the `'backbutton'` JS event

https://github.com/ionic-team/capacitor-plugins/blob/22fb04179bd13fabea6187c42ed3ffc2faa866c1/app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java#L54

This event is not cancelable and in some cases, undesired, since its default action triggers a history pop state.

For instance, when a video is playing fullscreen on the webview and the `'backbutton'` event is triggered, the video closes (desired), but the webview switches to the previous page (undesired).

### Platform(s)
Android

### Preferred Solution
Add a plugin configuration for stop triggering `'backbutton'` on JS.

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

that code just fires a js event, but does nothing related to closing views or navigating, so you might have some code somewhere listening for that event and doing the closing/navigation.

**Comment by diegood12** [comment]
It was a [Quasar](https://github.com/quasarframework/quasar) issue actually... I was searching in the plugin code to find what was causing the weird behaviour. But what was happening is actually a default behaviour from Quasar. which I could disable by adding

```javascript
{
  framework: {
    config: {
      capacitor: {
        backButton: false,
      },
    },
  }
}
```

to the `quasar.conf.js` file.

Since it's not really an issue with the App plugin, I'm closing this.
