### ISSUE TITLE
@capacitor/google-maps not found

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor-plugins#866]
### Plugin(s)
@capacitor/google-maps

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3
```

### Current Behavior

Getting error when running `npm install @capacitor/google-maps`

<img width="665" alt="Screenshot 2022-03-11 at 22 16 55" src="https://user-images.githubusercontent.com/12111716/157954303-9365731e-b9f2-443c-b3d8-674a069cafe2.png">

### Expected Behavior
Being able to install as per [documentation](https://github.com/ionic-team/capacitor-plugins/tree/plugin/google-maps/google-maps#install) :)

**Comment by jcesarmobile** [comment]
The plugin is not released yet, that docs you link aren’t on the main branch.

**Comment by UltimateGemini** [comment]
When will it be release?
