### ISSUE TITLE
Add AdMob Sdk & AdMob Plugins

### ISSUE THREAD

**Issue by MoAsmar** [ionic-team/capacitor-plugins#867]
### Plugin
This is a request to add a new Plugin for "AdMob SDK" & "AdMob" for google AdMob ads monetization.

### Description
We as developers are used to monetizing our ionic apps and games with AdMob ads, using the latest Google AdMob SDK. 
We need this plugin to show AdMob ads easily!

### Platform(s)
Android & IOS

### Preferred Solution
We need the ionic team to build this plugin and add more useful plugins that we have in the Cordova plugins list.
This will push us migrate to capacitor sooner, I am not able to migrate due to the lack of lots of Cordova plugins.

**Comment by RaymondM45** [comment]
I need the software of Google AdMob SDK.

**Comment by jcesarmobile** [comment]
There is a community admob plugin
https://github.com/capacitor-community/admob
