### ISSUE TITLE
Adding App.addListener('backButton', callback) does not disable default back navigation

### ISSUE THREAD

**Issue by distante** [ionic-team/capacitor-plugins#869]
### Plugin(s)
@capacitor/app: "^1.1.1"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
```

### Platform(s)
Android

### Current Behavior
Even when a new `App.eventlistener` for `backButton` is registered, tapping the Hardware back button triggers a back navigation.

### Expected Behavior
Just the new back button callback should be called and not back navigation should be triggered.

### Other Technical Details
I also see that when no event listener is registered, an `App.addListener` log is visible. After add an event listener, two logs are there. 

### Additional Context
I also tried to wait for ionic's `platform.ready()` before I registered my listener, but the second  `App.addListener` always happens after mine.

If I attach a log into `AppPlugin.java` `handleOnBackPressed` I see that I always land on the else branch 
https://github.com/ionic-team/capacitor-plugins/blob/3ec2008bc0311c837346ecbdd0afd105149b427a/app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java#L43-L58

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by distante** [comment]
Looks like this was an error with @ionic/angular, with the latest version (released 14 hours ago) I can not reproduce this for a repo.

**Comment by stefanhuber** [comment]
I experience the same behavior with a stencil project and the ionic-router
