### ISSUE TITLE
Text Zoom does not Zoom on iPads

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/capacitor-plugins#879]
### Plugin(s)

`@capacitor/text-zoom@1.0.8`

### Capacitor Version

```
> $ npx cap doctor                                                                                                        [±main ✓]
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/core: 3.4.3
  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

In the Accessibility settings, set the font size to something that is obviously huge like this:

![iPad-settings-lg-font](https://user-images.githubusercontent.com/1526846/158850155-8fb96240-b7cd-4395-ae6a-d6bdbe75930b.jpeg)

Then start the sample app and you will see that the text size is not affected:

![iPad-lg-font](https://user-images.githubusercontent.com/1526846/158850577-7c919604-915d-4f4f-a1ef-aff32491d5cb.jpeg)

### Expected Behavior

Text size should be affected on iPad based on the accessibility settings. This works on an iPhone (one screenshot shows normal operation, other shows restarting app after bumping up the font size in the accessibility settings of the phone):

![iPhone-reg-font](https://user-images.githubusercontent.com/1526846/158850799-21ef4bc5-ebd9-43d6-b655-4a64f9977a80.jpeg)

![iPhone-lg-font](https://user-images.githubusercontent.com/1526846/158850815-3be2f7d9-fec1-4b92-b7d8-df9fee608ec0.jpeg)

### Code Reproduction

https://github.com/kensodemann/test-text-zoom

The only code change from a stock blank starter is here: https://github.com/kensodemann/test-text-zoom/blob/main/src/app/app.component.ts#L11

Running it should be fairly standard:

- `git clone` and cd into it...
- `npm i`
- `npm run build`
- `npx cap sync`
- `npx cap open ios`

**Comment by jcesarmobile** [comment]
this has been documented in 4.0.0 beta 0, it requires capacitor 4.0.0 beta 1 and using `"preferredContentMode": "mobile"` configuration option
