### ISSUE TITLE
PushNotificationActionPerformed not triggered on Android

### ISSUE THREAD

**Issue by damienaulombard** [ionic-team/capacitor-plugins#883]
### Plugin(s)
@capacitor/push-notifications

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/ios: 3.3.4
  @capacitor/android: 3.3.4
```

### Platform(s)
Android

### Current Behavior
The listener 'pushNotificationActionPerformed' is not triggered when clicking on the notification in notification center. While it is in iOS. So impossible to redirect the users on the specific page passed in the notification object.

### Expected Behavior
When the user taps on the notification in his notification center, it should open the app, trigger the listener 'pushNotificationActionPerformed', and in our case, redirect him to the desired page. 

### Code Reproduction
https://github.com/damienaulombard/capacitor-push-notification-issue

### Other Technical Details
Followed the implementation on the official documentation here : https://capacitorjs.com/docs/apis/push-notifications#install

### Additional Context
Maybe more or less linked with this issue : https://github.com/ionic-team/capacitor-plugins/issues/848 (but in my case, only Android is having problems)

**Comment by MattOnyx** [comment]
I noticed something that may be linked to this issue: the listeners for 'pushNotificationReceived' and 'pushNotificationActionPerformed' are getting dropped after multiple events, like rebooting the phone or updating the app. Removing them and adding them back when starting the app is the only workaround I found for now.

**Comment by jcesarmobile** [comment]
The provided app doesn't have @capacitor/push-notifications plugin installed nor any code for handling the `PushNotificationActionPerformed`.
Can you commit the relevant code?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
