### ISSUE TITLE
Geolocation - request permission full prompt

### ISSUE THREAD

**Issue by josuelmm** [ionic-team/capacitor-plugins#887]
## FeatureRequest

###Plugin
Geolocation

### Description
When making the permission request, the permission selection alert should be full prompt, like the attached image

### Platform(s)
Android

### Preferred Solution
Let the permission request come out like the image

<img src="https://developer.android.com/images/training/location/approximate-full-prompt.svg"  width="310px">

**Comment by jcesarmobile** [comment]
The prompts are handled by the OS, not by Capacitor. The screenshot you provide is the new android 12 prompt.

**Comment by josuelmm** [comment]
I have android 12. And using this plugin when requesting permission does not return it this way.

**Comment by josuelmm** [comment]
According to the Android documentation, two permissions must be requested at the same time for it to display the permission request that way.

https://developer.android.com/training/location/permissions#fig-approximate-only
