### ISSUE TITLE
Geolocation - request permission full prompt

### ISSUE THREAD

**Issue by josuelmm** [ionic-team/capacitor-plugins#889]
## FeatureRequest

###Plugin
Geolocation

### Description
When making the permission request, the permission selection alert should be full prompt, like the attached image.
According to the Android documentation, two permissions must be requested at the same time for it to display the permission request that way.

https://developer.android.com/training/location/permissions#fig-approximate-only

### Platform(s)
Android

### Preferred Solution
Let the permission request come out like the image
Request ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION in a single runtime request.

<img src="https://developer.android.com/images/training/location/approximate-full-prompt.svg"  width="310px">

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
The plugin by default presents that dialog on Android 12+ devices

**Comment by josuelmm** [comment]
I get permission as follows:

async requestPermissionLocation(){
    await Geolocation.requestPermissions().then(
      result => {
        if (!result.location && !result.coarseLocation){
          this.showAlertLocation();
        }else{
          this.AppComponent.gpsSignal.emit('online');
          this.permissionGps = true;
        }
      },
      err =>{
        this.openNativeSettings.open('application_details');
      }
    );
  }

Return this

<img src="https://i.imgur.com/ttU980q.jpg" width="320px">

**Comment by josuelmm** [comment]
In other native apps that request permission like this, it returns like this
<img src="https://i.imgur.com/T4IxyzI.jpg" width="320px">

**Comment by josuelmm** [comment]
It is obvious that permissions must be declared.. I have this permission in manifest

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />

    <uses-feature android:name="android.hardware.location.network" />
    <uses-feature android:name="android.hardware.location.gps" />

**Comment by thomasvidas** [comment]
@josuelmm if you could create a small sample app, it would help us nail the exact issue you're running into. By small sample app, I mean
- Make a new capacitor project
- Install the geolocation plugin
- Prompt for location in the same way you are in your existing app

This way the Capacitor team can easily verify your issue. We can't create sample projects like this for every issue that comes in, which is why we ask the reporter to create a small app with a reproducible example.
