### ISSUE TITLE
PushNotification.requestPermissions() always return 'denied'

### ISSUE THREAD

**Issue by danilbeltsov** [ionic-team/capacitor-plugins#896]
### Plugin(s)
@capacitor/push-notifications 1.0.4-1.0.9

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.4.0
```

### Platform(s)

android (?), ios

### Current Behavior

No matter which button you press - the response always `denied`
<img width="380" alt="image" src="https://user-images.githubusercontent.com/12997141/159732319-8184e6a6-ca0b-4072-9718-a7e23e23ed34.png">

### Expected Behavior

`granted` for pressing Allow button, and `denied` for Don't allow

### Code Reproduction

```
PushNotifications.requestPermissions().then((result) => {
      console.log('result: ', result);
      if (result.receive === 'granted') {
        PushNotifications.register();
      }
    });
```

### Other Technical Details

IOS version 15.3.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
