### ISSUE TITLE
Add event listener when browser changes url

### ISSUE THREAD

**Issue by janverhoeckx** [ionic-team/capacitor-plugins#897]
### Plugin
Browser

### Description
Add an event listener for when the browser changes the url. This way the app code can act when the browser is navigating to another url (for example close the in app browser). The Cordova in app browser plugin already has this feature. See event `loadstart` https://github.com/apache/cordova-plugin-inappbrowser#inappbrowseraddeventlistener.

### Platform(s)
* iOS
* Android

### Preferred Solution
Extend `addListener` with event `loadstart` like in the Cordova in app browser.

### Alternatives
For now using the Cordova in app browser instead of the Capacitor Browser.

### Additional Context
Similar feature in Cordova: https://github.com/apache/cordova-plugin-inappbrowser#inappbrowseraddeventlistener

**Comment by jcesarmobile** [comment]
This is technically not possible, browser plugin uses SFSafariViewController on iOS and Chrome Custom Tabs on Android, which don't provide a way of listening for url changes.

**Comment by Bernix01** [comment]
Not the same but what about.. [this for iOS](https://developer.apple.com/documentation/safariservices/sfsafariviewcontrollerdelegate/1621216-safariviewcontroller) and [this for android](https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#configure-a-custom-action-button) will achieve a similar goal while keeping the underlying native dependencies.
