### ISSUE TITLE
How to use TextZoom plugin?

### ISSUE THREAD

**Issue by andares** [ionic-team/capacitor-plugins#90]
### Plugin(s)

I try to use TextZoom plugin to disable system text scale. but I can't get it from `Plugins` object like this:

```js
import { Plugins } from "@capacitor/core"

const { TextZoom } = Plugins // TextZoom is undefined
```

I try to install `@capacitor/text-zoom` and import it like this:

```js
import { TextZoom } from "@capacitor/text-zoom"
```

but I've got an error `registerPlugin is undefined`

Did the text zoom plugins is work now? thanks.

### Capacitor Version

My capacitor version is `2.4.2`

### Platform(s)

preact base pwa application in android 10

**Comment by jcesarmobile** [comment]
All the plugins in this repo are for Capacitor 3.

The usage is the second one, fails because you are on 2.4.2.

**Comment by arielhasidim** [comment]
https://www.youtube.com/watch?v=anJ1IYuGvhQ
