### ISSUE TITLE
bug(filesystem): appendFile crash on android if no base64

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-plugins#901]
### Plugin(s)
filesystem

### Capacitor Version
3.x

### Platform(s)
android

### Current Behavior
app crash if the provided string is not proper base64

### Expected Behavior
appendFile should error instead of crashing

### Code Reproduction
https://github.com/jcesarmobile/issue-5541

**Comment by tachibana-shin** [comment]
try: [capacitor-fs](https://www.npmjs.com/package/capacitor-fs)
