### ISSUE TITLE
Capacitor camera not opening on android 12 pixel 4a

### ISSUE THREAD

**Issue by fahad-cinnova** [ionic-team/capacitor-plugins#905]
import { Plugins } from '@capacitor/core';

const { Camera } = Plugins;

I'm using this code for capture the image in ionic angular :

const capturedPhoto = await Camera.getPhoto({
resultType: CameraResultType.Uri,
source: CameraSource.Prompt,
quality: 100
});

These are the version i'm using :
"@ionic-native/core": "^5.0.0",
"@ionic/angular": "^5.0.0",

Google pixel 4a (android version 12) not opening the camera for capture the image.
So anyone have the solution for this ???

**Comment by jcesarmobile** [comment]
Doesn't look like you are using Capacitor 3, I have no problems using @capacitor/camera plugin with @capacitor/android 3.x in Android 12 devices, so it there was a problem on Capacitor 2 there might be fixed.

If you are using Capacitor 3, create a new issue and provide all the information required by the issue template, including a sample app where the bug can be reproduced.
