### ISSUE TITLE
PushNotification always showing AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor-plugins#912]
### Plugin(s)
```
"@capacitor/push-notifications": "^1.0.9",
"@capacitor-community/fcm": "^2.0.2",
```

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3

[success] Android looking great! 👌
```

### Platform(s)

Android
Not checked on IOS yet. 

### Current Behavior
FCM Token not generating. but if i send Notification form FCM dashboard i receive it Successfully. But i am not able to get FCM Token. 

### Expected Behavior
It should return FCM Token. 

### Code Reproduction
```
addListeners = async () => {
    await PushNotifications.addListener('registration', token => {
      console.info('Registration token: ', token.value);
    });

    await PushNotifications.addListener('registrationError', err => {
      console.error('Registration error: ', err.error);
    });

    await PushNotifications.addListener('pushNotificationReceived', notification => {
      console.log('Push notification received: ', notification);
    });

    await PushNotifications.addListener('pushNotificationActionPerformed', notification => {
      console.log('Push notification action performed', notification.actionId, notification.inputValue);
    });
  }

  registerNotifications = async () => {
    let permStatus = await PushNotifications.checkPermissions();

    if (permStatus.receive === 'prompt') {
      permStatus = await PushNotifications.requestPermissions();
    }

    if (permStatus.receive !== 'granted') {
      throw new Error('User denied permissions!');
    }

    await PushNotifications.register();
  }
```

**Comment by guidofranzini** [comment]
I have the same problem with iOS, it never trigger the function to generate the token:
PushNotifications.addListener('registration', (token) => {})

- capacitor 3
- push-notifications 1.0.9

**Comment by Saqib92** [comment]
> I have the same problem with iOS, it never trigger the function to generate the token: PushNotifications.addListener('registration', (token) => {})
> 
> * capacitor 3
> * push-notifications 1.0.9

For me It worked on Real Device. I was testing it in Android Emulator. But when i tested it on real Device it Worked. Didn't check on IOS yet.

**Comment by jcesarmobile** [comment]
Closing as the reporter fixed the issue.

I think push notifications also work on Android Emulator, as long as it includes google services and I think you also need to log in with a Google account into the play store app of the emulator.

**Comment by Saqib92** [comment]
> 

When logging into Google account into the play store app on Emulator showing error. That might be the issue i was facing. But when i tried on Real device it worked.
