### ISSUE TITLE
Keyboard plugin TS declaration file update

### ISSUE THREAD

**Issue by saradevh** [ionic-team/capacitor-plugins#918]
Hello,

I was wondering, shouldn't [KeyboardStyle](https://github.com/ionic-team/capacitor-plugins/blob/8e8783622d6e77c38c4aa741a622455302f30486/keyboard/src/definitions.ts#L67) be there instead of hardcoded values? KeyboardStyle is declared in the same file.
`style?: KeyboardStyle`

https://github.com/ionic-team/capacitor-plugins/blob/8e8783622d6e77c38c4aa741a622455302f30486/keyboard/src/definitions.ts#L31

Thanks!

**Comment by jcesarmobile** [comment]
KeyboardStyle values are uppercase, so not really sure if they will work since the config expects lowercase values, also KeyboardStyle.Default  is not a valid value for the config

it could be done by changing the config native code to support Default value and uppercase values

**Comment by jcesarmobile** [comment]
this has been fixed on 4.0.0 beta 0
