### ISSUE TITLE
Issue about trigger on push notification

### ISSUE THREAD

**Issue by creativalab** [ionic-team/capacitor-plugins#932]
### Plugin
    "@capacitor-community/facebook-login": "^3.3.0",
    "@capacitor/android": "3.4.3",
    "@capacitor/app": "1.1.1",
    "@capacitor/camera": "^1.3.1",
    "@capacitor/core": "3.4.3",
    "@capacitor/device": "^1.1.2",
    "@capacitor/filesystem": "^1.1.0",
    "@capacitor/haptics": "1.1.4",
    "@capacitor/ios": "^3.4.3",
    "@capacitor/keyboard": "1.2.2",
    "@capacitor/push-notifications": "^1.0.9",
    "@capacitor/status-bar": "1.0.8",
    "@capacitor/storage": "^1.2.5",
    "@ionic/vue": "^6.0.0",
    "@ionic/vue-router": "^6.0.0",

### Description

Hi, i tried push with firebase integration. It works on Android.
On iOS i accept notifications but there are no triggers about "registration" or "registrationError".
Where did i make a mistake?

Thanks

### Platform(s)
iOS

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by creativalab** [comment]
Hi,
I solved it by deleting the

#if USE_PUSH
...
#endif

Inside my AppDelegate.swift file around the functions for

    didRegisterForRemoteNotificationsWithDeviceToken
    didFailToRegisterForRemoteNotificationsWithError

**Comment by jcesarmobile** [comment]
That is documented on the capacitor 3 upgrade guide

https://capacitorjs.com/docs/updating/3-0#remove-usepush-compilation-condition
