### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by nowrap** [ionic-team/capacitor-plugins#938]
### Plugin(s)

- @capacitor/geolocation 1.3.1
- @capacitor/splash-screen: 1.2.2

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/ios: 3.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS on macOS 12.3.1 with XCode 13.3.1

### Current Behavior

The build within XCode failed with these messages:
`CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'CapacitorGeolocation' from project 'Pods')`
`CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'CapacitorSplashScreen' from project 'Pods')`

### Expected Behavior

A successfull build

### Code Reproduction

none, sorry

### Other Technical Details

The following things didn't change the behavior:
- pod repo update
- npx cap sync

### Additional Context

none, sorry

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by nowrap** [comment]
I'll try to provide a reproduction github repos. May take a bit time.

A newly started capacitor project with added @capacitor/splash-screen didn't throw the error.

**Comment by nowrap** [comment]
Sorry, today the build worked.
There was an update of the capacitor-native-biometric package, which had 2 other errors with swift 5:
https://github.com/epicshaggy/capacitor-native-biometric/issues/46

Maybe the errors "Command CompileSwiftSources failed with a nonzero exit code" where followups of this?
