### ISSUE TITLE
Missing MapOptions Interfaces 

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/capacitor-plugins#946]
## Feature Request

How do use the [MapOptions interface](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions) on the new google map plugins?

### Plugin
Google-maps

### Description

I would like to disable the [default ui](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.disableDefaultUI) but the MapOptions seems to be missing many properties

### Platform(s)
Web, iOS, Android

### Preferred Solution
Add the `MapOptions` in the `GoogleMapConfig`

### Additional Context
[MapOtions](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions) has many params such as [Styles](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.styles) & `DisableDefaultUI` that would be nice and useful for some of us already using the JS API

`@angular/google-maps` has `setOptions(options: google.maps.MapOptions|null)` that can be leveraged

**Comment by muuvmuuv** [comment]
Second this to be able to add Snazzy themes

**Comment by Antonyodu** [comment]
I really need this implemented, the plugin is not so useful for me without these fixes.

**Comment by Antonyodu** [comment]
@jongbonga  I added this 
  ` // Enables/disables all default UI buttons. May be overridden individually.
       disableDefaultUI?: boolean;`
       
to the plugin  "definations..d.ts" file   located  in 
node_modules/@capacitor/google-maps/dist/typings/definitions.d.ts

`export interface GoogleMapConfig {
    /**
     * Override width for native map.
     */
    width?: number;
    /**
     * Override height for native map.
     */
    height?: number;
    /**
     * Override absolute x coordinate position for native map.
     */
    x?: number;
    /**
     * Override absolute y coordinate position for native map.
     */
    y?: number;
    /**
     * Default location on the Earth towards which the camera points.
     */
    center: LatLng;
    /**
     * Sets the zoom of the map.
     */
    zoom: number;
    // Enables/disables all default UI buttons. May be overridden individually.
       disableDefaultUI?: boolean;
    /**
     * Enables image-based lite mode on Android.
     *
     * @default false
     */
    androidLiteMode?: boolean;
    /**
     * Override pixel ratio for native map.
     */
    devicePixelRatio?: number;
}`


You can try it if it works for you

**Comment by LuisJoseSanchez** [comment]
Thanks a lot @Antonyodu, that worked for me!

**Comment by mandrasch** [comment]
> @jongbonga I added this **// Enables/disables all default UI buttons. May be overridden individually. export interface GoogleMapConfig { disableDefaultUI?: boolean; }
> 
> to the plugin "definations..d.ts" file located in node_modules/@capacitor/google-maps/dist/typings/definitions.d.ts
> 
> You can try it if it works for you

Hey, angular newbie here: Could you maybe provide information on how a clean override be achieved? (If i override it in `node_modules` it will be lost on next fresh install)

(Wanted to set styles via MapOptions, see https://github.com/ionic-team/capacitor-plugins/issues/1169)

Thanks very much in advance!

**Comment by muuvmuuv** [comment]
Anyone that wants *styling* in native Google Maps, just use some package manager that supports patching and use this:

<details>
<summary>Patch</summary>

```patch
diff --git a/dist/typings/definitions.d.ts b/dist/typings/definitions.d.ts
index a380b1edc9c83d5dc947861f40735986350d7c58..3056e34f4ae911b313224b2fb10b8a31908004eb 100644
--- a/dist/typings/definitions.d.ts
+++ b/dist/typings/definitions.d.ts
@@ -65,6 +65,10 @@ export interface GoogleMapConfig {
      * Override pixel ratio for native map.
      */
     devicePixelRatio?: number;
+    /**
+     * Map styles.
+     */
+    mapStyle?: string
 }
 /**
  * Configuration properties for a Google Map Camera
diff --git a/dist/typings/ts_old/definitions.d.ts b/dist/typings/ts_old/definitions.d.ts
index 00663cacca4f4bce06c7f4b92a535de90a731d34..86c477b86d6d2413d637b02dd50459af2ac6e639 100644
--- a/dist/typings/ts_old/definitions.d.ts
+++ b/dist/typings/ts_old/definitions.d.ts
@@ -65,6 +65,10 @@ export interface GoogleMapConfig {
      * Override pixel ratio for native map.
      */
     devicePixelRatio?: number;
+    /**
+     * Map styles.
+     */
+    mapStyle?: string
 }
 /**
  * Configuration properties for a Google Map Camera
diff --git a/ios/Plugin/GoogleMapConfig.swift b/ios/Plugin/GoogleMapConfig.swift
index 8ffe054c92d540f729923bfa160c5d4951ef99db..6bcb3dc829ad3506af0d2b04190f6c6800340cf9 100644
--- a/ios/Plugin/GoogleMapConfig.swift
+++ b/ios/Plugin/GoogleMapConfig.swift
@@ -8,6 +8,7 @@ public struct GoogleMapConfig: Codable {
     let y: Double
     let center: LatLng
     let zoom: Double
+    let mapStyle: String
 
     init(fromJSObject: JSObject) throws {
         guard let width = fromJSObject["width"] as? Double else {
@@ -37,6 +38,8 @@ public struct GoogleMapConfig: Codable {
         guard let lat = latLngObj["lat"] as? Double, let lng = latLngObj["lng"] as? Double else {
             throw GoogleMapErrors.invalidArguments("LatLng object is missing the required 'lat' and/or 'lng' property")
         }
+        
+        let mapStyle = fromJSObject["mapStyle"] as? String ?? ""
 
         self.width = round(width)
         self.height = round(height)
@@ -44,5 +47,6 @@ public struct GoogleMapConfig: Codable {
         self.y = y
         self.zoom = zoom
         self.center = LatLng(lat: lat, lng: lng)
+        self.mapStyle = mapStyle
     }
 }
diff --git a/ios/Plugin/Map.swift b/ios/Plugin/Map.swift
index 36eca54639111325f0da95fd96cfe51122b1eae5..5e40dcf80ab5e80055f67841d9e5c390f2b088ea 100644
--- a/ios/Plugin/Map.swift
+++ b/ios/Plugin/Map.swift
@@ -12,7 +12,7 @@ class GMViewController: UIViewController {
     var mapViewBounds: [String: Double]!
     var GMapView: GMSMapView!
     var cameraPosition: [String: Double]!
-
+    
     private var clusterManager: GMUClusterManager?
 
     var clusteringEnabled: Bool {
@@ -115,6 +115,14 @@ public class Map {
                     target.addSubview(self.mapViewController.view)
                     self.mapViewController.GMapView.delegate = self.delegate
                 }
+                
+                if !self.config.mapStyle.isEmpty {
+                    do {
+                        self.mapViewController.GMapView.mapStyle = try GMSMapStyle(jsonString: self.config.mapStyle)
+                    } catch {
+                        // IGNORE
+                    }
+                }
 
                 self.delegate.notifyListeners("onMapReady", data: [
                     "mapId": self.id
```

</details>

And then use "mapStyle" in "config" of `GoogleMap.create`:

```ts
try {
  this.#map = await GoogleMap.create({
    id: this.name,
    element: this.mapRef.nativeElement,
    apiKey: environment.googleApiKey,
    forceCreate: true,
    config: {
      center: { lat, lng },
      zoom: this.zoom,
      mapStyle:
        '[{"featureType":"water","elementType":"geometry","stylers":[{"color":"#e9e9e9"},{"lightness":17}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#ffffff"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#ffffff"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":16}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":21}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#dedede"},{"lightness":21}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"lightness":16}]},{"elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#333333"},{"lightness":40}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#f2f2f2"},{"lightness":19}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#fefefe"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#fefefe"},{"lightness":17},{"weight":1.2}]}]',
    },
  })
} catch (error) {
  this.log.error(StackGlobal.Map, 'Could not create map', error)
  return
}
```
