### ISSUE TITLE
Custom toolbar for Browser

### ISSUE THREAD

**Issue by Samnan** [ionic-team/capacitor-plugins#95]
### Plugin
Browser

### Description
It would be nice to have some sort of control on the browser toolbar. For example, custom set of buttons instead of default.

### Platform(s)
iOS
Android

### Preferred Solution
Add an option to BrowserOption object to allow customizing the browser toolbar

### Alternatives
None

### Additional Context
None

**Comment by jcesarmobile** [comment]
this is not possible

**Comment by dotNetkow** [comment]
Stealing (Borrowing) an expanded answer that one of the Capacitor devs wrote in the Capacitor Slack channel:

"If you look at Cordova’s themeable browser, you can see that it is doing a lot of work. It starts with a web view and then builds all the UI chrome and has to re-implement a lot of the basic tasks of a web browser.

The browser plugin, in contrast, uses SFSafariViewController and Custom Tabs. These are newer, more abstracted APIs that provide much better integration with the system (for things like cookies, bookmarks, saved logins, etc). These trade flexibility in appearance for significantly increased security and ease-of-use by the end user.

Custom Tabs allows you to add a few custom elements like an overflow menu, but SFSafariViewController pretty much only allows you to specify a tint color. So, yes, it is not possible to support customization in the way you requested.
Could someone, theoretically, make a Capacitor version of the themeable browser plugin by using web views and reinventing the surrounding chrome? Sure. But that is not what Browser is."
