### ISSUE TITLE
Capacitor-Google Maps issue on Android

### ISSUE THREAD

**Issue by notseih** [ionic-team/capacitor-plugins#953]
### Plugin(s)

Capacitor - Google Maps

### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Everything is working as intended on the web view when I launch the web server but on Android I’m having issues. The sidemenu opens like always, but im unable to click on the elements that overlap the map. Same if I try to put an ion-button on top of the map, is shows but its unclikable. If I open the sidemenu, and drag the click on top of the menu entries, i can see the map moving behind.
Here u can see how it works on the web view:
![webview](https://user-images.githubusercontent.com/104075920/166591497-55c85fba-fa18-4200-9899-8f6e74611bd1.gif)

And here on Android:
![android](https://user-images.githubusercontent.com/104075920/166595002-bf0de29a-cb89-4809-9b31-9cd05146c6c4.gif)

### Expected Behavior

 It should work same as on the web view, i can click the button, open the sidemenu and click on every item without the map blocking it.

### Code Reproduction

https://github.com/notseih/pruebaMap

### Other Technical Details

If anyone is going to try it with the repo, remember to put your google maps API Key on the enviroments/enviroment.ts and also in the androidmanifest.xml

**Comment by KevinToala** [comment]
same issue

**Comment by notseih** [comment]
Has anyone figured what's happening or any way to fix it?

**Comment by RiaanLaubscher** [comment]
I can't even see the map on android for ionic react. I know the component is there and probably hidden underneath the webview but I cannot figure out how to show it. I have added `background: none` to literally every single parent component of the `capacitor-google-map` component, but still can't see it.

**Comment by notseih** [comment]
> I can't even see the map on android for ionic react. I know the component is there and probably hidden underneath the webview but I cannot figure out how to show it. I have added `background: none` to literally every single parent component of the `capacitor-google-map` component, but still can't see it.

At least mine is showing... Im sure you tried this but just in case is your ion-content on the .scss looking like this? `ion-content{
    --background: transparent;
}`

**Comment by RiaanLaubscher** [comment]
@notseih I have a React project so my files are slightly different. I have `.css` files instead of `.scss`. But I don't use that anyway at the moment to set css properties. I just set the style on the react `<IonContent/>` component like so:

`<IonContent style={{ background: "transparent" }}>`

This still does not work.

**Comment by nuno** [comment]
Same here :(

**Comment by francolondra** [comment]
@theproducer  I checked the package @capacitor/google-maps and the versión is 1.0.0 .Do you know when the team upload the new version on the package with this changes #966

**Comment by fryiee** [comment]
@IT-MikeS / @theproducer - as @francolondra said, do we have an ETA on the tagged version being bumped for installation? This is a blocker for us.

**Comment by theproducer** [comment]
> @IT-MikeS / @theproducer - as @francolondra said, do we have an ETA on the tagged version being bumped for installation? This is a blocker for us.

Yeah, we'll see if we can get one out today (Wednesday), if not, at least before the end of the week.

**Comment by notseih** [comment]
> Yeah, we'll see if we can get one out today (Wednesday), if not, at least before the end of the week.

Any news on the update? @theproducer

**Comment by francescoklekoo** [comment]
Any news on the update? @IT-MikeS 
Thanks

**Comment by IT-MikeS** [comment]
> Any news on the update? @IT-MikeS 
> 
> Thanks

Should be out now 👍

**Comment by francolondra** [comment]
The bug is fixed, but when I browse and select the item, the window remains as well as the image. I understand that the problem is that the background is transparent, but I  understand that is other bug of package.
![WhatsApp Image 2022-06-18 at 1 14 36 AM](https://user-images.githubusercontent.com/40376158/174422382-1419d97a-449b-4a6f-bbbd-ba2d42c07889.jpeg)
