### ISSUE TITLE
browser load local file url

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/capacitor-plugins#955]
### Plugin

@capaitor/browser

### Description
It would be nice if the Browser can also load local files like PDFs for example. This is working in the inappbrowser plugin from cordova. 

### Platform(s)
Android, iOS

### Preferred Solution
Load native file resolveLocalFilesystemUrl 
file://file.pdf

### Alternatives

https://github.com/apache/cordova-plugin-inappbrowser

**Comment by jcesarmobile** [comment]
This is technically not possible by limitation of the native components that the plugin uses
