### ISSUE TITLE
Add web support for Push Notifications

### ISSUE THREAD

**Issue by hardmaster92** [ionic-team/capacitor-plugins#956]
### Plugin
Push Notifications

### Description
Since some plugins have a web version (where available), I think it's good to have web support for Push Notifications too. This feature is supported on almost all browsers except iOS Safari (and desktop Safari implementation is not standard).

### Platform(s)
Web

### Preferred Solution
Using browser's Push API.

### Additional Context
I understand that the major obstacle here is the necessity of a Service Worker capable of handling push notifications. For Angular - there is such provided out of the box by the @angular/pwa module. I think Vue also has it, and I'm not quite sure for React.

**Comment by jcesarmobile** [comment]
We have this issue already
https://github.com/ionic-team/capacitor/issues/1282

It's in capacitor repository instead of in plugins repository because it will most likely need code changes in core to make push work.
