### ISSUE TITLE
Google maps language support

### ISSUE THREAD

**Issue by DanyloKatranGitHub** [ionic-team/capacitor-plugins#957]
### Plugin
@capacitor/google-maps

### Description
Google map is shown in the local user language.
Can I force the use of English locale?
There is no param for GoogleMap init method to provide language.

### Platform(s)
Web, Android, iOS

### Preferred Solution
Add a param to GoogleMap init method that will initialize google map with a certain locale.

**Comment by jcesarmobile** [comment]
The native iOS and Android SDKs don't seem to provide a way of setting the map locale/language, they use the device language.
Should be possible to implement for web.
