### ISSUE TITLE
Plugin share no ios file app option

### ISSUE THREAD

**Issue by gigallo** [ionic-team/capacitor-plugins#958]
### Plugin(s)
Share

### Capacitor Version
"@capacitor/share": "^1.1.2"

### Current Behavior
When trying to share a file in ios the option to save it to file app doesn't appear

### Code Reproduction
await Share.share({
        title: "File test",
        text: this.displayableMedia.name || "download",
        url: this.displayableMedia.src,
        dialogTitle: "Salva o condividi",
      });

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙
