### ISSUE TITLE
Push notification on tap notification.inputValue is undefined

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor-plugins#964]
### Plugin(s)

@capacitor/push-notifications : 1.0.9

### Capacitor Version

```
npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.1
  @capacitor/cli: 3.5.0

[success] Android looking great! 👌
```

### Platform(s)

Android for now

### Current Behavior

It is not giving the payload when you tap on the notification, It will trigger the `pushNotificationActionPerformed` but it is having inputValue undefined. I just copied docs code just to test. [https://capacitorjs.com/docs/apis/push-notifications](push-notification)

### Expected Behavior

I should get body, title and custom data 

### Code Reproduction

![image](https://user-images.githubusercontent.com/23274631/167765689-07766d21-861c-4989-8ea4-231174efae7e.png)
![image](https://user-images.githubusercontent.com/23274631/167765832-0b91a8b4-779d-4543-81b4-935ee022fa67.png)

### Other Technical Details

```
Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.2
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by jcesarmobile** [comment]
Docs say
> inputValue | string | Text entered on the notification action. Only available on iOS.

https://capacitorjs.com/docs/apis/push-notifications#actionperformed

You are not creating an action and you are testing on android, so it’s expected.

to get the inputValue you have to create a notification action that creates a text box on the notification and test on iOS, then, if you provide a text when the push notification appears the value should be there,

**Comment by indraraj26** [comment]
So I would like to get title and body when someone tap on notification. Is there anyway to get it. 

If app is in foreground it is invoking `pushNotificationReceived` with body and title according to that I can navigate the user to respective page.

But if app is in background I get an notification, If I tap on it. I don't get it body, title payload.

Thank you.
![image](https://user-images.githubusercontent.com/23274631/168138239-94c967df-2777-4e76-857d-eb5c31f455bc.png)

**Comment by indraraj26** [comment]
Hi,

I see this in documentation, Do we have any demo where we have enabled the foreground message receive by extending the FirebaseMessagingService.

Thank you.

_This plugin does support data-only notifications, but will NOT call pushNotificationReceived if the app has been killed. To handle this scenario, you will need to create a service that extends FirebaseMessagingService, see [Handling FCM Messages](https://firebase.google.com/docs/cloud-messaging/android/receive)._

**Comment by indraraj26** [comment]
I just checked this [thread ](https://github.com/ionic-team/capacitor-plugins/issues/909)but I am having hard to time to implement, I checked your replied there that I have to import capacitor one.
It is not able to resolve firebase package, Do I have to install any package?

![image](https://user-images.githubusercontent.com/23274631/168144607-389c1989-7845-44e7-a7ff-53dd92bc9ca8.png)
![image](https://user-images.githubusercontent.com/23274631/168144950-74c07490-b835-4d99-a58f-d62ef4093406.png)
