### ISSUE TITLE
feat: support sharing a file with text

### ISSUE THREAD

**Issue by yarinvak** [ionic-team/capacitor-plugins#98]
### Plugin
Share

### Description
Allowing share of a file combined with text

### Platform(s)
Android

### Preferred Solution
see https://github.com/ionic-team/capacitor-plugins/pull/97

### Additional Context
I have created a PR that should solve the issue (allowing file share along with text) https://github.com/ionic-team/capacitor-plugins/pull/97

**Comment by jcesarmobile** [comment]
I can't reproduce
